### ISSUE TITLE
ArgumentError backtrace to not point to the correct line

### ISSUE THREAD

**Issue by tjoyal** [oracle/truffleruby#1041]
I'm not exactly sure what is happening here, but the backtrace points to an empty line.

Experiment:
```ruby
puts <<STATS
RUBY_ENGINE: #{RUBY_ENGINE}
RUBY_VERSION: #{RUBY_VERSION}
RUBY_REVISION: #{RUBY_REVISION}
RUBY_PATCHLEVEL: #{RUBY_PATCHLEVEL}
RUBY_RELEASE_DATE: #{RUBY_RELEASE_DATE}
RUBY_ENGINE_VERSION: #{RUBY_ENGINE_VERSION}

STATS

def test(a)
  return if false

  nil
end

test
```

Results:
```
RUBY_ENGINE: ruby
RUBY_VERSION: 2.3.3
RUBY_REVISION: 56859
RUBY_PATCHLEVEL: 222
RUBY_RELEASE_DATE: 2016-11-21
RUBY_ENGINE_VERSION: 2.3.3

experiment.rb:11:in `test': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from experiment.rb:17:in `<main>'
```

```
RUBY_ENGINE: truffleruby
RUBY_VERSION: 2.3.5
RUBY_REVISION: 59905
RUBY_PATCHLEVEL: 0
RUBY_RELEASE_DATE: 2018-01-29
RUBY_ENGINE_VERSION: 0.0-e8fc582e5f

experiment.rb:13:in `test': wrong number of arguments (0 for 1) (ArgumentError)
	from experiment.rb:17:in `<main>'
```

**Comment by chrisseaton** [comment]
I ran it again with precisely 2.3.5, as that's what we're compatible with

```
RUBY_ENGINE: ruby
RUBY_VERSION: 2.3.5
RUBY_REVISION: 59905
RUBY_PATCHLEVEL: 376
RUBY_RELEASE_DATE: 2017-09-14
RUBY_ENGINE_VERSION: 2.3.5

../test.rb:11:in `test': wrong number of arguments (given 0, expected 1) (ArgumentError)
	from ../test.rb:17:in `<main>'
```

The error message for `ArgumentError` isn't exactly the same either. I get the right line number though. I have a later commit than you do.

**Comment by chrisseaton** [comment]
I've got a fix for this coming.

**Comment by eregon** [comment]
@chrisseaton Could you take a look at this, and whether it's still a bug?

**Comment by eregon** [comment]
Thank you for reporting the issue.

The line number seems correct with 1.0.0-rc3:
```
RUBY_ENGINE: truffleruby
RUBY_VERSION: 2.4.4
RUBY_REVISION: 63013
RUBY_PATCHLEVEL: 0
RUBY_RELEASE_DATE: 2018-06-26
RUBY_ENGINE_VERSION: 1.0.0-rc3

arg.rb:11:in `test': wrong number of arguments (0 for 1) (ArgumentError)
	from arg.rb:17:in `<main>'
```

The message is
```
# TruffleRuby
arg.rb:11:in `test': wrong number of arguments (0 for 1) (ArgumentError)
# MRI 2.4.4
arg.rb:11:in `test': wrong number of arguments (given 0, expected 1) (ArgumentError)
```
So we should probably still fix that, but the line number is now correct so I'll close this issue.
