### ISSUE TITLE
Possible finalizer error in openssl

### ISSUE THREAD

**Issue by tjoyal** [oracle/truffleruby#1048]
Following https://github.com/oracle/truffleruby/issues/1043 I was able to progress to a new exception in what I'm experimenting with.

I'm having a hard time trying to find a consistent reproduction step for it, but cranking up the threads count(20-50 was doing it for me) and running it few times made it show up.

#### Experiment

```rb
puts <<STATS
RUBY_ENGINE: #{RUBY_ENGINE}
RUBY_VERSION: #{RUBY_VERSION}
RUBY_REVISION: #{RUBY_REVISION}
RUBY_PATCHLEVEL: #{RUBY_PATCHLEVEL}
RUBY_RELEASE_DATE: #{RUBY_RELEASE_DATE}
RUBY_ENGINE_VERSION: #{RUBY_ENGINE_VERSION}

STATS

THREAD_COUNT = ARGV[0].to_i
URL = ARGV[1]
CATCH_EXCEPTIONS = ARGV[2] == 'true'

puts <<SPECIFICS
THREAD_COUNT: #{THREAD_COUNT}
URL: #{URL}
CATCH_EXCEPTIONS: #{CATCH_EXCEPTIONS}

SPECIFICS

require 'net/http'
require 'openssl'

def perform
  uri = URI.parse(URL)

  request = Net::HTTP::Get.new(uri.request_uri)
  http = Net::HTTP.new(uri.host, uri.port)

  http.open_timeout = 1
  http.read_timeout = 0.001

  if uri.scheme == "https"
    http.use_ssl = true
  end

  http.request(request)
rescue Exception => e
  puts "Thread exception: #{e.class} #{e.message}"
  raise unless CATCH_EXCEPTIONS
end

def run
  threads = []
  THREAD_COUNT.times do
    threads << Thread.new do
      perform
    end
  end

  puts "Join threads"
  threads.each(&:join)
end

run

puts "Result: Success"
```

#### Result

```
RUBY_ENGINE: truffleruby
RUBY_VERSION: 2.3.5
RUBY_REVISION: 59905
RUBY_PATCHLEVEL: 0
RUBY_RELEASE_DATE: 2018-01-31
RUBY_ENGINE_VERSION: 0.0-1e536a0846

THREAD_COUNT: 48
URL: https://...
CATCH_EXCEPTIONS: false

Join threads
Thread exception: Net::ReadTimeout Net::ReadTimeout
Thread exception: Net::ReadTimeout Net::ReadTimeout
Thread exception: Net::ReadTimeout Net::ReadTimeout
Thread exception: Net::ReadTimeout Net::ReadTimeout
Thread exception: Net::ReadTimeout Net::ReadTimeout
/Users/tjoyal/projects/truffleruby/lib/mri/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/protocol.rb:154:in `readuntil'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/protocol.rb:164:in `readline'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http/response.rb:40:in `read_status_line'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http/response.rb:29:in `read_new'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1424:in `block in transport_request'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1421:in `catch'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1421:in `transport_request'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1394:in `request'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1387:in `block in request'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:853:in `start'
	from /Users/tjoyal/projects/truffleruby/lib/mri/net/http.rb:1385:in `request'
	from experiment.rb:39:in `perform'
	from experiment.rb:49:in `block (2 levels) in run'
Thread exception: Net::ReadTimeout Net::ReadTimeout

com.oracle.truffle.llvm.runtime.SulongRuntimeException: IllegalStateException com.oracle.truffle.nfi.impl.LibFFIFunction@77149a52[140679071416464]
...
```

And then these `...` would be different break points that I can only presume origin from a similar source:
- https://gist.github.com/tjoyal/eb021198dcaa55bf6505a86510193c95 Truffleruby ossl_x509_free in ossl_x509cert.c:40:5 mutex unlock
- https://gist.github.com/tjoyal/53bf8a59cee537a9f28bbf0ca1fc433d Truffleruby ossl_ssl_session_free in ossl_ssl_session.c:13:5 mutex unlock
- https://gist.github.com/tjoyal/4c14d53ba82e0c324650b28befce4622 Truffleruby ossl_ssl_shutdown in ossl_ssl.c:1163:2 mutex unlock

To make it worst, I would not reclaim the terminal interaction, the process just hang in there.

I was not able to reproduce the Sulong failure:
- Without doing an https interaction
- When rescuing the http timeout

Java stacktraces are truncated, I could not find an option similar to `-Xbacktraces.limit=9999` for the java stack. If there is a flag for it I'll be happy to regenerate them.

**Comment by eregon** [comment]
I started to look at this.
I can reproduce fairly often but not always.

It seems that somehow a callback from the native libssl tries to lock or unlock a lock which is not in the expected state.
The first issue is that backtraces are very confusing and missing important information, so I'm addressing that in #1058.

We should add some options to run finalizers more deterministically, for instance run the remaining finalizers on exit or completely disabling them.

**Comment by eregon** [comment]
I use a slight variant of the script: https://gist.github.com/eregon/c883b500adbe6014683810b87ea284c2

Thanks to the better error reporting, it starts to be clearer what are some of the issues.

```
$ jt ruby https2.rb 400 https://github.com
...
Thread exception: RubyTruffleError Error in C extension code (SulongRuntimeException):
Exception thrown by a callback during the native call com.oracle.truffle.nfi.impl.LibFFIFunction@dccae2b(140373705631776) (IllegalStateException)
	from ossl_sslctx_s_alloc (LLVM IR Function ossl_sslctx_s_alloc in /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/openssl.su@d82b9a5cc67d62753401d8fdec8a9d58797d70ce_ossl_ssl.bc in Block {id: 0 name: implicit0})
	from com.oracle.truffle.llvm.nodes.func.LLVMNativeCallUtils.callNativeFunction(LLVMNativeCallUtils.java:72)
Caused by:
<no message> (KillException)
Translated to internal error
/home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext.rb:211:in `execute_without_conversion'
/home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext.rb:211:in `execute_with_mutex'
/home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext.rb:1456:in `__allocate__'
/home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:898:in `new'
/home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:898:in `connect'
/home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:863:in `do_start'
/home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:852:in `start'
/home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:1385:in `request'
https2.rb:38:in `perform'
https2.rb:49:in `block (2 levels) in run'
```

So we try to kill other threads when the main thread ends.
But throwing an exception through a native callback is problematic.
Essentially the native function ends normally (ignoring the exception) and the exception is re-thrown after.

```
$ jt ruby https2.rb 1000 https://github.com
...
Thread exception: RubyTruffleError Error in C extension code (SulongRuntimeException):
Exception thrown by a callback during the native call com.oracle.truffle.nfi.impl.LibFFIFunction@75bb5f25(140695008565200) (IllegalStateException)
	from ossl_start_ssl in ossl_ssl.c:1287:8 (LLVM IR Function ossl_start_ssl in /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/openssl.su@d82b9a5cc67d62753401d8fdec8a9d58797d70ce_ossl_ssl.bc in Block {id: 11 name: implicit32})
	from ossl_ssl_connect_nonblock (LLVM IR Function ossl_ssl_connect_nonblock in /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/openssl.su@d82b9a5cc67d62753401d8fdec8a9d58797d70ce_ossl_ssl.bc in Block {id: 77 name: %rb_tr_scan_args.exit})
	from com.oracle.truffle.llvm.nodes.func.LLVMNativeCallUtils.callNativeFunction(LLVMNativeCallUtils.java:72)
Caused by:
ossl.c:487:in `unlock': Attempt to unlock a mutex which is not locked (ThreadError)
	from /home/eregon/code/truffleruby-ws/truffleruby/src/main/c/openssl/ossl.c:487:in `ossl_lock_unlock'
	from /home/eregon/code/truffleruby-ws/truffleruby/src/main/c/openssl/ossl.c:494:in `ossl_lock_callback'
# native callback here, but not shown in the backtrace currently
	from /home/eregon/code/truffleruby-ws/truffleruby/src/main/c/openssl/ossl_ssl.c:1287:in `ossl_start_ssl'
	from /home/eregon/code/truffleruby-ws/truffleruby/src/main/c/openssl/ossl_ssl.c:1363:in `ossl_ssl_connect_nonblock'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext.rb:211:in `execute_without_conversion'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext.rb:211:in `execute_with_mutex'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/truffle/truffle/cext_ruby.rb:27:in `connect_nonblock'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/protocol.rb:44:in `ssl_socket_connect'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:929:in `connect'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:863:in `do_start'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:852:in `start'
	from /home/eregon/code/truffleruby-ws/truffleruby/lib/mri/net/http.rb:1385:in `request'
	from https2.rb:38:in `perform'
	from https2.rb:49:in `block (2 levels) in run'
```
Not clear why this one tries to unlock a Mutex the thread does not hold.

I noticed the `rb_nativethread_lock*` functions should:
* Be declared as returning `void` not `int`.
* On MRI cause `rb_bug` if they fail.

And those are used by OpenSSL to do its locking (`CRYPTO_set_locking_callback` & co).
Maybe we should just use pthread_mutex for those, that's what MRI does (and Ruby Mutex uses another implementation).

**Comment by deepj** [comment]
@eregon after passing OpenSSL all tests it seems to be this OK. In my case when I set to 100 threads instead of 1000 I get result success. In case of 1000 threads I got some timeouts `Failed to open TCP connection to github.com:443` or `Net::OpenTimeout`. I guess, this is expected.

**Comment by eregon** [comment]
Indeed, it looks fine now.
With 400 threads MRI also starts to fail connecting.
