### ISSUE TITLE
gem install fails with java.io.IOException: Error while trying to parse null

### ISSUE THREAD

**Issue by strzibny** [oracle/truffleruby#1124]
Hello,

I wanted to give TruffleRuby a try today. I downloaded GraalVM 0.31, unpacked it, added a symlink for `chruby`, installed the LLVM dependencies and tried installing gems.

However an error appeared:

```
$ gem install bundler --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `RubyTruffleError' at /home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require' - java.io.IOException: Error while trying to parse null
	RuntimeException com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1044)
	com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1409)
	org.truffleruby.language.loader.FeatureLoader.parseSource(FeatureLoader.java:341)
	org.truffleruby.cext.Linker.loadLibrary(Linker.java:135)
	org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:278)
	org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:165)
	org.truffleruby.language.loader.RequireNode.require(RequireNode.java:130)
	org.truffleruby.language.loader.RequireNodeGen.executeRequire(RequireNodeGen.java:34)
	org.truffleruby.core.kernel.KernelNodes$KernelRequireNode.require(KernelNodes.java:1343)
	org.truffleruby.core.kernel.KernelNodesFactory$KernelRequireNodeFactory$KernelRequireNodeGen.execute(KernelNodesFactory.java:4593)
	org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
		caused by Error while trying to parse null IOException com.oracle.truffle.llvm.Runner.parse(Runner.java:197)
	com.oracle.truffle.llvm.Runner.parse(Runner.java:171)
	com.oracle.truffle.llvm.Sulong.parse(Sulong.java:115)
	com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:596)
	com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1040)
	com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1409)
	org.truffleruby.language.loader.FeatureLoader.parseSource(FeatureLoader.java:341)
	org.truffleruby.cext.Linker.loadLibrary(Linker.java:135)
	org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:278)
	org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:165)
	org.truffleruby.language.loader.RequireNode.require(RequireNode.java:130)
		caused by External function @SSLv23_method cannot be found. LinkageError com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunction(NFIContextExtension.java:254)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.resolve(LLVMFunctionDescriptor.java:217)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.createNativeWrapper(LLVMFunctionDescriptor.java:235)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor.toNative(LLVMFunctionDescriptor.java:487)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:450)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:428)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactory$CachedToNativeNode.toNative(LLVMObjectNativeFactory.java:233)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactoryFactory$CachedToNativeNodeGen.executeAndSpecialize(LLVMObjectNativeFactoryFactory.java:319)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactoryFactory$CachedToNativeNodeGen.execute(LLVMObjectNativeFactoryFactory.java:283)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactory$CachingLibrary.toNative(LLVMObjectNativeFactory.java:176)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.transitionToNative(LLVMToNativeNode.java:107)
		caused by <no message> LazyStackTrace
		caused by <no message> TruffleStackTrace com.oracle.truffle.api.TruffleStackTrace.fillIn(TruffleStackTrace.java:170)
	com.oracle.truffle.api.TruffleStackTrace.addStackFrameInfo(TruffleStackTrace.java:233)
	com.oracle.truffle.api.TruffleLanguage$LanguageImpl.onThrowable(TruffleLanguage.java:1845)
	com.oracle.truffle.api.impl.TVMCI.onThrowable(TVMCI.java:177)
	org.graalvm.compiler.truffle.runtime.GraalTVMCI.onThrowable(GraalTVMCI.java:112)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:250)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:209)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	com.oracle.truffle.llvm.Runner.handleParserResult(Runner.java:238)
ERROR:  Loading command: install (RubyTruffleError)
	java.io.IOException: Error while trying to parse null
	RuntimeException com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1044)
	com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1409)
	org.truffleruby.language.loader.FeatureLoader.parseSource(FeatureLoader.java:341)
	org.truffleruby.cext.Linker.loadLibrary(Linker.java:135)
	org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:278)
	org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:165)
	org.truffleruby.language.loader.RequireNode.require(RequireNode.java:130)
	org.truffleruby.language.loader.RequireNodeGen.executeRequire(RequireNodeGen.java:34)
	org.truffleruby.core.kernel.KernelNodes$KernelRequireNode.require(KernelNodes.java:1343)
	org.truffleruby.core.kernel.KernelNodesFactory$KernelRequireNodeFactory$KernelRequireNodeGen.execute(KernelNodesFactory.java:4593)
	org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
		caused by Error while trying to parse null IOException com.oracle.truffle.llvm.Runner.parse(Runner.java:197)
	com.oracle.truffle.llvm.Runner.parse(Runner.java:171)
	com.oracle.truffle.llvm.Sulong.parse(Sulong.java:115)
	com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:596)
	com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1040)
	com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1409)
	org.truffleruby.language.loader.FeatureLoader.parseSource(FeatureLoader.java:341)
	org.truffleruby.cext.Linker.loadLibrary(Linker.java:135)
	org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:278)
	org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:165)
	org.truffleruby.language.loader.RequireNode.require(RequireNode.java:130)
		caused by External function @SSLv23_method cannot be found. LinkageError com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunction(NFIContextExtension.java:254)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.resolve(LLVMFunctionDescriptor.java:217)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$UnresolvedFunction.createNativeWrapper(LLVMFunctionDescriptor.java:235)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor.toNative(LLVMFunctionDescriptor.java:487)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:450)
	com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LLVMFunctionDescriptorNativeLibrary.toNative(LLVMFunctionDescriptor.java:428)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactory$CachedToNativeNode.toNative(LLVMObjectNativeFactory.java:233)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactoryFactory$CachedToNativeNodeGen.executeAndSpecialize(LLVMObjectNativeFactoryFactory.java:319)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactoryFactory$CachedToNativeNodeGen.execute(LLVMObjectNativeFactoryFactory.java:283)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMObjectNativeFactory$CachingLibrary.toNative(LLVMObjectNativeFactory.java:176)
	com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.transitionToNative(LLVMToNativeNode.java:107)
		caused by <no message> LazyStackTrace
		caused by <no message> TruffleStackTrace com.oracle.truffle.api.TruffleStackTrace.fillIn(TruffleStackTrace.java:170)
	com.oracle.truffle.api.TruffleStackTrace.addStackFrameInfo(TruffleStackTrace.java:233)
	com.oracle.truffle.api.TruffleLanguage$LanguageImpl.onThrowable(TruffleLanguage.java:1845)
	com.oracle.truffle.api.impl.TVMCI.onThrowable(TVMCI.java:177)
	org.graalvm.compiler.truffle.runtime.GraalTVMCI.onThrowable(GraalTVMCI.java:112)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:250)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:234)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:224)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:209)
	org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:185)
	com.oracle.truffle.llvm.Runner.handleParserResult(Runner.java:238)
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/openssl.rb:13:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/security.rb:12:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/package.rb:44:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/truffle/truffle/patching.rb:56:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/truffle/truffle/patching.rb:56:in `require_original'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/patches/stdlib/rubygems/package.rb:1:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/dependency_installer.rb:4:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/commands/install_command.rb:4:in `<top (required)>'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:205:in `load_and_instantiate'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:125:in `[]'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:183:in `find_command'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:168:in `process_args'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:139:in `run'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/gem_runner.rb:55:in `run'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/bin/gem:39:in `<main>'
Exception `NoMethodError' at /home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:169:in `method_missing' - undefined method `invoke_with_build_args' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:169:in `method_missing'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:169:in `process_args'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/command_manager.rb:139:in `run'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/gem_runner.rb:55:in `run'
	/home/strzibny/bin/graalvm-0.31/jre/languages/ruby/bin/gem:39:in `<main>'
Exception: `Gem::SystemExitException' /home/strzibny/bin/graalvm-0.31/jre/languages/ruby/lib/mri/rubygems/user_interaction.rb:390:in `terminate_interaction' - Exiting RubyGems with exit_code 1
Exception: `SystemExit' /home/strzibny/bin/graalvm-0.31/jre/languages/ruby/bin/gem:41:in `exit' - SystemExit

```

Here is my setup:

```
$ cat /etc/redhat-release 
Fedora release 26 (Twenty Six)
$ ruby -v
truffleruby 0.31, like ruby 2.3.5 <GraalVM 0.31 1.8.0_151-b12 with Graal> [linux-x86_64]
$ gem -v
2.5.2.1
```

**Comment by chrisseaton** [comment]
Wow that's a bad stack trace. The real problem seems to be right in the middle!

```
caused by External function @SSLv23_method cannot be found. LinkageError com.oracle.truffle.llvm.runtime.NFIContextExtension.getNativeFunction(NFIContextExtension.java:254)
```

It's not finding `SSLv23_method` in your `libssl`. Do you have `libssl` installed as per these instructions?

https://github.com/oracle/truffleruby/blob/326623f4179a2e362c4a1c4db4cdd3e66fc81fcb/doc/user/installing-libssl.md#fedora

We should do more to try to catch these exceptions and direct people to the relevant documentation.

**Comment by strzibny** [comment]
Oh my god, thanks for such a prompt answer. I didn't have the old libssl version installed. Unfortunately I couldn't find issue with an error such as this here so at least this might be helpful for others. I can confirm that the instructions for downgrading on Fedora 26 worked like a charm. :)
