### ISSUE TITLE
NullPointerException in ExceptionOperations.getFormatter

### ISSUE THREAD

**Issue by numberpi** [oracle/truffleruby#1171]
```
Caused by: java.lang.NullPointerException
	at org.truffleruby.core.exception.ExceptionOperations.getFormatter(ExceptionOperations.java:101)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.createMethodMissingNode(UnresolvedDispatchNode.java:204)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.doDynamicObject(UnresolvedDispatchNode.java:161)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.lambda$executeDispatch$0(UnresolvedDispatchNode.java:100)
	at com.oracle.truffle.api.nodes.Node.atomic(Node.java:521)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:67)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:42)
	at org.truffleruby.language.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:46)
	at org.truffleruby.interop.RubyMessageResolution$ForeignKeysNode.access(RubyMessageResolution.java:262)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignKeysSubNode.accessWithTarget(RubyMessageResolutionForeign.java:312)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignKeysSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:376)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignKeysSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:360)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignKeysSubNode$KeysRootNode.execute(RubyMessageResolutionForeign.java:326)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:64)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:43)
	at com.oracle.truffle.api.interop.InteropAccessNode.doCached(InteropAccessNode.java:186)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeAndSpecialize(InteropAccessNodeGen.java:82)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:45)
	at com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:67)
	at com.oracle.truffle.api.interop.ForeignAccess.send(ForeignAccess.java:198)
	at com.oracle.truffle.api.interop.ForeignAccess.sendKeys(ForeignAccess.java:728)
	at com.oracle.truffle.api.vm.DefaultScope.hasKeys(DefaultScope.java:78)
	at com.oracle.truffle.api.vm.DefaultScope.topScope(DefaultScope.java:58)
	at com.oracle.truffle.api.vm.PolyglotImpl$EngineImpl.createDefaultTopScope(PolyglotImpl.java:634)
	at com.oracle.truffle.api.TruffleLanguage.findTopScopes(TruffleLanguage.java:877)
	at com.oracle.truffle.api.TruffleLanguage$Env.findTopScopes(TruffleLanguage.java:1636)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.findTopScopes(TruffleLanguage.java:1989)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.findTopScopes(TruffleInstrument.java:643)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.findTopScopes(TruffleInstrument.java:639)
	at de.hpi.swa.trufflelsp.GlobalsInstrument$3.onEnter(GlobalsInstrument.java:120)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventFilterChainNode.innerOnEnter(ProbeNode.java:777)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onEnter(ProbeNode.java:534)
	... 28 more
```

I got this exception while experimenting with truffle ruby/python.

I have a TruffleInstrument calling ```env.findTopScopes("ruby");``` which causes this exception.
The NullPointer occurs because ```Layouts.MODULE.getFields(context.getCoreLibrary().getTruffleExceptionOperationsModule()).getConstant(name)``` returns ```null``` (```constants``` in ```ModuleFields``` is empty)

The overall triggering call of this is ```context.eval(Source.newBuilder("python", "def myfunc():\n    return 42", "MySourceSection").build())```

So, the problem seems to be, that I was trying to evaluate python code but looking up ruby top scopes in my instrument. But a ```NullPointerException``` should not occur, right?

**Comment by chrisseaton** [comment]
No it shouldn't be a `NullPointerException`. We'll look into this - thanks for reporting.

**Comment by numberpi** [comment]
Sorry for the delay from my side now.
I am not able to reproduce the error with my current codebase anymore. I think, that this error occurred only because I had a big architectural bug in my code and was using TruffleInstruments wrong, which is fixed by now.

**Comment by numberpi** [comment]
Oh, wait, I found a way to reproduce:

```
java.lang.Exception: Event onEnter failed for instrument class de.hpi.swa.trufflelsp.instrument.SampleInstrument and listener/factory de.hpi.swa.trufflelsp.instrument.SampleInstrument$1@12a94400.
	at com.oracle.truffle.api.instrumentation.ProbeNode.exceptionEventForClientInstrument(ProbeNode.java:633)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onEnter(ProbeNode.java:880)
	at com.oracle.truffle.api.instrumentation.ProbeNode.onEnter(ProbeNode.java:139)
	at com.oracle.truffle.js.nodes.JavaScriptNodeWrapper.execute(JavaScriptNodeWrapper.java:46)
	at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:139)
	at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:64)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:43)
	at com.oracle.truffle.js.parser.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:210)
	at com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:81)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:737)
	at org.graalvm.polyglot.Context.eval(Context.java:311)
	at com.oracle.truffle.js.shell.JSLauncher.runREPL(JSLauncher.java:379)
	at com.oracle.truffle.js.shell.JSLauncher.executeScripts(JSLauncher.java:357)
	at com.oracle.truffle.js.shell.JSLauncher.launch(JSLauncher.java:80)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:109)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:54)
	at com.oracle.truffle.js.shell.JSLauncher.main(JSLauncher.java:70)
Caused by: java.lang.NullPointerException
	at org.truffleruby.core.exception.ExceptionOperations.getFormatter(ExceptionOperations.java:122)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.createMethodMissingNode(UnresolvedDispatchNode.java:203)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.doDynamicObject(UnresolvedDispatchNode.java:160)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.lambda$0(UnresolvedDispatchNode.java:99)
	at com.oracle.truffle.api.nodes.Node.atomic(Node.java:554)
	at org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:66)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:42)
	at org.truffleruby.language.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:46)
	at org.truffleruby.interop.RubyMessageResolution$ForeignKeysNode.access(RubyMessageResolution.java:301)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignKeysSubNode.accessWithTarget(RubyMessageResolutionForeign.java:341)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignKeysSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:377)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignKeysSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:361)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignKeysSubNode$KEYSRootNode.execute(RubyMessageResolutionForeign.java:360)
	at com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:64)
	at com.oracle.truffle.api.impl.DefaultDirectCallNode.call(DefaultDirectCallNode.java:43)
	at com.oracle.truffle.api.interop.InteropAccessNode.doCached(InteropAccessNode.java:186)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeAndSpecialize(InteropAccessNodeGen.java:82)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:45)
	at com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:67)
	at com.oracle.truffle.api.interop.ForeignAccess.send(ForeignAccess.java:198)
	at com.oracle.truffle.api.interop.ForeignAccess.sendKeys(ForeignAccess.java:728)
	at com.oracle.truffle.api.vm.DefaultScope.hasKeys(DefaultScope.java:76)
	at com.oracle.truffle.api.vm.DefaultScope.topScope(DefaultScope.java:57)
	at com.oracle.truffle.api.vm.PolyglotImpl$EngineImpl.createDefaultTopScope(PolyglotImpl.java:676)
	at com.oracle.truffle.api.TruffleLanguage.findTopScopes(TruffleLanguage.java:923)
	at com.oracle.truffle.api.TruffleLanguage$Env.findTopScopes(TruffleLanguage.java:1882)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.findTopScopes(TruffleLanguage.java:2244)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.findTopScopes(TruffleInstrument.java:652)
	at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.findTopScopes(TruffleInstrument.java:648)
	at de.hpi.swa.trufflelsp.instrument.SampleInstrument$1.onEnter(SampleInstrument.java:31)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventFilterChainNode.innerOnEnter(ProbeNode.java:1144)
	at com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onEnter(ProbeNode.java:863)
	... 16 more
Caused by: Attached Guest Language Frames (3)
```

The setup is as follows:

I have a dummy instrument:
```java
@Registration(id = "Sampleinstrument")
public class SampleInstrument extends TruffleInstrument {

    @com.oracle.truffle.api.Option(name = "", help = "Test", category = OptionCategory.USER) //
    static final OptionKey<Boolean> Sampleinstrument = new OptionKey<>(true);

    @Override
    protected void onCreate(Env env) {
        env.getInstrumenter().attachExecutionEventListener(SourceSectionFilter.ANY, new ExecutionEventListener() {

            public void onReturnValue(EventContext context, VirtualFrame frame, Object result) {
            }

            public void onReturnExceptional(EventContext context, VirtualFrame frame, Throwable exception) {
            }

            public void onEnter(EventContext context, VirtualFrame frame) {
                env.findTopScopes("ruby"); // <-- here is the NPE-causing call
            }
        });
    }

    @Override
    protected OptionDescriptors getOptionDescriptors() {
        return new SampleInstrumentOptionDescriptors();
    }

}
```

And I am running the `com.oracle.truffle.js.shell.JSLauncher` with following options:
`--Sampleinstrument`
`--polyglot`
and the `SampleInstrument` class and the `truffleruby.jar` and `truffleruby-launcher.jar` on the classpath.

**Comment by eregon** [comment]
I think this has been fixed, much of that code changed but we now have tests or the Ruby top scope object, so this should no longer happen.
