### ISSUE TITLE
gu install org.graalvm.ruby Fails

### ISSUE THREAD

**Issue by kittylyst** [oracle/truffleruby#1373]
Trying to install TruffleRuby on top of EE v1.0.0 fails immediately:

`$ gu -v install org.graalvm.ruby

Error: Missing file: org.graalvm.ruby

$ java -version

java version "1.8.0_161"

Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

GraalVM 1.0.0-rc1 (build 25.71-b01-internal-jvmci-0.42, mixed mode)`

This is on Mac 10.11.1

Any ideas? Also, the downloads page only has a CE TruffleRuby available for download - there seems to be no way to manually download an EE artifact.

**Comment by chrisseaton** [comment]
For RC1 it's

```
gu -v install -c org.graalvm.ruby
```

And for RC2, to be released imminently, it's

```
gu -v install org.graalvm.ruby
```

Sorry for the confusion.

All languages are CE - when you install them in EE you then need to run `jre/lib/svm/bin/rebuild-images ruby` to update them to be EE. Again, sorry for that being confusing. We're still working to make this all appear logical.

**Comment by kittylyst** [comment]
Ok, that seems to work. 2 more bits of feedback:

* If you've installed the 1.0.0 GraalVM, then the gu command looks like it needs to be run with su
* The downloader will always try and re-download, it doesn't check if it's already downloaded but later steps of the install failed.

**Comment by chrisseaton** [comment]
> If you've installed the 1.0.0 GraalVM, then the gu command looks like it needs to be run with su

If you install it in a root location, then yes because installing a language installs it in the same location. I think that's ok - if you install standard Ruby as root using a system package manager, and then try to install gems, it'll need root to do that.

An alternative would be to install gems and NPM modules in something like `~/.graalvm`.

**Comment by chrisseaton** [comment]
Also, I'm afraid in RC1 it's not clear whether you have CE or EE when you actually run Ruby. RC2 will clearly say 'CE' or 'EE' in the version string so you can't be mistaken.

**Comment by kittylyst** [comment]
Oh, completely, you just might want to mention that in the docs.

**Comment by chrisseaton** [comment]
Probable relevant part:

```
...
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_name in libffi.a(closures.o)
...
```

Can you try not as a root, please? So just having the tarball in your local directory and going from there?

10.11 also might be pushing it... we don't have a test system that extends to old versions of macOS.

```
$ sudo jre/lib/svm/bin/rebuild-images ruby
Password:
Building ruby...
   classlist:   3,979.49 ms
       (cap):   2,865.45 ms
       setup:   6,618.88 ms
  (typeflow):  44,155.90 ms
   (objects):  62,476.90 ms
  (features):   8,016.41 ms
    analysis: 117,127.97 ms
9769 method(s) included for runtime compilation
    universe:   3,764.34 ms
     (parse):   8,039.21 ms
    (inline):   8,519.93 ms
   (compile):  70,237.11 ms
     compile:  91,300.99 ms
       image:  19,838.60 ms
   debuginfo:  13,341.64 ms
       write: 114,731.13 ms
fatal error: java.lang.RuntimeException: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/bin/ruby -Wl,-alias,_com_002eoracle_002esvm_002ecore_002ecode_002eCEntryPointCallStubs_002ecom_005f002eoracle_005f002esvm_005f002ecore_005f002eJavaMainWrapper_005f002erun_005f0028int_005f002corg_005f002egraalvm_005f002enativeimage_005f002ec_005f002etype_005f002eCCharPointerPointer_005f0029_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029,_main -L/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535 -L/Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535/ruby.o -ljitdebug -lffi -Wl,-framework,CoreFoundation -lz -lpthread -lpthread -ldl -lstrictmath -llibchelper

Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/bin/ruby -L/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535 -L/Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -alias _com_002eoracle_002esvm_002ecore_002ecode_002eCEntryPointCallStubs_002ecom_005f002eoracle_005f002esvm_005f002ecore_005f002eJavaMainWrapper_005f002erun_005f0028int_005f002corg_005f002egraalvm_005f002enativeimage_005f002ec_005f002etype_005f002eCCharPointerPointer_005f0029_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029 _main /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535/ruby.o -ljitdebug -lffi -framework CoreFoundation -lz -lpthread -lpthread -ldl -lstrictmath -llibchelper -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_name in libffi.a(closures.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:398)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:240)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:78)
Caused by: java.lang.RuntimeException: host C compiler or linker does not seem to work: java.lang.RuntimeException: returned 1

Running command: cc -v -o /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/bin/ruby -Wl,-alias,_com_002eoracle_002esvm_002ecore_002ecode_002eCEntryPointCallStubs_002ecom_005f002eoracle_005f002esvm_005f002ecore_005f002eJavaMainWrapper_005f002erun_005f0028int_005f002corg_005f002egraalvm_005f002enativeimage_005f002ec_005f002etype_005f002eCCharPointerPointer_005f0029_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029,_main -L/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535 -L/Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535/ruby.o -ljitdebug -lffi -Wl,-framework,CoreFoundation -lz -lpthread -lpthread -ldl -lstrictmath -llibchelper

Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -arch x86_64 -macosx_version_min 10.11.0 -o /Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/languages/ruby/bin/ruby -L/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535 -L/Library/Java/JavaVirtualMachines/graalvm-1.0.0-rc1/Contents/Home/jre/lib/svm/clibraries/darwin-amd64 -alias _com_002eoracle_002esvm_002ecore_002ecode_002eCEntryPointCallStubs_002ecom_005f002eoracle_005f002esvm_005f002ecore_005f002eJavaMainWrapper_005f002erun_005f0028int_005f002corg_005f002egraalvm_005f002enativeimage_005f002ec_005f002etype_005f002eCCharPointerPointer_005f0029_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029 _main /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/SVM-498990258106482535/ruby.o -ljitdebug -lffi -framework CoreFoundation -lz -lpthread -lpthread -ldl -lstrictmath -llibchelper -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/lib/darwin/libclang_rt.osx.a
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
Undefined symbols for architecture x86_64:
  "_mkostemp", referenced from:
      _open_temp_exec_file_name in libffi.a(closures.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.oracle.svm.hosted.image.NativeBootImageViaCC.write(NativeBootImageViaCC.java:177)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:881)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:381)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image building with exit status 1
```

**Comment by eregon** [comment]
Closing this issue, no reply from the reporter. Please open a new issue if it's still a problem with the latest release.
