### ISSUE TITLE
Unicorn doesn't compile

### ISSUE THREAD

**Issue by obrie** [oracle/truffleruby#1379]
* TruffleRuby version: truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]

* OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

* LLVM version: 3.8

Output:

```
$ gem install unicorn
Building native extensions.  This could take a while...
ERROR:  Error installing unicorn:
	ERROR: Failed to build gem native extension.

    current directory: /home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/unicorn-5.4.0/ext/unicorn_http
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/bin/truffleruby -r ./siteconf20180628-32149-1369s86.rb extconf.rb
checking for SIZEOF_OFF_T in ruby.h... yes
checking for SIZEOF_SIZE_T in ruby.h... yes
checking for SIZEOF_LONG in ruby.h... yes
checking for rb_str_set_len() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
checking for gmtime_r() in time.h... yes
creating Makefile

current directory: /home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/unicorn-5.4.0/ext/unicorn_http
make "DESTDIR=" clean

current directory: /home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/unicorn-5.4.0/ext/unicorn_http
make "DESTDIR="
compiling httpdate.c
compiling unicorn_http.c
In file included from unicorn_http.rl:12:
./common_field_optimization.h:19:3: error: initializer element is not a compile-time constant
  f("ACCEPT"),
  ^~~~~~~~~~~
./common_field_optimization.h:18:37: note: expanded from macro 'f'
# define f(N) { (sizeof(N) - 1), N, Qnil }
                                    ^~~~
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/cext/include/ruby/ruby.h:430:14: note: expanded from macro 'Qnil'
#define Qnil rb_tr_get_nil()
             ^~~~~~~~~~~~~~~
1 error generated.
Makefile:210: recipe for target 'unicorn_http.bc' failed
make: *** [unicorn_http.bc] Error 1

make failed, exit code 2
```

Happy to dig into a fix, but not really sure where to start.

**Comment by eregon** [comment]
I fixed this particular compilation error in https://github.com/oracle/truffleruby/commit/d8a9acbf8242ee7f70d218a2ade6e9baad22b8e5, which will be in the next release.
With that, `gem install unicorn` succeeds (also compiling kgio and raindrops), but fails at runtime:
```
$ truffleruby -S unicorn --help
truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': Cannot convert LLVMTypedForeignObject:0x0 to LLVMNativePointer (IllegalStateException) (RuntimeError)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
        ...
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from truffleruby/lib/ruby/gems/2.4.0/gems/kgio-2.11.2/lib/kgio.rb:21:in `<top (required)>'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from truffleruby/lib/ruby/gems/2.4.0/gems/unicorn-5.4.0/lib/unicorn.rb:4:in `<top (required)>'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from truffleruby/lib/ruby/gems/2.4.0/gems/unicorn-5.4.0/lib/unicorn/launcher.rb:9:in `<top (required)>'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from truffleruby/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from truffleruby/lib/ruby/gems/2.4.0/gems/unicorn-5.4.0/bin/unicorn:3:in `<top (required)>'
	from truffleruby/src/main/ruby/core/kernel.rb:337:in `load'
	from truffleruby/src/main/ruby/core/kernel.rb:337:in `load'
	from truffleruby/bin/unicorn:23:in `<main>'
```

So requiring `kgio_ext` extension fails because a Ruby object needs to be stored in native memory and that needs special handling currently. I did not investigate more than that so far. We would need to take a look further to see how to handle that case.

Note that `unicorn` and fork-based servers are not expected to work well on TruffleRuby, due to [not supporting `fork()` at the moment](https://github.com/oracle/truffleruby/blob/master/doc/user/compatibility.md#fork).
Instead, non-forking servers like Puma should work better (we test Puma specifically).

**Comment by obrie** [comment]
That makes sense, thanks!
