### ISSUE TITLE
Couchbase gem fails to load with call to rb_const_set

### ISSUE THREAD

**Issue by obrie** [oracle/truffleruby#1380]
* TruffleRuby version: truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]

* OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

* LLVM version: 3.8

The `couchbase` gem successfully compiles, but when I tried to load it I get the following error:

```
truffleruby-1.0.0-rc2 :001 > require 'couchbase'
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/version.rb:3: warning: already initialized constant JSON::VERSION
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/version.rb:4: warning: previous definition of VERSION was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/version.rb:5: warning: previous definition of VERSION_ARRAY was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/version.rb:6: warning: previous definition of VERSION_MAJOR was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/version.rb:7: warning: previous definition of VERSION_MINOR was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/version.rb:8: warning: previous definition of VERSION_BUILD was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/common.rb:99: warning: already initialized constant JSON::NaN
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/common.rb:100: warning: previous definition of NaN was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/common.rb:101: warning: already initialized constant JSON::Infinity
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/common.rb:102: warning: previous definition of Infinity was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/common.rb:104: warning: previous definition of MinusInfinity was here
/home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/json-1.8.6/lib/json/common.rb:128: warning: already initialized constant JSON::UnparserError
/home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/json/lib/json/common.rb:129: warning: previous definition of UnparserError was here
NameError: wrong constant name _INTERNED
	from <unavailable>:1:in `const_set'
	from <unavailable>:in `rb_const_set'
	from /home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/couchbase-1.3.15/ext/couchbase_ext/couchbase_ext.c:1476:in `Init_couchbase_ext'
	from /home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `gem_original_require'
	from /home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/mri/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/aaron/.rvm/gems/truffleruby-1.0.0-rc2/gems/couchbase-1.3.15/lib/couchbase.rb:22:in `<top (required)>'
	from /home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from /home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from (irb):1:in `<top (required)>'
	from /home/aaron/.rvm/rubies/truffleruby-1.0.0-rc2/bin/irb:29:in `<main>'
```

The line in question is: https://github.com/couchbase/couchbase-ruby-client/blob/4dd4920100f81edda4d205649fdf5e2f9fcc417a/ext/couchbase_ext/couchbase_ext.c#L1476

Any thoughts on what might be an issue here?

**Comment by obrie** [comment]
Interesting.  Dug into this a little bit more and it seems like `_INTERNED` is normally not a valid constant name, but MRI appears to allow it in C extensions (or at least doesn't raise an error).

**Comment by iliabylich** [comment]
MRI allows many different things in C API (like ivars without `@` prefix). The reason is that these validations exist only in ruby interfaces.

**Comment by obrie** [comment]
Makes sense -- is the intention to *not* keep that same compatibility with MRI and instead submit patches to those gems which are doing things not normally allowed in Ruby?

**Comment by eregon** [comment]
@obrie No, TruffleRuby tries to be as compatible with MRI as possible.
We just need to be more flexible in the implementation of `rb_const_set`.

**Comment by obrie** [comment]
:+1: Sounds good -- thanks for the follow-up!

**Comment by eregon** [comment]
I fixed it in https://github.com/oracle/truffleruby/commit/e58fce02768bdd34b180e62f51072705f8d09b5a with specs in https://github.com/oracle/truffleruby/commit/ab4f0a4b25e2685e05e6d7a9c702bf53a70e5b68.
It will be available in 1.0.0-RC4.

In the meantime, you can [build from source](https://github.com/oracle/truffleruby/blob/master/doc/contributor/workflow.md) if you want to try.
I could not check myself as I do not have Couchbase.

**Comment by eregon** [comment]
@obrie Thank you for the great issue report and investigating!

**Comment by eregon** [comment]
TruffleRuby 1.0.0-rc5 was released, with the fix for this bug.
@obrie Could you verify it works as expected now?

**Comment by obrie** [comment]
This looks great, thank you!
