### ISSUE TITLE
sqlite3 gem doing queries eventually errors with SQLite3::CantOpenException

### ISSUE THREAD

**Issue by enebo** [oracle/truffleruby#1381]
version: TR 1.0.0RC3, Fedora core 28

I was messing around with some random sqlite3 bench script and decided to make it do a much smaller query and loop more to see warmup effects.  Here is the script:

```ruby
#!/usr/bin/env ruby
#
require 'benchmark'
require 'thread'
require 'rubygems'
require 'sqlite3'

SQLITE3_DB = 'test.db'

def new_sqlite_connection
  SQLite3::Database.new SQLITE3_DB
end

def sqlite_query
  new_sqlite_connection.execute 'select * from dummies'
end

# seed sqlite
File.delete SQLITE3_DB if File.exists? SQLITE3_DB
new_sqlite_connection.tap do |db|
  db.execute "create table dummies ( a integer );"
  db.execute "insert into dummies values ( 1000 );"
  (1..6).each do |i| # 2 ^ 20
    db.execute "insert into dummies (a) select d.a from dummies as d;"
  end
end

def sleep_some_time
  50.times { sleep 0.1 }
end

Benchmark.bm do |b|
  20.times do
    b.report('sqlite        ') do
      100.times { sqlite_query }
    end
  end
end
```

After a few iterations I see the error:

```text
1.0.0 ~ 1013% ruby work/snippets/sqli.rb 
       user     system      total        real
sqlite         13.299219   0.117375  13.416594 (  6.720328)
sqlite          4.804292   0.028230   4.832522 (  3.798499)
sqlite          5.479347   0.039249   5.518596 (  4.029949)
sqlite          4.600413   0.021082   4.621495 (  3.471549)
sqlite          3.657513   0.016082   3.673595 (  3.176211)
sqlite          6.475054   0.040117   6.515171 (  4.339600)
sqlite          3.264387   0.016117   3.280504 (  3.261587)
sqlite          3.276019   0.021153   3.297172 (  3.272137)
sqlite          3.198251   0.021059   3.219310 (  3.201240)
sqlite          4.441118   0.029014   4.470132 (  3.469288)
sqlite        /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/truffle/truffle/cext.rb:1068:in `rb_exc_raise': 0x7f467b3d1c70 (SQLite3::CantOpenException)
	from <unavailable>:in `rb_exc_raise'
	from /home/enebo/.rvm/gems/truffleruby-1.0.0-rc3/gems/sqlite3-1.3.13/ext/sqlite3/exception.c:93:in `rb_sqlite3_raise'
	from /home/enebo/.rvm/gems/truffleruby-1.0.0-rc3/gems/sqlite3-1.3.13/ext/sqlite3/database.c:135:in `initialize'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/truffle/truffle/cext_ruby.rb:27:in `initialize'
	from work/snippets/sqli.rb:11:in `new'
	from work/snippets/sqli.rb:11:in `new_sqlite_connection'
	from work/snippets/sqli.rb:15:in `sqlite_query'
	from work/snippets/sqli.rb:35:in `block (4 levels) in <main>'
	from work/snippets/sqli.rb:35:in `times'
	from work/snippets/sqli.rb:35:in `block (3 levels) in <main>'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/benchmark.rb:293:in `measure'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/benchmark.rb:375:in `item'
	from work/snippets/sqli.rb:34:in `block (2 levels) in <main>'
	from work/snippets/sqli.rb:33:in `times'
	from work/snippets/sqli.rb:33:in `block in <main>'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/benchmark.rb:173:in `benchmark'
	from /home/enebo/.rvm/rubies/truffleruby-1.0.0-rc3/lib/mri/benchmark.rb:205:in `bm'
	from work/snippets/sqli.rb:32:in `<main>'
```

It would appear some finalization is not happening and TR is running into a resource limit in sqlite3?  Just thought you may be interested in this.

**Comment by chrisseaton** [comment]
Cheers for the report 🍻 - we have some native handles that we know leak, so it could be that, or possible something else.

**Comment by aardvark179** [comment]
I've got a fix for the specific leak causing this problem which is going through our internal CI at the moment. There are some other less common leaks which I hope to fix up soon.

**Comment by enebo** [comment]
@aardvark179 I think this is fixed in rc11 since I ran it for a looong time and it ran to completion.

**Comment by aardvark179** [comment]
I think this is also fixed with the new approach to C extensions coming in rc12 - providing the GC runs often enough. This appears to be the case for MRI as well. If I close the database connection explicitly then I can run the test reliably on both MRI and TruffleRuby for an extremely long time.
