### ISSUE TITLE
gem install rails fail {nokogiri.su failed}

### ISSUE THREAD

**Issue by chenjianxin** [oracle/truffleruby#1387]
ubuntu:18.04
graalvm 1.0 rc3
ruby 2.4.4

```
compiling xml_xpath_context.c
xml_xpath_context.c:176:65: warning: function 'xpath_generic_exception_handler' declared 'noreturn' should not return [-Winvalid-noreturn]
  va_list args; rb_raise(rb_eRuntimeError, "%s", "Exception:"); return;
                                                                ^
1 warning generated.
compiling xslt_stylesheet.c
linking shared-object nokogiri/nokogiri.su
llvm-link: /home/elecbuggy/Downloads/graalvm-ce-1.0.0-rc3-linux-amd64/graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.4/ports/x86_64-unknown-linux-gnu/libxslt/1.1.32/lib/libexslt.a:1:2: error: expected integer
!<arch>
 ^
llvm-link: error loading file '/home/elecbuggy/Downloads/graalvm-ce-1.0.0-rc3-linux-amd64/graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.4/ports/x86_64-unknown-linux-gnu/libxslt/1.1.32/lib/libexslt.a'
/home/elecbuggy/Downloads/graalvm-ce-1.0.0-rc3-linux-amd64/graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/cext/linker.rb:54:in `link_bitcode': Linker failed (RuntimeError)
	from /home/elecbuggy/Downloads/graalvm-ce-1.0.0-rc3-linux-amd64/graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/cext/linker.rb:48:in `main'
	from /home/elecbuggy/Downloads/graalvm-ce-1.0.0-rc3-linux-amd64/graalvm-ce-1.0.0-rc3/jre/languages/ruby/lib/cext/linker.rb:108:in `<main>'
Makefile:226: recipe for target 'nokogiri.su' failed
make: *** [nokogiri.su] Error 1

make failed, exit code 2
```

**Comment by eregon** [comment]
@chenjianxin Thank for the report.

Could you try `bundle config build.nokogiri --use-system-libraries` before `bundle install`?
See #62 for details.

**Comment by nirvdrum** [comment]
@chenjianxin Unfortunately, our Nokogiri support is still in development. In particular, we can't yet compile libxml2 & libxslt and link against them in the Nokogiri source tree. As a temporary measure, you would need to compile Nokogiri using your system installed libraries.

The Nokogiri team provides [comprehensive documentation](http://www.nokogiri.org/tutorials/installing_nokogiri.html#install_with_system_libraries) on how to use your system libraries, both with and without Bundler.

**Comment by eregon** [comment]
I will close this issue as the workaround is now clearly mentioned on both #1400 and #62 and the later issue already tracks progress on nokogiri.
