### ISSUE TITLE
Error running './lib/truffle/post_install_hook.sh'

### ISSUE THREAD

**Issue by thbar** [oracle/truffleruby#1405]
I used RVM to install TruffleRuby to 1.0.0-rc5, got success but also an error in red in the middle of the installation process:

```
$ ram get master
# SNIP
$ rvm install truffleruby-1.0.0-rc5
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/truffleruby-1.0.0-rc5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl/cert.pem' is already up to date.
Requirements installation successful.
truffleruby-1.0.0-rc5 - #downloading truffleruby-1.0.0-rc5-macos-amd64, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630    0   630    0     0    681      0 --:--:-- --:--:-- --:--:--   681
100 41.6M  100 41.6M    0     0  2638k      0  0:00:16  0:00:16 --:--:-- 3355k
truffleruby-1.0.0-rc5 - #extracting truffleruby-1.0.0-rc5-macos-amd64 to /Users/thbar/.rvm/src/truffleruby-1.0.0-rc5.....
truffleruby-1.0.0-rc5 - #installing to /Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5.
truffleruby-1.0.0-rc5 - #compiling c-extensions...............

##### the part below is in red #########
Error running './lib/truffle/post_install_hook.sh',
please read /Users/thbar/.rvm/log/1533457987_truffleruby-1.0.0-rc5/cext.log
##### end of red #############

truffleruby-1.0.0-rc5 - #making binaries executable..
truffleruby-1.0.0-rc5 - #gemset created /Users/thbar/.rvm/gems/truffleruby-1.0.0-rc5@global
truffleruby-1.0.0-rc5 - #importing gemset /Users/thbar/.rvm/gemsets/global.gems...................................................
truffleruby-1.0.0-rc5 - #generating global wrappers.......
truffleruby-1.0.0-rc5 - #gemset created /Users/thbar/.rvm/gems/truffleruby-1.0.0-rc5
truffleruby-1.0.0-rc5 - #importing gemsetfile /Users/thbar/.rvm/gemsets/default.gems evaluated to empty gem list
truffleruby-1.0.0-rc5 - #generating default wrappers.......
```

The `cext.log` file mentioned contains:

```
$ cat /Users/thbar/.rvm/log/1533457987_truffleruby-1.0.0-rc5/cext.log
[2018-08-05 10:33:10] ./lib/truffle/post_install_hook.sh
current path: /Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5
GEM_HOME=/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc3
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc3/bin:/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc3@global/bin:/Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc3/bin:/Users/thbar/.rvm/bin:/Users/thbar/.pyenv/shims:/Users/thbar/.nvm/versions/node/v8.9.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
GEM_PATH=/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc3:/Users/thbar/.rvm/gems/truffleruby-1.0.0-rc3@global
command(1): ./lib/truffle/post_install_hook.sh
Compiling the OpenSSL C extension
/Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/lib/truffle/rbconfig.rb:35: warning: loading in progress, circular require considered harmful - /Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/lib/truffle/rbconfig.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for openssl/ssl.h... yes
checking for OpenSSL version is 0.9.8 or later... yes
checking for SSL_library_init() in openssl/ssl.h with -Werror=deprecated-declarations... yes
checking for SSLv3_method()... yes
checking for TLSv1_1_method()... yes
checking for TLSv1_2_method()... yes
checking for RAND_egd()... yes
checking for ENGINE_load_builtin_engines() in openssl/engine.h with -Werror=deprecated-declarations... yes
checking for ENGINE_load_openbsd_dev_crypto() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_openbsd_dev_crypto in openssl/engine.h... no
checking for ENGINE_load_dynamic() in openssl/engine.h with -Werror=deprecated-declarations... yes
checking for ENGINE_load_4758cca() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_4758cca in openssl/engine.h... no
checking for ENGINE_load_aep() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_aep in openssl/engine.h... no
checking for ENGINE_load_atalla() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_atalla in openssl/engine.h... no
checking for ENGINE_load_chil() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_chil in openssl/engine.h... no
checking for ENGINE_load_cswift() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_cswift in openssl/engine.h... no
checking for ENGINE_load_nuron() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_nuron in openssl/engine.h... no
checking for ENGINE_load_sureware() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_sureware in openssl/engine.h... no
checking for ENGINE_load_ubsec() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_ubsec in openssl/engine.h... no
checking for ENGINE_load_padlock() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_padlock in openssl/engine.h... no
checking for ENGINE_load_capi() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_capi in openssl/engine.h... no
checking for ENGINE_load_gmp() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_gmp in openssl/engine.h... no
checking for ENGINE_load_gost() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_gost in openssl/engine.h... no
checking for ENGINE_load_cryptodev() in openssl/engine.h with -Werror=deprecated-declarations... yes
checking for ENGINE_load_aesni() in openssl/engine.h with -Werror=deprecated-declarations... no
checking for ENGINE_load_aesni in openssl/engine.h... no
checking for EVP_CIPHER_CTX_new()... yes
checking for EVP_CIPHER_CTX_free()... yes
checking for SSL_CTX_clear_options() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_CTX_clear_options in openssl/ssl.h... yes
checking for ASN1_TIME_adj()... yes
checking for EVP_CIPHER_CTX_copy()... yes
checking for EVP_PKEY_base_id()... yes
checking for HMAC_CTX_copy()... yes
checking for PKCS5_PBKDF2_HMAC()... yes
checking for X509_NAME_hash_old()... yes
checking for X509_STORE_CTX_get0_current_crl()... yes
checking for X509_STORE_set_verify_cb()... yes
checking for i2d_ASN1_SET_ANY()... yes
checking for SSL_SESSION_cmp()... no
checking for SSL_set_tlsext_host_name() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_set_tlsext_host_name in openssl/ssl.h... yes
checking for CRYPTO_THREADID.ptr in openssl/crypto.h... yes
checking for EVP_PKEY_get0()... yes
checking for SSL_CTX_set_next_proto_select_cb()... yes
checking for EVP_CTRL_GCM_GET_TAG in openssl/evp.h... yes
checking for EC_curve_nist2nid()... yes
checking for X509_REVOKED_dup()... yes
checking for X509_STORE_CTX_get0_store()... yes
checking for SSL_CTX_set_alpn_select_cb()... yes
checking for SSL_CTX_set1_curves_list() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_CTX_set1_curves_list in openssl/ssl.h... yes
checking for SSL_CTX_set_ecdh_auto() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_CTX_set_ecdh_auto in openssl/ssl.h... yes
checking for SSL_get_server_tmp_key() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_get_server_tmp_key in openssl/ssl.h... yes
checking for SSL_is_server()... yes
checking for CRYPTO_lock()... yes
checking for SSL.ctx in openssl/ssl.h... yes
checking for BN_GENCB_new()... no
checking for BN_GENCB_free()... no
checking for BN_GENCB_get_arg()... no
checking for EVP_MD_CTX_new()... no
checking for EVP_MD_CTX_free()... no
checking for HMAC_CTX_new()... no
checking for HMAC_CTX_free()... no
checking for RAND_pseudo_bytes() in openssl/rand.h with -Werror=deprecated-declarations... yes
checking for X509_STORE_get_ex_data()... no
checking for X509_STORE_set_ex_data()... no
checking for X509_CRL_get0_signature()... no
checking for X509_REQ_get0_signature()... no
checking for X509_REVOKED_get0_serialNumber()... no
checking for X509_REVOKED_get0_revocationDate()... no
checking for X509_get0_tbs_sigalg()... no
checking for X509_STORE_CTX_get0_untrusted()... no
checking for X509_STORE_CTX_get0_cert()... no
checking for X509_STORE_CTX_get0_chain()... no
checking for OCSP_SINGLERESP_get0_id()... no
checking for SSL_CTX_get_ciphers()... no
checking for X509_up_ref()... no
checking for X509_CRL_up_ref()... no
checking for X509_STORE_up_ref()... no
checking for SSL_SESSION_up_ref()... no
checking for EVP_PKEY_up_ref()... no
checking for SSL_CTX_set_tmp_ecdh_callback() in openssl/ssl.h with -Werror=deprecated-declarations... yes
checking for SSL_CTX_set_min_proto_version() in openssl/ssl.h with -Werror=deprecated-declarations... no
checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... no
checking for SSL_CTX_get_security_level()... no
checking for X509_get0_notBefore()... no
checking for SSL_SESSION_get_protocol_version()... no
creating extconf.h
creating Makefile
compiling openssl_missing.c
compiling ossl.c
compiling ossl_asn1.c
compiling ossl_bio.c
compiling ossl_bn.c
compiling ossl_cipher.c
compiling ossl_config.c
compiling ossl_digest.c
compiling ossl_engine.c
compiling ossl_hmac.c
compiling ossl_ns_spki.c
compiling ossl_ocsp.c
compiling ossl_pkcs12.c
compiling ossl_pkcs5.c
compiling ossl_pkcs7.c
compiling ossl_pkey.c
compiling ossl_pkey_dh.c
compiling ossl_pkey_dsa.c
compiling ossl_pkey_ec.c
compiling ossl_pkey_rsa.c
compiling ossl_rand.c
compiling ossl_ssl.c
compiling ossl_ssl_session.c
compiling ossl_x509.c
compiling ossl_x509attr.c
compiling ossl_x509cert.c
compiling ossl_x509crl.c
compiling ossl_x509ext.c
compiling ossl_x509name.c
compiling ossl_x509req.c
compiling ossl_x509revoked.c
compiling ossl_x509store.c
linking shared-object openssl.su
/Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/lib/cext/linker.rb:54:in `link_bitcode': Linker failed (RuntimeError)
	from /Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/lib/cext/linker.rb:48:in `main'
	from /Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/lib/cext/linker.rb:108:in `<main>'
make: *** [openssl.su] Error 1
```

It must be noted that the log mentions bits of `1.0.0-rc3`.

Despite this error, the installation seems to have worked:

```
$ rvm truffleruby-1.0.0-rc5
Using /Users/thbar/.rvm/gems/truffleruby-1.0.0-rc5
$ bundle --version
Bundler version 1.16.3
$ which bundle
/Users/thbar/.rvm/rubies/truffleruby-1.0.0-rc5/bin/bundle
```

**Comment by eregon** [comment]
@thbar Thank you for the detailed report!
This is the same problem as https://github.com/oracle/truffleruby/issues/1386#issuecomment-410471567 , that is `llvm-link` is not found in `PATH` and in contrast to `clang` and `opt` TruffleRuby doesn't look for `llvm-link` in Homebrew and MacPorts LLVM `bin` directories. I fixed the bug in 1a4983265b2000d38ca0ca6eab689b3b6c125913 and it will be in the next release.

A workaround until then is to add LLVM's `bin` directory on PATH.
For Homebrew, that's:
```bash
export PATH="/usr/local/opt/llvm@4/bin:$PATH"
```

In your case, it seems the later RVM installation steps worked better due to, I guess, having openssl 1.0 in Homebrew, so the shipped OpenSSL C extension is already compiled against the right version. I plan to check for this case in the future, so there is no attempt to even recompile if there is already the right openssl version.

**Comment by eregon** [comment]
It is now documented again that adding LLVM's `bin` on `PATH` is necessary on macOS for 1.0.0-rc5: 7b0f39995313deb2f8fe84998e32219def42bb32.

**Comment by eregon** [comment]
I wrote an additional test for this scenario: 05381c1212c6ca007c9e1add83f2dcce6b63422f
I think we should be reasonably sure it works now, so I'll close this issue and it will be fixed in the next released.
@thbar Thank you for the report again.

**Comment by eregon** [comment]
This should now be fixed in the TruffleRuby 1.0.0-rc6 release.
@thbar Does `rvm install truffleruby` work out of the box for you now?

**Comment by thbar** [comment]
@eregon it's fixed (it's even working without the previous `PATH` trick for `llvm`, as mentioned in your docs).

**Comment by ioquatix** [comment]
@eregon maybe docs need to be updated?

```
^_^ > sudo port install clang-4.0 llvm-4.0
Portfile changed since last build; discarding previous state.
--->  Fetching distfiles for clang-4.0
--->  Verifying checksums for clang-4.0
--->  Extracting clang-4.0
--->  Configuring clang-4.0
Error: clang-4.0 has been replaced by clang-8.0; please install that instead.
Error: Failed to configure clang-4.0: obsolete port
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_lang_llvm-4.0/clang-4.0/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port clang-4.0 failed
```

**Comment by eregon** [comment]
@ioquatix Installing `clang`/`llvm` will no longer be needed in the next release, the docs already reflect that.
