### ISSUE TITLE
JRuby-compatible Java interop problems with wrapping Java return values

### ISSUE THREAD

**Issue by grddev** [oracle/truffleruby#1408]
After installing The following Ruby program fails when running under `truffleruby --jvm`. The program represents a small component extracted from a much larger code base (that was using a non-standard Java class rathern than Scanner).

```ruby
require 'java'
s = Java::JavaUtil::Scanner.new("123 456 token")
s.nextBigInteger; s.locale; s.match
```

Resulted in the following issue

```
.../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:383:in `wrap_java_value': java.lang.Character cannot be cast to com.oracle.truffle.api.interop.TruffleObject (ClassCastException) (RuntimeError)
	from org.truffleruby.language.dispatch.UncachedDispatchNode.executeDispatch(UncachedDispatchNode.java:85)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:42)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:112)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	from org.truffleruby.core.cast.BooleanCastNodeGen.executeBoolean(BooleanCastNodeGen.java:76)
	from org.truffleruby.language.control.IfNode.execute(IfNode.java:32)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
Translated to internal error
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:91:in `add_static_field'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `block in add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `each'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:190:in `build'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:267:in `make_proxy'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:389:in `wrap_java_value'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:91:in `add_static_field'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `block in add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `each'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:190:in `build'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:267:in `make_proxy'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:389:in `wrap_java_value'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_dispatcher.rb:45:in `block in method_for_dispatch'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `[]'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `locale'
	from test.rb:4:in `<main>
```

I have tried with various variations of the methods `next`, `nextBigInteger`, `nextBigDecimal`, `locale`, and `match`, and produced a couple different results.

With `s.nextBigDecimal; nextBigInteger; s.next; s.match` it produced the following results

```
.../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:383:in `wrap_java_value': java.util.regex.Matcher cannot be cast to com.oracle.truffle.api.interop.TruffleObject (ClassCastException) (RuntimeError)
	from org.truffleruby.language.dispatch.UncachedDispatchNode.executeDispatch(UncachedDispatchNode.java:85)
	from org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:116)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
	from org.truffleruby.language.dispatch.CachedUnboxedDispatchNode.executeDispatch(CachedUnboxedDispatchNode.java:79)
Translated to internal error
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_dispatcher.rb:45:in `block in method_for_dispatch'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `[]'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `match'
	from test.rb:4:in `<main>'
```

With `s.locale` first, I got the following
```
.../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:383:in `wrap_java_value': java.lang.IllegalAccessException cannot be cast to com.oracle.truffle.api.interop.TruffleObject (ClassCastException) (RuntimeError)
	from org.truffleruby.language.dispatch.UncachedDispatchNode.executeDispatch(UncachedDispatchNode.java:85)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:42)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:112)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	from org.truffleruby.core.cast.BooleanCastNodeGen.executeBoolean(BooleanCastNodeGen.java:76)
	from org.truffleruby.language.control.IfNode.execute(IfNode.java:32)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
Translated to internal error
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:49:in `invoke_java_method'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:443:in `unreflect_getter'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:85:in `add_static_field'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `block in add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `each'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:190:in `build'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:267:in `make_proxy'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:389:in `wrap_java_value'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:91:in `add_static_field'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `block in add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `each'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:80:in `add_static_fields'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:190:in `build'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:267:in `make_proxy'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_utilities.rb:389:in `wrap_java_value'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/java_dispatcher.rb:45:in `block in method_for_dispatch'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `[]'
	from .../graalvm-ce-1.0.0-rc5/Contents/Home/jre/languages/ruby/lib/truffle/java/proxy_builder.rb:262:in `locale'
	from test.rb:3:in `<main>'
```

**Comment by chrisseaton** [comment]
We only support a tiny part of JRuby-Style Java interop in TruffleRuby.

https://github.com/oracle/truffleruby/blob/master/doc/user/jruby-java-interop.md

We're actually considering removing it to a separate gem.

But we do have our own extensive approach to polyglot programming, which supports many languages, not just Java https://github.com/oracle/truffleruby/blob/master/doc/user/polyglot.md.

To use our approach use need to write

```ruby
s = Java.type('java.util.Scanner').new("123 456 token")
puts s.nextBigInteger.toString
puts s.locale.toString
puts s.match.toString
```

Are you able to share more of your code base using JRuby-style Java interop? We're interested in more use-cases.

**Comment by chrisseaton** [comment]
Sorry we're not planning to support JRuby-style interop any-time soon now. Thanks for your help diagnosing the issue and we know some people will want JRuby-style interop, but it's just not a priority immediately.
