### ISSUE TITLE
Cannot compile native extension for gem hamlit

### ISSUE THREAD

**Issue by jameschenjav** [oracle/truffleruby#1427]
ruby -v:
truffleruby 1.0.0-rc6, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]
os: Ubuntu 16.04.5 LTS

Is there anything I can do? 
```
$ gem install hamlit
Fetching: hamlit-2.8.10.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing hamlit:
	ERROR: Failed to build gem native extension.

    current directory: /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/hamlit-2.8.10/ext/hamlit
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/bin/truffleruby -r ./siteconf20180912-25533-177vnvq.rb extconf.rb
creating Makefile

current directory: /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/hamlit-2.8.10/ext/hamlit
make "DESTDIR=" clean

current directory: /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/hamlit-2.8.10/ext/hamlit
make "DESTDIR="
compiling hamlit.c
hamlit.c:272:5: error: statement requires expression of integer type ('VALUE' (aka 'void *') invalid)
    switch (value) {
    ^       ~~~~~
hamlit.c:273:12: error: expression is not an integer constant expression
      case Qtrue:
           ^~~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:429:15: note: expanded from macro 'Qtrue'
#define Qtrue ((VALUE)(&rb_tr_true))
              ^~~~~~~~~~~~~~~~~~~~~~
hamlit.c:277:12: error: expression is not an integer constant expression
      case Qnil:
           ^~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:430:14: note: expanded from macro 'Qnil'
#define Qnil ((VALUE)(&rb_tr_nil))
             ^~~~~~~~~~~~~~~~~~~~~
hamlit.c:279:12: error: expression is not an integer constant expression
      case Qfalse:
           ^~~~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:428:16: note: expanded from macro 'Qfalse'
#define Qfalse ((VALUE)(&rb_tr_false))
               ^~~~~~~~~~~~~~~~~~~~~~~
hamlit.c:384:3: error: statement requires expression of integer type ('VALUE' (aka 'void *') invalid)
  switch (value) {
  ^       ~~~~~
hamlit.c:385:10: error: expression is not an integer constant expression
    case Qtrue:
         ^~~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:429:15: note: expanded from macro 'Qtrue'
#define Qtrue ((VALUE)(&rb_tr_true))
              ^~~~~~~~~~~~~~~~~~~~~~
hamlit.c:395:10: error: expression is not an integer constant expression
    case Qfalse:
         ^~~~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:428:16: note: expanded from macro 'Qfalse'
#define Qfalse ((VALUE)(&rb_tr_false))
               ^~~~~~~~~~~~~~~~~~~~~~~
hamlit.c:397:10: error: expression is not an integer constant expression
    case Qnil:
         ^~~~
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/ruby.h:430:14: note: expanded from macro 'Qnil'
#define Qnil ((VALUE)(&rb_tr_nil))
             ^~~~~~~~~~~~~~~~~~~~~
8 errors generated.
Makefile:211: recipe for target 'hamlit.bc' failed
make: *** [hamlit.bc] Error 1

make failed, exit code 2

Gem files will remain installed in /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/hamlit-2.8.10 for inspection.
Results logged to /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/hamlit-2.8.10/gem_make.out
```

**Comment by jameschenjav** [comment]
I can't install rmagick and ruby-oci8 either:
```
Building native extensions.  This could take a while...
ERROR:  Error installing rmagick:
	ERROR: Failed to build gem native extension.

    current directory: /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/ext/RMagick
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/bin/truffleruby -r ./siteconf20180912-27042-177vnvq.rb extconf.rb
checking for clang... yes
checking for Magick-config... no
checking for pkg-config... yes
checking for outdated ImageMagick version (<= 6.4.9)... no
checking for presence of MagickWand API (ImageMagick version >= 6.9.0)... yes
checking for Ruby version >= 1.8.5... yes
checking for stdint.h... /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:468:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:600:in `try_cpp'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:1107:in `block in have_header'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:957:in `block in checking_for'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:362:in `block (2 levels) in postpone'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:332:in `open'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:362:in `block in postpone'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:332:in `open'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:358:in `postpone'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:956:in `checking_for'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/mri/mkmf.rb:1106:in `have_header'
	from extconf.rb:39:in `configure_headers'
	from extconf.rb:18:in `initialize'
	from extconf.rb:548:in `new'
	from extconf.rb:548:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/bin/truffleruby
```

ruby-oci8
```
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-oci8:
	ERROR: Failed to build gem native extension.

    current directory: /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.6/ext/oci8
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/bin/truffleruby -r ./siteconf20180912-27103-177vnvq.rb extconf.rb
checking for load library path...
  LD_LIBRARY_PATH...
    checking /usr/lib/oracle/12.1/client64/lib... yes
  /usr/lib/oracle/12.1/client64/lib/libclntsh.so.12.1 looks like an instant client.
checking for cc... ok
checking for gcc... yes
checking for LP64... yes
checking for sys/types.h... yes
checking for ruby header... ok
checking for OCIEnvCreate() in oci.h... no
/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.6/ext/oci8/oraconf.rb:1125:in `initialize': RuntimeError (RuntimeError)
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.6/ext/oci8/oraconf.rb:267:in `new'
	from /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/ruby/gems/2.4.0/gems/ruby-oci8-2.2.6/ext/oci8/oraconf.rb:267:in `get'
	from extconf.rb:22:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/bin/truffleruby
	--with-instant-client
	--without-instant-client
```

**Comment by nirvdrum** [comment]
@jameschenjav, thanks for the thorough report! Unfortunately, our C extension support is still evolving. We're anticipating much better support coming in the next (1.0.0 RC 7?) release. But we can try the gems you've listed specifically in the meanwhile.

It looks like for rmagick and ruby-oci8 you're either missing some development libraries or our build process isn't finding them. Do these gems install with MRI cleanly on the same machine?

**Comment by eregon** [comment]
Thank you for the report.

I took a look at the `rmagick` case.
I could reproduce on Fedora, and the problem seems to be that `-fopenmp` is passed to `clang` and the linker does not seem to support that (`/usr/bin/ld: cannot find -lomp`).
Specifically, RMagick's `extconf.rb` seems to call `MagickWand-config --cflags` which gives on my system: `-I/usr/include/ImageMagick-6 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16`.
Could you share the contents of the `mkmf.log`, whose path is printed at the end of `gem install rmagick` to confirm it is the same problem?

For `hamlit`, a workaround might be to use the original pure-Ruby `haml` gem, which could run quite efficiently on TruffleRuby thanks to our String representation (but I did not try it).

**Comment by jameschenjav** [comment]
@nirvdrum yes I can install them with MRI
```
$ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
$ gem uninstall ruby-oci8

Select gem to uninstall:
 1. ruby-oci8-2.2.5
 2. ruby-oci8-2.2.5.1
 3. ruby-oci8-2.2.6
 4. All versions
> 3
Successfully uninstalled ruby-oci8-2.2.6
$ gem install ruby-oci8
Fetching: ruby-oci8-2.2.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ruby-oci8-2.2.6
1 gem installed
$ gem uninstall rmagick
Successfully uninstalled rmagick-2.16.0
$ gem install rmagick
Fetching: rmagick-2.16.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rmagick-2.16.0
1 gem installed
```

The log shows clang could not find `oci.h` provided by the gem
```
conftest.c:3:10: fatal error: 'oci.h' file not found
#include <oci.h>
         ^
1 error generated.
"clang -o conftest -I/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include -I/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include/ruby/backward -I/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/include -I.  -g -Wimplicit-function-declaration -Wno-unknown-warning-option -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-unused-value -Wno-incompatible-pointer-types -ferror-limit=500 /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/ruby.o /home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib/cext/sulongmock.o conftest.c  -L. -L/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib      -L/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib  -L/usr/lib/oracle/12.1/client64/lib -Wl,-rpath,/usr/lib/oracle/12.1/client64/lib -lclntsh   -L/home/jav/.rbenv/versions/truffleruby-1.0.0-rc6/lib  -L/usr/lib/oracle/12.1/client64/lib -Wl,-rpath,/usr/lib/oracle/12.1/client64/lib -lclntsh  "
```

**Comment by eregon** [comment]
`gem install hamlit` succeeds on master:
```
$ gem i hamlit
Fetching hamlit-2.10.0.gem
Fetching thor-0.20.3.gem
Fetching temple-0.8.2.gem
Fetching tilt-2.0.10.gem
Successfully installed temple-0.8.2
Successfully installed thor-0.20.3
Successfully installed tilt-2.0.10
Building native extensions. This could take a while...
Successfully installed hamlit-2.10.0
4 gems installed
```
So it should work in the next release.
Thank you for the bug report!

**Comment by eregon** [comment]
@jameschenjav FYI, TruffleRuby 19.3.0 was released and that should at least let `hamlit` install.
