### ISSUE TITLE
childprocess 0.9.0 gem opt fail: UnboundMethod#bind, rb_data_typed_object_wrap

### ISSUE THREAD

**Issue by JongleurX** [oracle/truffleruby#1430]
In trying to test TruffleRuby with the [Redmine](https://www.redmine.org/) (a popular project-management tool), I found a gem (`childprocess`) that presents warnings upon installation.

# Environment

Name | Value
------ | ------
OS | Ubuntu 18.04.1 LTS
TruffleRuby | CE 1.0.0-rc6 (installed manually)
Gemfile | [Redmine 3.4-stable](http://www.redmine.org/projects/redmine/repository/entry/branches/3.4-stable/Gemfile)

# Repro steps

1. Download `graalvm-ce-1.0.0-rc6` manually and extract it.
2. Run the commands below (approximation based on `.bash_history`).

```console
jeremy@Ubuntu:~$ sudo apt install curl subversion postgresql postgresql-contrib llvm libssl zlib make clang libc++-dev libc++abi-dev libssl-dev libz-dev libxml2-dev pkg-config
jeremy@Ubuntu:~$ export PATH=/home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc6/bin:$PATH
jeremy@Ubuntu:~$ gu install ruby
jeremy@Ubuntu:~$ svn co https://svn.redmine.org/redmine/branches/3.4-stable redmine-3.4
jeremy@Ubuntu:~$ cd redmine-3.4
jeremy@Ubuntu:~/redmine-3.4$ cp -pR config/database.yml.example config/database.yml
jeremy@Ubuntu:~/redmine-3.4$ vi config/database.yml ## edit adapters to use postgresql
jeremy@Ubuntu:~/redmine-3.4$ gem install bundler
jeremy@Ubuntu:~/redmine-3.4$ bundle config build.nokogiri --use-system-libraries
jeremy@Ubuntu:~/redmine-3.4$ bundle install
jeremy@Ubuntu:~/redmine-3.4$ bundle exec rake generate_secret_token
jeremy@Ubuntu:~/redmine-3.4$ RAILS_ENV=development bundle exec rake db:migrate
```

# Errors

* [truffle] opt fail         UnboundMethod#bind (builtin) <split-36f3401d>               |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
* [truffle] opt fail         Truffle::CExt#rb_data_typed_object_wrap /home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc6/jre/languages/ruby/lib/truffle/truffle/cext.rb:1341|Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation() 

 # Notes

I searched but couldn't find anything similar for the first issue (`UnboundMethod#bind`). The second problem (`rb_data_typed_object_wrap`) may already be fixed in rc7, per #1422.

# Details

Click below to see the full stack trace for the errors.

<details><summary>childprocess 0.9.0</summary>
<p>

Fetching childprocess 0.9.0
[truffle] opt fail         UnboundMethod#bind (builtin) <split-36f3401d>               |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation() 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
	at org.truffleruby.core.module.ModuleOperations.includesModule(ModuleOperations.java:42)
	at org.truffleruby.core.module.ModuleOperations.assignableTo(ModuleOperations.java:56)
	at org.truffleruby.core.module.ModuleOperations.canBindMethodTo(ModuleOperations.java:71)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodTo(CanBindMethodToModuleNode.java:48)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodToUncached(CanBindMethodToModuleNode.java:44)
	at org.truffleruby.language.methods.CanBindMethodToModuleNodeGen.executeCanBindMethodToModule(CanBindMethodToModuleNodeGen.java:47)
	at org.truffleruby.core.method.UnboundMethodNodes$BindNode.bind(UnboundMethodNodes.java:79)
	at org.truffleruby.core.method.UnboundMethodNodesFactory$BindNodeFactory$BindNodeGen.execute(UnboundMethodNodesFactory.java:328)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)

[truffle] opt fail         Truffle::CExt#rb_data_typed_object_wrap /home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc6/jre/languages/ruby/lib/truffle/truffle/cext.rb:1341|Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation() 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
	at org.truffleruby.core.module.ModuleOperations.includesModule(ModuleOperations.java:42)
	at org.truffleruby.core.module.ModuleOperations.assignableTo(ModuleOperations.java:56)
	at org.truffleruby.core.module.ModuleOperations.canBindMethodTo(ModuleOperations.java:71)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodTo(CanBindMethodToModuleNode.java:48)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodToUncached(CanBindMethodToModuleNode.java:44)
	at org.truffleruby.language.methods.CanBindMethodToModuleNodeGen.executeCanBindMethodToModule(CanBindMethodToModuleNodeGen.java:47)
	at org.truffleruby.core.method.UnboundMethodNodes$BindNode.bind(UnboundMethodNodes.java:79)
	at org.truffleruby.core.method.UnboundMethodNodesFactory$BindNodeFactory$BindNodeGen.execute(UnboundMethodNodesFactory.java:328)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:94)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:108)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:79)
	at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:36)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)

[truffle] opt fail         rb_data_typed_object_wrap                                   |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation() 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: CompilerAsserts.neverPartOfCompilation()
	at org.truffleruby.core.module.ModuleOperations.includesModule(ModuleOperations.java:42)
	at org.truffleruby.core.module.ModuleOperations.assignableTo(ModuleOperations.java:56)
	at org.truffleruby.core.module.ModuleOperations.canBindMethodTo(ModuleOperations.java:71)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodTo(CanBindMethodToModuleNode.java:48)
	at org.truffleruby.language.methods.CanBindMethodToModuleNode.canBindMethodToUncached(CanBindMethodToModuleNode.java:44)
	at org.truffleruby.language.methods.CanBindMethodToModuleNodeGen.executeCanBindMethodToModule(CanBindMethodToModuleNodeGen.java:47)
	at org.truffleruby.core.method.UnboundMethodNodes$BindNode.bind(UnboundMethodNodes.java:79)
	at org.truffleruby.core.method.UnboundMethodNodesFactory$BindNodeFactory$BindNodeGen.execute(UnboundMethodNodesFactory.java:328)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:94)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:108)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:99)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:79)
	at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:36)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:39)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:31)
	at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:38)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:50)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:190)
	at org.truffleruby.language.dispatch.CachedSingletonDispatchNode.executeDispatch(CachedSingletonDispatchNode.java:93)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:43)
	at org.truffleruby.language.dispatch.CallDispatchHeadNode.call(CallDispatchHeadNode.java:41)
	at org.truffleruby.interop.RubyMessageResolution$ForeignInvokeNode.access(RubyMessageResolution.java:351)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignInvokeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:254)
	at org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignInvokeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:235)
	at org.truffleruby.interop.RubyMessageResolutionForeign$ForeignInvokeSubNode$INVOKERootNode.execute(RubyMessageResolutionForeign.java:277)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at com.oracle.truffle.api.interop.InteropAccessNode.doCached(InteropAccessNode.java:186)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:35)
	at com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:82)
	at com.oracle.truffle.api.interop.ForeignAccess.sendInvoke(ForeignAccess.java:496)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvoke.doInvoke(LLVMTruffleInvoke.java:102)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvoke.cachedId(LLVMTruffleInvoke.java:119)
	at com.oracle.truffle.llvm.nodes.intrinsics.interop.LLVMTruffleInvokeNodeGen.executeGeneric(LLVMTruffleInvokeNodeGen.java:50)
	at com.oracle.truffle.llvm.nodes.intrinsics.llvm.LLVMIntrinsicRootNodeFactory$LLVMIntrinsicExpressionNodeGen.execute(LLVMIntrinsicRootNodeFactory.java:36)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:226)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:86)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:70)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirectIntrinsic(LLVMDispatchNode.java:122)
	at com.oracle.truffle.llvm.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:64)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNode.doDirectCached(LLVMLookupDispatchNode.java:78)
	at com.oracle.truffle.llvm.nodes.func.LLVMLookupDispatchNodeGen.executeDispatch(LLVMLookupDispatchNodeGen.java:56)
	at com.oracle.truffle.llvm.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:75)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:396)
	at com.oracle.truffle.llvm.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:380)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute_generic1(LLVMWriteNodeFactory.java:980)
	at com.oracle.truffle.llvm.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:961)
	at com.oracle.truffle.llvm.nodes.base.LLVMBasicBlockNode.execute(LLVMBasicBlockNode.java:80)
	at com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:99)
	at com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:75)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:269)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:258)

</p>
</details>

**Comment by JongleurX** [comment]
I tried again using `1.0.0-rc7`, and the errors seem to have gone away. 👏

```console
$ curl -LOk https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc7/truffleruby-1.0.0-rc7-linux-amd64.tar.gz
$ tar xf truffleruby-1.0.0-rc7-linux-amd64.tar.gz
$ export PATH=/home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc7/bin:$PATH
$ gu install ruby
$ /home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc7/jre/languages/ruby/lib/truffle/post_install_hook.sh
$ /home/jeremy/Coding/Rails/graalvm-ce-1.0.0-rc7/jre/bin/gu rebuild-images ruby polyglot
$ cd redmine-3.4
$ gem install bundler
$ bundle config build.nokogiri --use-system-libraries
$ bundle install      # this process is very slow before "Fetching gem metadata..." is displayed
$ bundle exec rake generate_secret_token
$ RAILS_ENV=development bundle exec rake db:migrate
```

**Comment by chrisseaton** [comment]
Thanks very much. Sorry we didn't respond to the original issue more quickly.
