### ISSUE TITLE
mysql2 prepared statements

### ISSUE THREAD

**Issue by gmalette** [oracle/truffleruby#1435]
Prepared statements don't seem to work in 1.0.0-rc7 and mysql2 0.5.2

The following program will raise:

```ruby
require 'bundler'
Bundler.setup(:default)

require "mysql2"

dbconfig = {
  # insert mysql config
}
conn = Mysql2::Client.new(dbconfig)

stmt = conn.prepare("SELECT * FROM users WHERE id < ?")
puts stmt.execute(1).to_a.inspect
```

```
/Users/gmalette/.rubies/truffleruby-1.0.0-rc7/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion': Cannot convert LLVMTypedForeignObject:0x0 to LLVMNativePointer (IllegalStateException) (RuntimeError)
        from java.lang.Throwable.<init>(Throwable.java:287)
        from java.lang.Exception.<init>(Exception.java:84)
        from java.lang.RuntimeException.<init>(RuntimeException.java:80)
        from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
        from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
        from java.lang.Throwable.<init>(Throwable.java:265)
        from java.lang.Exception.<init>(Exception.java:66)
        from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
        from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
        from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
        from org.truffleruby.interop.RubyMessageResolution$ForeignToNativeNode.access(RubyMessageResolution.java:190)
        from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:503)
        from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:602)
        from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:588)
        from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode$TO_NATIVERootNode.execute(RubyMessageResolutionForeign.java:520)
Translated to internal error
        from /Users/gmalette/.rubies/truffleruby-1.0.0-rc7/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
        from /Users/gmalette/.rubies/truffleruby-1.0.0-rc7/lib/truffle/truffle/cext_ruby.rb:36:in `_execute'
        from /Users/gmalette/.gem/truffleruby/2.4.4/gems/mysql2-0.5.2/lib/mysql2/statement.rb:7:in `block in execute'
        from /Users/gmalette/.gem/truffleruby/2.4.4/gems/mysql2-0.5.2/lib/mysql2/statement.rb:6:in `handle_interrupt'
        from /Users/gmalette/.gem/truffleruby/2.4.4/gems/mysql2-0.5.2/lib/mysql2/statement.rb:6:in `handle_interrupt'
        from /Users/gmalette/.gem/truffleruby/2.4.4/gems/mysql2-0.5.2/lib/mysql2/statement.rb:6:in `execute'
        from db.rb:19:in `<main>'
```

However, avoiding prepared statements and using `query` directly works

```diff
- stmt = conn.prepare("SELECT * FROM users WHERE id < ?")
- puts stmt.execute(1).to_a.inspect
+ results = conn.query("SELECT * FROM users < 1")
+ puts results.to_a.inspect
```

**Comment by chrisseaton** [comment]
Thanks very much for the bug report. We're all working on `mysql2` right now actually - so we will give this a go and get back to you.

**Comment by eregon** [comment]
@gmalette Could you try again on the latest TruffleRuby release (19.2.0)?
I think it might address this.

**Comment by gmalette** [comment]
@felix-d are you still using this? Can you try?

**Comment by chrisseaton** [comment]
I'll take this issue over from the Shopify side and try it out.

**Comment by eregon** [comment]
@chrisseaton OK, thanks, I'll re-assign to you then.

**Comment by chrisseaton** [comment]
This works now - but requires the commits that I know @eregon has in process.

**Comment by chrisseaton** [comment]
I'm assigned but can't close!

**Comment by felix-d** [comment]
No `@gmalette` we're not using prepared statements anymore
