### ISSUE TITLE
oj: error: use of undeclared identifier 'rb_eEncodingError'

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1437]
Hello,
I'm trying one of my project on truffle ruby 1.0.0-rc8, and it uses oj gem. I'm getting this error

```
$ gem install oj
Fetching: oj-3.6.13.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing oj:
	ERROR: Failed to build gem native extension.

    current directory: ~/.gem/truffleruby/2.4.4/gems/oj-3.6.13/ext/oj
~/.rubies/truffleruby-1.0.0-rc8/bin/truffleruby -r ./siteconf20181028-97127-10xa5ts.rb extconf.rb
>>>>> Creating Makefile for truffleruby version 2.4.4 on x86_64-darwin <<<<<
creating Makefile

current directory: ~/.gem/truffleruby/2.4.4/gems/oj-3.6.13/ext/oj
make "DESTDIR=" clean

current directory: ~/.gem/truffleruby/2.4.4/gems/oj-3.6.13/ext/oj
make "DESTDIR="
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
custom.c:423:15: error: use of undeclared identifier 'rb_eEncodingError'
            rb_raise(rb_eEncodingError, "Invalid type for raw JSON.\n");
                     ^
1 error generated.
make: *** [custom.bc] Error 1

make failed, exit code 2

Gem files will remain installed in ~/.gem/truffleruby/2.4.4/gems/oj-3.6.13 for inspection.
Results logged to ~/.gem/truffleruby/2.4.4/extensions/x86_64-darwin/2.4.0/oj-3.6.13/gem_make.out
```

**Comment by deepj** [comment]
Noticed now, there is https://github.com/oracle/truffleruby/issues/1400

Anyway, I couldn't find this particular error has been reported.

**Comment by deepj** [comment]
@eregon reported https://github.com/ohler55/oj/issues/513

**Comment by eregon** [comment]
I added `rb_eEncodingError` in 8d4d80c1f9d9d75c8bfdd014e27525ff21e33397.

Now, installing `oj` fails with:
```
$ gem install oj
Building native extensions.  This could take a while...
ERROR:  Error installing oj:
	ERROR: Failed to build gem native extension.

    current directory: truffleruby/lib/ruby/gems/2.4.0/gems/oj-3.7.0/ext/oj
truffleruby/bin/truffleruby -r ./siteconf20181104-22422-17fl85z.rb extconf.rb
>>>>> Creating Makefile for truffleruby version 2.4.4 on x86_64-linux <<<<<
creating Makefile

current directory: truffleruby/lib/ruby/gems/2.4.0/gems/oj-3.7.0/ext/oj
make "DESTDIR=" clean

current directory: truffleruby/lib/ruby/gems/2.4.0/gems/oj-3.7.0/ext/oj
make "DESTDIR="
compiling cache8.c
compiling circarray.c
compiling code.c
compiling compat.c
compiling custom.c
compiling dump.c
dump.c:324:16: warning: variable 'cnt' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
    } else if (0xFC == (0xFE & b)) {
               ^~~~~~~~~~~~~~~~~~
dump.c:330:16: note: uninitialized use occurs here
    for (; 0 < cnt; cnt--, str++) {
               ^~~
dump.c:324:12: note: remove the 'if' if its condition is always true
    } else if (0xFC == (0xFE & b)) {
           ^~~~~~~~~~~~~~~~~~~~~~~~
dump.c:314:13: note: initialize the variable 'cnt' to silence this warning
    int         cnt;
                   ^
                    = 0
1 warning generated.
compiling dump_compat.c
compiling dump_leaf.c
compiling dump_object.c
compiling dump_strict.c
dump_strict.c:18:9: warning: 'rb_eEncodingError' macro redefined [-Wmacro-redefined]
#define rb_eEncodingError       rb_eException
        ^
truffleruby/lib/cext/include/truffleruby/constants.h:83:9: note: previous definition is here
#define rb_eEncodingError rb_tr_get_EncodingError()
        ^
1 warning generated.
compiling err.c
compiling fast.c
compiling hash.c
compiling hash_test.c
compiling mimic_json.c
compiling object.c
compiling odd.c
compiling oj.c
oj.c:23:9: warning: 'rb_eEncodingError' macro redefined [-Wmacro-redefined]
#define rb_eEncodingError       rb_eException
        ^
truffleruby/lib/cext/include/truffleruby/constants.h:83:9: note: previous definition is here
#define rb_eEncodingError rb_tr_get_EncodingError()
        ^
1 warning generated.
compiling parse.c
compiling rails.c
rails.c:1027:5: error: statement requires expression of integer type ('VALUE' (aka 'void *') invalid)
    switch (state) {
    ^       ~~~~~
rails.c:1028:10: error: expression is not an integer constant expression
    case Qtrue:
         ^~~~~
truffleruby/lib/cext/include/ruby/ruby.h:431:15: note: expanded from macro 'Qtrue'
#define Qtrue ((VALUE)(&rb_tr_true))
              ^~~~~~~~~~~~~~~~~~~~~~
rails.c:1029:10: error: expression is not an integer constant expression
    case Qfalse:
         ^~~~~~
truffleruby/lib/cext/include/ruby/ruby.h:430:16: note: expanded from macro 'Qfalse'
#define Qfalse ((VALUE)(&rb_tr_false))
               ^~~~~~~~~~~~~~~~~~~~~~~
rails.c:1031:10: error: expression is not an integer constant expression
    case Qnil:
         ^~~~
truffleruby/lib/cext/include/ruby/ruby.h:432:14: note: expanded from macro 'Qnil'
#define Qnil ((VALUE)(&rb_tr_nil))
             ^~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make: *** [Makefile:212: rails.bc] Error 1

make failed, exit code 2
```

The `warning: 'rb_eEncodingError' macro redefined` is a problem in `oj` I mentioned above.

The `switch` error is a problem in our current C extension support, which we might fix later.

**Comment by ohler55** [comment]
Did the latest changes n the branch work for you?

**Comment by eregon** [comment]
They do, thank you. (also mentioned in https://github.com/ohler55/oj/issues/513#issuecomment-437241364)

**Comment by deepj** [comment]
I guess this can be closed since `oj` is possible to compile "successfully". On the other hand, `require 'oj'` fails anyway...

**Comment by ohler55** [comment]
How does it fail?

**Comment by deepj** [comment]
@ohler55 

```
$ ruby -v
truffleruby 1.0.0-rc10, like ruby 2.4.4, GraalVM CE Native [x86_64-darwin]
$ gem list | grep oj
oj (3.7.4)
$ irb
irb(main):001:0> require 'oj'
RuntimeError: Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.lang.RuntimeException.<init>(RuntimeException.java:80)
	from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
	from com.oracle.truffle.api.interop.InteropAccessNode.createMessageTarget(InteropAccessNode.java:261)
	from com.oracle.truffle.api.interop.InteropAccessNodeGen.executeAndSpecialize(InteropAccessNodeGen.java:72)
	from com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:45)
	from com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:69)
	from com.oracle.truffle.api.interop.ForeignAccess.sendToNative(ForeignAccess.java:432)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/oj-3.7.4/lib/oj.rb:21:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc10/bin/irb:29:in `<main>'
```

**Comment by ohler55** [comment]
I see. That gets down into the internals of Truffle. I can imagine that getting C extensions to work as expected is going to be a painful process. If there is anything I can do let me know.

**Comment by deepj** [comment]
@eregon I guess this has been fixed. Anyway, there is another issue with oj, see https://github.com/oracle/truffleruby/issues/1437#issuecomment-444677941 but this might be resolved by changes with native extensions in RC12

**Comment by ohler55** [comment]
Good to know progress is being made. I appreciate the updates.

**Comment by deepj** [comment]
OK. With RC12 there is a new issue

```
irb(main):001:0> require 'oj'
ERROR: pthread_mutex_init is unsupported!
truffleruby: org.graalvm.polyglot.PolyglotException: com.oracle.truffle.llvm.runtime.LLVMExitException
Original Internal Error:
com.oracle.truffle.llvm.runtime.LLVMExitException
```

@eregon ^^

**Comment by ohler55** [comment]
Is there an equivalent in the OS you are using?

**Comment by eregon** [comment]
@ohler55 I'm pretty sure it's a Sulong bug (our way to run C extensions), not a missing OS feature.

@deepj Would you mind opening a new issue to avoid mixing different bugs? This particular issue might also be present with other C extensions, so it seems even more important to have its own bug.

**Comment by deepj** [comment]
@eregon of course. I wanted to make it anyway.

**Comment by eregon** [comment]
@deepj Thanks!
Let's close this as the original issue (`use of undeclared identifier 'rb_eEncodingError'`) is solved, as well as  the conversion to native pointer.
