### ISSUE TITLE
sassc: `Native': undefined method `enum' for SassC::Native:Module

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1451]
Hello,
I'm getting with truffleruby 1.0.0-rc9 on macOS 10.14 the following issue when I'm trying to use `sassc`. `sassc` is an import gem for Rails since original Ruby implementation `sass` will become EOL in March 2019 . Yes, Rails 6.0 will have `webpacker` by default, and `sprocket` will become "obselete". But many older projects depend on `sass` and `sprocket`. 

To reproduce:

```ruby
require 'sassc'

template = <<-SCSS
.foo {
  baz: bang; }
      SCSS
      expected_output = <<-CSS
/* line 1, stdin */
.foo {
  baz: bang; }
CSS

puts SassC::Engine.new(template, line_comments: true).render
```

Error:

```
~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native/sass_value.rb:7:in `Native': undefined method `enum' for SassC::Native:Module (NoMethodError)
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native/sass_value.rb:4:in `SassC'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native/sass_value.rb:3:in `<top (required)>'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native.rb:13:in `require_relative'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native.rb:13:in `Native'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native.rb:6:in `SassC'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc/native.rb:5:in `<top (required)>'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc.rb:7:in `require_relative'
	from ~/.gem/truffleruby/2.4.4/gems/sassc-2.0.0/lib/sassc.rb:7:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from sassc.rb:1:in `require'
	from sassc.rb:1:in `<main>'
```

There is no issue on Ruby 2.5.3

**Comment by deepj** [comment]
@eregon if there is no issue with the above code in the recent master. Feel free close this.

**Comment by deepj** [comment]
@eregon this can be closed. The code above works in RC16. No issue is occurred
