### ISSUE TITLE
falcon: Message not supported: TO_NATIVE (UnsupportedMessageException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1452]
Based on @eregon's request https://github.com/socketry/async/issues/29#issuecomment-436277623

```
D, [2018-11-06T08:24:09.330000 #22009] DEBUG -- Async::IO::Socket: Binding to #<Addrinfo: 127.0.0.1:9292 TCP>
D, [2018-11-06T08:24:09.355000 #22009] DEBUG -- Async::IO::Socket: Binding to #<Addrinfo: [::1]:9292 TCP>
D, [2018-11-06T08:24:09.370000 #22009] DEBUG -- <Async::Reactor:0x6ee stopped=false>: Exiting run-loop because finished.
~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion': Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException) (RuntimeError)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.lang.RuntimeException.<init>(RuntimeException.java:80)
	from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
	from org.truffleruby.interop.RubyMessageResolution$ForeignToNativeNode.access(RubyMessageResolution.java:190)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:503)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:602)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:588)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode$TO_NATIVERootNode.execute(RubyMessageResolutionForeign.java:520)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/truffle/truffle/cext_ruby.rb:36:in `close'
	from ~/.gem/truffleruby/2.4.4/gems/async-1.10.3/lib/async/reactor.rb:208:in `close'
	from ~/.gem/truffleruby/2.4.4/gems/async-1.10.3/lib/async/reactor.rb:56:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command/serve.rb:97:in `run'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command/serve.rb:124:in `invoke'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/lib/falcon/command.rb:70:in `invoke'
	from ~/.gem/truffleruby/2.4.4/gems/falcon-0.19.2/bin/falcon:26:in `<top (required)>'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `load'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `load'
	from ~/.gem/truffleruby/2.4.4/bin/falcon:23:in `<main>'
```

To reproduce:

```ruby
run lambda {|env| [200, {}, ["Hello World"]]}
```

Then run it:

```
falcon --verbose serve -c the-script-above.rb
```

**Comment by deepj** [comment]
It's possible to skip that using `NIO4R_PURE=true` environment variable. Unfortunately, `falcon` uses a forking model => https://github.com/socketry/falcon#memory-usage so it doesn't run.

**Comment by deepj** [comment]
@eregon this can be closed. It doesn't happen anymore

**Comment by eregon** [comment]
@deepj Thanks for checking and reporting this!
In general, with the new approach to C extensions, we should no longer have "Cannot convert to native" errors, because every Ruby object can now be stored in native memory.
