### ISSUE TITLE
mini_racer: `process_args': Unknown argument: -stdlib=libc++

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1453]
I've tried to install `mini_racer` on `truffle-ruby-1.0.0.rc9`, and I got this issue

```
$ gem install mini_racer
ERROR:  Error installing mini_racer:
	ERROR: Failed to build gem native extension.

    current directory: ~/.gem/truffleruby/2.4.4/gems/mini_racer-0.2.4/ext/mini_racer_extension
~/.rubies/truffleruby-1.0.0-rc9/bin/truffleruby -r ./siteconf20181106-34762-1kf6esd.rb extconf.rb
checking for -lpthread... yes
checking for -lobjc... yes
creating Makefile

current directory: ~/.gem/truffleruby/2.4.4/gems/mini_racer-0.2.4/ext/mini_racer_extension
make "DESTDIR=" clean

current directory: ~/.gem/truffleruby/2.4.4/gems/mini_racer-0.2.4/ext/mini_racer_extension
make "DESTDIR="
compiling mini_racer_extension.cc
clang-4.0: warning: argument unused during compilation: '-rdynamic' [-Wunused-command-line-argument]
In file included from mini_racer_extension.cc:2:
In file included from ~/.rubies/truffleruby-1.0.0-rc9/lib/cext/include/ruby.h:33:
~/.rubies/truffleruby-1.0.0-rc9/lib/cext/include/ruby/ruby.h:830:1: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
struct RBasic {
^
In file included from mini_racer_extension.cc:6:
~/.rubies/truffleruby-1.0.0-rc9/lib/cext/include/ruby/encoding.h:281:1: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
struct rb_econv_t {};
^
2 warnings generated.
linking shared-object mini_racer_extension.su
~/.rubies/truffleruby-1.0.0-rc9/lib/cext/linker.rb:67:in `process_args': Unknown argument: -stdlib=libc++ (RuntimeError)
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/cext/linker.rb:21:in `main'
	from ~/.rubies/truffleruby-1.0.0-rc9/lib/cext/linker.rb:150:in `<main>'
make: *** [mini_racer_extension.su] Error 1

make failed, exit code 2
```

**Comment by chrisseaton** [comment]
Are you using some abstraction interface to `mini_racer`, such as `execjs`? Could we substitute our JS interpreter instead?

**Comment by deepj** [comment]
This is one of Rails projects on which I'm recently working. And `mini_racer` is used in Rails Assets Pipeline using `execjs`. Yes, it'd be possible to use GraalVM JavaScript interpreter.

I just was curious if sulong could run something like `mini_racer` with embedded V8.

**Comment by deepj** [comment]
@eregon This can be closed. The error is not occurred anymore in this context. It's possible to compile the most recent gem without any issue.
