### ISSUE TITLE
Pressing arrow as first key in `irb` crashes it

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1486]
If I run an irb console, pressing any of the arrow keys as first key will crash the console. If I press anything else, a letter, enter, then the arrow keys work just as one would expect.

I'm using `truffleruby 1.0.0-rc9, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]`
On Ubuntu 16.04, installed through RVM

Upon pressing the key, this is the output, and then things will hang indefinetly.
```
truffleruby-1.0.0-rc9 :001 > Exception in thread "NonBlockingInputStreamThread" java.lang.AssertionError: No current context available.
        at java.lang.Throwable.<init>(Throwable.java:265)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.AssertionError.<init>(AssertionError.java:58)
        at java.lang.AssertionError.<init>(AssertionError.java:74)
        at com.oracle.truffle.polyglot.PolyglotContextImpl.requireContext(PolyglotContextImpl.java:290)
        at com.oracle.truffle.polyglot.PolyglotImpl$EngineImpl.getCurrentContext(PolyglotImpl.java:512)
        at com.oracle.truffle.api.TruffleLanguage.getCurrentContext(TruffleLanguage.java:1291)
        at org.truffleruby.RubyLanguage.getCurrentContext(RubyLanguage.java:109)
        at org.truffleruby.language.RubyBaseNode.getContext(RubyBaseNode.java:90)
        at org.truffleruby.language.methods.ExceptionTranslatingNode.translate(ExceptionTranslatingNode.java:90)
        at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:54)
        at org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:42)
        at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
        at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:118)
        at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:223)
        at org.truffleruby.RubyContext.send(RubyContext.java:453)
        at org.truffleruby.core.adapters.InputStreamAdapter.read(InputStreamAdapter.java:29)
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:291)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:199)
Caused by: Attached Guest Language Frames (1)
```

Once this happens, the irb just hangs. If I ctrl-c, then over about a minute, lots of spam will be output before finally dieing. I join the file with all the spam.

[truffleruby-irb-arrow-errors.txt](https://github.com/oracle/truffleruby/files/2626198/truffleruby-irb-arrow-errors.txt)

**Comment by deepj** [comment]
I guess this is a duplicity of #1478

**Comment by MaxLap** [comment]
Wow, my bad, didn't think of checking with the name of exception, I just searched for irb... 

Well, on my side this reproduces 100% of the time.
