### ISSUE TITLE
Range with excluding and float while calling rand causes TypeError: cannot exclude non Integer end value

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1506]
No issue under MRI.

To reproduce:
```ruby
rand(0...1.0)
```

Error:
```
TypeError: cannot exclude non Integer end value
	from (irb):2:in `max'
	from (irb):2:in `random_range'
	from (irb):2:in `random'
	from (irb):2:in `rand'
	from (irb):2
	from ~/.rubies/truffleruby-1.0.0-rc9/bin/irb:29:in `<main>'
```

**Comment by deepj** [comment]
This causes an issue to run Rubocop specs.

```
bundle exec rake spec

An error occurred while loading ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb.
Failure/Error: -rand(0...1.0),

TypeError:
  cannot exclude non Integer end value
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:58:in `max'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:58:in `random_range'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:58:in `random'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:58:in `rand'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:58:in `block (3 levels) in <top (required)>'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:56:in `block (2 levels) in <top (required)>'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:91:in `block in <top (required)>'
# ./spec/rubocop/cop/rails/pluralization_grammar_spec.rb:3:in `<top (required)>'
# ./tasks/spec_runner.rake:29:in `block in run_specs'
# ./tasks/spec_runner.rake:41:in `with_encoding'
# ./tasks/spec_runner.rake:25:in `run_specs'
# ./tasks/spec_runner.rake:112:in `block in <top (required)>'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `call'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
# ~/.rubies/truffleruby-1.0.0-rc13/lib/mri/monitor.rb:214:in `mon_synchronize'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
# ~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.5-compliant syntax, but you are running 2.4.4.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Randomized with seed 48626


Finished in 0.108 seconds (files took 2 minutes 51.3 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 48626
```

**Comment by gogainda** [comment]
fixed in pull/2218
