### ISSUE TITLE
BSON::ByteBuffer#put_hash causes Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1508]
To reproduce:
```ruby
require 'bson'

buffer = BSON::ByteBuffer.new
buffer.put_hash({}, false)
```

Error:

```
RuntimeError: Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (IllegalStateException)
	from java.lang.Throwable.<init>(Throwable.java:287)
	from java.lang.Exception.<init>(Exception.java:84)
	from java.lang.RuntimeException.<init>(RuntimeException.java:80)
	from java.lang.IllegalStateException.<init>(IllegalStateException.java:75)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode$LLVMObjectToNativeNode.transitionToNative(LLVMToNativeNode.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:301)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen$LLVMObjectToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:201)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNode.doOther(LLVMToNativeNode.java:78)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeAndSpecialize(LLVMToNativeNodeGen.java:129)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMToNativeNodeGen.executeWithTarget(LLVMToNativeNodeGen.java:50)
Caused by:
Message not supported: TO_NATIVE (UnsupportedMessageException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from com.oracle.truffle.api.interop.InteropException.<init>(InteropException.java:52)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.<init>(UnsupportedMessageException.java:57)
	from com.oracle.truffle.api.interop.UnsupportedMessageException.raise(UnsupportedMessageException.java:84)
	from org.truffleruby.interop.RubyMessageResolution$ForeignToNativeNode.access(RubyMessageResolution.java:190)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode.accessWithTarget(RubyMessageResolutionForeign.java:506)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeAndSpecialize(RubyMessageResolutionForeignFactory.java:602)
	from org.truffleruby.interop.RubyMessageResolutionForeignFactory$ForeignToNativeSubNodeGen.executeWithTarget(RubyMessageResolutionForeignFactory.java:588)
	from org.truffleruby.interop.RubyMessageResolutionForeign$ForeignToNativeSubNode$TO_NATIVERootNode.execute(RubyMessageResolutionForeign.java:523)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc10/lib/truffle/truffle/cext_ruby.rb:36:in `put_hash'
	from (irb):6
	from ~/.rubies/truffleruby-1.0.0-rc10/bin/irb:29:in `<main>'
```

**Comment by chrisseaton** [comment]
@aardvark179 can you take a look, please?

**Comment by deepj** [comment]
@eregon @chrisseaton @aardvark179 OK with RC12. This can be closed as well.

Only what I noticed is the following difference

MRI:
```
irb(main):004:0> buffer.put_hash({}, false)
=> #<BSON::ByteBuffer:0x00007fc7b2174e00>
```

TruffleRuby 1.0.0 RC12

```
irb(main):004:0> buffer.put_hash({}, false)
=> #<BSON::ByteBuffer:0xd58>
```

The object's hash is shorter in case of TruffleRuby 1.0.0 RC12.

**Comment by aardvark179** [comment]
Glad to hear this one is working in RC12.
