### ISSUE TITLE
Running Puma tests are aborted without any reason

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1526]
To reproduce

```
git clone https://github.com/puma/puma.git
cd puma
bundle install
bundle exec rake spec --trace
```

Error:

```
bundle exec rake test --trace
** Invoke test (first_time)
** Invoke compile (first_time)
** Invoke compile:x86_64-darwin (first_time)
** Invoke compile:puma_http11:x86_64-darwin (first_time)
** Invoke copy:puma_http11:x86_64-darwin:2.4.4 (first_time)
** Invoke lib/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/puma_http11/2.4.4/puma_http11.su (first_time, not_needed)
** Invoke tmp/x86_64-darwin/puma_http11/2.4.4 (first_time, not_needed)
** Invoke tmp/x86_64-darwin/puma_http11/2.4.4/Makefile (first_time, not_needed)
** Invoke tmp/x86_64-darwin/puma_http11/2.4.4 (not_needed)
** Invoke ext/puma_http11/extconf.rb (first_time, not_needed)
** Invoke ext/puma_http11/http11_parser.c (first_time, not_needed)
** Invoke ext/puma_http11/http11_parser.rl (first_time, not_needed)
** Invoke ext/puma_http11/io_buffer.c (first_time, not_needed)
** Invoke ext/puma_http11/mini_ssl.c (first_time, not_needed)
** Invoke ext/puma_http11/puma_http11.c (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/History.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage (first_time, not_needed)
** Invoke History.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/LICENSE (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage (not_needed)
** Invoke LICENSE (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage (not_needed)
** Invoke README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin (first_time, not_needed)
** Invoke bin/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin/puma-wild (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin (not_needed)
** Invoke bin/puma-wild (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin/pumactl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/bin (not_needed)
** Invoke bin/pumactl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/architecture.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (first_time, not_needed)
** Invoke docs/architecture.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/deployment.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/deployment.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images/puma-connection-flow-no-reactor.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images (first_time, not_needed)
** Invoke docs/images/puma-connection-flow-no-reactor.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images/puma-connection-flow.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images (not_needed)
** Invoke docs/images/puma-connection-flow.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images/puma-general-arch.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/images (not_needed)
** Invoke docs/images/puma-general-arch.png (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/nginx.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/nginx.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/plugins.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/plugins.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/restart.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/restart.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/signals.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/signals.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs/systemd.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/docs (not_needed)
** Invoke docs/systemd.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/PumaHttp11Service.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (first_time, not_needed)
** Invoke ext/puma_http11/PumaHttp11Service.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/ext_help.h (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/ext_help.h (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/extconf.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/extconf.rb (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/http11_parser.c (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/http11_parser.c (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/http11_parser.h (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/http11_parser.h (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/http11_parser.java.rl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/http11_parser.java.rl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/http11_parser.rl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/http11_parser.rl (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/http11_parser_common.rl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/http11_parser_common.rl (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/io_buffer.c (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/io_buffer.c (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/mini_ssl.c (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/mini_ssl.c (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma/Http11.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma (first_time, not_needed)
** Invoke ext/puma_http11/org/jruby/puma/Http11.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma/Http11Parser.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma (not_needed)
** Invoke ext/puma_http11/org/jruby/puma/Http11Parser.java (first_time, not_needed)
** Invoke ext/puma_http11/http11_parser.java.rl (not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma/MiniSSL.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/org/jruby/puma (not_needed)
** Invoke ext/puma_http11/org/jruby/puma/MiniSSL.java (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11/puma_http11.c (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/ext/puma_http11 (not_needed)
** Invoke ext/puma_http11/puma_http11.c (not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib (first_time, not_needed)
** Invoke lib/puma.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/accept_nonblock.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/accept_nonblock.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/app/status.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/app (first_time, not_needed)
** Invoke lib/puma/app/status.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/binder.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/binder.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/cli.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/cli.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/client.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/client.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/cluster.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/cluster.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/commonlogger.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/commonlogger.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/compat.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/compat.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/configuration.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/configuration.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/const.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/const.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/control_cli.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/control_cli.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/convenient.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/convenient.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/daemon_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/daemon_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/delegation.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/delegation.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/detect.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/detect.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/dsl.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/dsl.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/events.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/events.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/io_buffer.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/io_buffer.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/java_io_buffer.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/java_io_buffer.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/jruby_restart.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/jruby_restart.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/launcher.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/launcher.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/minissl.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/minissl.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/null_io.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/null_io.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/plugin.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/plugin.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/plugin/tmp_restart.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/plugin (first_time, not_needed)
** Invoke lib/puma/plugin/tmp_restart.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack/backports/uri/common_193.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack/backports/uri (first_time, not_needed)
** Invoke lib/puma/rack/backports/uri/common_193.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack/builder.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack (first_time, not_needed)
** Invoke lib/puma/rack/builder.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack/urlmap.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack (not_needed)
** Invoke lib/puma/rack/urlmap.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/rack_default.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/rack_default.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/reactor.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/reactor.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/runner.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/runner.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/server.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/server.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/single.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/single.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/state_file.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/state_file.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/tcp_logger.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/tcp_logger.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/thread_pool.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/thread_pool.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma/util.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/puma (not_needed)
** Invoke lib/puma/util.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/rack/handler/puma.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/lib/rack/handler (first_time, not_needed)
** Invoke lib/rack/handler/puma.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle (first_time, not_needed)
** Invoke tools/jungle/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d (first_time, not_needed)
** Invoke tools/jungle/init.d/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d (not_needed)
** Invoke tools/jungle/init.d/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d/run-puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/init.d (not_needed)
** Invoke tools/jungle/init.d/run-puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d (first_time, not_needed)
** Invoke tools/jungle/rc.d/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d (not_needed)
** Invoke tools/jungle/rc.d/puma (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d/puma.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/rc.d (not_needed)
** Invoke tools/jungle/rc.d/puma.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart (first_time, not_needed)
** Invoke tools/jungle/upstart/README.md (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart/puma-manager.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart (not_needed)
** Invoke tools/jungle/upstart/puma-manager.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart/puma.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/jungle/upstart (not_needed)
** Invoke tools/jungle/upstart/puma.conf (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools/trickletest.rb (first_time, not_needed)
** Invoke tmp/x86_64-darwin/stage/tools (first_time, not_needed)
** Invoke tools/trickletest.rb (first_time, not_needed)
** Execute copy:puma_http11:x86_64-darwin:2.4.4
install -c tmp/x86_64-darwin/puma_http11/2.4.4/puma_http11.su lib/puma/puma_http11.su
cp tmp/x86_64-darwin/puma_http11/2.4.4/puma_http11.su tmp/x86_64-darwin/stage/lib/puma/puma_http11.su
** Execute compile:puma_http11:x86_64-darwin
** Execute compile:x86_64-darwin
** Execute compile
** Invoke ensure_no_puma_gem (first_time)
** Execute ensure_no_puma_gem
** Execute test
Run options: --seed 46966

# Running:

.....rake aborted!
Command failed with status (1): [ruby -w -I"lib" -I"~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib" "~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/test_app_status.rb" "test/test_binder.rb" "test/test_cli.rb" "test/test_config.rb" "test/test_events.rb" "test/test_http10.rb" "test/test_http11.rb" "test/test_integration.rb" "test/test_iobuffer.rb" "test/test_minissl.rb" "test/test_null_io.rb" "test/test_persistent.rb" "test/test_puma_server.rb" "test/test_puma_server_ssl.rb" "test/test_pumactl.rb" "test/test_rack_handler.rb" "test/test_rack_server.rb" "test/test_tcp_logger.rb" "test/test_tcp_rack.rb" "test/test_thread_pool.rb" "test/test_unix_socket.rb" "test/test_web_server.rb" ]
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/testtask.rb:130:in `block (3 levels) in define'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/file_utils.rb:57:in `call'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/file_utils.rb:57:in `sh'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/file_utils.rb:105:in `ruby'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/testtask.rb:117:in `block (2 levels) in define'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/file_utils_ext.rb:59:in `verbose'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/testtask.rb:111:in `block in define'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `call'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
~/.rubies/truffleruby-1.0.0-rc10/lib/mri/monitor.rb:214:in `mon_synchronize'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
~/.gem/truffleruby/2.4.4/bin/rake:23:in `load'
~/.gem/truffleruby/2.4.4/bin/rake:23:in `load'
~/.gem/truffleruby/2.4.4/bin/rake:23:in `<top (required)>'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `__send__'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
~/.gem/truffleruby/2.4.4/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `load'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `load'
~/.gem/truffleruby/2.4.4/bin/bundle:23:in `<main>'
Tasks: TOP => test
```

**Comment by deepj** [comment]
Still reproducible in RC11

**Comment by deepj** [comment]
@eregon @chrisseaton I guess this can be closed. At least in RC13 or RC14-dev I can run these tests.

**Comment by chrisseaton** [comment]
Thanks!
