### ISSUE TITLE
Truffle error message

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1535]
I'm getting the printout bellow when running the full spec suite for my application.  Running each spec file individually does not output anything wrong.  I've not managed to reproduce this with a short spec file. 

To reproduce this I think one needs to clone my repo: 

https://github.com/rbotafogo/cantata

and run the specs in the spec directory with:

```
$ ruby --polyglot --jvm -Xsingle_threaded -S rspec tests.rb -f documentation
```

```
[truffle] opt fail         #each_with_index resource:/truffleruby/core/enumerable.rb:334 <split-1af1f99d>|Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: too many loop explosion iterations - does the explosion not terminate for method HotSpotMethod<OutgoingForeignCallNodeGen.executeCall(VirtualFrame, TruffleObject, Object[])>? 
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: too many loop explosion iterations - does the explosion not terminate for method HotSpotMethod<OutgoingForeignCallNodeGen.executeCall(VirtualFrame, TruffleObject, Object[])>?
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: too many loop explosion iterations - does the explosion not terminate for method HotSpotMethod<OutgoingForeignCallNodeGen.executeCall(VirtualFrame, TruffleObject, Object[])>?
	at org.graalvm.compiler.replacements.PEGraphDecoder.tooManyLoopExplosionIterations(PEGraphDecoder.java:605)
	at org.graalvm.compiler.replacements.PEGraphDecoder.checkLoopExplosionIteration(PEGraphDecoder.java:599)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:506)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:414)
	at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:556)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:436)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.fastPartialEvaluation(PartialEvaluator.java:475)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.createGraph(PartialEvaluator.java:220)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:382)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:546)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:495)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:169)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:224)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:710)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:776)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:42)
```

**Comment by eregon** [comment]
@rbotafogo Can you still reproduce with rc10?

**Comment by rbotafogo** [comment]
No.  I don't get the same error.  

Thanks for the fix
