### ISSUE TITLE
PolyglotException: truffleposix_stat_mode is not available

### ISSUE THREAD

**Issue by rahmanusta** [oracle/truffleruby#1536]
I'm trying native-image tool with ruby. However, I'm getting the following error.
```
Rahmans-MacBook-Air:classes usta$ ./org.asciidoctor.asciidoctornative 
[ruby] WARNING could not determine TruffleRuby's home - the standard library will not be available - set -Xhome= or use -Xlog=config to see details
[ruby] WARNING could not determine TruffleRuby's home - the standard library will not be available - set -Xhome= or use -Xlog=config to see details
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.lang.Throwable.<init>(Throwable.java:310)
        at java.lang.Exception.<init>(Exception.java:102)
        at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
        at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
        at com.oracle.svm.reflect.proxies.Proxy_1_AsciidoctorNative_main.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: org.graalvm.polyglot.PolyglotException: truffleposix_stat_mode is not available (NotImplementedError)
```
What is the problem here ?

**Comment by eregon** [comment]
This should be fixed in 23.0 as the home is automatically copied and detected.
