### ISSUE TITLE
hiredis fails to compile

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1546]
hiredis is notably used by Discourse.

```
$ gem install hiredis
Fetching: hiredis-0.6.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing hiredis:
	ERROR: Failed to build gem native extension.

    current directory: truffleruby/lib/ruby/gems/2.4.0/gems/hiredis-0.6.3/ext/hiredis_ext
truffleruby/bin/truffleruby -r ./siteconf20190122-24515-1xs7lf8.rb extconf.rb
checking for sys/socket.h... yes
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb net.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb hiredis.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb sds.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb async.c
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb read.c
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o
checking for rb_thread_fd_select()... yes
creating Makefile

current directory: truffleruby/lib/ruby/gems/2.4.0/gems/hiredis-0.6.3/ext/hiredis_ext
make "DESTDIR=" clean

current directory: truffleruby/lib/ruby/gems/2.4.0/gems/hiredis-0.6.3/ext/hiredis_ext
make "DESTDIR="
compiling connection.c
compiling hiredis_ext.c
compiling reader.c
linking shared-object hiredis/ext/hiredis_ext.su
llvm-link: ./../../vendor/hiredis/libhiredis.a:1:2: error: expected integer
!<arch>
 ^
llvm-link: error loading file './../../vendor/hiredis/libhiredis.a'
truffleruby/lib/cext/linker.rb:96:in `link_bitcode': Linker failed: ["llvm-link", "-o", "out.bc", "connection.bc", "hiredis_ext.bc", "reader.bc", "./../../vendor/hiredis/libhiredis.a"] (RuntimeError)
	from truffleruby/lib/cext/linker.rb:27:in `main'
	from truffleruby/lib/cext/linker.rb:150:in `<main>'
make: *** [Makefile:229: hiredis_ext.su] Error 1

make failed, exit code 2
```

This is due to hiredis-rb [building a static version of the hiredis library](https://github.com/redis/hiredis-rb/blob/61bb83eef86d8dc730f3352ba1d0aabe548a4d3a/ext/hiredis_ext/extconf.rb#L32).

One way might be to change hiredis-rb to build a dynamic library, or to support static libraries (#1088).

**Comment by nirvdrum** [comment]
This will be an interesting one to benchmark, too. It's an optional component intended to be faster than the pure Ruby driver.

**Comment by eregon** [comment]
`gem install hiredies` and `ruby -rhiredis -e0` now succeed on master:
```
$ gem i hiredis
Fetching hiredis-0.6.3.gem
Building native extensions. This could take a while...
Successfully installed hiredis-0.6.3
1 gem installed
$ ruby -rhiredis -e0
```
