### ISSUE TITLE
oga: requiring causes RuntimeError: Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1547]
To reproduce:

```ruby
require 'oga'
```

Error:

```
RuntimeError: Cannot convert LLVMTypedForeignObject+0x0 to LLVMNativePointer (LLVMPolyglotException)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/truffle/truffle/cext.rb:221:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/truffle/truffle/cext.rb:221:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/truffle/truffle/cext_ruby.rb:36:in `terminals_native='
	from ~/.gem/truffleruby/2.4.4/gems/ruby-ll-2.1.2/lib/ll/driver_config.rb:12:in `terminals='
	from ~/.gem/truffleruby/2.4.4/gems/oga-2.15/lib/oga/xml/parser.rb:28:in `Parser'
	from ~/.gem/truffleruby/2.4.4/gems/oga-2.15/lib/oga/xml/parser.rb:25:in `XML'
	from ~/.gem/truffleruby/2.4.4/gems/oga-2.15/lib/oga/xml/parser.rb:7:in `Oga'
	from ~/.gem/truffleruby/2.4.4/gems/oga-2.15/lib/oga/xml/parser.rb:6:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ~/.gem/truffleruby/2.4.4/gems/oga-2.15/lib/oga.rb:16:in `<top (required)>'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc11/lib/mri/rubygems/core_ext/kernel_require.rb:133:in `require'
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc11/bin/irb:29:in `<main>'
```

**Comment by eregon** [comment]
This is already fixed on `master`, thanks to the new C extension work by @aardvark179:
```
$ gem i oga
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: ansi-1.5.0.gem (100%)
Successfully installed ansi-1.5.0
Fetching: ruby-ll-2.1.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ruby-ll-2.1.2
Fetching: oga-2.15.gem (100%)
Building native extensions.  This could take a while...
Successfully installed oga-2.15
4 gems installed
$ ruby -roga -e 'p Oga'
Oga
```

So let me close the issue, and I'll ping here when RC12 is released.
