### ISSUE TITLE
numeric type error using gem 'roots'

### ISSUE THREAD

**Issue by jzakiya** [oracle/truffleruby#1555]
Testing my gem `roots` with truffleruby-1.0.0-rc11, installed via rvm on 64-bit Linux I7 laptop.
https://rubygems.org/gems/roots
https://github.com/jzakiya/roots

When using method `root` on integer > 19 digits gets shown error, works correctly on MRI and JRuby.

```
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
➜  ~ irb
2.6.0 :001 > require 'roots'
 => true 
2.6.0 :002 > 5899999999992422944294.root 2
 => 76811457478.63676 
2.6.0 :003 > 5899999999992422944294.iroot 2
 => 76811457478 
2.6.0 :004 > 

```

```
truffleruby-1.0.0-rc11 :016 > 5899999999992422944294.iroot 2
 => 76811457478 
truffleruby-1.0.0-rc11 :017 > 5899999999992422944294.root 2
TypeError: Truffle doesn't have a case for the org.truffleruby.core.numeric.IntegerNodesFactory$PowNodeFactory$PowNodeGen node with values of type  Integer(com.oracle.truffle.object.basic.DynamicObjectBasic) Rational(com.oracle.truffle.object.basic.DynamicObjectBasic)
        from /home/jzakiya/.rvm/gems/truffleruby-1.0.0-rc11/gems/roots-2.2.1/lib/roots.rb:146:in `**'
        from /home/jzakiya/.rvm/gems/truffleruby-1.0.0-rc11/gems/roots-2.2.1/lib/roots.rb:146:in `root'
        from (irb):17
        from /home/jzakiya/.rvm/rubies/truffleruby-1.0.0-rc11/bin/irb:29:in `<main>'

truffleruby-1.0.0-rc11 :023 >   1234566789012345678.root 2
 => 1111110610.611 
truffleruby-1.0.0-rc11 :024 > 12345667890123456789.root 2
TypeError: Truffle doesn't have a case for the org.truffleruby.core.numeric.IntegerNodesFactory$PowNodeFactory$PowNodeGen node with values of type  Integer(com.oracle.truffle.object.basic.DynamicObjectBasic) Rational(com.oracle.truffle.object.basic.DynamicObjectBasic)
        from /home/jzakiya/.rvm/gems/truffleruby-1.0.0-rc11/gems/roots-2.2.1/lib/roots.rb:146:in `**'
        from /home/jzakiya/.rvm/gems/truffleruby-1.0.0-rc11/gems/roots-2.2.1/lib/roots.rb:146:in `root'
        from (irb):24
        from /home/jzakiya/.rvm/rubies/truffleruby-1.0.0-rc11/bin/irb:29:in `<main>'
truffleruby-1.0.0-rc11 :025 > 
```

**Comment by bjfish** [comment]
This appears to work now on current master. I compared the results above between MRI 2.6.5 and TruffleRuby.
