### ISSUE TITLE
ArrayIndexOutOfBoundsException while running "bundle install"

### ISSUE THREAD

**Issue by MaxLap** [oracle/truffleruby#1565]
Note, this was in November, on rc9. I haven't haven't run my tests with truffle since.

On Travis, I got a similar error (ArrayIndexOutOfBoundsException) during `bundle install`. I have no reproduction scenario.

In 2 different, non consecutive runs, during `bundle install`, I got the following ArrayIndexOutOfBoundsException which have different backtraces.

```
Fetching gem metadata from https://rubygems.org/.
Retrying fetcher due to error (2/4): RuntimeError Index 0 out of bounds for length 0 (ArrayIndexOutOfBoundsException)
	from com.oracle.truffle.llvm.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:96)
	from com.oracle.truffle.llvm.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:83)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:118)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:230)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
	from com.oracle.truffle.llvm.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:107)
Translated to internal error.
```
Then got the same error and backtrace for the 3/4 and the 4/4 and in the report (which is the 4th attempt's error). 
Here is the travis build: https://travis-ci.org/deep-cover/deep-cover/builds/461626040
Raw log: [truffleruby-out-of-bound1.txt](https://github.com/oracle/truffleruby/files/2633879/truffleruby-out-of-bound1.txt)

---

Again, during `bundle install`. This time, the repeats have different values and backtraces.

```
Fetching gem metadata from https://rubygems.org/.
Retrying fetcher due to error (2/4): RuntimeError Index 2 out of bounds for length 1 (ArrayIndexOutOfBoundsException)
	from com.oracle.truffle.llvm.parser.model.functions.FunctionDefinition.generateBlock(FunctionDefinition.java:200)
	from com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:181)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:432)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:448)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:222)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.access$700(LLVMScanner.java:52)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner$LazyScanner.scanBlock(LLVMScanner.java:474)
	from com.oracle.truffle.llvm.parser.model.functions.LazyFunctionParser.parse(LazyFunctionParser.java:58)
	from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.convert(LazyToTruffleConverterImpl.java:90)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LazyLLVMIRFunction.resolve(LLVMFunctionDescriptor.java:198)
Translated to internal error.
Retrying fetcher due to error (3/4): RuntimeError Index 1 out of bounds for length 1 (ArrayIndexOutOfBoundsException)
	from com.oracle.truffle.llvm.parser.model.functions.FunctionDefinition.generateBlock(FunctionDefinition.java:200)
	from com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:181)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:432)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:448)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:222)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.access$700(LLVMScanner.java:52)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner$LazyScanner.scanBlock(LLVMScanner.java:474)
	from com.oracle.truffle.llvm.parser.model.functions.LazyFunctionParser.parse(LazyFunctionParser.java:58)
	from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.convert(LazyToTruffleConverterImpl.java:90)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LazyLLVMIRFunction.resolve(LLVMFunctionDescriptor.java:198)
Translated to internal error.
Retrying fetcher due to error (4/4): RuntimeError Index: 3, Size: 8 (IndexOutOfBoundsException)
	from java.lang.Throwable.<init>(Throwable.java:265)
	from java.lang.Exception.<init>(Exception.java:66)
	from java.lang.RuntimeException.<init>(RuntimeException.java:62)
	from java.lang.IndexOutOfBoundsException.<init>(IndexOutOfBoundsException.java:56)
	from java.util.ArrayList.rangeCheck(ArrayList.java:657)
	from java.util.ArrayList.get(ArrayList.java:433)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.abbreviatedRecord(LLVMScanner.java:234)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:227)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.access$700(LLVMScanner.java:52)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner$LazyScanner.scanBlock(LLVMScanner.java:474)

## A bit lower, the 4th error:
RuntimeError: Index 3 out of bounds for length 1 (ArrayIndexOutOfBoundsException)
	from com.oracle.truffle.llvm.parser.model.functions.FunctionDefinition.generateBlock(FunctionDefinition.java:200)
	from com.oracle.truffle.llvm.parser.listeners.Function.record(Function.java:181)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.passRecordToParser(LLVMScanner.java:432)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.unabbreviatedRecord(LLVMScanner.java:448)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.scanToOffset(LLVMScanner.java:222)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner.access$700(LLVMScanner.java:52)
	from com.oracle.truffle.llvm.parser.scanner.LLVMScanner$LazyScanner.scanBlock(LLVMScanner.java:474)
	from com.oracle.truffle.llvm.parser.model.functions.LazyFunctionParser.parse(LazyFunctionParser.java:58)
	from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.convert(LazyToTruffleConverterImpl.java:90)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$LazyLLVMIRFunction.resolve(LLVMFunctionDescriptor.java:198)
Translated to internal error
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `internal_raise'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `raise'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/cli.rb:21:in `start'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `load'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `load'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/bundle:23:in `<main>'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/truffleruby_executable_hooks:24:in `eval'
  /home/travis/.rvm/gems/truffleruby-1.0.0-rc9/bin/truffleruby_executable_hooks:24:in `<main>'
```
Here is the travis build: https://travis-ci.org/deep-cover/deep-cover/builds/461395118
Raw log: [truffleruby-out-of-bound2.txt](https://github.com/oracle/truffleruby/files/2633887/truffleruby-out-of-bound2.txt)

**Comment by eregon** [comment]
@MaxLap Thank you for the detailed report!
It seems an issue on the Sulong side (the Truffle interpreter we use for C extensions), so I filed a bug there and will update here when it's fixed.

**Comment by eregon** [comment]
I believe this has been fixed in Sulong and should be in the next release, although we still need to add a stress test for concurrent loading of C extensions.
@MaxLap Thank you for the report.

**Comment by eregon** [comment]
I added a stress test for concurrently loading C extensions and fixed a couple race conditions triggered by the test. This should work reliably now.
