### ISSUE TITLE
bundle exec, require and rescue causes LoadError

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1567]
The require's exception would be caught by the `rescue`.

**Gemfile**

```ruby
source 'https://rubygems.org'

gem 'pry', platform: :mri
```

**load_error.rb**

```ruby
begin
  require 'pry'
rescue
  nil
end
```

To reproduce:

```
bundle
bundle exec ruby load_error.rb
```

Error:

```
load_error.rb:2:in `require': cannot load such file -- pry (LoadError)
	from load_error.rb:2:in `<main>'
```

Expected:

No exception and nothing is printed.

```
$ ruby -v
truffleruby 1.0.0-rc12, like ruby 2.4.4, GraalVM CE Native [x86_64-darwin]
$ gem -v
2.6.14.1
$ bundle -v
Bundler version 1.17.3
```

**Comment by deepj** [comment]
Sorry, my mistake. I haven't realized `rescue` catches only `StandardError` exceptions. `LoadError` is `ScriptError`. The problem is in https://github.com/dry-rb/dry-initializer/blob/master/spec/spec_helper.rb#L4
