### ISSUE TITLE
keyword splats cause sometime SyntaxError: syntax error, unexpected '['

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1571]
I couldn't prepare some simple reproducible example for this issue. But it's easy to reproduce in rom specs. The problem lies in https://github.com/rom-rb/rom/blob/master/repository/lib/rom/repository/class_interface.rb#L125 when `root.command(type, **opts)` is called.

To reproduce:

```
git clone https://github.com/rom-rb/rom.git
cd rom/repository
bundle
bundle exec rspec spec/integration/typed_structs_spec.rb:51
```

Error:

```
[dry-types] Int type was renamed to Integer
Run options: include {:locations=>{"./spec/integration/typed_structs_spec.rb"=>[51]}}

Randomized with seed 14310
F

Failures:

  1) ROM repository with typed structs read-write type coercions loads typed structs
     Failure/Error: root.command(type, **opts).call(*input)

     SyntaxError:
       (eval):2: syntax error, unexpected '['
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:159:in `class_eval'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:159:in `block in attributes'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:157:in `each_key'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:157:in `each_pair'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:157:in `each_key'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:157:in `attributes'
     # ~/.gem/truffleruby/2.4.4/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:103:in `attribute'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:39:in `block (3 levels) in call'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:38:in `each'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:38:in `block (2 levels) in call'
     # ~/.gem/truffleruby/2.4.4/gems/dry-core-0.4.7/lib/dry/core/class_builder.rb:42:in `call'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:100:in `build_class'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:37:in `block in call'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:193:in `block in fetch_or_store'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:172:in `fetch'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:192:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/cache.rb:31:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/struct_compiler.rb:30:in `call'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:54:in `block in visit_relation'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:50:in `fetch'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:50:in `visit_relation'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:42:in `__send__'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:42:in `visit'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:34:in `block in call'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:193:in `block in fetch_or_store'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:172:in `fetch'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:192:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/cache.rb:31:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_compiler.rb:34:in `call'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_registry.rb:25:in `block in []'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:193:in `block in fetch_or_store'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:172:in `fetch'
     # ~/.gem/truffleruby/2.4.4/gems/concurrent-ruby-1.1.4/lib/concurrent/map.rb:192:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/cache.rb:57:in `fetch_or_store'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/mapper_registry.rb:25:in `[]'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/relation.rb:496:in `mapper'
     # ~/dev/bugs/truffleruby/rom/core/lib/rom/relation/commands.rb:50:in `command'
     # ./lib/rom/repository/class_interface.rb:125:in `create'
     # ./spec/integration/typed_structs_spec.rb:51:in `block (3 levels) in <top (required)>'

Finished in 4.01 seconds (files took 6.67 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/integration/typed_structs_spec.rb:50 # ROM repository with typed structs read-write type coercions loads typed structs

Randomized with seed 14310
```

I guess there is similar issue https://github.com/oracle/truffleruby/issues/1469 to this.

**Comment by deepj** [comment]
@chrisseaton I guess this has been solved by your fix https://github.com/oracle/truffleruby/commit/0c71a5bf5d2681cf2acbb875fd779c505f6f55b8

**Comment by chrisseaton** [comment]
Not really sure what would have fixed that but ok.

**Comment by deepj** [comment]
@chrisseaton I'll reopen it if I'll see it again
