### ISSUE TITLE
bson: External function @rb_num2ull cannot be found.

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1573]
To reproduce:

```ruby
require 'bson'

buffer = BSON::ByteBuffer.new
buffer.put_decimal128(0x0, 0xc)
```

Error:

```
RuntimeError: External function @rb_num2ull cannot be found. (LLVMLinkerException)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext_ruby.rb:41:in `put_decimal128'
	from (irb):3
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

**Comment by aardvark179** [comment]
The fix for this is now merged.
