### ISSUE TITLE
bson: RuntimeError: unknown type 12

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1574]
To reproduce:

```ruby
require 'bson'

buffer = BSON::ByteBuffer.new
buffer.put_bytes(1)
```

Error:

```
RuntimeError: unknown type 12
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:396:in `RB_TYPE_P'
	from ruby.c:126:in `RB_TYPE_P'
	from ~/.gem/truffleruby/2.4.4/gems/bson-4.4.2/ext/bson/bson_native.c:799:in `rb_bson_byte_buffer_put_bytes'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext_ruby.rb:41:in `put_bytes'
	from (irb):7
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

Expected:

```
ArgumentError (Invalid input)
```

**Comment by aardvark179** [comment]
The fix for this is now merged.
