### ISSUE TITLE
bson: rb_sym_to_s not implemented

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1575]
To reproduce:

```ruby
require 'bson'

BSON::CodeWithScope.new('this.value = name', { :name => 'test' }).to_bson
```

Error:

```
RuntimeError: rb_sym_to_s not implemented
	from ruby.c:2752:in `rb_tr_error'
	from ruby.c:4236:in `rb_sym_to_s'
	from ~/.gem/truffleruby/2.4.4/gems/bson-4.4.2/ext/bson/bson_native.c:326:in `put_hash_callback'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:1036:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:1036:in `block in rb_hash_foreach'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:1035:in `each'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:1035:in `rb_hash_foreach'
	from ruby.c:1574:in `rb_hash_foreach'
	from ~/.gem/truffleruby/2.4.4/gems/bson-4.4.2/ext/bson/bson_native.c:357:in `rb_bson_byte_buffer_put_hash'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext_ruby.rb:41:in `put_hash'
	from ~/.gem/truffleruby/2.4.4/gems/bson-4.4.2/lib/bson/hash.rb:42:in `to_bson'
	from ~/.gem/truffleruby/2.4.4/gems/bson-4.4.2/lib/bson/code_with_scope.rb:94:in `to_bson'
	from (irb):11
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

**Comment by chrisseaton** [comment]
This'll be a one-line fix.

**Comment by aardvark179** [comment]
I've now got a fixes for all the unexpectedly failing BSON tests in CI. The redefinition of `NilClass#==` by BSON did throw for a little bit.

**Comment by aardvark179** [comment]
The fix for this is now merged.

**Comment by deepj** [comment]
@aardvark179 Just a question. Do you say all BSON specs are just passed?
