### ISSUE TITLE
Bug when using $stdout

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1577]
Hello....

The following code works fine in MRI Ruby but crashes in Truffle:

```ruby
    class Test
      def to_s
        puts "hello there"
      end
    end

    $stdout = StringIO.new
    t = Test.new
    puts t
    out = $stdout.string
    $stdout = STDOUT
    puts out
```

```
Failure/Error: write(DEFAULT_RECORD_SEPARATOR) unless line[-1] == ?\n

NoMethodError:
  undefined method `[]' for nil:NilClass
/home/rbotafogo/lib/graalvm-ce-1.0.0-rc12/jre/languages/ruby/lib/truffle/stringio.rb:412:in `block in puts'
/home/rbotafogo/lib/graalvm-ce-1.0.0-rc12/jre/languages/ruby/lib/truffle/stringio.rb:394:in `each'
/home/rbotafogo/lib/graalvm-ce-1.0.0-rc12/jre/languages/ruby/lib/truffle/stringio.rb:394:in `puts'
./specs/tmp.rb:38:in `puts'
./specs/tmp.rb:38:in `<top (required)>'
```

**Comment by aardvark179** [comment]
This appears to be happening because we don't have the same fallback behaviour as MRI when `to_s` doesn't return a string during `StringIO#puts`. I will submit a fix for this.

**Comment by aardvark179** [comment]
The fix for this has now been merged.
