### ISSUE TITLE
bcrypt_pbkdf: External function @SHA512Init cannot be found. (LLVMLinkerException)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1588]
To reproduce:

```ruby
require 'bcrypt_pbkdf'

BCryptPbkdf::key('pass2', 'salt2', 12, 2)
```

Error:

```
RuntimeError: External function @SHA512Init cannot be found. (LLVMLinkerException)
Translated to internal error
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_without_conversion'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext.rb:296:in `execute_with_mutex'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/truffle/truffle/cext_ruby.rb:41:in `__bc_crypt_pbkdf'
	from ~/.gem/truffleruby/2.4.4/gems/bcrypt_pbkdf-1.0.0/lib/bcrypt_pbkdf.rb:21:in `key'
	from (irb):3
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

**Comment by chrisseaton** [comment]
I think this is likely because the standard Ruby VM happens to include the function `SHA512Init`. It's not reasonably part of what anyone intended to be part of the Ruby C extension API. But we can probably make this one work.

**Comment by eregon** [comment]
Maybe we should fix this upstream?
e.g., to use `require` instead of calling internal `Init` functions?

**Comment by chrisseaton** [comment]
@eregon it's not an `_Init` function in that sense (no underscore.)

But the problem isn't what I thought either:

https://github.com/net-ssh/bcrypt_pbkdf-ruby/blob/98fec744f7a1fea42ffd0420ef34f9159b1c61f7/ext/mri/sha2.h#L10

```
inline void SHA512Init(SHA2_CTX* ctx) { crypto_hash_sha512_init(ctx); }
```

**Comment by eregon** [comment]
So that C extension should define `SHA512Init` but somehow it's not found?

I wonder why that gem doesn't use the bundled `Digest::SHA512` (there might be a C-API for it too) and define its own, but that's a different matter.

**Comment by eregon** [comment]
I get a different error on master now:
```
$ ruby test.rb 
lib/truffle/truffle/cext_ruby.rb:20:in `__bc_crypt_pbkdf': TruffleRuby doesn't have a case for the com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.LLVMMemoryIntrinsicFactory$LLVMMallocNodeGen node with values of type  com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl (TypeError)
	from com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.LLVMMemoryIntrinsicFactory$LLVMMallocNodeGen.executeAndSpecialize(LLVMMemoryIntrinsicFactory.java:111)
	from com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.LLVMMemoryIntrinsicFactory$LLVMMallocNodeGen.executeGeneric_generic2(LLVMMemoryIntrinsicFactory.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.LLVMMemoryIntrinsicFactory$LLVMMallocNodeGen.executeGeneric(LLVMMemoryIntrinsicFactory.java:49)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	from /home/eregon/code/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/bcrypt_pbkdf-1.0.1/lib/bcrypt_pbkdf.rb:21:in `key'
	from test.rb:3:in `<main>'
```

**Comment by bjfish** [comment]
@eregon The error appers that malloc doesn't want a pointer.  Should the link below be `u_int8_t* okey = xmalloc(okeylen);` ?

https://github.com/net-ssh/bcrypt_pbkdf-ruby/blob/47aca2d4debfdaf96563d9488f16f3ad08b0ca3b/ext/mri/bcrypt_pbkdf_ext.c#L11

**Comment by eregon** [comment]
Yeah, that seems clearly a bug in the code (it will over-allocate by 2x).
On latest TruffleRuby this error probably doesn't happen since VALUE is `unsigned long` now.

**Comment by bjfish** [comment]
I've sent a PR for the `xmalloc` fix: https://github.com/net-ssh/bcrypt_pbkdf-ruby/pull/7

However, after the fix I still see an error:
```
/Users/bfish/Documents/projects/bcrypt_pbkdf-ruby/ext/mri/bcrypt_pbkdf.c:121:in `bcrypt_pbkdf': External LLVMFunction SHA512Init cannot be found. (LLVMLinkerException) (RuntimeError)
Translated to internal error
	from /Users/bfish/Documents/projects/bcrypt_pbkdf-ruby/ext/mri/bcrypt_pbkdf_ext.c:14:in `bc_crypt_pbkdf'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/mxbuild/truffleruby-native/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:39:in `__bc_crypt_pbkdf'
	from /Users/bfish/Documents/projects/bcrypt_pbkdf-ruby/lib/bcrypt_pbkdf.rb:21:in `key'
```

Also, I still see the error:
```
TypeError: TruffleRuby doesn't have a case for the com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.LLVMMemoryIntrinsicFactory$LLVMMallocNodeGen node with values of type com.oracle.truffle.llvm.runtime.pointer.LLVMPointerImpl
``` 
using the latest master: https://github.com/oracle/truffleruby/commit/6d82d89ee6d02c855c18db6ae1a3f0a9d182b090
so I'm not sure about the `unsigned long` here.

**Comment by bjfish** [comment]
The recommendation here appears to resolve the next error:
https://stackoverflow.com/questions/33301404/why-does-inline-void-foo-in-a-common-header-just-work/33305507#33305507

**Comment by eregon** [comment]
Right, so it should be `static inline` and this is a bug of the C ext and it only works on some versions of some C compiler?

**Comment by eregon** [comment]
It installs and the example works fine with 5f3339321c6bf3f30e7993101b2f2abce7f1b0f4:
```
$ ruby -v bcrypt_pbkdf.rb
truffleruby 21.1.0-dev-c03738b2, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
"\xD6\x0E0\xA2\x83\xCEy\xB02h\xE7\xFC"
```
