### ISSUE TITLE
pty is missing in the standard library

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1589]
See https://ruby-doc.org/stdlib-2.0.0/libdoc/pty/rdoc/PTY.html

To reproduce:

```ruby
require 'pty'
```

Error:

```
LoadError: cannot load such file -- pty
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from ~/.rubies/truffleruby-1.0.0-rc12/lib/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from ~/.rubies/truffleruby-1.0.0-rc12/bin/irb:29:in `<main>'
```

This gem is used in [querly](https://github.com/soutaro/querly/blob/b39154602301caa8f09af0c1b765723a774a4e74/test/cli/console_test.rb) tests

**Comment by chrisseaton** [comment]
I'm just working on updating our documentation on standard libraries.

#### Standard libraries

The following standard libraries are unsupported.

* `continuation`
* `dbm`
* `gdbm`
* `sdbm`
* `io/console` (partially implemented, could be implemented in the future)
* `io/nonblock` (could be implemented in the future)
* `io/wait` (partially implemented, could be implemented in the future)
* `pty` (could be implemented in the future)
* `ripper` (could be implemented in the future)
* `win32`
* `win32ole`

`fiddle` is not yet implemented - the module and some methods are there
but not enough to run anything serious.

We provide our own included implementation of the interface of the `ffi` gem,
like JRuby and Rubinius, but the implemention of this is limited at the
moment.

**Comment by eregon** [comment]
`pty` is used by the tests of the `debug` gem:
https://github.com/ruby/debug/blob/d0a3372a864d3906ac2a81907b9222dba15883be/test/support/utils.rb#L3

It would be worth trying if importing the `pty` sources from CRuby works.

**Comment by eregon** [comment]
@bjfish Could you try that?

**Comment by matthewford** [comment]
also causes an issue with the appsignal apm

**Comment by matthewford** [comment]
wicked_pdf gem also use pty

**Comment by chrisseaton** [comment]
I have a PR partially done to add pty - will take a look at it again. It's also needed to run the debug gem tests.

**Comment by eregon** [comment]
JRuby recently used libfixposix to get `pty` working in https://github.com/jruby/jruby/issues/6552, possibly relevant for us, as from reading that issue posix_spawn doesn't have that ability. But we could probably also do it https://github.com/oracle/truffleruby/blob/master/src/main/c/spawn-helper/spawn-helper.c and that would be simpler/more direct.

**Comment by eregon** [comment]
As a note, https://github.com/Shopify/shipit-engine used in [ruby-bench](https://github.com/ruby/ruby-bench/tree/main/benchmarks/shipit) requires `pty`:
```
$ ruby benchmarks/shipit/benchmark.rb
...
<internal:core> core/kernel.rb:231:in `gem_original_require': cannot load such file -- pty (LoadError)
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundled_gems.rb:69:in `require'
	from /home/eregon/code/ruby-bench/benchmarks/shipit/vendor/bundle/truffleruby/33.0.1.2/gems/shipit-engine-0.40.1/lib/shipit/command.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:229:in `gem_original_require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundled_gems.rb:69:in `require'
	from /home/eregon/code/ruby-bench/benchmarks/shipit/vendor/bundle/truffleruby/33.0.1.2/gems/shipit-engine-0.40.1/lib/shipit.rb:43:in `<top (required)>'
	from <internal:core> core/kernel.rb:229:in `gem_original_require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundled_gems.rb:69:in `require'
	from /home/eregon/code/ruby-bench/benchmarks/shipit/vendor/bundle/truffleruby/33.0.1.2/gems/shipit-engine-0.40.1/lib/shipit-engine.rb:1:in `<top (required)>'
	from <internal:core> core/kernel.rb:229:in `gem_original_require'
	from <internal:/home/eregon/.rubies/truffleruby-33.0.1/lib/mri/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundled_gems.rb:69:in `require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler/runtime.rb:55:in `each'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler/runtime.rb:55:in `block in require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler/runtime.rb:44:in `each'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler/runtime.rb:44:in `require'
	from /home/eregon/.rubies/truffleruby-33.0.1/lib/mri/bundler.rb:212:in `require'
	from /home/eregon/code/ruby-bench/benchmarks/shipit/config/application.rb:19:in `<top (required)>'
	from <internal:core> core/kernel.rb:292:in `require_relative'
	from /home/eregon/code/ruby-bench/benchmarks/shipit/config/environment.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:292:in `require_relative'
	from benchmarks/shipit/benchmark.rb:13:in `<main>'
```

**Comment by eregon** [comment]
One thought is also since we run extensions natively maybe fork() would work, if there is no Ruby C API call between the fork() and exec().

**Comment by eregon** [comment]
This is the call to `fork()`: https://github.com/ruby/ruby/blob/66e61d0cffca501f335175c6ca4948d535a0e86d/ext/pty/pty.c#L242
I see some `rb_*` calls between the fork and exec but not too many, that itself might be workable.
It uses a lot of functions and details from CRuby process.c though, so seems hard to implement without copying lots of logic notably all the `rb_execarg` stuff.

JRuby uses this:
https://github.com/jruby/jruby/blob/a3180b45aecc2a30096ec736d0eeee20cf90259e/lib/ruby/stdlib/pty.rb#L2
https://github.com/byteit101/subspawn
https://github.com/byteit101/subspawn/blob/master/subspawn/lib/subspawn/replace-pty.rb

`subspawn` can be installed on TruffleRuby with:
```
export TRUFFLERUBYOPT="--experimental-options --reuse-precompiled-gems=ffi-binary-libfixposix"
gem install subspawn subspawn-posix
```
(because [ffi-binary-libfixposix](https://rubygems.org/gems/ffi-binary-libfixposix/versions) doesn't have a ruby platform gem)

And it seems to partially work:
```
$ ruby -v -rpty -e 'PTY.spawn("printf", "OK") { |r,w,pid| p r.readpartial(10); r.close; w.close; Process.wait(pid) }'
ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]
"OK"

$ ruby -v -rsubspawn/replace-pty -e 'PTY.spawn("printf", "OK") { |r,w,pid| p r.readpartial(10); r.close; w.close; Process.wait(pid) }'
truffleruby 34.0.0-dev-b6e7895e (2026-03-06), like ruby 3.4.7, Oracle GraalVM Native [x86_64-linux]
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/subspawn-posix-0.1.1/lib/subspawn/posix/pty.rb:46: warning: assigned but unused variable - name
"OK"
<internal:core> core/errno.rb:48:in 'Errno.handle': No child processes - No child process: 392932 (Errno::ECHILD)
	from <internal:core> core/truffle/process_operations.rb:150:in 'block in Truffle::ProcessOperations.wait'
	from <internal:core> core/truffle/ffi/pointer.rb:264:in 'Truffle::FFI::MemoryPointer.new'
	from <internal:core> core/truffle/process_operations.rb:145:in 'Truffle::ProcessOperations.wait'
	from <internal:core> core/process.rb:601:in 'Process#wait'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/subspawn-0.1.1/lib/subspawn.rb:211:in 'SubSpawn.pty_spawn'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/subspawn-0.1.1/lib/subspawn.rb:196:in 'SubSpawn.pty_spawn_compat'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/subspawn-0.1.1/lib/subspawn/replace-pty.rb:21:in 'PTY.spawn'
	from -e:1:in '<main>'
```

Maybe we could ship `subspawn` with TruffleRuby (might be tricky to integrate in the build system), or let users install it or so.
Then we'd have a `pty.rb` which would just be `require 'subspawn/replace-pty'`.

One downside of using `subspawn` and its prebuilt binaries is we'd depend on it being maintained.
