### ISSUE TITLE
TypeError: superclass mismatch for class Psych::Parser::Mark

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1599]
This happens when I want to try to run `path_expander` in TruffleRuby. Doesn't happen in MRI

To reproduce
```ruby
git clone https://github.com/seattlerb/path_expander.git
cd path_expander
gem install hoe
rake
```

Error:

```
ruby.c:1887: warning: already initialized constant Psych::Parser::ANY
ruby.c:1887: warning: already initialized constant Psych::Parser::UTF8
ruby.c:1887: warning: already initialized constant Psych::Parser::UTF16LE
ruby.c:1887: warning: already initialized constant Psych::Parser::UTF16BE
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:7: warning: already initialized constant Psych::ClassLoader::BIG_DECIMAL
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:7: warning: previous definition of BIG_DECIMAL was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:8: warning: already initialized constant Psych::ClassLoader::COMPLEX
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:8: warning: previous definition of COMPLEX was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:9: warning: already initialized constant Psych::ClassLoader::DATE
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:9: warning: previous definition of DATE was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:10: warning: already initialized constant Psych::ClassLoader::DATE_TIME
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:10: warning: previous definition of DATE_TIME was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:11: warning: already initialized constant Psych::ClassLoader::EXCEPTION
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:11: warning: previous definition of EXCEPTION was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:12: warning: already initialized constant Psych::ClassLoader::OBJECT
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:12: warning: previous definition of OBJECT was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:13: warning: already initialized constant Psych::ClassLoader::PSYCH_OMAP
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:13: warning: previous definition of PSYCH_OMAP was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:14: warning: already initialized constant Psych::ClassLoader::PSYCH_SET
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:14: warning: previous definition of PSYCH_SET was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:15: warning: already initialized constant Psych::ClassLoader::RANGE
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:15: warning: previous definition of RANGE was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:16: warning: already initialized constant Psych::ClassLoader::RATIONAL
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:16: warning: previous definition of RATIONAL was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:17: warning: already initialized constant Psych::ClassLoader::REGEXP
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:17: warning: previous definition of REGEXP was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:18: warning: already initialized constant Psych::ClassLoader::STRUCT
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:18: warning: previous definition of STRUCT was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:19: warning: already initialized constant Psych::ClassLoader::SYMBOL
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:19: warning: previous definition of SYMBOL was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/class_loader.rb:65: warning: already initialized constant Psych::ClassLoader::CACHE
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/class_loader.rb:65: warning: previous definition of CACHE was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:9: warning: already initialized constant Psych::ScalarScanner::TIME
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/scalar_scanner.rb:9: warning: previous definition of TIME was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:12: warning: already initialized constant Psych::ScalarScanner::FLOAT
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/scalar_scanner.rb:12: warning: previous definition of FLOAT was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/scalar_scanner.rb:17: warning: already initialized constant Psych::ScalarScanner::INTEGER
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/scalar_scanner.rb:18: warning: previous definition of INTEGER was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/stream.rb:13: warning: already initialized constant Psych::Nodes::Stream::ANY
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/stream.rb:13: warning: previous definition of ANY was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/stream.rb:16: warning: already initialized constant Psych::Nodes::Stream::UTF8
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/stream.rb:16: warning: previous definition of UTF8 was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/stream.rb:19: warning: already initialized constant Psych::Nodes::Stream::UTF16LE
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/stream.rb:19: warning: previous definition of UTF16LE was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/stream.rb:22: warning: already initialized constant Psych::Nodes::Stream::UTF16BE
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/stream.rb:22: warning: previous definition of UTF16BE was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:43: warning: already initialized constant Psych::Nodes::Sequence::ANY
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/sequence.rb:43: warning: previous definition of ANY was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:46: warning: already initialized constant Psych::Nodes::Sequence::BLOCK
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/sequence.rb:46: warning: previous definition of BLOCK was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/sequence.rb:49: warning: already initialized constant Psych::Nodes::Sequence::FLOW
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/sequence.rb:49: warning: previous definition of FLOW was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:10: warning: already initialized constant Psych::Nodes::Scalar::ANY
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:10: warning: previous definition of ANY was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:13: warning: already initialized constant Psych::Nodes::Scalar::PLAIN
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:13: warning: previous definition of PLAIN was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:16: warning: already initialized constant Psych::Nodes::Scalar::SINGLE_QUOTED
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:16: warning: previous definition of SINGLE_QUOTED was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:19: warning: already initialized constant Psych::Nodes::Scalar::DOUBLE_QUOTED
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:19: warning: previous definition of DOUBLE_QUOTED was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:22: warning: already initialized constant Psych::Nodes::Scalar::LITERAL
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:22: warning: previous definition of LITERAL was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/scalar.rb:25: warning: already initialized constant Psych::Nodes::Scalar::FOLDED
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/scalar.rb:25: warning: previous definition of FOLDED was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:17: warning: already initialized constant Psych::Nodes::Mapping::ANY
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/mapping.rb:17: warning: previous definition of ANY was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:20: warning: already initialized constant Psych::Nodes::Mapping::BLOCK
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/mapping.rb:20: warning: previous definition of BLOCK was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/nodes/mapping.rb:23: warning: already initialized constant Psych::Nodes::Mapping::FLOW
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/nodes/mapping.rb:23: warning: previous definition of FLOW was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/visitors/visitor.rb:11: warning: already initialized constant Psych::Visitors::Visitor::DISPATCH
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/visitors/visitor.rb:11: warning: previous definition of DISPATCH was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/visitors/to_ruby.rb:334: warning: already initialized constant Psych::Visitors::ToRuby::SHOVEL
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/visitors/to_ruby.rb:334: warning: previous definition of SHOVEL was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/handler.rb:27: warning: already initialized constant Psych::Handler::OPTIONS
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/handler.rb:27: warning: previous definition of OPTIONS was here
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/handler.rb:30: warning: already initialized constant Psych::Handler::EVENTS
~/.rubies/truffleruby-1.0.0-rc13/lib/mri/psych/handler.rb:30: warning: previous definition of EVENTS was here
rake aborted!
TypeError: superclass mismatch for class Psych::Parser::Mark
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/parser.rb:34:in `Parser'
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/parser.rb:33:in `Psych'
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych/parser.rb:2:in `<top (required)>'
~/.gem/truffleruby/2.4.4/gems/psych-3.1.0/lib/psych.rb:24:in `<top (required)>'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe/package.rb:44:in `new'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe/package.rb:44:in `define_package_tasks'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe.rb:729:in `block in load_plugin_tasks'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe.rb:723:in `each'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe.rb:723:in `load_plugin_tasks'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe.rb:808:in `post_initialize'
~/.gem/truffleruby/2.4.4/gems/hoe-3.17.1/lib/hoe.rb:390:in `spec'
~/dev/bugs/truffleruby/path_expander/rakefile:24:in `<top (required)>'
~/.gem/truffleruby/2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by deepj** [comment]
My RubyGems is `2.6.14.1`. What I know, the tests have been possible to run in RC12, not now. Maybe the problem on my side only.

**Comment by deepj** [comment]
It seems, this happened while upgrading RC12 -> RC13. When I haven't removed old gems. Interesting, there was no problem with RC11 -> RC12.

Feel free to close this since there is a solution - remove old gems.

**Comment by deepj** [comment]
@eregon I guess this can be closed.

**Comment by eregon** [comment]
Right, thanks. I guess it was due to reusing the same GEM_HOME. This should not happen so easily anymore.
