### ISSUE TITLE
Some constants are not propagated into RSpec specs

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1615]
I have a following structure of an application

```
- app.rb
- spec
    - spec_helper.rb
    - app_spec.rb
```

**app.rb**

```ruby
class App
  def say(words)
     "App says: #{words}"
  end
end
```

**spec_helper.rb**

```ruby
# frozen_string_literal: true

ENV['RACK_ENV'] = 'test'

require_relative '../app'

RSpec.configure do |config|
end
```

**app_spec.rb**

```
RSpec.describe App do
end
```

After running `rspec` I get `NameError: uninitialized constant App`. Under MRI there is no issue with this.

**Comment by deepj** [comment]
Quite lots projects are affected by this.

Try

```
git clone https://github.com/piotrmurach/pastel.git
cd pastel
bundle exec rspec ci
```

```
~/.rubies/truffleruby-1.0.0-rc13/bin/truffleruby -I~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib:~/.gem/truffleruby/2.4.4/gems/rspec-support-3.8.0/lib ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\{unit,integration\}\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 48626
F...........~/dev/bugs/truffleruby/pastel/lib/pastel/delegator.rb:81:in `respond_to_missing?': Pastel::Delegator#valid? at ~/.rubies/truffleruby-1.0.0-rc13/lib/mri/forwardable.rb:157 forwarding to private method TrueClass#valid?
.FFFFFFFFFF...........................................................................................

Failures:

  1) Pastel#undecorate undecorates string detecting color escape codes
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/undecorate_spec.rb:8:in `block (2 levels) in <top (required)>'

  2) Pastel::ColorParser::parse parses nested colors with one reset
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:43:in `block (2 levels) in <top (required)>'

  3) Pastel::ColorParser::parse parses simple color
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:11:in `block (2 levels) in <top (required)>'

  4) Pastel::ColorParser::parse parses nested colors with two resets
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:50:in `block (2 levels) in <top (required)>'

  5) Pastel::ColorParser::parse parses malformed control sequence
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:63:in `block (2 levels) in <top (required)>'

  6) Pastel::ColorParser::parse parses chained colors in regular syntax
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:29:in `block (2 levels) in <top (required)>'

  7) Pastel::ColorParser::parse parses many colors
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:35:in `block (2 levels) in <top (required)>'

  8) Pastel::ColorParser::parse parses chained colors in shorthand syntax
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:23:in `block (2 levels) in <top (required)>'

  9) Pastel::ColorParser::parse parses string with no color
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:7:in `block (2 levels) in <top (required)>'

  10) Pastel::ColorParser::parse parses simple color and style
      Failure/Error: scanner = StringScanner.new(text)

      NameError:
        uninitialized constant Pastel::ColorParser::StringScanner
        Did you mean?  StringIO
      # ./lib/pastel/color_parser.rb:31:in `const_missing'
      # ./lib/pastel/color_parser.rb:31:in `parse'
      # ./spec/unit/color_parser_spec.rb:17:in `block (2 levels) in <top (required)>'

  11) Pastel::ColorParser::parse parses unrest color
      Failure/Error: scanner = StringScanner.new(text)

      NameError:
        uninitialized constant Pastel::ColorParser::StringScanner
        Did you mean?  StringIO
      # ./lib/pastel/color_parser.rb:31:in `const_missing'
      # ./lib/pastel/color_parser.rb:31:in `parse'
      # ./spec/unit/color_parser_spec.rb:57:in `block (2 levels) in <top (required)>'

Top 2 slowest examples (0.513 seconds, 25.5% of total time):
  Pastel::Delegator.inspect inspects delegator styles chain
    0.258 seconds ./spec/unit/delegator_spec.rb:11
  Pastel coloring dsl combines colored strings with regular ones
    0.255 seconds ./spec/unit/decorate_dsl_spec.rb:15

Top 2 slowest example groups:
  Pastel#undecorate
    0.088 seconds average (0.088 seconds / 1 example) ./spec/unit/undecorate_spec.rb:3
  Pastel::Delegator
    0.08325 seconds average (0.333 seconds / 4 examples) ./spec/unit/delegator_spec.rb:3

Finished in 2.01 seconds (files took 3.08 seconds to load)
114 examples, 11 failures

Failed examples:

rspec ./spec/unit/undecorate_spec.rb:6 # Pastel#undecorate undecorates string detecting color escape codes
rspec ./spec/unit/color_parser_spec.rb:42 # Pastel::ColorParser::parse parses nested colors with one reset
rspec ./spec/unit/color_parser_spec.rb:10 # Pastel::ColorParser::parse parses simple color
rspec ./spec/unit/color_parser_spec.rb:49 # Pastel::ColorParser::parse parses nested colors with two resets
rspec ./spec/unit/color_parser_spec.rb:62 # Pastel::ColorParser::parse parses malformed control sequence
rspec ./spec/unit/color_parser_spec.rb:28 # Pastel::ColorParser::parse parses chained colors in regular syntax
rspec ./spec/unit/color_parser_spec.rb:34 # Pastel::ColorParser::parse parses many colors
rspec ./spec/unit/color_parser_spec.rb:22 # Pastel::ColorParser::parse parses chained colors in shorthand syntax
rspec ./spec/unit/color_parser_spec.rb:6 # Pastel::ColorParser::parse parses string with no color
rspec ./spec/unit/color_parser_spec.rb:16 # Pastel::ColorParser::parse parses simple color and style
rspec ./spec/unit/color_parser_spec.rb:56 # Pastel::ColorParser::parse parses unrest color

Randomized with seed 48626

~/.rubies/truffleruby-1.0.0-rc13/bin/truffleruby -I~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/lib:~/.gem/truffleruby/2.4.4/gems/rspec-support-3.8.0/lib ~/.gem/truffleruby/2.4.4/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\{unit,integration\}\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by deepj** [comment]
@chrisseaton @eregon if I may vote for some further priority, I would pick this one as a next priority. It's a quite lot specs including the most of my apps failing on this.

**Comment by chrisseaton** [comment]
I get `uninitialized constant App` when I try with MRI 2.6.2. Can you check you're trying with the same MRI version?

**Comment by chrisseaton** [comment]
I added `require_relative 'spec_helper'` to the top of `app_spec` and then it works in both.

**Comment by chrisseaton** [comment]
I think this is fixed - I can run `rspec` on pastel.

But - I can't run `bundle expec rspec ci` on MRI or TruffleRuby, and as I said I couldn't run your demo on either MRI or TruffleRuby. I don't know if you've got any thoughts on that?

**Comment by deepj** [comment]
@chrisseaton it seems to be an issue in RC14 and previous releases. See pastel specs

RC15

```
$ ruby -v
truffleruby 1.0.0-rc15, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]
$ rspec

Randomized with seed 19003
.............................................................Pastel::Delegator#valid? at ~/.rubies/truffleruby-1.0.0-rc15/lib/mri/forwardable.rb:158 forwarding to private method TrueClass#valid?
{:uplevel=>3}
.~/.rubies/truffleruby-1.0.0-rc15/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - ~/.gem/truffleruby/2.6.2/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb~/.rubies/truffleruby-1.0.0-rc15/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - ~/.gem/truffleruby/2.6.2/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb~/.rubies/truffleruby-1.0.0-rc15/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - ~/.gem/truffleruby/2.6.2/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb~/.rubies/truffleruby-1.0.0-rc15/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - ~/.gem/truffleruby/2.6.2/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb....................................................

Top 2 slowest examples (0.451 seconds, 20.6% of total time):
  Pastel::Color#lookup looksup colors
    0.258 seconds ./spec/unit/color/lookup_spec.rb:4
  Pastel::Color.decorate doesn't decorate nil
    0.193 seconds ./spec/unit/color/decorate_spec.rb:68

Top 2 slowest example groups:
  Pastel::Color#lookup
    0.168 seconds average (0.336 seconds / 2 examples) ./spec/unit/color/lookup_spec.rb:3
  Pastel::Color::new
    0.055 seconds average (0.055 seconds / 1 example) ./spec/unit/color/new_spec.rb:3

Finished in 2.19 seconds (files took 3.18 seconds to load)
114 examples, 0 failures

Randomized with seed 19003
```

RC14

```
$ ruby -v
truffleruby 1.0.0-rc14, like ruby 2.6.2, GraalVM CE Native [x86_64-darwin]
$ rspec

Randomized with seed 60432
.......Pastel::Delegator#valid? at ~/.rubies/truffleruby-1.0.0-rc14/lib/mri/forwardable.rb:158 forwarding to private method TrueClass#valid?
{:uplevel=>3}
................................................................................................FFFFFFFFFFF

Failures:

  1) Pastel#undecorate undecorates string detecting color escape codes
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ~/.rubies/truffleruby-1.0.0-rc14/lib/mri/forwardable.rb:230:in `parse'
     # ./spec/unit/undecorate_spec.rb:8:in `block (2 levels) in <top (required)>'

  2) Pastel::ColorParser::parse parses unrest color
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:57:in `block (2 levels) in <top (required)>'

  3) Pastel::ColorParser::parse parses simple color
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:11:in `block (2 levels) in <top (required)>'

  4) Pastel::ColorParser::parse parses chained colors in shorthand syntax
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:23:in `block (2 levels) in <top (required)>'

  5) Pastel::ColorParser::parse parses nested colors with one reset
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:43:in `block (2 levels) in <top (required)>'

  6) Pastel::ColorParser::parse parses many colors
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:35:in `block (2 levels) in <top (required)>'

  7) Pastel::ColorParser::parse parses chained colors in regular syntax
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:29:in `block (2 levels) in <top (required)>'

  8) Pastel::ColorParser::parse parses malformed control sequence
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:63:in `block (2 levels) in <top (required)>'

  9) Pastel::ColorParser::parse parses simple color and style
     Failure/Error: scanner = StringScanner.new(text)

     NameError:
       uninitialized constant Pastel::ColorParser::StringScanner
       Did you mean?  StringIO
     # ./lib/pastel/color_parser.rb:31:in `const_missing'
     # ./lib/pastel/color_parser.rb:31:in `parse'
     # ./spec/unit/color_parser_spec.rb:17:in `block (2 levels) in <top (required)>'

  10) Pastel::ColorParser::parse parses string with no color
      Failure/Error: scanner = StringScanner.new(text)

      NameError:
        uninitialized constant Pastel::ColorParser::StringScanner
        Did you mean?  StringIO
      # ./lib/pastel/color_parser.rb:31:in `const_missing'
      # ./lib/pastel/color_parser.rb:31:in `parse'
      # ./spec/unit/color_parser_spec.rb:7:in `block (2 levels) in <top (required)>'

  11) Pastel::ColorParser::parse parses nested colors with two resets
      Failure/Error: scanner = StringScanner.new(text)

      NameError:
        uninitialized constant Pastel::ColorParser::StringScanner
        Did you mean?  StringIO
      # ./lib/pastel/color_parser.rb:31:in `const_missing'
      # ./lib/pastel/color_parser.rb:31:in `parse'
      # ./spec/unit/color_parser_spec.rb:50:in `block (2 levels) in <top (required)>'

Top 2 slowest examples (0.243 seconds, 12.1% of total time):
  Pastel#alias_color aliases color and combines with regular ones
    0.167 seconds ./spec/unit/alias_color_spec.rb:12
  Pastel::Color#lookup caches color lookups
    0.076 seconds ./spec/unit/color/lookup_spec.rb:9

Top 2 slowest example groups:
  Pastel#alias_color
    0.07 seconds average (0.21 seconds / 3 examples) ./spec/unit/alias_color_spec.rb:3
  Pastel::Color.valid?
    0.067 seconds average (0.201 seconds / 3 examples) ./spec/unit/color/valid_spec.rb:3

Finished in 2 seconds (files took 2.63 seconds to load)
114 examples, 11 failures

Failed examples:

rspec ./spec/unit/undecorate_spec.rb:6 # Pastel#undecorate undecorates string detecting color escape codes
rspec ./spec/unit/color_parser_spec.rb:56 # Pastel::ColorParser::parse parses unrest color
rspec ./spec/unit/color_parser_spec.rb:10 # Pastel::ColorParser::parse parses simple color
rspec ./spec/unit/color_parser_spec.rb:22 # Pastel::ColorParser::parse parses chained colors in shorthand syntax
rspec ./spec/unit/color_parser_spec.rb:42 # Pastel::ColorParser::parse parses nested colors with one reset
rspec ./spec/unit/color_parser_spec.rb:34 # Pastel::ColorParser::parse parses many colors
rspec ./spec/unit/color_parser_spec.rb:28 # Pastel::ColorParser::parse parses chained colors in regular syntax
rspec ./spec/unit/color_parser_spec.rb:62 # Pastel::ColorParser::parse parses malformed control sequence
rspec ./spec/unit/color_parser_spec.rb:16 # Pastel::ColorParser::parse parses simple color and style
rspec ./spec/unit/color_parser_spec.rb:6 # Pastel::ColorParser::parse parses string with no color
rspec ./spec/unit/color_parser_spec.rb:49 # Pastel::ColorParser::parse parses nested colors with two resets

Randomized with seed 60432
```

**Comment by chrisseaton** [comment]
Works for me in RC15 and development. I do get this message though - where's this form?

```
Randomized with seed 19003
.............................................................Pastel::Delegator#valid? at /Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/mri/forwardable.rb:158 forwarding to private method TrueClass#valid?
{:uplevel=>3}
./Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb:30: warning: loading in progress, circular require considered harmful - /Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb/Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb:101: warning: loading in progress, circular require considered harmful - /Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb/Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb:136: warning: loading in progress, circular require considered harmful - /Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb/Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb:181: warning: loading in progress, circular require considered harmful - /Users/chrisseaton/Documents/truffleruby-1.0.0-rc15-macos-amd64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/built_in/be.rb....................................................

Top 2 slowest examples (1.25 seconds, 64.9% of total time):
  Pastel::Color::new allows to disable coloring
    1.21 seconds ./spec/unit/color/new_spec.rb:4
  Pastel::Color#lookup caches color lookups
    0.036 seconds ./spec/unit/color/lookup_spec.rb:9

Top 2 slowest example groups:
  Pastel::Color::new
    1.22 seconds average (1.22 seconds / 1 example) ./spec/unit/color/new_spec.rb:3
  Pastel::Delegator
    0.06975 seconds average (0.279 seconds / 4 examples) ./spec/unit/delegator_spec.rb:3

Finished in 1.92 seconds (files took 1.19 seconds to load)
114 examples, 0 failures
```

**Comment by eregon** [comment]
@chrisseaton Which message? The Delegator warning, or the circular require waning?

**Comment by chrisseaton** [comment]
The circular require warning is only on TruffleRuby. The delegator warning is also on MRI.

**Comment by deepj** [comment]
@chrisseaton uf, the bug is reproducible in RC14 and previous versions, not in RC15

**Comment by chrisseaton** [comment]
Sorry not sure what you mean - so it's fixed? Or do you care about the bug still being in RC14? We can't fix that, sorry.

**Comment by deepj** [comment]
Yes, the point of the whole was it was bug until RC14, but there is anymore in RC15. I'd interest in what fixed it.

**Comment by chrisseaton** [comment]
Ah - I'm not really sure. Bisecting to find the fix would be interesting but not something I'll do unless there's a more specific need. Glad it's fixed anyway.

**Comment by deepj** [comment]
Isn't it fixed by this `autoload :C, "path"; require "path" now correctly triggers the autoload.`?

**Comment by chrisseaton** [comment]
Possibly - as I say I'd have to bisect to figure it out and is there a need?

**Comment by eregon** [comment]
FWIW, I had a quick look and it doesn't look like `Pastel` uses `autoload` itself, maybe a dependency?

**Comment by deepj** [comment]
@eregon I guess this has a connection to RSpec how it loads specs I guess.  I had the same issue with my specs including the issue is reproducible by above code from me in RC14.

**Comment by eregon** [comment]
First thing is `color_parser.rb` uses `StringScanner` but no gem file requires it.
@deepj  So that's a bug of the gem, could you report it?
So this can happen on MRI too:
```
$ bundle exec ruby -Ilib -rpastel -e 'p Pastel::ColorParser.parse("foo")'
Traceback (most recent call last):
	1: from -e:1:in `<main>'
pastel/lib/pastel/color_parser.rb:31:in `parse': uninitialized constant Pastel::ColorParser::StringScanner (NameError)
```

When running specs, it looks like on MRI, `strscan` is required by `erb`, which is required by `rspec-core-3.8.0/lib/rspec/core/configuration_options.rb`.

We had a workaround that `erb` wouldn't use `strscan` (and therefore not require it either), which I removed in 4e70101c67a96d7b2347928447f5283889062920.
So that fixed it, I'll add this change to the ChangeLog.
