### ISSUE TITLE
rescue/else/ensure inside do/end is not supported 

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1618]
This is already used e.g. in [ActiveSupport](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/testing/parallelization.rb#L93) I personally use this on daily basis

To reproduce

```
def method
  puts 'Doing something'
ensure
  puts 'Done!'
end
```

Error:

```
syntax error, unexpected kENSURE (SyntaxError)
```

**Comment by deepj** [comment]
@eregon @chrisseaton is it possible to make a priority from this, please?

Already used in Rails codebase https://github.com/rails/rails/blob/master/activesupport/lib/active_support/descendants_tracker.rb#L95

```
`require': ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/descendants_tracker.rb:95: syntax error, unexpected kRESCUE (SyntaxError)
	from ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/callbacks.rb:4:in `<top (required)>'
	from ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:3:in `require'
	from ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/testing/setup_and_teardown.rb:3:in `<top (required)>'
	from ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/test_case.rb:6:in `require'
	from ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/test_case.rb:6:in `<top (required)>'
	from ~/dev/bugs/truffleruby/rails/activesupport/test/abstract_unit.rb:29:in `require'
	from ~/dev/bugs/truffleruby/rails/activesupport/test/abstract_unit.rb:29:in `<top (required)>'
	from ~/dev/bugs/truffleruby/rails/activesupport/test/array_inquirer_test.rb:3:in `require'
	from ~/dev/bugs/truffleruby/rails/activesupport/test/array_inquirer_test.rb:3:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.2/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `require'
	from ~/.gem/truffleruby/2.6.2/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from ~/.gem/truffleruby/2.6.2/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `select'
	from ~/.gem/truffleruby/2.6.2/gems/rake-12.3.1/lib/rake/rake_test_loader.rb:5:in `<main>'
```

**Comment by chrisseaton** [comment]
@aardvark179 fixed this - will be in the next release.

**Comment by deepj** [comment]
@chrisseaton Isn't the entry about this issue in changelog wrong? It'd belong to RC17

**Comment by chrisseaton** [comment]
Right - thanks I'll tidy up the changelog. We have union merging and old PRs that get merged and in combination that can do odd things.

**Comment by Confusion** [comment]
Note to those that may be looking for 1.0.0-rc17, like I was: this has ended up in 19.0.0

**Comment by chrisseaton** [comment]
RC 17 was the promoted RC that became 19, and the change log mentions this issue by number.

https://github.com/oracle/truffleruby/blob/master/CHANGELOG.md#1900-may-2019

This issue is also marked as having the 19 milestone. I guess GH renames it on the issue info box, but not in the text.
