### ISSUE TITLE
bootsnap:  `caller_locations': Truffle doesn't have a case for the org.truffleruby.core.kernel.KernelNodesFactory$CallerLocationsNodeFactory$CallerLocationsNodeGen node with values of type Range

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1619]
Version

```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

This happens when a regular Rails application booting with enabled bootsnap.

Error:

```
~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `caller_locations': Truffle doesn't have a case for the org.truffleruby.core.kernel.KernelNodesFactory$CallerLocationsNodeFactory$CallerLocationsNodeGen node with values of type  Range(com.oracle.truffle.object.basic.DynamicObjectBasic) org.truffleruby.language.NotProvided (TypeError)
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:42:in `require_relative'
	from ~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/mri/cgi/cookie.rb:2:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/mri/cgi.rb:294:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/i18n-1.5.1/lib/i18n/exceptions.rb:3:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/i18n-1.5.1/lib/i18n.rb:6:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/activesupport-5.2.2/lib/active_support/i18n.rb:7:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/activesupport-5.2.2/lib/active_support/inflector/inflections.rb:6:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/activesupport-5.2.2/lib/active_support/inflector.rb:4:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/activesupport-5.2.2/lib/active_support/core_ext/module/introspection.rb:3:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:9:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache.rb:39:in `setup'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap.rb:24:in `setup'
	from ~/.gem/truffleruby/2.6.1/gems/bootsnap-1.3.2/lib/bootsnap/setup.rb:33:in `<top (required)>'
	from ~/dev/bugs/app/config/boot.rb:4:in `require'
	from ~/dev/bugs/app/config/boot.rb:4:in `<top (required)>'
	from bin/rails:8:in `require_relative'
	from bin/rails:8:in `<main>'
```

**Comment by deepj** [comment]
@eregon I haven't seen this for a while

**Comment by eregon** [comment]
I think @norswap fixed this (`Kernel#caller_locations(Range)`), let's close it.
