### ISSUE TITLE
dalli: ArgumentError: load error, unknown type 6

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1622]
Similar to #1574 

Version:

```
truffleruby 1.0.0-rc14-dev-f6b387c4, like ruby 2.6.1, Interpreted [x86_64-darwin]
```

To reproduce:

```
git clone https://github.com/petergoldstein/dalli.git
cd dalli
bundle
ruby -Itest test/test_dalli.rb
```

Error:

```
E, [2019-03-17T00:30:31.275000 #41309] ERROR -- : Unexpected exception during Dalli request: ArgumentError: load error, unknown type 6
E, [2019-03-17T00:30:31.277000 #41309] ERROR -- : ~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `construct'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `get_symbol'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `block in set_instance_variables'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `times'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `set_instance_variables'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `construct'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `load'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `deserialize'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:513:in `generic_response'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:272:in `get'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:70:in `request'
	~/dev/bugs/truffleruby/dalli/lib/dalli/options.rb:19:in `block in request'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/mri/monitor.rb:230:in `mon_synchronize'
	~/dev/bugs/truffleruby/dalli/lib/dalli/options.rb:18:in `request'
	~/dev/bugs/truffleruby/dalli/lib/dalli/client.rb:368:in `perform'
	~/dev/bugs/truffleruby/dalli/lib/dalli/client.rb:59:in `get'
	test/test_dalli.rb:127:in `block (4 levels) in <main>'
	~/dev/bugs/truffleruby/dalli/test/memcached_mock.rb:84:in `memcached_persistent'
	test/test_dalli.rb:119:in `test_0001_support get/set'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
E, [2019-03-17T00:30:31.296000 #41309] ERROR -- : Unexpected exception during Dalli request: ArgumentError: load error, unknown type 6
E, [2019-03-17T00:30:31.297000 #41309] ERROR -- : ~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `construct'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `get_symbol'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `block in set_instance_variables'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `times'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `set_instance_variables'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `construct'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `load'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:442:in `deserialize'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:513:in `generic_response'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:272:in `get'
	~/dev/bugs/truffleruby/dalli/lib/dalli/server.rb:70:in `request'
	~/dev/bugs/truffleruby/dalli/lib/dalli/options.rb:19:in `block in request'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/mri/monitor.rb:230:in `mon_synchronize'
	~/dev/bugs/truffleruby/dalli/lib/dalli/options.rb:18:in `request'
	~/dev/bugs/truffleruby/dalli/lib/dalli/client.rb:368:in `perform'
	~/dev/bugs/truffleruby/dalli/lib/dalli/client.rb:59:in `get'
	test/test_dalli.rb:127:in `block (4 levels) in <main>'
	~/dev/bugs/truffleruby/dalli/test/memcached_mock.rb:84:in `memcached_persistent'
	test/test_dalli.rb:119:in `test_0001_support get/set'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:98:in `block (3 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:195:in `capture_exceptions'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:95:in `block (2 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:265:in `time_it'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:94:in `block in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:211:in `with_info_handler'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest/test.rb:93:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:960:in `run_one_method'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:334:in `run_one_method'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:321:in `block (2 levels) in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `each'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:320:in `block in run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:360:in `on_signal'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:347:in `with_info_handler'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:319:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `block in __run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `map'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:159:in `__run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:136:in `run'
	~/.rubies/truffleruby-1.0.0-nightly/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
```

There is more issues on RC13 but not on RC14-dev. Then there are some problems with numbers of TCP connections, but I don't know anything about that.

**Comment by eregon** [comment]
TruffleRuby is now in Dalli's CI (https://github.com/petergoldstein/dalli/issues/988) so this must be fixed.
