### ISSUE TITLE
pg: rb_fd_init not implemented

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1634]
To reproduce:

```ruby
require 'sequel'

Sequel.connect('postgres://localhost/rom_factory')
```

Error:

```
Traceback (most recent call last):
       16: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/connection_pool.rb:127:in `make_new'
       15: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:241:in `connect'
       14: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:241:in `each'
       13: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:241:in `block in connect'
       12: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:140:in `execute'
       11: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
       10: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
        9: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
        8: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
        7: from ~/.gem/truffleruby/2.6.2/gems/sequel-5.18.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
        6: from ~/.rubies/truffleruby-1.0.0-rc14/lib/truffle/truffle/cext_ruby.rb:41:in `async_exec'
        5: from ~/.gem/truffleruby/2.6.2/gems/pg-0.21.0/ext/pg_connection.c:3186:in `pgconn_async_exec'
        4: from ~/.gem/truffleruby/2.6.2/gems/pg-0.21.0/ext/pg_connection.c:3120:in `pgconn_block'
        3: from ~/.gem/truffleruby/2.6.2/gems/pg-0.21.0/ext/pg_connection.c:2417:in `wait_socket_readable'
        2: from ruby.c:3542:in `rb_fd_init'
        1: from ruby.c:2802:in `rb_tr_error'
Sequel::DatabaseConnectionError (RuntimeError: rb_fd_init not implemented)
```

**Comment by aardvark179** [comment]
I’m working my way through pg issues at the moment, I’ll take a look.

**Comment by aardvark179** [comment]
Okay, that area of `pg` change substantially in https://github.com/ged/ruby-pg/commit/65092156a4084fbc121dcd4928abaac5dd39d61b, which is why I haven't seen the same issue while testing. If you can use a more recent version of pg then that will partially solve the problem, but you'll need to wait a couple of days for my various PRs to get merged for all of this to be fully working.

To fix this at `pg` version 0.21.0 we'll need to fill in quite a few more C APIs related to file descriptors.

**Comment by deepj** [comment]
@aardvark179 Yes, it's possible to use more current version of `pg`. In fact, I haven't realized the old version is used in this case.

**Comment by eregon** [comment]
`pg` no longer seems to use `rb_fd_init` so I'll close this issue.
Also, TruffleRuby is now tested in pg's TravisCI.
