### ISSUE TITLE
Polyglot - require 'git' failed by "threads not allowed in single-threaded mode"

### ISSUE THREAD

**Issue by TisonKun** [oracle/truffleruby#1643]
After install gem [ruby-git](https://github.com/ruby-git/ruby-git), I can `require` it in irb

```
$ irb
irb(main):001:0> require 'git'
=> true
irb(main):002:0>
```

However, when I try to access it in a plotglot context, it fails with "Exception in thread "main" threads not allowed in single-threaded mode (SecurityError)"

The code is

``` java
Context context = context = Context.newBuilder("ruby").allowAllAccess(true).build();
context.eval("ruby", "require 'git'");
```

and error logs

```
Exception in thread "main" threads not allowed in single-threaded mode (SecurityError)
	at <ruby> block in Git::Lib#command(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:954:25411-25448)
	at <ruby> block in Git::Lib#with_custom_env_variables(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:930:24743-24769)
	at <ruby> Git::Lib#with_custom_env_variables(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:927:24630-24661)
	at <ruby> Git::Lib#command(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:953:25376-25409)
	at <ruby> Git::Lib#current_command_version(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:865:22626-22669)
	at <ruby> Git::Lib#meets_required_version?(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git/lib.rb:875:22856-22931)
	at <ruby> <top (required)>(/Users/tison/.sdkman/candidates/java/1.0.0-rc-13-grl/jre/languages/ruby/lib/ruby/gems/2.4.0/gems/git-1.5.0/lib/git.rb:25:629-662)
	at <ruby> <top (required)>(Unnamed:1:0-12)
	at <ruby> null(Unknown)
	at org.graalvm.polyglot.Context.eval(Context.java:361)
	at io.tison.polyglot.ruby.Ruby.generateGitInfo(Ruby.java:20)
	at io.tison.polyglot.GitPlot.main(GitPlot.java:9)
```

**Comment by TisonKun** [comment]
since I already set `#allowAllAccess(true)`, I don't know how to resolve this issue.

**Comment by TisonKun** [comment]
Code around error log reported is 

```ruby
      with_custom_env_variables do
        command_thread = Thread.new do
          output = run_command(git_cmd, &block)
          exitstatus = $?.exitstatus
        end  
        command_thread.join
      end  
```

**Comment by chrisseaton** [comment]
@TisonKun sorry this issue is a little complicated at the moment. The relevant documentation is here

https://github.com/oracle/truffleruby/blob/master/doc/user/polyglot.md#embedded-configuration

When you use TruffleRuby from anything other there than the `ruby` launcher (or `irb` or whatever) you get an *embedded configuration*. This includes enabling single-threaded mode.

For what you want to do, probably just turn off single-threaded mode, by setting `ruby.single-threaded` to `false`.

As I say there's some complexity around this, so please try it and let me know, but that should already fix your issue. I can explain in more depth why this is needed if you're really interested.

**Comment by chrisseaton** [comment]
@eregon do you think it's still right that we're setting `single-threaded` in this configuration? I have a vague idea something changed in this area recently...

**Comment by TisonKun** [comment]
Add an option to workaround,

`.option("ruby.single_threaded", "false")`

and now process can fall through without exceptions.

However, the application becomes unable to exit when it executed the last statement.

The repository is here https://github.com/TisonKun/graal-polyglot-demo

**Comment by eregon** [comment]
> @eregon do you think it's still right that we're setting `single-threaded` in this configuration? I have a vague idea something changed in this area recently...

At some point we made `single-threaded` default to `embedded`. This is still needed for `js` at least, until we have a more general solution in Truffle. cc @eleinadani

**Comment by eregon** [comment]
Maybe this should be more dynamic: we'd wait for the first thread creation and check if that succeed, then OK, otherwise turn on single-threaded mode and raise the exception.
