### ISSUE TITLE
multi_string_replace: rb_eval_string_protect not implemented

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1652]
To reproduce:

```
git clone https://github.com/jedld/multi_string_replace.git
cd multi_string_replace
bundle
bundle exec rake compile:multi_string_replace
bundle exec rake
```

Error:

```
An error occurred while loading spec_helper.
Failure/Error: require "multi_string_replace/multi_string_replace"

RuntimeError:
  rb_eval_string_protect not implemented
# ./src/main/c/cext/ruby.c:2880:in `rb_tr_error'
# ./src/main/c/cext/ruby.c:4666:in `rb_eval_string_protect'
# ./ext/multi_string_replace/multi_string_replace.c:111:in `Init_multi_string_replace'
# ./lib/multi_string_replace.rb:2:in `require'
# ./lib/multi_string_replace.rb:2:in `<top (required)>'
# ./spec/spec_helper.rb:2:in `require'
# ./spec/spec_helper.rb:2:in `<top (required)>'
```

TruffleRuby 1.0.0 RC15

**Comment by aardvark179** [comment]
I have a fix for this that I'm putting through CI at the moment.
