### ISSUE TITLE
Should not reach here

### ISSUE THREAD

**Issue by rbotafogo** [oracle/truffleruby#1678]
The following code in Galaaz get "should not reach here" message:

    require 'galaaz'
    R.library 'tidyverse'
    # read data file
    @financas = R.read_csv2('finance.csv',
                            locale: R.locale(date_names: "br", decimal_mark: ",", 
                                             grouping_mark: "."))

    @financas =
      @financas.
        mutate('Valor BRR': :'Valor Nominal' *
                            E.if_else((:Data.eq "04/12/2018"), 1, 3.86))

/home/rbotafogo/desenv/galaaz/lib/R_interface/rsupport.rb:235:in `exec_function': java.lang.RuntimeException: com.oracle.truffle.r.runtime.RInternalError: java.lang.RuntimeException: com.oracle.truffle.r.runtime.RInternalError: should not reach here: invalid wrapping: DynamicObjectBasic (RInternalError) (RuntimeError)
	from com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:330)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	from com.oracle.truffle.r.nodes.function.call.CallRFunctionNode.execute(CallRFunctionNode.java:63)
	from com.oracle.truffle.r.nodes.function.RCallNode$DispatchedCallNode.execute(RCallNode.java:1212)
	from com.oracle.truffle.r.nodes.function.RCallNode$FunctionDispatch.dispatch(RCallNode.java:918)
Caused by:
com.oracle.truffle.r.runtime.RInternalError: java.lang.RuntimeException: com.oracle.truffle.r.runtime.RInternalError: should not reach here: invalid wrapping: DynamicObjectBasic (RuntimeException)
	from com.oracle.truffle.r.ffi.impl.nfi.HandleNFIUpCallExceptionNode.execute(HandleNFIUpCallExceptionNode.java:48)
	from com.oracle.truffle.r.ffi.impl.upcalls.Rf_evalCall$Rf_evalCallFactory$1.execute(Rf_evalCall.java:80)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	from com.oracle.truffle.api.interop.InteropAccessNode$CachedNode.doCached(InteropAccessNode.java:304)
	from com.oracle.truffle.api.interop.InteropAccessNodeFactory$CachedNodeGen.executeImpl(InteropAccessNodeFactory.java:42)
Caused by:
java.lang.RuntimeException: com.oracle.truffle.r.runtime.RInternalError: should not reach here: invalid wrapping: DynamicObjectBasic (RInternalError)
	from com.oracle.truffle.r.nodes.function.FunctionDefinitionNode.execute(FunctionDefinitionNode.java:330)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	from com.oracle.truffle.r.nodes.function.call.CallRFunctionNode.execute(CallRFunctionNode.java:63)
	from com.oracle.truffle.r.nodes.function.RCallNode$DispatchedCallNode.execute(RCallNode.java:1212)
	from com.oracle.truffle.r.nodes.function.RCallNode$FunctionDispatch.dispatch(RCallNode.java:918)
Caused by:
com.oracle.truffle.r.runtime.RInternalError: should not reach here: invalid wrapping: DynamicObjectBasic (RuntimeException)
	from com.oracle.truffle.r.ffi.impl.nfi.HandleNFIUpCallExceptionNode.execute(HandleNFIUpCallExceptionNode.java:48)
	from com.oracle.truffle.r.ffi.impl.upcalls.CARCall$CARCallFactory$1.execute(CARCall.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	from com.oracle.truffle.api.interop.InteropAccessNode$CachedNode.doCached(InteropAccessNode.java:304)
	from com.oracle.truffle.api.interop.InteropAccessNodeFactory$CachedNodeGen.executeImpl(InteropAccessNodeFactory.java:42)
Caused by:
should not reach here: invalid wrapping: DynamicObjectBasic (RInternalError)
	from com.oracle.truffle.r.runtime.RInternalError.shouldNotReachHere(RInternalError.java:132)
	from com.oracle.truffle.r.runtime.ffi.FFIWrapNode.wrap(FFIWrapNode.java:129)
	from com.oracle.truffle.r.runtime.ffi.FFIWrapNodeGen.executeAndSpecialize(FFIWrapNodeGen.java:183)
	from com.oracle.truffle.r.runtime.ffi.FFIWrapNodeGen.execute(FFIWrapNodeGen.java:100)
	from com.oracle.truffle.r.ffi.impl.upcalls.CARCall$CARCallFactory$1.execute(CARCall.java:71)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
Translated to internal error
	from /home/rbotafogo/desenv/galaaz/lib/R_interface/rsupport.rb:271:in `exec_function_name'
	from /home/rbotafogo/desenv/galaaz/lib/R_interface/robject.rb:180:in `method_missing'
	from bugs/should_not.rb:12:in `<main>'
rake aborted!

To reproduce:

- Clone de development branch of galaaz
- on directory ~/desenv/galaaz run 'rake blugs:should_not'

**Comment by chrisseaton** [comment]
Thanks for the report. I'll move it to FastR though, as it's their exception. It many eventually be something that Ruby is done wrong, but it should probably start with them.
