### ISSUE TITLE
GC.stat :total_allocated_objects is not supported

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1681]
I'm not sure if TruffleRuby is able to support this or Rails needs to change this in code here

https://github.com/rails/rails/blob/6-0-stable/activesupport/lib/active_support/notifications/instrumenter.rb#L159

But there is a specific case for JRuby where this part returns `0` instead.

This causes the following error in across Rails 6 tests in `ActiveSupport::Notification.instrument`

```
ArgumentError: wrong number of arguments (given 1, expected 0)
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/instrumenter.rb:159:in `stat'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/instrumenter.rb:159:in `now_allocations'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/instrumenter.rb:81:in `start!'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/subscriber.rb:132:in `start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/log_subscriber.rb:103:in `start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/fanout.rb:156:in `start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/fanout.rb:58:in `block in start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/fanout.rb:58:in `each'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/fanout.rb:58:in `start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/instrumenter.rb:36:in `start'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications/instrumenter.rb:22:in `instrument'
    ~/dev/bugs/truffleruby/rails/activesupport/lib/active_support/notifications.rb:180:in `instrument'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/abstract_controller/base.rb:136:in `process'
    ~/dev/bugs/truffleruby/rails/actionview/lib/action_view/rendering.rb:39:in `process'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_controller/metal.rb:191:in `dispatch'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_controller/test_case.rb:513:in `process'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_controller/test_case.rb:400:in `post'
    ~/dev/bugs/truffleruby/rails/actionpack/test/controller/request_forgery_protection_test.rb:778:in `block in test_should_not_warn_if_form_authenticity_param_matches_form_authenticity_token'
```

**Comment by aardvark179** [comment]
There's two separate issues here
1. We don't have the correct behaviour for `GC.stat` as we should accept keys
2. `ActiveSupport` should probably make that definition conditional on the key being present in the result of a `GC.stat`, not on the ruby implementation.

**Comment by deepj** [comment]
@aardvark179 

>ActiveSupport should probably make that definition conditional on the key being present in the result of a GC.stat, not on the ruby implementation.

Have you idea how to detect it? I could make PR to Rails

**Comment by eregon** [comment]
@deepj One possibility is to check with `GC.method(:stat).arity != 0`.
A probably much more reliable way would be to call `GC.stat :total_allocated_objects` and if that raise any exception define the fallback.

I'm thinking we should implement this `GC.stat` call as returning `0` in TruffleRuby for now.

**Comment by aardvark179** [comment]
Or do
```
        unless GC.stat.include?(:total_allocated_objects)
          def now_allocations
            0
          end
        else
          def now_allocations
            GC.stat :total_allocated_objects
          end
        end
```
Not perfect, but it will set things up properly no matter the Ruby implementation.
