### ISSUE TITLE
[interop] Cannot print Python objects in polyglot shell from Ruby

### ISSUE THREAD

**Issue by fniephaus** [oracle/truffleruby#1691]
## Repro

```java
polyglot --jvm --shell
GraalVM MultiLanguage Shell 19.0.0
Copyright (c) 2013-2019, Oracle and/or its affiliates
  Python version 3.7.0
  Ruby version 2.6.2
js> -verboseErrors
Verbose errors is now on.
js> python>
python> import polyglot
python> polyglot.export_value({}, "a")
{}
python> ruby>
ruby> puts Polyglot.import('a')
Internal error occured: org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.RaiseException: AttributeError: 'dict' object has no attribute 'object_id' (PException)
Translated to internal error (RuntimeError)
org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.RaiseException: AttributeError: 'dict' object has no attribute 'object_id' (PException)
Translated to internal error (RuntimeError)
	at com.oracle.truffle.api.TruffleStackTrace.materializeHostException(TruffleStackTrace.java:103)
	at com.oracle.truffle.api.TruffleStackTrace.materializeHostFrames(TruffleStackTrace.java:172)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.materializeHostFrames(TruffleLanguage.java:2458)
	at com.oracle.truffle.polyglot.PolyglotExceptionImpl.<init>(PolyglotExceptionImpl.java:175)
	at com.oracle.truffle.polyglot.PolyglotExceptionImpl.<init>(PolyglotExceptionImpl.java:98)
	at com.oracle.truffle.polyglot.PolyglotImpl.wrapGuestException(PolyglotImpl.java:400)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:812)
	at org.graalvm.polyglot.Context.eval(Context.java:341)
	at org.graalvm.launcher.MultiLanguageShell.readEvalPrint(MultiLanguageShell.java:197)
	at org.graalvm.launcher.PolyglotLauncher.runShell(PolyglotLauncher.java:419)
	at org.graalvm.launcher.PolyglotLauncher.launch(PolyglotLauncher.java:219)
	at org.graalvm.launcher.PolyglotLauncher.main(PolyglotLauncher.java:429)
Original Internal Error:
org.truffleruby.language.control.RaiseException: AttributeError: 'dict' object has no attribute 'object_id' (PException)
Translated to internal error (RuntimeError)
Caused by: Attached Guest Language Frames (8)
```

Maybe this is related to https://github.com/oracle/truffleruby/issues/1686?

/cc @janehmueller

**Comment by eregon** [comment]
Relates to #1679.

**Comment by eregon** [comment]
Works fine now:
```
ruby> puts Polyglot.import('a')
#<Polyglot::ForeignHashIterable[Python] {}>
```
