### ISSUE TITLE
The regular expression in tool/jt.rb does not match the new jvmci version format

### ISSUE THREAD

**Issue by Mogztter** [oracle/truffleruby#1693]
The regular expression is `/8u(\d+)-(jvmci-0.\d+)/` but the latest version of jvmci is `8u212-jvmci-20-b01` (ie. not prefixed by a "0.").

As a consequence the following command is failing:

```console
$ ruby tool/jt.rb mx version
Error during command: mx version
Traceback (most recent call last):
	6: from tool/jt.rb:2458:in `<main>'
	5: from tool/jt.rb:2449:in `main'
	4: from tool/jt.rb:626:in `mx'
	3: from tool/jt.rb:476:in `mx'
	2: from tool/jt.rb:470:in `find_java_home'
	1: from tool/jt.rb:1879:in `install_jvmci'
tool/jt.rb:133:in `jvmci_update_and_version': JVMCI version not found in ci.jsonnet:
```

And also:

```console
$ JVMCI_VERSION=jvmci-20-b01 ruby tool/jt.rb install jvmci
Error during command: install jvmci
Traceback (most recent call last):
	4: from tool/jt.rb:2458:in `<main>'
	3: from tool/jt.rb:2449:in `main'
	2: from tool/jt.rb:1868:in `install'
	1: from tool/jt.rb:1879:in `install_jvmci'
tool/jt.rb:128:in `jvmci_update_and_version': Could not parse JDK update and JVMCI version from $JVMCI_VERSION (RuntimeError)
```

**Comment by aardvark179** [comment]
The fix for this has now been merged.
