### ISSUE TITLE
Infinite loop when naming a top level function 'hash' and using a Symbol

### ISSUE THREAD

**Issue by Confusion** [oracle/truffleruby#1700]
TruffleRuby 19.0.0, JDK 11.0.3

Probably related to #1699. Issue becomes a regular infinite loop if you replace the symbol by e.g. an integer.

The following code results in an infinite loop, without detecting a StackOverflowError.
```
def hash                                                                                                                                                                     
  [:a].map {|v| [v, v]}.to_h                                                       
end                                                                                
                                                                                   
puts hash[nil]    
```

Output, after ctrl-C:
```
$ truffleruby hangs.rb 
^C^C^Changs.rb:7:in `block (2 levels) in <top (required)>': Interrupt (Interrupt)
	from hangs.rb:7:in `block in <top (required)>'
	from hangs.rb:7:in `execute_coerce_to'
	from hangs.rb:7:in `coerce_to'
	from hangs.rb:7:in `coerce_to_int'
	from hangs.rb:7:in `[]'
	from hangs.rb:7:in `detect_recursion'
	from hangs.rb:7:in `inspect'
	from hangs.rb:7:in `coerce_to_failed'
	from hangs.rb:7:in `execute_coerce_to'
        [ repetition elided]
```

**Comment by chrisseaton** [comment]
Yes the same as #1699. I'll close as a duplicate. Thanks.
