### ISSUE TITLE
Haml >= 5.0 doesn't work on TruffleRuby, due to using Ripper

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1712]
```haml
%section.container
  %h1= 'Title'
  %h2= Time.now
  .content
    Hello World
```

```
$ haml --trace hello.haml
/home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/temple-0.8.1/lib/temple/static_analyzer.rb:40:in `static?': undefined method `lex' for Ripper:Class (NoMethodError)
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:160:in `block in compile_attribute'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:160:in `block in all?'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:160:in `each'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:160:in `all?'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:160:in `compile_attribute'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:107:in `compile_attribute_values'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:61:in `block in compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:60:in `map'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/attribute_compiler.rb:60:in `compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:111:in `compile_tag'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:32:in `compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:32:in `block (2 levels) in compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:32:in `each'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:32:in `block in compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:42:in `compile_root'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:32:in `compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/compiler.rb:23:in `call'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/temple-0.8.1/lib/temple/engine.rb:50:in `block in call'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/temple-0.8.1/lib/temple/engine.rb:50:in `inject'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/temple-0.8.1/lib/temple/engine.rb:50:in `call'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/temple_engine.rb:43:in `compile'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/engine.rb:65:in `initialize'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/exec.rb:302:in `new'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/exec.rb:302:in `process_result'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/exec.rb:44:in `parse'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/lib/haml/exec.rb:24:in `parse!'
	from /home/eregon/.rubies/truffleruby-19.1.0/lib/ruby/gems/2.6.0/gems/haml-5.1.1/bin/haml:9:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-19.1.0/bin/haml:23:in `load'
	from /home/eregon/.rubies/truffleruby-19.1.0/bin/haml:23:in `load'
	from /home/eregon/.rubies/truffleruby-19.1.0/bin/haml:23:in `<main>'
```

Related to #1585 and #1692.

Either we should implement enough of Ripper for this to work, or we should change Haml to better detect if Ripper is available, assuming Ripper is just an optimization here.

https://github.com/haml/haml/blob/master/CHANGELOG.md#500
> Analyze attribute values by Ripper and render static attributes beforehand. (Takashi Kokubun)

Found by @Mogztter in https://github.com/asciidoctor/asciidoctor/pull/3305

**Comment by eregon** [comment]
File using Ripper in Haml:
https://github.com/haml/haml/blob/master/lib/haml/attribute_parser.rb

**Comment by eregon** [comment]
It notably checks using https://github.com/judofyr/temple/blob/408ae218fcbcdf52b2895c9f0fb9015078984491/lib/temple/static_analyzer.rb#L33

So as usual, either we don't define `Ripper` at all and let it `LoadError`, or we probably have to implement most of it.

**Comment by Mogztter** [comment]
Thanks @eregon 👍

**Comment by eregon** [comment]
I forgot to update this issue:
A workaround was merged in `temple` in https://github.com/judofyr/temple/pull/127 by @k0kubun, thanks!
Therefore Haml works in TruffleRuby >= 19.3.0.

It's not ideal yet for performance though (#1747).
