### ISSUE TITLE
Net/SFTP: rb_str_drop_bytes not implemented

### ISSUE THREAD

**Issue by mauricioszabo** [oracle/truffleruby#1730]
While I was trying to use Net::SFTP library, I found the following error:

Exception rb_str_drop_bytes not implemented

With backtrace:

```
ruby.c:2903:in `rb_tr_error'
ruby.c:4327:in `rb_str_drop_bytes'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/src/main/c/openssl/ossl_asn1.c:1162:in `ossl_asn1prim_to_der'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:37:in `to_der'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/truffle/truffle/cext.rb:967:in `rb_funcall'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/src/main/c/openssl/ossl.c:248:in `ossl_to_der'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/src/main/c/openssl/ossl.c:258:in `ossl_to_der_if_possible'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/src/main/c/openssl/ossl_asn1.c:1195:in `ossl_asn1cons_to_der'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/truffle/truffle/cext_ruby.rb:37:in `to_der'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/openssl.rb:213:in `ssh_do_verify'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:209:in `block in verify_signature'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/verifiers/accept_new.rb:26:in `verify_signature'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:209:in `verify_signature'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:73:in `exchange_keys'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:406:in `exchange_keys'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:228:in `proceed!'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:167:in `accept_kexinit'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:90:in `initialize'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
/home/mauricio/bin/graalvm-ce-19.1.1/jre/languages/ruby/lib/ruby/gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp.rb:31:in `start'
.... and so on...
```

Ruby's version output:
truffleruby 19.1.1, like ruby 2.6.2, GraalVM CE Native

On Ubuntu 18.04.2 LTS

**Comment by HoneyryderChuck** [comment]
Getting the same error when using the ASN1 layer of `ruby-openssl` (https://travis-ci.org/swisscom/ruby-netsnmp/jobs/567174660)

**Comment by eregon** [comment]
https://github.com/oracle/truffleruby/pull/1732 is a PR aiming to implement `rb_str_drop_bytes`.

**Comment by wangyin-git** [comment]
How about 'rb_io_set_nonblock'.  I got a #<RuntimeError: rb_io_set_nonblock not implemented>

ruby version:
truffleruby 19.1.0, like ruby 2.6.2, GraalVM CE Native [x86_64-linux]

**Comment by eregon** [comment]
@wangyin-git We'll implement `rb_io_set_nonblock`, it's needed for `async` too IIRC.

**Comment by eregon** [comment]
`rb_str_drop_bytes` has been implemented in #1740, it will be in the next release.

For `rb_io_set_nonblock`, I split it in a separate issue: #1741.

**Comment by eregon** [comment]
@mauricioszabo @HoneyryderChuck TruffleRuby 19.3.0 was released, could you verify it works now?

**Comment by HoneyryderChuck** [comment]
Issue seems to have been fixed https://travis-ci.org/swisscom/ruby-netsnmp/jobs/608498676, although build is failing, apparently because bundling is taking too much time.

**Comment by eregon** [comment]
@HoneyryderChuck It looks like it's getting stuck while running specs. Running spec in "verbose mode" with `--format documentation` should show which spec hangs.

Could you file a new issue with that, since it's separate from this one?

**Comment by HoneyryderChuck** [comment]
sure, will keep u posted.
