### ISSUE TITLE
truffleruby is broken with rake test suite

### ISSUE THREAD

**Issue by hsbt** [oracle/truffleruby#1739]
HI, I would like to support truffleruby in rake.

I try to add truffleruby provided by RVM in GitHub Actions. But I got the test failure like this:

https://github.com/ruby/rake/runs/196971401#step:6:5

I'm not sure why that has happened. It's great to resolve at the next version of truffleruby.

Thanks,

**Comment by chrisseaton** [comment]
There's two failures here

```
2019-08-19T11:48:57.4884841Z   1) Error:
2019-08-19T11:48:57.4884892Z TestRakeFileUtils#test_sh_with_hash_option:
2019-08-19T11:48:57.4884956Z RuntimeError: Unknown spawn option: chdir
2019-08-19T11:48:57.4885308Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `block in posix_spawnp'
2019-08-19T11:48:57.4885535Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `each_pair'
2019-08-19T11:48:57.4885702Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `posix_spawnp'
2019-08-19T11:48:57.4886096Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `spawn'
2019-08-19T11:48:57.4886305Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `spawn'
2019-08-19T11:48:57.4886461Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `spawn'
2019-08-19T11:48:57.4886640Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `system'
2019-08-19T11:48:57.4886795Z     /home/runner/work/rake/rake/lib/rake/file_utils.rb:54:in `sh'
2019-08-19T11:48:57.4886972Z     /home/runner/work/rake/rake/test/test_rake_file_utils.rb:189:in `block in test_sh_with_hash_option'
2019-08-19T11:48:57.4887151Z     /home/runner/work/rake/rake/lib/rake/file_utils_ext.rb:59:in `verbose'
2019-08-19T11:48:57.4887325Z     /home/runner/work/rake/rake/test/test_rake_file_utils.rb:188:in `test_sh_with_hash_option'
2019-08-19T11:48:57.4887358Z 
2019-08-19T11:48:57.4887397Z   2) Error:
2019-08-19T11:48:57.4887451Z TestRakeClean#test_clean:
2019-08-19T11:48:57.4887501Z RuntimeError: <no message> (UnsupportedOperationException)
2019-08-19T11:48:57.4887552Z 	from org.truffleruby.core.kernel.TruffleKernelNodes$LoadNode.load(TruffleKernelNodes.java:75)
2019-08-19T11:48:57.4887623Z 	from org.truffleruby.core.kernel.TruffleKernelNodesFactory$LoadNodeFactory$LoadNodeGen.executeAndSpecialize(TruffleKernelNodesFactory.java:225)
2019-08-19T11:48:57.4887683Z 	from org.truffleruby.core.kernel.TruffleKernelNodesFactory$LoadNodeFactory$LoadNodeGen.execute(TruffleKernelNodesFactory.java:207)
2019-08-19T11:48:57.4887735Z 	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
2019-08-19T11:48:57.4887964Z 	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:51)
2019-08-19T11:48:57.4888001Z 	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:54)
2019-08-19T11:48:57.4888035Z 	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:328)
2019-08-19T11:48:57.4888101Z 	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:318)
2019-08-19T11:48:57.4888139Z 	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:305)
2019-08-19T11:48:57.4888178Z 	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
2019-08-19T11:48:57.4888230Z Translated to internal error
2019-08-19T11:48:57.4888364Z     /home/runner/work/rake/rake/test/test_rake_clean.rb:7:in `load'
2019-08-19T11:48:57.4888491Z     /home/runner/work/rake/rake/test/test_rake_clean.rb:7:in `block in load'
2019-08-19T11:48:57.4888632Z     /home/runner/work/rake/rake/test/test_rake_clean.rb:7:in `each'
2019-08-19T11:48:57.4888755Z     /home/runner/work/rake/rake/test/test_rake_clean.rb:7:in `load'
2019-08-19T11:48:57.4888880Z     /home/runner/work/rake/rake/test/test_rake_clean.rb:7:in `test_clean'
```

For `#spwan` with `:chdir` it looks like this is indeed not yet supported - it's tagged https://github.com/oracle/truffleruby/blob/5458f470b90d9c37eca0378f5b0ad1075f871999/spec/tags/core/process/spawn_tags.txt#L77-L78.

For the `UnsupportedOperationException` it's from here https://github.com/oracle/truffleruby/blob/5458f470b90d9c37eca0378f5b0ad1075f871999/src/main/java/org/truffleruby/core/kernel/TruffleKernelNodes.java#L74, so this is `#load` with `wrap` set, which is also indeed not yet supported, and tagged https://github.com/oracle/truffleruby/blob/5458f470b90d9c37eca0378f5b0ad1075f871999/spec/tags/core/kernel/load_tags.txt#L5-L14.

So it's two unimplemented features. The error message could be better on the second one.

We'll need to implement these features, thanks.

**Comment by hsbt** [comment]
@chrisseaton Thanks. I temporary removed `truffleruby` on CI of ruby/rake. I will add it again when it was resolved.

**Comment by chrisseaton** [comment]
I've got a fix on the way for `Kernel#load` (the second failure.)

The first failure is a bit more tricky - it requires us to `chdir` on the thread running `spawn` (because it's not actually part of the system call) but we run threads in parallel so we might cause problems doing that. JRuby run a sub-command to change directory and then run the spawn. Maybe we should do that as well.

**Comment by eregon** [comment]
`spawn(chdir:)` is tracked as #1492, I'll try to get to that.
I think the most promising approach there is to use a small executable to chdir() and then exec(), much like Java does in some cases.

**Comment by chrisseaton** [comment]
`Kernel#load` is fixed in https://github.com/oracle/truffleruby/commit/5ccaefbfc7bb5030c1032f7e7eb1331c9566d1e7.

**Comment by eregon** [comment]
I fixed `spawn(chdir:)` (#1492) in d39f45e6fc1d50354fa2ed237883e5a798996bd3, it will be in the next release.
I'll try to run the tests locally to make sure they pass now.

**Comment by chrisseaton** [comment]
Thanks for that @eregon - I though supporting chdir was going to be very difficult.

**Comment by eregon** [comment]
TruffleRuby now runs in Rake's CI: https://github.com/ruby/rake/pull/331
@hsbt Thank you for the bug report!
