### ISSUE TITLE
Runtime Error with Agoo web server

### ISSUE THREAD

**Issue by tiredenzo** [oracle/truffleruby#1823]
Hello,
while tryiing to run [Agoo](https://github.com/ohler55/agoo) with truffleruby-19.3.0

with the provided example in the documentation

```
require 'agoo'

Agoo::Server.init(6464, 'root')

class MyHandler
  def call(req)
    [ 200, { }, [ "hello world" ] ]
  end
end

handler = MyHandler.new
Agoo::Server.handle(:GET, "/hello", handler)
Agoo::Server.start()
```
app.rb

```gem install agoo```
```ruby app.rb```

Accessing the browser to `http://localhost:6464/hello`

I get the following stacktrace in my console

```
/home/enzo/.rvm/rubies/truffleruby-19.3.0/lib/truffle/truffle/cext_ruby.rb:20:in `start': TruffleRuby doesn't have a case for the org.truffleruby.cext.UnwrapNodeGen node with values of type  java.lang.Integer=0 (TypeError)
	from org.truffleruby.cext.UnwrapNodeGen.executeAndSpecialize(UnwrapNodeGen.java:309)
	from org.truffleruby.cext.UnwrapNodeGen.execute(UnwrapNodeGen.java:133)
	from org.truffleruby.cext.ValueWrapperManager$UnwrapperFunction.execute(ValueWrapperManager.java:339)
	from org.truffleruby.cext.UnwrapperFunctionGen$InteropLibraryExports$Cached.execute(UnwrapperFunctionGen.java:83)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode$LLVMLookupDispatchForeignNode.doGeneric(LLVMDispatchNode.java:272)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode$LLVMLookupDispatchForeignNode.doUnknownType(LLVMDispatchNode.java:296)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen$LLVMLookupDispatchForeignNodeGen.execute(LLVMDispatchNodeGen.java:563)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doForeign(LLVMDispatchNode.java:228)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:126)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:392)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:376)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:111)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:392)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:376)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:111)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:175)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:134)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:392)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:376)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:111)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:175)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:134)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric_generic1(LLVMValueProfilingNodeFactory.java:392)
	from com.oracle.truffle.llvm.runtime.nodes.others.LLVMValueProfilingNodeFactory$LLVMI64ProfiledValueNodeGen.executeGeneric(LLVMValueProfilingNodeFactory.java:376)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWritePointerNodeGen.execute(LLVMWriteNodeFactory.java:714)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNode.doDirect(LLVMDispatchNode.java:111)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeAndSpecialize(LLVMDispatchNodeGen.java:175)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMDispatchNodeGen.executeDispatch(LLVMDispatchNodeGen.java:134)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMCallNode.executeGeneric(LLVMCallNode.java:70)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMVoidStatementNodeGen.execute(LLVMVoidStatementNodeGen.java:21)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.execute(LLVMBasicBlockNode.java:158)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.executeGeneric(LLVMDispatchBasicBlockNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.executeGeneric(LLVMFunctionRootNode.java:74)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:78)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.interop.LLVMForeignCallNode.execute(LLVMForeignCallNode.java:186)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$Execute.doCached(LLVMFunctionDescriptor.java:528)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.executeAndSpecialize(LLVMFunctionDescriptorGen.java:131)
	from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Cached.execute(LLVMFunctionDescriptorGen.java:96)
	from com.oracle.truffle.llvm.runtime.pointer.ManagedPointerLibraries.execute(ManagedPointerLibraries.java:69)
	from com.oracle.truffle.llvm.runtime.pointer.ManagedPointerLibrariesGen$InteropLibraryExports$Cached.execute(ManagedPointerLibrariesGen.java:625)
	from org.truffleruby.cext.CExtNodes$CallCWithMutexNode.execute(CExtNodes.java:154)
	from org.truffleruby.cext.CExtNodes$CallCWithMutexNode.callCWithMutex(CExtNodes.java:138)
	from org.truffleruby.cext.CExtNodesFactory$CallCWithMutexNodeFactory$CallCWithMutexNodeGen.executeAndSpecialize(CExtNodesFactory.java:305)
	from org.truffleruby.cext.CExtNodesFactory$CallCWithMutexNodeFactory$CallCWithMutexNodeGen.execute(CExtNodesFactory.java:218)
	from org.truffleruby.cext.CExtNodes$CallCWithMuteAndFramexNode.callCWithMutex(CExtNodes.java:180)
	from org.truffleruby.cext.CExtNodesFactory$CallCWithMuteAndFramexNodeFactory$CallCWithMuteAndFramexNodeGen.executeAndSpecialize(CExtNodesFactory.java:484)
	from org.truffleruby.cext.CExtNodesFactory$CallCWithMuteAndFramexNodeFactory$CallCWithMuteAndFramexNodeGen.execute(CExtNodesFactory.java:467)
	from org.truffleruby.cext.CExtNodesFactory$UnwrapValueNodeFactory$UnwrapValueNodeGen.execute(CExtNodesFactory.java:6637)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.CatchForLambdaNode.execute(CatchForLambdaNode.java:49)
	from org.truffleruby.core.module.ModuleNodes$DefineMethodNode$CallMethodWithProcBody.execute(ModuleNodes.java:1193)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:193)
	from org.truffleruby.language.dispatch.CachedSingletonDispatchNode.executeDispatch(CachedSingletonDispatchNode.java:95)
	from org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:136)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:115)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:103)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.CatchNextNode.execute(CatchNextNode.java:31)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:39)
	from org.truffleruby.language.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.exceptions.TopLevelRaiseHandler.execute(TopLevelRaiseHandler.java:39)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:244)
	from org.graalvm.compiler.truffle.runtime.OptimizedIndirectCallNode.call(OptimizedIndirectCallNode.java:48)
	from org.truffleruby.language.loader.CodeLoader$DeferredCall.call(CodeLoader.java:107)
	from org.truffleruby.language.TruffleBootNodes$MainNode.main(TruffleBootNodes.java:155)
	from org.truffleruby.language.TruffleBootNodesFactory$MainNodeFactory$MainNodeGen.executeAndSpecialize(TruffleBootNodesFactory.java:384)
	from org.truffleruby.language.TruffleBootNodesFactory$MainNodeFactory$MainNodeGen.execute(TruffleBootNodesFactory.java:363)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:193)
	from org.truffleruby.language.dispatch.CachedSingletonDispatchNode.executeDispatch(CachedSingletonDispatchNode.java:95)
	from org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:136)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:115)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:103)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.CatchForLambdaNode.execute(CatchForLambdaNode.java:49)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:256)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:64)
	from org.truffleruby.language.yield.CallBlockNode.callBlockCached(CallBlockNode.java:53)
	from org.truffleruby.language.yield.CallBlockNodeGen.executeAndSpecialize(CallBlockNodeGen.java:100)
	from org.truffleruby.language.yield.CallBlockNodeGen.executeCallBlock(CallBlockNodeGen.java:56)
	from org.truffleruby.language.yield.YieldNode.dispatch(YieldNode.java:37)
	from org.truffleruby.language.yield.YieldNodeGen.executeAndSpecialize(YieldNodeGen.java:46)
	from org.truffleruby.language.yield.YieldNodeGen.executeDispatchWithArrayArguments(YieldNodeGen.java:33)
	from org.truffleruby.language.yield.YieldNode.executeDispatch(YieldNode.java:29)
	from org.truffleruby.interop.ForeignExecuteHelperNode.callProc(ForeignExecuteHelperNode.java:32)
	from org.truffleruby.interop.ForeignExecuteHelperNodeGen.executeAndSpecialize(ForeignExecuteHelperNodeGen.java:69)
	from org.truffleruby.interop.ForeignExecuteHelperNodeGen.executeCall(ForeignExecuteHelperNodeGen.java:53)
	from org.truffleruby.interop.RubyObjectType.execute(RubyObjectType.java:493)
	from org.truffleruby.interop.RubyObjectTypeGen$InteropLibraryExports$Cached.executeNode_AndSpecialize(RubyObjectTypeGen.java:1078)
	from org.truffleruby.interop.RubyObjectTypeGen$InteropLibraryExports$Cached.execute(RubyObjectTypeGen.java:1064)
	from com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:3137)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1699)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:1780)
	from com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:98)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:348)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:338)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:325)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:135)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:937)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2459)
	from org.graalvm.polyglot.Value.execute(Value.java:368)
	from org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:233)
	from org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:121)
	from org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	from org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	from org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:38)
	from app.rb:13:in `<main>'
```

Thank you

**Comment by eregon** [comment]
Thank you for the bug report.

@aardvark179 Could you look into what causes this?

**Comment by aardvark179** [comment]
The original bug reported here appears to be fixed, but there is a remaining problem with Agoo's use of `rb_rescue2` which I am submitting a PR for.

**Comment by deepj** [comment]
@eregon Isn't this issue fixed in this commit https://github.com/oracle/truffleruby/commit/2208822c0ca2c79788bc0acc7297f15d9d79fd2c?

I can run the example above without any noticeable issues. Except one, after terminating server (`Ctrl + C`) I'm getting

```
truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException
```

**Comment by eregon** [comment]
Yes, @aardvark179 fixed it. Would you mind opening a separate issue for the Ctrl+C issue?

**Comment by eregon** [comment]
Seems related to https://github.com/oracle/truffleruby/issues/1972
