### ISSUE TITLE
opt fail: node is not LIRLowerable NewFrame

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#1825]
The second error is a compilation error:
```
[truffle] opt fail         Truffle::RegexpOperations.last_match resource:/truffleruby/core/truffle/regexp_operations.rb:24 <split-2c0d7f5>|Reason org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 32|NewFrame
	at node: 32|NewFrame
org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 32|NewFrame
	at node: 32|NewFrame
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:378)
	at org.graalvm.compiler.core.LIRGenerationPhase.emitBlock(LIRGenerationPhase.java:85)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:75)
	at org.graalvm.compiler.core.LIRGenerationPhase.run(LIRGenerationPhase.java:46)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:117)
	at org.graalvm.compiler.lir.phases.LIRPhase.apply(LIRPhase.java:109)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR0(LIRCompilerBackend.java:155)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitLIR(LIRCompilerBackend.java:113)
	at org.graalvm.compiler.core.gen.LIRCompilerBackend.emitBackEnd(LIRCompilerBackend.java:83)
	at org.graalvm.compiler.core.target.Backend.emitBackEnd(Backend.java:279)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:145)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:129)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compilePEGraph(TruffleCompilerImpl.java:528)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:470)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:644)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:586)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:179)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:299)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:267)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:710)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:691)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$Request.run(BackgroundCompileQueue.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:176)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:479)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 32|NewFrame
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.emitNode(NodeLIRBuilder.java:484)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doRoot(NodeLIRBuilder.java:473)
	at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:376)
	... 29 more       
```

That should let the process continue, although it might be quite a bit slower.

_Originally posted by @eregon in https://github.com/oracle/truffleruby/issues/1824#issuecomment-558228094_

**Comment by eregon** [comment]
@deepj Can you reproduce this error or did it happen only once?

**Comment by petenorth** [comment]
I have seen two other stack traces that look similar but are initiated from different Ruby classes. I think that in both cases the SubstrateVM was under memory pressure (?). Are these separate issues or related?

```
[truffle] opt fail         String#downcase resource:/truffleruby/core/string.rb:1559   |Reason org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 31|NewFrame
 	at node: 31|NewFrame 
 org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 31|NewFrame
 	at node: 31|NewFrame
```

```
 [truffle] opt fail         Hash#default resource:/truffleruby/core/hash.rb:178         |Reason org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 20|NewFrame
	at node: 20|NewFrame 
 org.graalvm.compiler.graph.GraalGraphError: org.graalvm.compiler.debug.GraalError: should not reach here: node is not LIRLowerable: 20|NewFrame
	at node: 20|NewFrame 
```
The stack traces continue then as in issue reported above 

```
at org.graalvm.compiler.core.gen.NodeLIRBuilder.doBlock(NodeLIRBuilder.java:378)
...
```

**Comment by eregon** [comment]
@petenorth Thanks, it looks related indeed.
This is a compiler bug, so I guess it can trigger on basically any Ruby code.

**Comment by eregon** [comment]
Tracked internally as GR-19746.
Does anyone still see this happen? Maybe it was fixed in Graal.
