### ISSUE TITLE
rdiscount: `Integer': can't convert nil into Integer (TypeError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1850]
To reproduce:

```
gem install rdiscount
```

Error:

```
Building native extensions. This could take a while...
ERROR:  Error installing rdiscount:
	ERROR: Failed to build gem native extension.

    current directory: ~/.gem/truffleruby/2.6.2/gems/rdiscount-2.2.0.1/ext
~/.rubies/truffleruby-19.3.0/bin/truffleruby -I ~/.rubies/truffleruby-19.3.0/lib/mri -r ./siteconf20191208-70328-xt6i6h.rb extconf.rb
checking for random()... yes
checking for srandom()... yes
checking for rand()... yes
checking for srand()... yes
checking size of unsigned long... ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:771:in `Integer': can't convert nil into Integer (TypeError)
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:771:in `block in try_constant'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:441:in `popen'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:441:in `block in xpopen'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:353:in `open'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:434:in `xpopen'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:770:in `try_constant'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:1379:in `block in check_sizeof'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:987:in `block in checking_for'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:383:in `block (2 levels) in postpone'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:353:in `open'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:383:in `block in postpone'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:353:in `open'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:379:in `postpone'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:986:in `checking_for'
	from ~/.rubies/truffleruby-19.3.0/lib/mri/mkmf.rb:1378:in `check_sizeof'
	from extconf.rb:11:in `block in sized_int'
	from extconf.rb:11:in `block in find'
	from extconf.rb:11:in `each'
	from extconf.rb:11:in `find'
	from extconf.rb:11:in `sized_int'
	from extconf.rb:15:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=~/.rubies/truffleruby-19.3.0/bin/truffleruby
	--with-rdiscount-dir
	--without-rdiscount-dir
	--with-rdiscount-include
	--without-rdiscount-include=${rdiscount-dir}/include
	--with-rdiscount-lib
	--without-rdiscount-lib=${rdiscount-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  ~/.gem/truffleruby/2.6.2/extensions/x86_64-darwin/19.3.0/rdiscount-2.2.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in ~/.gem/truffleruby/2.6.2/gems/rdiscount-2.2.0.1 for inspection.
Results logged to ~/.gem/truffleruby/2.6.2/extensions/x86_64-darwin/19.3.0/rdiscount-2.2.0.1/gem_make.out
```

**Comment by aardvark179** [comment]
Is this on macOS? I've just tried locally on Linux and it installs fine on our current development version, I'll check on macOS and 19.3 later.

**Comment by deepj** [comment]
Yes, I'm on macOS

**Comment by bjfish** [comment]
I currently get the error `dyld: Library not loaded: libpolyglot-mock.dylib` when trying to install using master.

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by deepj** [comment]
It seems this is fixed in the recent master. Compilation is ok, and this works as well

```
$ ruby -v
truffleruby 21.0.0-dev-6265f317, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
$ ruby -rrdiscount -e "puts RDiscount.new('Hello World!', :smart, :filter_html).to_html"
<p>Hello World!</p>
```

**Comment by eregon** [comment]
Great, thanks for checking!
