### ISSUE TITLE
Rubocop fails to parse files in TruffleRuby 19.3.1

### ISSUE THREAD

**Issue by jaimerave** [oracle/truffleruby#1883]
When I run rubocop 0.79.0 this is the error I'm getting

```
rubocop -d app/models/promotion.rb
For /Users/rave/Projects/backend-api: configuration from /Users/rave/Projects/backend-api/.rubocop.yml
Default configuration from /Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/config/default.yml
Inspecting 1 file
Scanning /Users/rave/Projects/backend-api/app/models/promotion.rb
An error occurred while Lint/Void cop was inspecting /Users/rave/Projects/backend-api/app/models/promotion.rb:2:2.
can't modify frozen Array
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/lint/void.rb:80:in `pop'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/lint/void.rb:80:in `check_begin'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/lint/void.rb:72:in `on_begin'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:136:in `with_cop_error_handling'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:32:in `on_begin'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:99:in `on_class'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:33:in `on_class'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/ast/traversal.rb:14:in `walk'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:124:in `investigate'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:112:in `offenses'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:296:in `inspect_file'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:244:in `block in do_inspection_loop'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:276:in `block in iterate_until_no_changes'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:269:in `loop'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:269:in `iterate_until_no_changes'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:240:in `do_inspection_loop'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:119:in `block in file_offenses'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:143:in `file_offense_cache'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:117:in `file_offenses'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:108:in `process_file'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:86:in `inject'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:73:in `inspect_files'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/runner.rb:39:in `run'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli/command.rb:10:in `run'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli/environment.rb:17:in `run'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli.rb:65:in `run_command'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/lib/rubocop/cli.rb:41:in `run'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/exe/rubocop:13:in `block in <top (required)>'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/mri/benchmark.rb:308:in `realtime'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/lib/gems/gems/rubocop-0.79.0/exe/rubocop:12:in `<top (required)>'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/bin/rubocop:23:in `load'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/bin/rubocop:23:in `load'
/Users/rave/.rbenv/versions/truffleruby-19.3.1/bin/rubocop:23:in `<main>'
```

The file I'm trying to check is this:

```ruby
class Promotion < ActiveRecord::Base
  enum discount_type: { fixed: 0, percentage: 1 }

  # Direct relations
  has_many :promotion_regions
  has_many :regions, through: :promotion_regions
  has_many :transactions

  # Validations
  validates_presence_of :summary, :begins, :ends, :discount_type, :discount_value

  # Scopes
  scope :active, -> { now = Time.now; where('promotions.begins <= ?', now).where('promotions.ends >= ?', now) }

  def name
    "Promotion ID #{id}"
  end

  def active?
    now = Time.now
    begins <= now && now <= ends
  end

  def expired?
    !active?
  end
end
```

It works fine in MRI 2.6.5. The source code of rubocop is in https://github.com/rubocop-hq/rubocop

**Comment by bjfish** [comment]
Here is a minimal reproduction:
```
a = Object.new
def a.to_a
  [].freeze
end
b = *a
puts "b.frozen? #{b.frozen?}"
```
results in `true`, expected to be `false`.

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/3d7e9628e324f8991b6f1728fc268d5dc80bdc03.
