### ISSUE TITLE
actionpack: RuntimeError: Cannot convert a Ruby String with BINARY encoding containing non-US-ASCII character 229 to a Java String

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1907]
```
truffleruby 20.1.0-dev-c138bc04, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
git clone https://github.com/rails/rails.git
cd rails
bundle # there is a need to comment out some gems such as blade
cd actionpack
bundle exec ruby -Itest test/dispatch/static_test.rb
```

Error:

```
Error:
StaticEncodingTest#test_serves_static_index_file_in_directory:
RuntimeError: Cannot convert a Ruby String with BINARY encoding containing non-US-ASCII character 229 to a Java String (CannotConvertBinaryRubyStringToJavaString)
	from org.truffleruby.core.rope.RopeOperations.decodeNonAscii(RopeOperations.java:171)
	from org.truffleruby.core.rope.RopeOperations.decodeRopeSegment(RopeOperations.java:228)
	from org.truffleruby.core.rope.RopeOperations.decodeRopeSegment(RopeOperations.java:221)
	from org.truffleruby.core.rope.RopeOperations.decodeRope(RopeOperations.java:216)
	from org.truffleruby.core.string.StringOperations.getString(StringOperations.java:63)
	from org.truffleruby.core.exception.ExceptionNodes$ExceptionErrnoErrorPrimitiveNode.exceptionErrnoError(ExceptionNodes.java:328)
	from org.truffleruby.core.exception.ExceptionNodesFactory$ExceptionErrnoErrorPrimitiveNodeFactory$ExceptionErrnoErrorPrimitiveNodeGen.execute(ExceptionNodesFactory.java:1331)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:42)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:41)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
Translated to internal error
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `errno_error'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `new'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `handle'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `block in initialize'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `new'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `initialize'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `new'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `stat'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:95:in `file_readable?'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:35:in `match?'
    ~/dev/bugs/truffleruby/rails/actionpack/lib/action_dispatch/middleware/static.rb:123:in `call'
    ~/.gem/truffleruby/2.6.5/gems/rack-2.2.2/lib/rack/mock.rb:84:in `request'
    ~/dev/bugs/truffleruby/rails/actionpack/test/dispatch/static_test.rb:248:in `get'
    ~/dev/bugs/truffleruby/rails/actionpack/test/dispatch/static_test.rb:64:in `test_serves_static_index_file_in_directory'
```

**Comment by deepj** [comment]
Hm, isn't the error coming from rack in the end?

**Comment by bjfish** [comment]
I believe this error should now be resolved at https://github.com/oracle/truffleruby/commit/d48f341845fb68cbe616e42b9a82fb0cedaca507.
