### ISSUE TITLE
mini_racer is not working

### ISSUE THREAD

**Issue by SamSaffron** [oracle/truffleruby#1914]
```
irb(main):001:0> require 'mini_racer'
=> true
irb(main):002:0> MiniRacer::Context.new.eval("1+1")
Traceback (most recent call last):
        9: from /home/sam/.rubies/truffleruby-dev/bin/irb:37:in `<main>'
        8: from /home/sam/.rubies/truffleruby-dev/bin/irb:37:in `load'
        7: from /home/sam/.rubies/truffleruby-dev/bin/irb:37:in `load'
        6: from /home/sam/.rubies/truffleruby-dev/lib/gems/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        5: from (irb):2
        4: from (irb):2:in `new'
        3: from /home/sam/.gem/truffleruby/2.6.5/gems/mini_racer-0.2.9/lib/mini_racer.rb:156:in `initialize'
        2: from /home/sam/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `init_unsafe'
        1: from /home/sam/.gem/truffleruby/2.6.5/gems/mini_racer-0.2.9/ext/mini_racer_extension/mini_racer_extension.cc:771:in `rb_context_init_unsafe'
RuntimeError (External function _ZN2v82V813InitializeICUEPKc cannot be found. (LLVMLinkerException))
Translated to internal error
irb(main):003:0> 
```

I would say this is one of the most important gems for Discourse support, hopefully there is a simple fix here @eregon

**Comment by deepj** [comment]
@SamSaffron this is a duplicate of #1827

**Comment by SamSaffron** [comment]
thanks @deepj I should have searched, closing!
