### ISSUE TITLE
oga: multiple Oga::XML::PullParser specs fail

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1919]
```
truffleruby 20.1.0-dev-daa9b865, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce
```
git clone https://gitlab.com/yorickpeterse/oga.git
cd oga
bundle
rspec ./spec/oga/xml/pull_parser
```

**NOTE**: `ragel` needs to be installed on your OS

Error:

```
....FFFFFFFFF

Failures:

  1) Oga::XML::PullParser doctypes ignores doctypes
     Failure/Error: expect(amount).to eq(0)

       expected: 0
            got: 4

       (compared using ==)
     # ./spec/oga/xml/pull_parser/doctype_spec.rb:16:in `block (3 levels) in <top (required)>'

  2) Oga::XML::PullParser tracking element nesting sets the nesting for the outer element
     Failure/Error: expect(@parser.nesting).to eq(%w{a}) if node.name == 'a'

     NoMethodError:
       undefined method `name' for [:T_ELEM_NAME, "a"]:Array
     # ./spec/oga/xml/pull_parser/element_nesting_spec.rb:11:in `block (4 levels) in <top (required)>'
     # ./lib/oga/xml/parser.rb:226:in `block in each_token'
     # ./lib/oga/xml/lexer.rb:223:in `call'
     # ./lib/oga/xml/lexer.rb:223:in `add_token'
     # ./lib/oga/xml/lexer.rb:384:in `add_element'
     # ./lib/oga/xml/lexer.rb:355:in `on_element_name'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1015:in `rb_funcall'
     # ./ext/c/lexer.rl:54:in `liboga_xml_lexer_callback'
     # ./ext/ragel/base_lexer.rl:404:in `oga_xml_lexer_advance'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `advance_native'
     # ./lib/oga/xml/lexer.rb:176:in `block in advance'
     # ./lib/oga/xml/lexer.rb:130:in `read_data'
     # ./lib/oga/xml/lexer.rb:175:in `advance'
     # ./lib/oga/xml/parser.rb:223:in `each_token'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:996:in `rb_funcall_with_block'
     # ruby.c:1961:in `rb_funcall_with_block'
     # ruby.c:1928:in `rb_block_call'
     # ~/.gem/truffleruby/2.6.5/gems/ruby-ll-2.1.2/ext/c/driver.c:324:in `ll_driver_parse'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `parse'
     # ./lib/oga/xml/pull_parser.rb:68:in `parse'
     # ./spec/oga/xml/pull_parser/element_nesting_spec.rb:10:in `block (3 levels) in <top (required)>'

  3) Oga::XML::PullParser tracking element nesting pops element names after leaving an element
     Failure/Error: expect(@parser.nesting).to receive(:pop).twice

       ([]).pop(*(any args))
           expected: 2 times with any arguments
           received: 0 times with any arguments
     # ./spec/oga/xml/pull_parser/element_nesting_spec.rb:18:in `block (3 levels) in <top (required)>'

  4) Oga::XML::PullParser elements parses an element
     Failure/Error: expect(name).to eq('person')

       expected: "person"
            got: nil

       (compared using ==)
     # ./spec/oga/xml/pull_parser/element_spec.rb:16:in `block (3 levels) in <top (required)>'

  5) Oga::XML::PullParser elements parses the text of an element
     Failure/Error: expect(text).to eq('Alice')

       expected: "Alice"
            got: nil

       (compared using ==)
     # ./spec/oga/xml/pull_parser/element_spec.rb:26:in `block (3 levels) in <top (required)>'

  6) Oga::XML::PullParser tracking nodes tracks the current node
     Failure/Error: expect(@parser.node.is_a?(Oga::XML::Element)).to eq(true)

       expected: true
            got: false

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -true
       +false

     # ./spec/oga/xml/pull_parser/general_spec.rb:11:in `block (4 levels) in <top (required)>'
     # ./lib/oga/xml/parser.rb:226:in `block in each_token'
     # ./lib/oga/xml/lexer.rb:223:in `call'
     # ./lib/oga/xml/lexer.rb:223:in `add_token'
     # ./lib/oga/xml/lexer.rb:384:in `add_element'
     # ./lib/oga/xml/lexer.rb:355:in `on_element_name'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1015:in `rb_funcall'
     # ./ext/c/lexer.rl:54:in `liboga_xml_lexer_callback'
     # ./ext/ragel/base_lexer.rl:404:in `oga_xml_lexer_advance'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `advance_native'
     # ./lib/oga/xml/lexer.rb:176:in `block in advance'
     # ./lib/oga/xml/lexer.rb:130:in `read_data'
     # ./lib/oga/xml/lexer.rb:175:in `advance'
     # ./lib/oga/xml/parser.rb:223:in `each_token'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:996:in `rb_funcall_with_block'
     # ruby.c:1961:in `rb_funcall_with_block'
     # ruby.c:1928:in `rb_block_call'
     # ~/.gem/truffleruby/2.6.5/gems/ruby-ll-2.1.2/ext/c/driver.c:324:in `ll_driver_parse'
     # ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `parse'
     # ./lib/oga/xml/pull_parser.rb:68:in `parse'
     # ./spec/oga/xml/pull_parser/general_spec.rb:10:in `block (3 levels) in <top (required)>'

  7) Oga::XML::PullParser processing instructions returns a ProcessingInstruction node
     Failure/Error: expect(@node.is_a?(Oga::XML::ProcessingInstruction)).to eq(true)

       expected: true
            got: false

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -true
       +false

     # ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:14:in `block (3 levels) in <top (required)>'

  8) Oga::XML::PullParser processing instructions sets the name of the node
     Failure/Error: expect(@node.name).to eq('foo')

     NoMethodError:
       undefined method `name' for [-1, -1]:Array
     # ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:18:in `block (3 levels) in <top (required)>'

  9) Oga::XML::PullParser processing instructions sets the text of the node
     Failure/Error: expect(@node.text).to eq(' bar ')

     NoMethodError:
       undefined method `text' for [-1, -1]:Array
     # ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 1.55 seconds (files took 5.26 seconds to load)
13 examples, 9 failures

Failed examples:

rspec ./spec/oga/xml/pull_parser/doctype_spec.rb:9 # Oga::XML::PullParser doctypes ignores doctypes
rspec ./spec/oga/xml/pull_parser/element_nesting_spec.rb:9 # Oga::XML::PullParser tracking element nesting sets the nesting for the outer element
rspec ./spec/oga/xml/pull_parser/element_nesting_spec.rb:17 # Oga::XML::PullParser tracking element nesting pops element names after leaving an element
rspec ./spec/oga/xml/pull_parser/element_spec.rb:9 # Oga::XML::PullParser elements parses an element
rspec ./spec/oga/xml/pull_parser/element_spec.rb:19 # Oga::XML::PullParser elements parses the text of an element
rspec ./spec/oga/xml/pull_parser/general_spec.rb:9 # Oga::XML::PullParser tracking nodes tracks the current node
rspec ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:13 # Oga::XML::PullParser processing instructions returns a ProcessingInstruction node
rspec ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:17 # Oga::XML::PullParser processing instructions sets the name of the node
rspec ./spec/oga/xml/pull_parser/processing_instruction_spec.rb:21 # Oga::XML::PullParser processing instructions sets the text of the node
```

**Comment by deepj** [comment]
One thing. On my machine, specs run 2.21 secs in MRI, but TruffleRuby it's over 1m 33 secs...

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community
