### ISSUE TITLE
wrong number of arguments ( lib/truffle/digest/sha2.rb )

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1922]
I am running some rspecs for an existing project (all specs pass in MRI)

https://github.com/petenorth/schools-experience

and am seeing this stacktrace a number of times 

VERSION: truffleruby 20.1.0-dev-08311e22, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]

```2020-02-23T14:09:07.6307571Z   10) Concerns FullTextSearch .search_by_name should match on whole words at any position
2020-02-23T14:09:07.6310264Z       Failure/Error: expect(subject.search_by_name("School")).to include(primary, secondary, grammar)
2020-02-23T14:09:07.6310347Z 
2020-02-23T14:09:07.6310508Z       ArgumentError:
2020-02-23T14:09:07.6310671Z         wrong number of arguments (given 0, expected 1)
2020-02-23T14:09:07.6311340Z       # /truffleruby-head/lib/truffle/digest/sha2.rb:109:in `digest'
2020-02-23T14:09:07.6311677Z       # /truffleruby-head/lib/truffle/digest.rb:142:in `digest'
2020-02-23T14:09:07.6316080Z       # /truffleruby-head/lib/truffle/digest.rb:146:in `hexdigest'
2020-02-23T14:09:07.6316504Z       # /truffleruby-head/lib/gems/gems/pg_search-2.3.2/lib/pg_search/configuration.rb:22:in `alias'
2020-02-23T14:09:07.6316954Z       # /truffleruby-head/lib/gems/gems/pg_search-2.3.2/lib/pg_search/scope_options.rb:68:in `pg_search_rank_table_alias'
2020-02-23T14:09:07.6317345Z       # /truffleruby-head/lib/gems/gems/pg_search-2.3.2/lib/pg_search/scope_options.rb:17:in `apply'
2020-02-23T14:09:07.6317769Z       # /truffleruby-head/lib/gems/gems/pg_search-2.3.2/lib/pg_search/model.rb:20:in `search_by_name'
2020-02-23T14:09:07.6320972Z       # ./spec/models/concerns/full_text_search_spec.rb:17:in `block (4 levels) in <top (required)>'
2020-02-23T14:09:07.6321358Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `load'
2020-02-23T14:09:07.6321730Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `load'
2020-02-23T14:09:07.6322064Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `kernel_load'
2020-02-23T14:09:07.6322440Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:28:in `run'
2020-02-23T14:09:07.6325159Z       # /truffleruby-head/lib/mri/bundler/cli.rb:463:in `exec'
2020-02-23T14:09:07.6325560Z       # /truffleruby-head/lib/mri/bundler/cli.rb:27:in `dispatch'
2020-02-23T14:09:07.6325876Z       # /truffleruby-head/lib/mri/bundler/cli.rb:18:in `start'
2020-02-23T14:09:07.6326421Z       # /truffleruby-head/lib/mri/bundler/friendly_errors.rb:124:in `with_friendly_errors'```

**Comment by eregon** [comment]
Thanks for the report, we noticed this failure as well in Rails tests.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/ffc8f62e4342d0e14a61b3038b8e4f4bbfd28098.
