### ISSUE TITLE
wrong number of arguments on simple (?) spec

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1923]
I am running some rspecs for an existing project

https://github.com/petenorth/schools-experience

and am seeing this stacktrace a number of times (all specs pass in MRI)

VERSION: truffleruby 20.1.0-dev-08311e22, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]

```2020-02-23T14:09:07.9511991Z       ArgumentError:
2020-02-23T14:09:07.9512117Z         Wrong number of arguments. Expected 1 or more, got 0.
2020-02-23T14:09:07.9512436Z       # ./app/services/bookings/gitis/factory.rb:14:in `crm'
2020-02-23T14:09:07.9512857Z       # ./spec/services/bookings/gitis/factory_spec.rb:49:in `subject'
2020-02-23T14:09:07.9513257Z       # ./spec/services/bookings/gitis/factory_spec.rb:58:in `block (4 levels) in <top (required)>'
2020-02-23T14:09:07.9513600Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `load'
2020-02-23T14:09:07.9513914Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `load'
2020-02-23T14:09:07.9514261Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:74:in `kernel_load'
2020-02-23T14:09:07.9514600Z       # /truffleruby-head/lib/mri/bundler/cli/exec.rb:28:in `run'
2020-02-23T14:09:07.9514930Z       # /truffleruby-head/lib/mri/bundler/cli.rb:463:in `exec'
2020-02-23T14:09:07.9515259Z       # /truffleruby-head/lib/mri/bundler/cli.rb:27:in `dispatch'
2020-02-23T14:09:07.9515569Z       # /truffleruby-head/lib/mri/bundler/cli.rb:18:in `start'
2020-02-23T14:09:07.9515929Z       # /truffleruby-head/lib/mri/bundler/friendly_errors.rb:124:in `with_friendly_errors'```

**Comment by petenorth** [comment]
Seems to be fixed in 

`truffleruby 20.1.0-dev-cdced895, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]`
