### ISSUE TITLE
yajl-ffi: dlopen(yajl, 2): image not found (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1926]
```
truffleruby 20.1.0-dev-08311e22, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install yajl-ffi
ruby -r"yajl/ffi"
```

Error:

```
[ruby] WARNING: truffleruby starts IRB when stdin is a TTY instead of reading from stdin, use '-' to read from stdin
~/.rubies/truffleruby-dev/lib/truffle/ffi/library.rb:145:in `block in ffi_lib': dlopen(yajl, 2): image not found (UnsatisfiedLinkError) (LoadError)
	from com.oracle.svm.truffle.nfi.posix.PosixTruffleNFISupport.loadLibraryImpl(PosixTruffleNFIFeature.java:147)
	from com.oracle.svm.truffle.nfi.TruffleNFISupport.loadLibrary(TruffleNFISupport.java:197)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:201)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:174)
	from com.oracle.truffle.nfi.impl.NFILanguageImpl$LoadLibraryNode.execute(NFILanguageImpl.java:147)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
Translated to internal error.
dlopen(libyajl.dylib, 2): image not found (UnsatisfiedLinkError)
	from com.oracle.svm.truffle.nfi.posix.PosixTruffleNFISupport.loadLibraryImpl(PosixTruffleNFIFeature.java:147)
	from com.oracle.svm.truffle.nfi.TruffleNFISupport.loadLibrary(TruffleNFISupport.java:197)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:201)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:174)
	from com.oracle.truffle.nfi.impl.NFILanguageImpl$LoadLibraryNode.execute(NFILanguageImpl.java:147)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
Translated to internal error.
dlopen(libyajl.so.2, 2): image not found (UnsatisfiedLinkError)
	from com.oracle.svm.truffle.nfi.posix.PosixTruffleNFISupport.loadLibraryImpl(PosixTruffleNFIFeature.java:147)
	from com.oracle.svm.truffle.nfi.TruffleNFISupport.loadLibrary(TruffleNFISupport.java:197)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:201)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:174)
	from com.oracle.truffle.nfi.impl.NFILanguageImpl$LoadLibraryNode.execute(NFILanguageImpl.java:147)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
Translated to internal error.
dlopen(libyajl.so.2.dylib, 2): image not found (UnsatisfiedLinkError)
	from com.oracle.svm.truffle.nfi.posix.PosixTruffleNFISupport.loadLibraryImpl(PosixTruffleNFIFeature.java:147)
	from com.oracle.svm.truffle.nfi.TruffleNFISupport.loadLibrary(TruffleNFISupport.java:197)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:201)
	from com.oracle.truffle.nfi.impl.NFIContext.loadLibrary(NFIContext.java:174)
	from com.oracle.truffle.nfi.impl.NFILanguageImpl$LoadLibraryNode.execute(NFILanguageImpl.java:147)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
Translated to internal error
	from ~/.rubies/truffleruby-dev/lib/truffle/ffi/library.rb:99:in `map'
	from ~/.rubies/truffleruby-dev/lib/truffle/ffi/library.rb:99:in `ffi_lib'
	from ~/.gem/truffleruby/2.6.5/gems/yajl-ffi-0.1.2/lib/yajl/ffi.rb:11:in `FFI'
	from ~/.gem/truffleruby/2.6.5/gems/yajl-ffi-0.1.2/lib/yajl/ffi.rb:8:in `Yajl'
	from ~/.gem/truffleruby/2.6.5/gems/yajl-ffi-0.1.2/lib/yajl/ffi.rb:7:in `<top (required)>'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `call'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `<main>'
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community
