### ISSUE TITLE
minitest + simplecov integration causes uninitialized constant Minitest::SimpleCov (NameError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1929]
```
truffleruby 20.1.0-dev-b7e8555f, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

The problematic code:

```ruby
# frozen_string_literal: true

# How minitest plugins. See https://github.com/colszowka/simplecov/pull/756 for why we need this.
# https://github.com/seattlerb/minitest#writing-extensions
module Minitest
  def self.plugin_simplecov_init(_options)
    SimpleCov.external_at_exit = true

    Minitest.after_run do
      SimpleCov.at_exit_behavior if SimpleCov.respond_to?(:at_exit_behavior)
    end
  end
end
```
https://github.com/colszowka/simplecov/blob/v0.18.4/lib/minitest/simplecov_plugin.rb

To reproduce:

```
git clone https://github.com/rails/web-console.git
cd web-console
bundle
bundle exec rake
```

Error:

```
~/.gem/truffleruby/2.6.5/gems/simplecov-0.18.4/lib/minitest/simplecov_plugin.rb:7:in `const_missing': uninitialized constant Minitest::SimpleCov (NameError)
Did you mean?  SimpleDelegator
	from ~/.gem/truffleruby/2.6.5/gems/simplecov-0.18.4/lib/minitest/simplecov_plugin.rb:7:in `plugin_simplecov_init'
	from ~/.gem/truffleruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:86:in `block in init_plugins'
	from ~/.gem/truffleruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:84:in `each'
	from ~/.gem/truffleruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:84:in `init_plugins'
	from ~/.gem/truffleruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:135:in `run'
	from ~/.gem/truffleruby/2.6.5/gems/minitest-5.14.0/lib/minitest.rb:68:in `block in autorun'
rake aborted!
Command failed with status (1)
~/.gem/truffleruby/2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
~/.gem/truffleruby/2.6.5/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
~/.gem/truffleruby/2.6.5/bin/bundle:23:in `load'
~/.gem/truffleruby/2.6.5/bin/bundle:23:in `load'
~/.gem/truffleruby/2.6.5/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community
