### ISSUE TITLE
simdjson: `padded_string': External LLVMFunction _ZN8simdjson22allocate_padded_bufferEm cannot be found

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1931]
```
truffleruby 20.1.0-dev-d6e1b291, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install simdjson
ruby -rsimdjson -e 'p Simdjson.parse %|{"a": 12345}| # => {"a"=>12345}'
```

Error:

```
~/.gem/truffleruby/2.6.5/gems/simdjson-0.2.0/vendor/simdjson/singleheader/simdjson.h:527:in `padded_string': External LLVMFunction _ZN8simdjson22allocate_padded_bufferEm cannot be found. (LLVMLinkerException) (RuntimeError)
Translated to internal error
	from ~/.gem/truffleruby/2.6.5/gems/simdjson-0.2.0/vendor/simdjson/singleheader/simdjson.h:527:in `padded_string'
	from ~/.gem/truffleruby/2.6.5/gems/simdjson-0.2.0/ext/simdjson/simdjson.cpp:60:in `rb_simdjson_parse'
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `parse'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment]
That seems to happen because libsimdjson is compiled as native without bitcode:
https://github.com/saka1/simdjson_ruby/blob/93189b84d744c46d7f7cef381f497669e04f05bc/ext/simdjson/extconf.rb#L13-L18

**Comment by eregon** [comment]
One idea here is to compile libsimdjson with the toolchain as well, which seems to work by adding it to the PATH. That leads to some parse error though at runtime:
```
The processor is not supported by simdjson.
lib/truffle/truffle/cext.rb:1268:in `rb_exc_raise': parse error (Simdjson::ParseError)
	from src/main/c/cext/ruby.c:2114:in `rb_exc_raise'
	from lib/gems/gems/simdjson-0.2.0/ext/simdjson/simdjson.cpp:63:in `rb_simdjson_parse'
	from lib/truffle/truffle/cext_ruby.rb:39:in `parse'
	from -e:1:in `<main>'
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by eregon** [comment]
It works now, with 5f3339321c6bf3f30e7993101b2f2abce7f1b0f4:
```
$ ruby -v -rsimdjson -e 'p Simdjson.parse %|{"a": 12345}| # => {"a"=>12345}'
truffleruby 21.1.0-dev-c03738b2, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]
{"a"=>12345}
```
