### ISSUE TITLE
blingfire: `malloc': NotImplementedError in Fiddle

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1932]
```
truffleruby 20.1.0-dev-d6e1b291, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install blingfire
ruby -rblingfire -e "p BlingFire.text_to_words('Hello World!')"
```

Error:

```
~/.rubies/truffleruby-dev/lib/truffle/truffle/fiddle_backend.rb:295:in `malloc': NotImplementedError (NotImplementedError)
	from ~/.gem/truffleruby/2.6.5/gems/blingfire-0.1.0/lib/blingfire.rb:39:in `text_to_words'
	from -e:1:in `<main>'
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by eregon** [comment]
This is implemented now.
