### ISSUE TITLE
Hanami::Utils::String - value "diseappers" after calling Time.parse

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1946]
To reproduce:

```
gem install hanami-utils
ruby -rhanami/utils/string -e 'input = Hanami::Utils::String.new(Time.now); p Time.parse(input); p Time.parse(input)'
```

Error:

```
~/.rubies/truffleruby-dev/lib/mri/time.rb:194:in `make_time': no time information in #<Hanami::Utils::String:0x1ae0 @string=" "> (ArgumentError)
	from ~/.rubies/truffleruby-dev/lib/mri/time.rb:375:in `parse'
	from -e:1:in `<main>'
```

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/182c1cf85dd63aa1649e3adbb06da53afbb18e8f
