### ISSUE TITLE
Integer ** BigDecimal does not work but BigDecimal ** Integer does work

### ISSUE THREAD

**Issue by alecgorge** [oracle/truffleruby#1948]
### Truffleruby Version

`truffleruby 20.0.0, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]`

### Code to reproduce
```
require 'bigdecimal'
require 'bigdecimal/util'

# works
puts (2.to_d) ** 3
puts (2.to_d ** 3) == 8

# doesn't work
puts (2.to_d) ** 3.to_d
puts (2.to_d ** 3.to_d) == 8

# doesn't work
puts 2 ** (3.to_d)
puts (2 ** (3.to_d)) == 8
```

### Expected output (MRI)

```
0.8e1
true
0.8e1
true
0.8e1
true
```

### Actual output

**Error**

`scratch_4.rb:7:in ``**': TruffleRuby doesn't have a case for the org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen node with values of type  BigDecimal(com.oracle.truffle.object.DynamicObjectBasic) BigDecimal(com.oracle.truffle.object.DynamicObjectBasic) org.truffleruby.language.NotProvided (TypeError)`

<details><summary>Full Output</summary>

```
0.8e1
true
/Users/alecgorge/Library/Preferences/RubyMine2019.3/scratches/scratch_4.rb:9:in `**': TruffleRuby doesn't have a case for the org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen node with values of type  BigDecimal(com.oracle.truffle.object.DynamicObjectBasic) BigDecimal(com.oracle.truffle.object.DynamicObjectBasic) org.truffleruby.language.NotProvided (TypeError)
	from org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen.executeAndSpecialize(BigDecimalNodesFactory.java:2422)
	from org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen.execute(BigDecimalNodesFactory.java:2364)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
	from org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:130)
	from org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:96)
	from org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:136)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:115)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:103)
	from org.truffleruby.language.dispatch.RubyCallNode.executeArguments(RubyCallNode.java:136)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:91)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:52)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:32)
	from org.truffleruby.language.methods.CatchNextNode.execute(CatchNextNode.java:31)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:41)
	from org.truffleruby.language.methods.CatchRetryAsErrorNode.execute(CatchRetryAsErrorNode.java:32)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.exceptions.TopLevelRaiseHandler.execute(TopLevelRaiseHandler.java:41)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:330)
	from org.graalvm.compiler.truffle.runtime.OptimizedIndirectCallNode.call(OptimizedIndirectCallNode.java:54)
	from org.truffleruby.language.loader.CodeLoader$DeferredCall.call(CodeLoader.java:107)
	from org.truffleruby.language.TruffleBootNodes$MainNode.main(TruffleBootNodes.java:155)
	from org.truffleruby.language.TruffleBootNodesFactory$MainNodeFactory$MainNodeGen.executeAndSpecialize(TruffleBootNodesFactory.java:384)
	from org.truffleruby.language.TruffleBootNodesFactory$MainNodeFactory$MainNodeGen.execute(TruffleBootNodesFactory.java:363)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
	from org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:130)
	from org.truffleruby.language.dispatch.CachedSingletonDispatchNode.executeDispatch(CachedSingletonDispatchNode.java:95)
	from org.truffleruby.language.dispatch.UnresolvedDispatchNode.executeDispatch(UnresolvedDispatchNode.java:136)
	from org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	from org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:115)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:103)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:32)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:35)
	from org.truffleruby.language.methods.CatchForLambdaNode.execute(CatchForLambdaNode.java:51)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:349)
	from org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:67)
	from org.truffleruby.language.yield.CallBlockNode.callBlockCached(CallBlockNode.java:53)
	from org.truffleruby.language.yield.CallBlockNodeGen.executeAndSpecialize(CallBlockNodeGen.java:99)
	from org.truffleruby.language.yield.CallBlockNodeGen.executeCallBlock(CallBlockNodeGen.java:55)
	from org.truffleruby.language.yield.YieldNode.dispatch(YieldNode.java:37)
	from org.truffleruby.language.yield.YieldNodeGen.executeAndSpecialize(YieldNodeGen.java:46)
	from org.truffleruby.language.yield.YieldNodeGen.executeDispatchWithArrayArguments(YieldNodeGen.java:33)
	from org.truffleruby.language.yield.YieldNode.executeDispatch(YieldNode.java:29)
	from org.truffleruby.interop.ForeignExecuteHelperNode.callProc(ForeignExecuteHelperNode.java:32)
	from org.truffleruby.interop.ForeignExecuteHelperNodeGen.executeAndSpecialize(ForeignExecuteHelperNodeGen.java:69)
	from org.truffleruby.interop.ForeignExecuteHelperNodeGen.executeCall(ForeignExecuteHelperNodeGen.java:53)
	from org.truffleruby.interop.messages.RubyObjectMessages.execute(RubyObjectMessages.java:450)
	from org.truffleruby.interop.messages.RubyObjectMessagesGen$InteropLibraryExports$Cached.executeNode_AndSpecialize(RubyObjectMessagesGen.java:1038)
	from org.truffleruby.interop.messages.RubyObjectMessagesGen$InteropLibraryExports$Cached.execute(RubyObjectMessagesGen.java:1024)
	from com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:3778)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1699)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:1780)
	from com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:98)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
	from com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:1292)
	from com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2459)
	from org.graalvm.polyglot.Value.execute(Value.java:369)
	from org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:233)
	from org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:121)
	from org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	from org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	from org.truffleruby.launcher.RubyLauncher.main(RubyLauncher.java:38)
	from /Users/alecgorge/Library/Preferences/RubyMine2019.3/scratches/scratch_4.rb:9:in `<main>'
```
</details>

**Comment by bjfish** [comment]
`BigDecimal` is now implemented using the C extension and the examples above now work at https://github.com/oracle/truffleruby/commit/aa11d31adb031302a3b9e04d95c0376858c86b72
