### ISSUE TITLE
truffleruby: an exception escaped out of the interpreter - this is an implementation bug

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1952]
To reproduce:

```
git clone https://github.com/hopsoft/stimulus_reflex.git
cd stimulus_reflex
bundle
bundle exec rake test
```

Error:

```
yarn run v1.22.0
$ yarn run mocha --require @babel/register
error Command "mocha" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: org.truffleruby.language.control.DynamicReturnException
Original Internal Error:
org.truffleruby.language.control.DynamicReturnException
```

**Comment by eregon** [comment]
This is with the nightly builds right?
Probably caused by a `return` at the top-level of a file.

**Comment by deepj** [comment]
@eregon In my case

```
truffleruby 20.1.0-dev-1ff2bd4a, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

**Comment by deepj** [comment]
Closed due to I'm not welcome anymore in Ruby community

**Comment by andrykonchin** [comment]
I've tried to reproduce on the current TruffleRuby master and received the following error:

```
symbol not found in flat namespace '_rb_cObject'
```

`stimulus_reflex` 3.5.0.pre9, MacOS Monterey

<details>
<summary>Full output</summary>

```
bundler exec rake test_ruby
Using Interpreted TruffleRuby: mxbuild/truffleruby-jvm
$ /Users/andrykonchin/projects/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=/Users/andrykonchin/projects/truffleruby-ws/truffleruby/src/main/ruby/truffleruby \
  /Users/andrykonchin/projects/truffleruby-ws/truffleruby/exe/bundler \
  exec \
  rake \
  test_ruby
rake aborted!
dlopen(/Users/andrykonchin/projects/truffleruby-ws/graal/sdk/mxbuild/darwin-amd64/GRAALVM_D83C12B6D6_JAVA11/graalvm-d83c12b6d6-java11-22.3.0-dev/Contents/Home/languages/ruby/lib/gems/gems/nokogiri-1.13.6-x86_64-darwin/lib/nokogiri/3.0/nokogiri.bundle, 0x0002): symbol not found in flat namespace '_rb_cObject'
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:293:in `require_relative'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/andrykonchin/projects/truffleruby-gems-to-test/stimulus_reflex/lib/stimulus_reflex.rb:10:in `<top (required)>'
<internal:core> core/kernel.rb:293:in `require_relative'
/Users/andrykonchin/projects/truffleruby-gems-to-test/stimulus_reflex/test/test_helper.rb:13:in `<top (required)>'
<internal:core> core/kernel.rb:293:in `require_relative'
/Users/andrykonchin/projects/truffleruby-gems-to-test/stimulus_reflex/test/broadcasters/broadcaster_test_case.rb:3:in `<top (required)>'
<internal:core> core/kernel.rb:293:in `require_relative'
/Users/andrykonchin/projects/truffleruby-gems-to-test/stimulus_reflex/test/broadcasters/broadcaster_test.rb:3:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/andrykonchin/projects/truffleruby-gems-to-test/stimulus_reflex/rakefile:11:in `block in <top (required)>'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
<internal:core> core/kernel.rb:376:in `load'
/Users/andrykonchin/projects/truffleruby-ws/truffleruby/exe/bundler:42:in `<main>'
Tasks: TOP => test_ruby
(See full trace by running task with --trace)
```

</details>

**Comment by eregon** [comment]
@andrykonchin That sounds like somehow the precompiled-for-CRuby nokogiri was used, which is probably a Bundler bug, or maybe some local setup issue, I'll check with you directly.

**Comment by andrykonchin** [comment]
The specs have passed on the current TruffleRuby master:

```
bundle exec rake test_ruby
Run options: --seed 21890

# Running:

.........................................................

Finished in 2.515381s, 22.6606 runs/s, 71.9573 assertions/s.
57 runs, 181 assertions, 0 failures, 0 errors, 0 skips
➜  stimulus_reflex git:(master) ✗ bundler -v
Bundler version 2.2.32
➜  stimulus_reflex git:(master) ✗ ruby -v
truffleruby 22.3.0-dev-ff7a0b45, like ruby 3.0.3, Interpreted JVM [x86_64-darwin]
```

[stimulus_reflex](https://github.com/stimulusreflex/stimulus_reflex): [9ea8560829c2b587c23d9ce3f6059e1e896c3aa1](https://github.com/stimulusreflex/stimulus_reflex/commit/9ea8560829c2b587c23d9ce3f6059e1e896c3aa1)

Thank you for reporting the issue.
