### ISSUE TITLE
rbtrace:  rb_set_end_proc not implemented (RuntimeError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1959]
```
truffleruby 20.1.0-dev-3de4af67, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install rbtrace
ruby -rrbtrace
```

Error:

```
ruby.c:2974:in `rb_tr_error': rb_set_end_proc not implemented (RuntimeError)
	from ruby.c:477:in `rb_set_end_proc'
	from ~/.gem/truffleruby/2.6.5/gems/rbtrace-0.4.11/ext/rbtrace.c:1132:in `Init_rbtrace'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `call'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `<main>'
```

**Comment by bjfish** [comment]
This is now implemented at https://github.com/oracle/truffleruby/commit/b8e7164c6aa9f12d126a19a6c48c66b55abc2430.
