### ISSUE TITLE
fork is not available (NotImplementedError) when running rails server as a daemon

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1962]
VERSION: `truffleruby 20.1.0-dev-c7c38a12, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]`

To reproduce

```
gem install rails
rails new blog
cd blog
rails server
```
the server successfully starts with output
```
RubyDep: WARNING: Your Ruby may not be supported.
RubyDep: WARNING: Your Ruby is: 2.6.5 'truffleruby' (unrecognized). If you need this version supported, please open an issue at http://github.com/e2/ruby_dep
RubyDep: WARNING: (To disable warnings, see:http://github.com/e2/ruby_dep/wiki/Disabling-warnings )
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 4.3.3 (truffleruby 20.1.0-dev-c7c38a12 - ruby 2.6.5), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Use Ctrl-C to stop
```

If I then try to start the rails server as a daemon 

`rails server -d`

then the output is
```
RubyDep: WARNING: Your Ruby may not be supported.
RubyDep: WARNING: Your Ruby is: 2.6.5 'truffleruby' (unrecognized). If you need this version supported, please open an issue at http://github.com/e2/ruby_dep
RubyDep: WARNING: (To disable warnings, see:http://github.com/e2/ruby_dep/wiki/Disabling-warnings )
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
/home/runner/.rubies/truffleruby-head/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:428:in `fork': fork is not available (NotImplementedError)
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:428:in `daemon'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:428:in `daemonize_app'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:315:in `start'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:39:in `start'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by deepj** [comment]
@petenorth This is not TruffleRuby issue since JRuby or TruffleRuby can't support fork either. This is a problem of Rails and its detection of fork + Rails app cannot be run as a deamon by this way

**Comment by eregon** [comment]
Indeed, Process.daemon cannot be supported without `fork`.
On JRuby:
```
$ jruby -ve 'Process.daemon'
jruby 9.2.11.0 (2.5.7) 2020-03-02 612d7a05a6 OpenJDK 64-Bit Server VM 25.232-b07-jvmci-19.3-b04 on 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07 +jit [linux-x86_64]
NoMethodError: undefined method `daemon' for Process:Module
```
On TruffleRuby:
```
ruby -ve 'Process.daemon'
truffleruby 20.1.0-dev-c7c38a12, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]
-e:1:in `fork': fork is not available (NotImplementedError)
	from -e:1:in `daemon'
	from -e:1:in `<main>'
```

So maybe we should simply not define the method since fork is not supported currently.

**Comment by eregon** [comment]
Just removing the method (in `bin/rails`) doesn't result in a better error though:
```
$ rails server -d         
RubyDep: WARNING: Your Ruby may not be supported.
RubyDep: WARNING: Your Ruby is: 2.6.5 'truffleruby' (unrecognized). If you need this version supported, please open an issue at http://github.com/e2/ruby_dep
RubyDep: WARNING: (To disable warnings, see:http://github.com/e2/ruby_dep/wiki/Disabling-warnings )
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:428:in `daemonize_app': undefined method `daemon' for Process:Module (NoMethodError)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rack-2.2.2/lib/rack/server.rb:315:in `start'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:39:in `start'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

**Comment by eregon** [comment]
Here is what happens on JRuby 9.2.11.0:
```
$ rails server -d
=> Booting Puma
=> Rails 6.0.2.1 application starting in development 
=> Run `rails server --help` for more startup options
NoMethodError: undefined method `daemon' for Process:Module
   daemonize_app at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/rack-2.2.2/lib/rack/server.rb:428
           start at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/rack-2.2.2/lib/rack/server.rb:315
           start at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:39
         perform at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:147
             tap at org/jruby/RubyKernel.java:1897
         perform at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/commands/server/server_command.rb:138
             run at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor/command.rb:27
  invoke_command at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor/invocation.rb:127
        dispatch at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/thor-1.0.1/lib/thor.rb:392
         perform at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/command/base.rb:69
          invoke at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/command.rb:46
          <main> at /home/eregon/.rubies/jruby-9.2.11.0/lib/ruby/gems/shared/gems/railties-6.0.2.1/lib/rails/commands.rb:18
         require at org/jruby/RubyKernel.java:974
          <main> at bin/rails:4
```

So except removing the method, or raising a Process.daemon-specific error I don't think we can do much here.

**Comment by petenorth** [comment]
I think for CI purposes `rails server &` is sufficient. I normally deploy a containerized app and so would not require the daemon functionality.

**Comment by eregon** [comment]
Let's keep it open for tracking improving the error message, and removing the non-working implementation.
