### ISSUE TITLE
rails: routes with with_options cause TypeError (no implicit conversion of Symbol into String)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1963]
```
truffleruby 20.1.0-dev-c7c38a12, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
rails new journey
cd journey
```
Edit `config/routes.rb`

```ruby
Rails.application.routes.draw do
  with_options only: :index, constraints: { format: :json } do
    resources :users
  end
end
```

```
bundle exec rails s
open http://localhost:3000
```

Error:

```
TypeError (no implicit conversion of Symbol into String):

actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:93:in `convert_type'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:93:in `rb_convert_type'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:93:in `StringValue'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:93:in `union'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:93:in `visit_SYMBOL'
actionpack (6.0.2.1) lib/action_dispatch/journey/visitors.rb:64:in `visit'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:84:in `visit_CAT'
actionpack (6.0.2.1) lib/action_dispatch/journey/visitors.rb:64:in `visit'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:97:in `visit_GROUP'
actionpack (6.0.2.1) lib/action_dispatch/journey/visitors.rb:64:in `visit'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:84:in `visit_CAT'
actionpack (6.0.2.1) lib/action_dispatch/journey/visitors.rb:64:in `visit'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:84:in `visit_CAT'
actionpack (6.0.2.1) lib/action_dispatch/journey/visitors.rb:64:in `visit'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:80:in `accept'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:173:in `to_regexp'
actionpack (6.0.2.1) lib/action_dispatch/journey/path/pattern.rb:163:in `match'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:110:in `block in find_routes'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:109:in `block in find_all'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:109:in `each'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:109:in `find_all'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:109:in `find_routes'
actionpack (6.0.2.1) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.1) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.2.1) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.1) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.1) lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.2.1) lib/rails/engine.rb:526:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `call'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by eregon** [comment]
Looks like `Regexp.union` needs to accept Symbols:
https://github.com/rails/rails/blob/ec69083cf3352c78f840de50fdf20ef30334e0b1/actionpack/lib/action_dispatch/journey/path/pattern.rb#L93

**Comment by deepj** [comment]
@eregon thanks. If you or someone else will take a look at this, please at the same time take a look at it with https://github.com/oracle/truffleruby/issues/1938

It took me many hours to locate the issue above because loading and solving paths was extremely slow

**Comment by bjfish** [comment]
Here's a minimal case:
```
ruby -e 'p Regexp.union(:json)'
/json/
jt ruby -e 'p Regexp.union(:json)'
/Users/bfish/Documents/truffleruby-ws/truffleruby/src/main/ruby/truffleruby/core/type.rb:310:in `convert_type': no implicit conversion of Symbol into String (TypeError)
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/src/main/ruby/truffleruby/core/type.rb:291:in `rb_convert_type'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/src/main/ruby/truffleruby/core/kernel.rb:171:in `StringValue'
	from /Users/bfish/Documents/truffleruby-ws/truffleruby/src/main/ruby/truffleruby/core/regexp.rb:134:in `union'
	from -e:1:in `<main>'
```

**Comment by bjfish** [comment]
This is fixed at: https://github.com/oracle/truffleruby/commit/577494ffc67ce3b1fa2e1cd4161c07a88ccaf9dd
