### ISSUE TITLE
incompatible character encodings error with cucumber and capybara gem (incompatible character encodings: ASCII-8BIT and UTF-8)

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#1967]
`truffleruby 20.1.0-dev-afa60631, like ruby 2.6.5, GraalVM CE Native [x86_64-linux]`

The following code works without issue on MRI

```
require 'capybara/rspec/matchers';
require 'capybara';
require 'cucumber/core/ast/data_table';
require 'cucumber/multiline_argument/data_table';

include Capybara::RSpecMatchers
include Capybara

node = Capybara.string <<-HTML
     <div id="uk-telephone-number" class="govuk-summary-list__row uk-telephone-number">
        <dd class="govuk-summary-list__value">
           It’s just an idea
        </dd>
      </div>
HTML

raw = %{
             | Heading                                 | Value                             |
             | What they want out of school experience | It’s just an idea                 |
             | Degree stage                            | Final year                        |
             | Degree subject                          | Bioscience                        |
             | Teaching stage                          | I want to be a teacher            |
             | Teaching subject                        | First choice: Biology             |
             | Teaching subject                        | Second choice: Biology            |
}

table=Cucumber::MultilineArgument::DataTable.from(raw)

table.hashes.each do |row|
  node.has_css?('dd', text: /#{row['Value']}/i)
end
```
but with TruffleRuby there is an error

```
/home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:557:in `search_region': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:557:in `match'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:557:in `match?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:557:in `match?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:557:in `matches_text_regexp?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:513:in `matches_text_filter?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:433:in `matches_system_filters?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/queries/selector_query.rb:109:in `matches_filters?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:32:in `block in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in select'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block (2 levels) in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each_with_block'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `call'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `yield'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `<<'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in lazy'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block (2 levels) in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each_with_block'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `call'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `yield'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `<<'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in lazy'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block (2 levels) in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `call'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each_with_block'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `call'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each_with_block'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in reset'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `resume'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `next'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `next'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:46:in `block in each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:45:in `loop'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/result.rb:45:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:110:in `any?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:110:in `block in assert_selector'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:844:in `block in _verify_selector_result'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/simple.rb:152:in `synchronize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:843:in `_verify_selector_result'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:109:in `assert_selector'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:39:in `block in has_selector?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:877:in `make_predicate'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:39:in `has_selector?'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/capybara-3.31.0/lib/capybara/node/matchers.rb:310:in `has_css?'
	from test.rb:30:in `block in <main>'
	from test.rb:29:in `each'
	from test.rb:29:in `<main>'
```

A GitHub workflow demonstrating this is in the following project
https://github.com/petenorth/truffleruby-capybara-test

**Comment by eregon** [comment]
Thank you for the simple reproducer!
We'll try to take a look soon.

**Comment by eregon** [comment]
It can be reproduced from:
```ruby
strs = ["It’s just an idea", "Final year"]
strs.each do |str|
  p str.encoding
  p /#{str}/i.encoding
end
```
MRI:
```
#<Encoding:UTF-8>
#<Encoding:UTF-8>
#<Encoding:UTF-8>
#<Encoding:US-ASCII>
```
TruffleRuby:
```
#<Encoding:UTF-8>
#<Encoding:UTF-8>
#<Encoding:UTF-8>
#<Encoding:ASCII-8BIT>
```

**Comment by petenorth** [comment]
@eregon that has fixed it! All the cucumber tests on the original project pass

```
386 scenarios (386 passed)
2478 steps (2478 passed)
51m2.132s
```

There is an issue with the process cleaning up which I think is to do with deoptimizaton prior to exiting which might be SVM related. You can view this here https://github.com/petenorth/schools-experience/runs/517853811?check_suite_focus=true . I don't know how to present this as an issue other than the logs from this run so I won't raise another issue.

**Comment by eregon** [comment]
Great news!

That issue seems caused by a OutOfMemoryError when the tests finish:
```
2020-03-18T23:49:31.7165172Z 386 scenarios (386 passed)
2020-03-18T23:49:31.7165502Z 2478 steps (2478 passed)
2020-03-18T23:49:31.7170591Z 51m2.132s
2020-03-18T23:56:40.1873349Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:17:49.2822309Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:17:49.2846430Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:17:49.2849814Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:17:49.2849993Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:17:49.2850146Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:22:40.1571264Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:22:40.1584057Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:22:40.1584301Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:22:40.1586941Z [ruby] WARNING OutOfMemoryError
2020-03-19T00:22:40.2009035Z [ruby] SEVERE: waited 5 seconds in the SafepointManager but 2605 of 5662 threads did not arrive - a thread is likely making a blocking native call which should use runBlockingSystemCallUntilResult() - check with jstack
2020-03-19T00:22:40.2011203Z Dumping stacktraces of blocked threads:
2020-03-19T00:23:26.8695358Z Fatal error: java.lang.OutOfMemoryError: Garbage-collected heap size exceeded.
...
```
5662 threads is huge and probably the cause of the OutOfMemoryError, probably something creates Threads recursively during `at_exit` or so.
