### ISSUE TITLE
ruby-gr: `type_to_nfi': -4 not implemented (NotImplementedError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1971]
```
truffleruby 20.1.0-dev-1237af4b, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

Note: In my case on macOS

```
brew install libgr
gem install ruby-gr
GRDIR=$(brew --prefix libgr) ruby -rgr
```

Error:

```
~/.rubies/truffleruby-dev/lib/truffle/truffle/fiddle_backend.rb:51:in `type_to_nfi': -4 not implemented (NotImplementedError)
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/fiddle_backend.rb:195:in `block in initialize'
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/fiddle_backend.rb:195:in `map'
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/fiddle_backend.rb:195:in `initialize'
	from ~/.rubies/truffleruby-dev/lib/mri/fiddle/import.rb:301:in `new'
	from ~/.rubies/truffleruby-dev/lib/mri/fiddle/import.rb:301:in `import_function'
	from ~/.rubies/truffleruby-dev/lib/mri/fiddle/import.rb:172:in `extern'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr_commons/extern.rb:15:in `try_extern'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr/ffi.rb:176:in `FFI'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr/ffi.rb:9:in `GR'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr/ffi.rb:5:in `<top (required)>'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr.rb:67:in `require_relative'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr.rb:67:in `GR'
	from ~/.gem/truffleruby/2.6.5/gems/ruby-gr-0.0.14/lib/gr.rb:42:in `<top (required)>'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `call'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `<main>'
```

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/6887e1fd15a576ddbe2c92498e144e792b5a960e.
