### ISSUE TITLE
scout_apm: events_to_events_array: unknown event 0x100000 (ArgumentError)

### ISSUE THREAD

**Issue by deepj** [oracle/truffleruby#1983]
```
truffleruby 20.1.0-dev-6887e1fd, like ruby 2.6.5, GraalVM CE Native [x86_64-darwin]
```

To reproduce:

```
gem install scout_apm
ruby -rscout_apm
```

Error:

```
~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:939:in `events_to_events_array': unknown event 0x100000 (ArgumentError)
	from ~/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:924:in `rb_tracepoint_new'
	from ruby.c:2893:in `rb_tracepoint_new'
	from ~/.gem/truffleruby/2.6.5/gems/scout_apm-2.6.7/ext/allocations/allocations.c:41:in `set_gc_hook'
	from ~/.gem/truffleruby/2.6.5/gems/scout_apm-2.6.7/ext/allocations/allocations.c:50:in `Init_hooks'
	from ~/.gem/truffleruby/2.6.5/gems/scout_apm-2.6.7/ext/allocations/allocations.c:61:in `Init_allocations'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:65:in `gem_original_require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:65:in `require'
	from ~/.gem/truffleruby/2.6.5/gems/scout_apm-2.6.7/lib/scout_apm.rb:96:in `<top (required)>'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `gem_original_require'
	from ~/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `call'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `require'
	from ~/.rubies/truffleruby-dev/bin/irb:1:in `<main>'
```

**Comment by eregon** [comment]
It comes from https://github.com/scoutapp/scout_apm_ruby/blob/6bf98166f885ebd57ee9051c719519f636d4525d/ext/allocations/allocations.c#L11-L41 (nice to have C backtraces :) )
`0x100000` is `RUBY_INTERNAL_EVENT_NEWOBJ`.

The code is conditional on whether `RUBY_INTERNAL_EVENT_NEWOBJ` is defined, so there are two ways to fix this issue:
* Implement that TracePoint event
* Do not define `RUBY_INTERNAL_EVENT_NEWOBJ`

This file seems used to count the total number of allocations.
Doing it this way seems likely to incur a significant performance it on TruffleRuby (they are far more efficient ways to get that data if needed via the Truffle memory tracer instrument), so I think we should try the second way here and see where that gets us.

**Comment by eregon** [comment]
`ruby -rscout_apm -e0` works with that constant not defined.
