### ISSUE TITLE
Failed to install/build appsignal gem extensions

### ISSUE THREAD

**Issue by brauliobo** [oracle/truffleruby#2014]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/braulio/.rvm/gems/truffleruby-20.1.0/gems/appsignal-2.3.4/ext
/home/braulio/.rvm/rubies/truffleruby-20.1.0/bin/truffleruby -I /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri -r ./siteconf20200521-385859-1k1yfrp.rb extconf.rb
/home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:596:in `const_missing': uninitialized constant Gem::Deprecate (NameError)
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:596:in `(singleton-def)'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:595:in `Gem'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:116:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/patches/rubygems.rb:1:in `require'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/patches/rubygems.rb:1:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/deprecate.rb:24:in `require'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/deprecate.rb:24:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/exceptions.rb:7:in `require'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/exceptions.rb:7:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/security.rb:8:in `require'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/security.rb:8:in `<top (required)>'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/package.rb:44:in `require'
        from /home/braulio/.rvm/rubies/truffleruby-20.1.0/lib/mri/rubygems/package.rb:44:in `<top (required)>'
        from extconf.rb:6:in `require'
        from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/braulio/.rvm/gems/truffleruby-20.1.0/gems/appsignal-2.3.4 for inspection.
Results logged to /home/braulio/.rvm/gems/truffleruby-20.1.0/extensions/x86_64-linux/20.1.0/appsignal-2.3.4/gem_make.out

An error occurred while installing appsignal (2.3.4), and Bundler cannot continue.
Make sure that `gem install appsignal -v '2.3.4' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  review_collector was resolved to 1.0.0, which depends on
    olery-logging was resolved to 1.1.1, which depends on
      appsignal

```

**Comment by eregon** [comment]
The latest `appsignal` 2.10.7 works fine:
```
$ gem i appsignal
Fetching rack-2.2.2.gem
Fetching appsignal-2.10.7.gem
Successfully installed rack-2.2.2
Building native extensions. This could take a while...
Successfully installed appsignal-2.10.7
2 gems installed
```

appsignal 2.3.4 used to do this: https://github.com/appsignal/appsignal-ruby/blob/v2.3.4/ext/extconf.rb

And can be reproduced simply with:
```
$ ruby -e 'require "rubygems/package"'
/home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:596:in `const_missing': uninitialized constant Gem::Deprecate (NameError)
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:596:in `(singleton-def)'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:595:in `Gem'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems.rb:116:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/patches/rubygems.rb:1:in `require'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/patches/rubygems.rb:1:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/deprecate.rb:24:in `require'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/deprecate.rb:24:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/exceptions.rb:7:in `require'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/exceptions.rb:7:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/security.rb:8:in `require'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/security.rb:8:in `<top (required)>'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/package.rb:44:in `require'
	from /home/eregon/.rubies/truffleruby-20.1.0/lib/mri/rubygems/package.rb:44:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

Which seems like a require or autoload bug.
The issue is `rubygems/deprecate.rb` defines `module Gem::Deprecate` but `Gem` hasn't been defined yet.

**Comment by eregon** [comment]
Actually, MRI 2.6.6 has the same issue, if run with `--disable-gems`:
```
$ ruby -v --disable-gems -e 'require "rubygems/package"' |& cat
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
/home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/deprecate.rb:24:in `<top (required)>': uninitialized constant Gem (NameError)
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/exceptions.rb:7:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/exceptions.rb:7:in `<top (required)>'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/security.rb:8:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/security.rb:8:in `<top (required)>'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/package.rb:44:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/package.rb:44:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

What saves it is without that flag it automatically defines an (empty) `Gem` module as a way to remember to require rubygems at startup.

So I think this is essentially a RubyGems issue: RubyGems 3.0.3 doesn't support to `require "rubygems/package"` directly, only through `require "rubygems"`.

**Comment by eregon** [comment]
RubyGems issue about this: https://github.com/rubygems/rubygems/issues/3650

**Comment by eregon** [comment]
Fixed in 8962ca0aa8cacf73650b9c7774745d1da718a899, thank you for the report!

**Comment by brauliobo** [comment]
thank you @eregon for the quick response and action, great work!
btw, how to fetch truffleruby git releases with rvm?

**Comment by eregon** [comment]
Do you mean installing TruffleRuby dev/nightly builds?
That's documented in the README: https://github.com/oracle/truffleruby/blob/master/README.md
`rvm install truffleruby-head`
