### ISSUE TITLE
Kernel#srand returns nil on the first call

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2028]
This causes RSpec 2 to fail:
https://github.com/rspec/rspec-core/blob/f9b0908e51135098ab162c148ed8c72867033dc1/lib/rspec/core/configuration.rb#L202
```
# In MSpec
$ bundle exec rspec
/home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:202:in `initialize': undefined method `%' for nil:NilClass (NoMethodError)
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core.rb:102:in `new'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core.rb:102:in `configuration'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:4:in `initialize'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `new'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'
	from /home/runner/.rubies/truffleruby-head/lib/gems/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:17:in `block in autorun'
```

Also affects TruffleRuby 20.1.0.

**Comment by eregon** [comment]
Fixed in a7435c5
