### ISSUE TITLE
mini_racer: `rb_context_init_unsafe': External function cannot be found.

### ISSUE THREAD

**Issue by SamSaffron** [oracle/truffleruby#2029]
#1827 got closed reopening here 

```
gem install mini_racer
ruby -rmini_racer -e 'context = MiniRacer::Context.new; context.eval "var adder = (a,b)=>a+b"; puts context.eval "adder(20,22)"'
```

```
ruby -rmini_racer -e 'context = MiniRacer::Context.new; context.eval "var adder = (a,b)=>a+b"; puts context.eval "adder(20,22)"'
/home/sam/.gem/truffleruby/2.6.5/gems/mini_racer-0.2.14/ext/mini_racer_extension/mini_racer_extension.cc:196:in `init_v8': External LLVMFunction _ZN2v82V813InitializeICUEPKc cannot be found. (LLVMLinkerException) (RuntimeError)
Translated to internal error
	from /home/sam/.gem/truffleruby/2.6.5/gems/mini_racer-0.2.14/ext/mini_racer_extension/mini_racer_extension.cc:786:in `rb_context_init_unsafe'
	from /home/sam/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `init_unsafe'
	from /home/sam/.gem/truffleruby/2.6.5/gems/mini_racer-0.2.14/lib/mini_racer.rb:164:in `initialize'
	from -e:1:in `new'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment]
Thanks. I've asked @deepj if it's OK if I reopen his issues in https://github.com/oracle/truffleruby/issues/1900.

**Comment by eregon** [comment]
I reopened #1827.
