### ISSUE TITLE
cannot run tests for the test-unit gem

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2058]
Hi,
for some reason I cannot run tests for this gem.

How to reproduce:
```
git clone git@github.com:test-unit/test-unit.git
bundle install
rake
```
wich fails with :
```
rake --trace                                           [31/07/20 | 12:04:43]
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/locale_path.rb:24:in `LocalePath'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/locale_path.rb:17:in `GetText'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/locale_path.rb:15:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/text_domain.rb:17:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleru§by-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/text_domain_manager.rb:14:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext.rb:19:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/tools/xgettext.rb:26:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/gettext-3.3.5/lib/gettext/tools.rb:21:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/packnga-1.0.4/lib/packnga/reference-task.rb:20:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/packnga-1.0.4/lib/packnga/document-task.rb:21:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/packnga-1.0.4/lib/packnga.rb:21:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:130:in `require'
/Users/novoi/.rubies/truffleruby-dev/bin/tmp/test-unit-master/rakefile:38:in `<top (required)>'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
../../rake:23:in `<main>'

Caused by:
LoadError: cannot load such file -- packnga
<internal:core> core/kernel.rb:236:in `gem_original_require'
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/novoi/.rubies/truffleruby-dev/bin/tmp/test-unit-master/rakefile:38:in `<top (required)>'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
../../rake:23:in `<main>'
```
From the stacktrace it points out to the gettext gem, but I didn't find any issues with it (all tests are passing for the gettext gem).

**Comment by eregon** [comment]
@bjfish Could you take a look, see if you can reproduce and try to find where this `nil` comes from?

**Comment by bjfish** [comment]
@gogainda The line this failed on contains `RbConfig::CONFIG["datadir"]`:
https://github.com/ruby-gettext/gettext/blob/192d16c194694b5a1f9d6f8cb11b935acad74dc8/lib/gettext/locale_path.rb#L24
which was recently fixed:
https://github.com/oracle/truffleruby/commit/ef531e23425af5884b010597ee265c611b3537c0

Please try updating to the latest nightly release, confirm that `ruby -e 'p RbConfig::CONFIG["datadir"]'` does not output `nil`, and retry `test-unit` tests.

**Comment by bjfish** [comment]
I observed 6 failures/errors when trying the test-unit tests:
https://gist.github.com/bjfish/425321b23ba04729bf9ae2807fa576e1

**Comment by gogainda** [comment]
@bjfish @eregon works with the latest nightly build, closing the issue

**Comment by gogainda** [comment]
@bjfish  @eregon  majority of the failed tests look the same:
```
<[{:class=>Test::Unit::Failure,
  :location=>
   ["/Users/bfish/Documents/projects/test-unit/test/test-test-case.rb:0:in `test_failure'",
    "/Users/bfish/Documents/projects/test-unit/test/test-test-case.rb:0:in `test_add_failed_assertion'"],
  :message=>"failure",
  :test_name=>"test_failure(TC_FailureError)"}]> expected but was
<[{:class=>Test::Unit::Failure,
  :location=>
   ["/Users/bfish/Documents/projects/test-unit/test/test-test-case.rb:0:in `test_failure'",
    "<internal:core> core/throw_catch.rb:0:in `catch'",
    "/Users/bfish/Documents/projects/test-unit/test/test-test-case.rb:0:in `test_add_failed_assertion'",
    "<internal:core> core/throw_catch.rb:0:in `catch'",
    "<internal:core> core/throw_catch.rb:0:in `catch'"],
  :message=>"failure",
  :test_name=>"test_failure(TC_FailureError)"}]>
```
Is it worth creating a new truffle ruby issue or it's up to the maintainers of the original gem to make tests more compatible between different ruby versions?

**Comment by bjfish** [comment]
@gogainda A new TruffleRuby issue can be created since these look like TruffleRuby compatibility issues.  If the tests pass on `MRI 2.6.6`, that usually indicates an issue in TruffleRuby.

**Comment by gogainda** [comment]
https://github.com/oracle/truffleruby/issues/2059
