### ISSUE TITLE
rubyzip test case failure: PathTraversalTest#test_entry_name_with_tilde

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2062]
### How to reproduce
```
git clone git@github.com:rubyzip/rubyzip.git
bundle install
rake
```
### Exception stack trace
```
rubyzip-master % /Users/novoi/.rubies/truffleruby-dev/bin/rake                   [3/08/20 | 10:56:54]
/Users/novoi/.rubies/truffleruby-dev/bin/truffleruby -w -I"lib:lib:test" -I"/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib" "/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "test/basic_zip_file_test.rb" "test/bzip2_support_test.rb" "test/case_sensitivity_test.rb" "test/central_directory_entry_test.rb" "test/central_directory_test.rb" "test/constants_test.rb" "test/crypto/null_encryption_test.rb" "test/crypto/traditional_encryption_test.rb" "test/decompressor_test.rb" "test/deflater_test.rb" "test/encryption_test.rb" "test/entry_set_test.rb" "test/entry_test.rb" "test/errors_test.rb" "test/extra_field_test.rb" "test/extra_field_ut_test.rb" "test/file_extract_directory_test.rb" "test/file_extract_test.rb" "test/file_options_test.rb" "test/file_permissions_test.rb" "test/file_split_test.rb" "test/file_test.rb" "test/filesystem/dir_iterator_test.rb" "test/filesystem/directory_test.rb" "test/filesystem/file_mutating_test.rb" "test/filesystem/file_nonmutating_test.rb" "test/filesystem/file_stat_test.rb" "test/inflater_test.rb" "test/input_stream_test.rb" "test/ioextras/abstract_input_stream_test.rb" "test/ioextras/abstract_output_stream_test.rb" "test/ioextras/fake_io_test.rb" "test/local_entry_test.rb" "test/output_stream_test.rb" "test/pass_thru_compressor_test.rb" "test/pass_thru_decompressor_test.rb" "test/path_traversal_test.rb" "test/samples/example_recursive_test.rb" "test/settings_test.rb" "test/stored_support_test.rb" "test/unicode_file_names_and_comments_test.rb" "test/zip64_full_test.rb" "test/zip64_support_test.rb" 
Warning: Error occurred while trying to load /Users/novoi/tmp/rubyzip-master/.simplecov. Error message: Unable to activate coveralls-0.8.23, because simplecov-0.18.5 conflicts with simplecov (~> 0.16.1)
Run options: --seed 15675

# Running:

............F....................................................................................................................................................................................................................................................................................................

Finished in 14.912076s, 20.4532 runs/s, 193.4674 assertions/s.

  1) Failure:
PathTraversalTest#test_entry_name_with_tilde [/Users/novoi/tmp/rubyzip-master/test/path_traversal_test.rb:21]:
In stderr.
--- expected
+++ actual
@@ -1 +1,2 @@
-""
+"WARNING: skipped '~tilde~' as unsafe.
+"


305 runs, 2885 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib" "/Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/rake-13.0.1/lib/rake/rake_test_loader.rb" "test/basic_zip_file_test.rb" "test/bzip2_support_test.rb" "test/case_sensitivity_test.rb" "test/central_directory_entry_test.rb" "test/central_directory_test.rb" "test/constants_test.rb" "test/crypto/null_encryption_test.rb" "test/crypto/traditional_encryption_test.rb" "test/decompressor_test.rb" "test/deflater_test.rb" "test/encryption_test.rb" "test/entry_set_test.rb" "test/entry_test.rb" "test/errors_test.rb" "test/extra_field_test.rb" "test/extra_field_ut_test.rb" "test/file_extract_directory_test.rb" "test/file_extract_test.rb" "test/file_options_test.rb" "test/file_permissions_test.rb" "test/file_split_test.rb" "test/file_test.rb" "test/filesystem/dir_iterator_test.rb" "test/filesystem/directory_test.rb" "test/filesystem/file_mutating_test.rb" "test/filesystem/file_nonmutating_test.rb" "test/filesystem/file_stat_test.rb" "test/inflater_test.rb" "test/input_stream_test.rb" "test/ioextras/abstract_input_stream_test.rb" "test/ioextras/abstract_output_stream_test.rb" "test/ioextras/fake_io_test.rb" "test/local_entry_test.rb" "test/output_stream_test.rb" "test/pass_thru_compressor_test.rb" "test/pass_thru_decompressor_test.rb" "test/path_traversal_test.rb" "test/samples/example_recursive_test.rb" "test/settings_test.rb" "test/stored_support_test.rb" "test/unicode_file_names_and_comments_test.rb" "test/zip64_full_test.rb" "test/zip64_support_test.rb" ]
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
Tasks: TOP => default => test

```

**Comment by bjfish** [comment]
Small error case for the issue:
```
%  ruby -v -e 'p File.absolute_path("~tilde~", "/")'
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
"/~tilde~"

%  ruby -v -e 'p File.absolute_path("~tilde~", "/")'
truffleruby 20.3.0-dev-de7ea9b7, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
"/Users/bfish/Documents/projects/rubyzip/~tilde~"
```

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/d5e20489bf63a558194e709e5fc9b7fc6b34ea2b.
