### ISSUE TITLE
Intermittent Puma CI failures

### ISSUE THREAD

**Issue by MSP-Greg** [oracle/truffleruby#2064]
Puma's CI is a bit unstable, and I've been working trying to stabilize it.  MRI seems stable, but some intermittent issues with JRuby & TruffleRuby.  The below is shown on some of the TruffleRuby failures:
```
Error in reactor loop escaped: <no message> (IllegalMonitorStateException)
  from java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
  from java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
  from java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
  from org.truffleruby.core.mutex.MutexOperations.unlockInternal(MutexOperations.java:100)
  from org.truffleruby.cext.CExtNodes$CallCWithMutexNode.callCWithMutex(CExtNodes.java:141)
  from org.truffleruby.cext.CExtNodesFactory$CallCWithMutexNodeFactory$CallCWithMutexNodeGen.execute(CExtNodesFactory.java:207)
  from org.truffleruby.cext.CExtNodes$CallCWithMuteAndFramexNode.callCWithMutex(CExtNodes.java:180)
  from org.truffleruby.cext.CExtNodesFactory$CallCWithMuteAndFramexNodeFactory$CallCWithMuteAndFramexNodeGen.execute(CExtNodesFactory.java:476)
  from org.truffleruby.cext.CExtNodesFactory$UnwrapValueNodeFactory$UnwrapValueNodeGen.execute(CExtNodesFactory.java:6794)
  from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
  from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
  from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
  from org.truffleruby.language.methods.CatchForLambdaNode.execute(CatchForLambdaNode.java:52)
  from org.truffleruby.core.module.ModuleNodes$DefineMethodNode$CallMethodWithProcBody.execute(ModuleNodes.java:1253)
  from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
  from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error (RuntimeError)
/home/runner/work/puma/puma/lib/puma/reactor.rb:136:in `select'
/home/runner/work/puma/puma/lib/puma/reactor.rb:136:in `run_internal'
/home/runner/work/puma/puma/lib/puma/reactor.rb:317:in `block in run_in_thread'
(null): ./../libev/ev.c:3656: int ev_run(struct ev_loop *, int): Assertion `("libev: ev_loop recursion during release detected", loop_done != EVBREAK_RECURSE)' failed.
truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: Ruby Thread id=64 from /home/runner/work/puma/puma/lib/puma/reactor.rb:314 terminated with internal error:
  at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:343)
  at org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:316)
  at java.lang.Thread.run(Thread.java:748)
  at com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:87)
  at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
  at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.oracle.truffle.llvm.runtime.LLVMExitException
Caused by: Attached Guest Language Frames (0)
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

Reactor:136 is the select statement below, the selector is a `NIO::Selector`:
```ruby
while true
  begin
    ready = selector.select @sleep_for
  rescue IOError => e
```

This may not be helpful, I'm happy to debug, etc...

**Comment by eregon** [comment]
Thank you for the report, and sorry about the transient issues.

The Java stacktrace is rather puzzling here, it shows that `unlockInternal()` doesn't have the lock, even though it should be guaranteed it's acquired by `lockInternal()` above:
https://github.com/oracle/truffleruby/blob/953ac5d2c62586de8f4b0a2cf9e0fad9de78cea0/src/main/java/org/truffleruby/cext/CExtNodes.java#L136-L141
And if there was an exception in `lockInternal()` we wouldn't call `unlockInternal()`.

I think maybe we can do `if (!lock.isHeldByCurrentThread()) { throw CompilerDirectives.shouldNotReachHere(); }` at the end of `lockInternal()` to be absolutely sure that `lockInternal()` has locked it.

Regarding the failed `Assertion` in C code I'm not sure what it means, and whether it's the cause or the consequence of the Java exception.

**Comment by MSP-Greg** [comment]
@eregon

Thanks for looking at this.  I don't know how significant this is, as I don't know how to interpret it.

It is intermittent, but when TruffleRuby fails, it is often the cause.  Oddly, sometimes Minitest completes all its reporting, shows no failures/errors, and then the above is shown.

Maybe CI is leaving an instance of TruffleRuby running, and it's failing after the CI has completed?  There are several tests where spawn/popen/etc is used to isolate Puma server processes.  Kind of odd, as MRI & JRuby seem stable.  Also, the failure involves a nio4r call, so I don't know it the 'state' causing the failure is generated by Puma or nio4r...

See https://github.com/MSP-Greg/puma/runs/951969367?check_suite_focus=true#step:7:633

**Comment by eregon** [comment]
A run with the new assertions:
https://github.com/puma/puma/runs/1033504877
```
truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: Ruby Thread id=84 from /home/runner/work/puma/puma/lib/puma/reactor.rb:315 terminated with internal error:
	at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:299)
	at org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:272)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:87)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:518)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Original Internal Error: 
java.lang.RuntimeException: Ruby Thread id=84 from /home/runner/work/puma/puma/lib/puma/reactor.rb:315 terminated with internal error:
	at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:299)
	at org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:272)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:87)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:518)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: the lock was not held when calling unlockInternal()
	at com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:460)
	at com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:406)
	at org.truffleruby.core.mutex.MutexOperations.unlockInternal(MutexOperations.java:103)
	at org.truffleruby.cext.CExtNodes$CallCWithMutexNode.callCWithMutex(CExtNodes.java:142)
	at org.truffleruby.cext.CExtNodesFactory$CallCWithMutexNodeFactory$CallCWithMutexNodeGen.execute(CExtNodesFactory.java:212)
	at org.truffleruby.cext.CExtNodes$CallCWithMuteAndFramexNode.callCWithMutex(CExtNodes.java:169)
	at org.truffleruby.cext.CExtNodesFactory$CallCWithMuteAndFramexNodeFactory$CallCWithMuteAndFramexNodeGen.execute(CExtNodesFactory.java:481)
	at org.truffleruby.cext.CExtNodesFactory$UnwrapValueNodeFactory$UnwrapValueNodeGen.execute(CExtNodesFactory.java:6761)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	at org.truffleruby.language.methods.CatchForLambdaNode.execute(CatchForLambdaNode.java:52)
	at org.truffleruby.core.module.ModuleNodes$DefineMethodNode$CallMethodWithProcBody.execute(ModuleNodes.java:1246)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:515)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:486)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:452)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:399)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:126)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:97)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:118)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:106)
	at org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:34)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	at org.truffleruby.language.exceptions.TryNode.execute(TryNode.java:61)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:62)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:33)
	at org.truffleruby.language.control.WhileNode$WhileRepeatingNode.executeRepeating(WhileNode.java:79)
	at com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:107)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:162)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:123)
	at org.truffleruby.language.control.WhileNode.execute(WhileNode.java:36)
	at org.truffleruby.language.methods.CatchBreakNode.execute(CatchBreakNode.java:40)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	at org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	at org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:42)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	at org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:47)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:515)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:486)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:452)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:399)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
	at org.truffleruby.language.dispatch.CachedDispatchNode.call(CachedDispatchNode.java:126)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:97)
	at org.truffleruby.language.dispatch.CachedBoxedDispatchNode.executeDispatch(CachedBoxedDispatchNode.java:87)
	at org.truffleruby.language.dispatch.DispatchHeadNode.dispatch(DispatchHeadNode.java:44)
	at org.truffleruby.language.dispatch.RubyCallNode.executeWithArgumentsEvaluated(RubyCallNode.java:118)
	at org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:106)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	at org.truffleruby.language.exceptions.TryNode.execute(TryNode.java:61)
	at org.truffleruby.language.exceptions.EnsureNode.executeCommon(EnsureNode.java:59)
	at org.truffleruby.language.exceptions.EnsureNode.execute(EnsureNode.java:40)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	at org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	at org.truffleruby.language.methods.CatchForProcNode.execute(CatchForProcNode.java:38)
	at org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:515)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:486)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:452)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:146)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:386)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:373)
	at org.truffleruby.core.proc.ProcOperations.rootCall(ProcOperations.java:46)
	at org.truffleruby.core.thread.ThreadNodes$ThreadInitializeNode.lambda$initialize$0(ThreadNodes.java:336)
	at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:284)
	... 5 more
Caused by: Attached Guest Language Frames (3)
rake aborted!
Command failed with status (1)
<internal:core> core/kernel.rb:402:in `load'
<internal:core> core/kernel.rb:402:in `load'
<internal:core> core/kernel.rb:402:in `load'
<internal:core> core/kernel.rb:402:in `load'
<internal:core> core/kernel.rb:402:in `load'
<internal:core> core/kernel.rb:402:in `load'
/home/runner/.rubies/truffleruby-head/bin/bundle:23:in `<main>'
Tasks: TOP => test:all => test
(See full trace by running task with --trace)
```

**Comment by eregon** [comment]
That's still confusing but now I have a guess, maybe the dying Thread, while inside `call_without_c_mutex` and trying to re-acquire the lock gets killed by e.g. `Thread#raise` (inside runUntilResult() and pollFromBlockingCall()) and then via the exception gets to a `call_with_c_mutex` call higher up the stack where it tries to unlock but the lock was not re-acquired as expected.

**Comment by eregon** [comment]
I think 06662f0c2bcfd68481e784b75dd6360b14c09935 should fix this.
Let's reopen if it happens again.
