### ISSUE TITLE
json_schemer failing test: JSONSchemerTest#test_json_schema_test_suite

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2065]
### How to reproduce
```
git clone git@github.com:davishmcclurg/json_schemer.git
bundle install
rake
```
### Stack trace
```
truffleruby 20.3.0-dev-9220194b, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]

# Running:

.....................Not using escape_utils.
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/uri_template-0.7.0/lib/uri_template/rfc6570.rb
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/uri_template-0.7.0/lib/uri_template/rfc6570.rb
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/uri_template-0.7.0/lib/uri_template/rfc6570.rb
/Users/novoi/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/uri_template-0.7.0/lib/uri_template/rfc6570.rb
F.....................

Finished in 4.951735s, 8.6838 runs/s, 554.7551 assertions/s.

  1) Failure:
JSONSchemerTest#test_json_schema_test_suite [/Users/novoi/tmp/json_schemer/test/json_schemer_test.rb:724]:
JSON-Schema-Test-Suite/tests/draft7/optional/content.json
```

**Comment by eregon** [comment]
A guess: this might due to TruffleRuby defaulting to the pure-Ruby json stdlib, if there is no `gem 'json'` in the Gemfile.

BTW, should it be `rake` or `bundle exec rake` to run tests?
I think `bundle exec rake` is safer.

**Comment by gogainda** [comment]
@eregon regarding rake I am not sure how it works , but I would be using this way of executing if it's safer

**Comment by eregon** [comment]
I don't anything in rake doing something like `require 'bundler/setup'`, so yeah it's safer to use `bundle exec rake` to make sure the right gems as specified by Gemfile.lock are used and not potentially other versions.

**Comment by bjfish** [comment]
A small reproduction case:
```
# Expected
% ruby -v -rbase64 -e 'Base64.strict_decode64("eyJmb28iOi%iYmFyIn0K")'
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /Users/bfish/.rbenv/versions/2.6.6/lib/ruby/2.6.0/base64.rb:74:in `strict_decode64'
/Users/bfish/.rbenv/versions/2.6.6/lib/ruby/2.6.0/base64.rb:74:in `unpack1': invalid base64 (ArgumentError)

#Actual
% ruby -v -rbase64 -e 'Base64.strict_decode64("eyJmb28iOi%iYmFyIn0K")'
truffleruby 20.3.0-dev-8463b89b, like ruby 2.6.6, GraalVM CE Native [x86_64-darwin]
```

**Comment by bjfish** [comment]
This test now passes with the fix at: https://github.com/oracle/truffleruby/commit/12c84fa6e11dc0dcabf4b5886aea40604f420a3c.
