### ISSUE TITLE
device_detector failing tests with errors

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2066]
### Hot to reproduce
```
git clone git@github.com:podigee/device_detector.git
bundle install
bundler exec rake
```

### Stack trace
```
  1) Error:
DeviceDetector::smartphone-12.yml::Mozilla / 5.0 (Linux; Android 9; Titan) AppleWebKit / 537.36 (KHTML, как Gecko) Chrome / 79.0.3945.116 Mobile Safari / 537.36#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

  2) Error:
DeviceDetector::smartphone-11.yml::Mozilla/5.0 (Linux; U; Android 4.0.4; fr-fr; SonyEricssonLT18i Build/Xperia Ultimate HDâ„¢ 3.0.2) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

  3) Error:
DeviceDetector::tablet-3.yml::Mozilla/5.0 (Linux; U; Android 4.1.1; fr-fr; eZeeâ€™Tab 971 Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

  4) Error:
DeviceDetector::smartphone-7.yml::Mozilla/5.0 (Linux; Android 4.4.2 mobiistar_KOOL_Lite; Build/KOT49H)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.131 Mobile Safari/537.36#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

  5) Error:
DeviceDetector::smartphone-8.yml::Mozilla/5.0 (Linux; U; Android 2.3.6; pt-br; XT321 Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Versão/4.0 Mobile Safari/533.1#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

  6) Error:
DeviceDetector::tablet-3.yml::Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; Ramos X10 PROæ—¶å°šç‰ˆ Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30#test_0001_should be detected:
RuntimeError: invalid pattern in look-behind (SyntaxException)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:503)
Translated to internal error
    <internal:core> core/string.rb:99:in `search_region'
    <internal:core> core/string.rb:99:in `=~'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `block in regex_find'
    <internal:core> core/enumerable.rb:626:in `block in find'
    <internal:core> core/enumerable.rb:624:in `each'
    <internal:core> core/enumerable.rb:624:in `find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:78:in `regex_find'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:54:in `block in matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `block in from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/memory_cache.rb:38:in `get_or_set'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:92:in `from_cache'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:52:in `matching_regex'
    /Users/novoi/tmp/device_detector/lib/device_detector/parser.rb:31:in `regex_meta'
    /Users/novoi/tmp/device_detector/lib/device_detector/device.rb:29:in `type'
    /Users/novoi/tmp/device_detector/lib/device_detector.rb:53:in `device_type'
    /Users/novoi/tmp/device_detector/spec/device_detector/detector_fixtures_spec.rb:69:in `test_0001_should be detected'

12051 runs, 74154 assertions, 0 failures, 6 errors, 0 skips
rake aborted!
Command failed with status (1)
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
<internal:core> core/kernel.rb:395:in `load'
/Users/novoi/.rubies/truffleruby-dev/bin/bundler:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by bjfish** [comment]
I think I have a small reproduction case for this:
```
r = /(?:^|[^A-Z0-9\-_]|[^A-Z0-9\-]_|sprd-)(?:acer|(?<!ZTE BLADE |ImSmart |ERGO |X-Style Tab )a(?:101|110|2[10]0|211|50[10]|51[10]|70[10])[);\/ ]|Android.*V3[67]0[);\/ ]|Android.*Z1[23456]0 Build|Android.*Z5\d{2} Build|Android.*T0[234678] Build|Android.*S55[);\/ ]|(?:A1-(713(HD)?|7[23]4|830|841|840FHD|81[01])|A3-A[1234][01]|B1-(7[1235-8][01](HD)?|7[23]3|8[1235]0|A71)|B3-(A[12]0|A3[02]|A40FHD)|E39)[);\/ ]|S5[12]0 Build|DA[0-9]+HQ?L[);\/ ]|Aspire V5-121|Predator G9-793|GT-810)/i
a ="Mozilla / 5.0 (Linux; Android 9; Titan) AppleWebKit / 537.36 (KHTML, как Gecko) Chrome / 79.0.3945.116 Mobile Safari / 537.36"
puts a =~ r
```
Expected (RegexpError):
```
% ruby ../../notes/patches/regex.rb 
Traceback (most recent call last):
	1: from ../../notes/patches/regex.rb:3:in `<main>'
../../notes/patches/regex.rb:3:in `=~': invalid pattern in look-behind: /(?:^|[^A-Z0-9\-_]|[^A-Z0-9\-]_|sprd-)(?:acer|(?<!ZTE BLADE |ImSmart |ERGO |X-Style Tab )a(?:101|110|2[10]0|211|50[10]|51[10]|70[10])[);\/ ]|Android.*V3[67]0[);\/ ]|Android.*Z1[23456]0 Build|Android.*Z5\d{2} Build|Android.*T0[234678] Build|Android.*S55[);\/ ]|(?:A1-(713(HD)?|7[23]4|830|841|840FHD|81[01])|A3-A[1234][01]|B1-(7[1235-8][01](HD)?|7[23]3|8[1235]0|A71)|B3-(A[12]0|A3[02]|A40FHD)|E39)[);\/ ]|S5[12]0 Build|DA[0-9]+HQ?L[);\/ ]|Aspire V5-121|Predator G9-793|GT-810)/i (RegexpError)
```
Actual (internal error)
```
% jt ruby ../../notes/patches/regex.rb
<internal:core> core/string.rb:99:in `search_region': invalid pattern in look-behind (SyntaxException) (RuntimeError)
	from org.joni.ScannerSupport.newSyntaxException(ScannerSupport.java:163)
	from org.joni.Analyser.setupLookBehind(Analyser.java:1419)
	from org.joni.Analyser.setupTree(Analyser.java:2030)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.setupTree(Analyser.java:1851)
	from org.joni.Analyser.setupTree(Analyser.java:1840)
	from org.joni.Analyser.compile(Analyser.java:110)
	from org.joni.Regex.<init>(Regex.java:155)
	from org.joni.Regex.<init>(Regex.java:134)
	from org.joni.Regex.<init>(Regex.java:129)
	from org.truffleruby.core.regexp.RegexpNodes.makeRegexpForEncoding(RegexpNodes.java:96)
	from org.truffleruby.core.regexp.RegexpNodes.lambda$createMatcher$0(RegexpNodes.java:79)
	from org.truffleruby.collections.ConcurrentOperations.getOrCompute(ConcurrentOperations.java:27)
	from org.truffleruby.core.regexp.EncodingCache.getOrCreate(EncodingCache.java:30)
	from org.truffleruby.core.regexp.RegexpNodes.createMatcher(RegexpNodes.java:79)
	from org.truffleruby.core.regexp.RegexpNodes$RegexpSearchRegionNode.searchRegion(RegexpNodes.java:443)
	from org.truffleruby.core.regexp.RegexpNodesFactory$RegexpSearchRegionNodeFactory$RegexpSearchRegionNodeGen.execute(RegexpNodesFactory.java:1466)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:47)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
	from com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:83)
Translated to internal error
	from <internal:core> core/string.rb:99:in `=~'
	from ../../notes/patches/regex.rb:3:in `<main>'
```

**Comment by eregon** [comment]
Right, so it seems just catching the internal SyntaxException and convert it to a RegexpError should fix it then.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/3e3610873282db9e45bef226c23df9fc00a2f746
