### ISSUE TITLE
Errno::ENOMEM: Cannot allocate memory

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2076]
```
/home/travis/.rvm/rubies/truffleruby-head/bin/truffleruby -w -I"lib:lib:test" -I"/home/travis/build/rubyzip/rubyzip/vendor/bundle/truffleruby/20.3.0-dev-cc7f184c/gems/rake-12.3.3/lib" "/home/travis/build/rubyzip/rubyzip/vendor/bundle/truffleruby/20.3.0-dev-cc7f184c/gems/rake-12.3.3/lib/rake/rake_test_loader.rb" "test/basic_zip_file_test.rb" "test/bzip2_support_test.rb" "test/case_sensitivity_test.rb" "test/central_directory_entry_test.rb" "test/central_directory_test.rb" "test/constants_test.rb" "test/crypto/null_encryption_test.rb" "test/crypto/traditional_encryption_test.rb" "test/decompressor_test.rb" "test/deflater_test.rb" "test/encryption_test.rb" "test/entry_set_test.rb" "test/entry_test.rb" "test/errors_test.rb" "test/extra_field_test.rb" "test/extra_field_ut_test.rb" "test/file_extract_directory_test.rb" "test/file_extract_test.rb" "test/file_options_test.rb" "test/file_permissions_test.rb" "test/file_split_test.rb" "test/file_test.rb" "test/filesystem/dir_iterator_test.rb" "test/filesystem/directory_test.rb" "test/filesystem/file_mutating_test.rb" "test/filesystem/file_nonmutating_test.rb" "test/filesystem/file_stat_test.rb" "test/inflater_test.rb" "test/input_stream_test.rb" "test/ioextras/abstract_input_stream_test.rb" "test/ioextras/abstract_output_stream_test.rb" "test/ioextras/fake_io_test.rb" "test/local_entry_test.rb" "test/output_stream_test.rb" "test/pass_thru_compressor_test.rb" "test/pass_thru_decompressor_test.rb" "test/path_traversal_test.rb" "test/samples/example_recursive_test.rb" "test/settings_test.rb" "test/stored_support_test.rb" "test/unicode_file_names_and_comments_test.rb" "test/zip64_full_test.rb" "test/zip64_support_test.rb" 

Run options: --seed 1854

# Running:

.................................................................................................................................................................................................................................................E...............................................................

Finished in 37.800801s, 8.0686 runs/s, 76.3476 assertions/s.

  1) Error:

ZipFsFileNonmutatingTest#test_popen:

Errno::ENOMEM: Cannot allocate memory - posix_spawnp ls

    <internal:core> core/truffle/process_operations.rb:455:in `spawn'

    <internal:core> core/truffle/process_operations.rb:110:in `spawn'

    <internal:core> core/io.rb:894:in `popen'

    /home/travis/build/rubyzip/rubyzip/test/filesystem/file_nonmutating_test.rb:475:in `test_popen'

305 runs, 2886 assertions, 0 failures, 1 errors, 0 skips

Coverage report generated for Unit Tests to /home/travis/build/rubyzip/rubyzip/coverage. 1621 / 1721 LOC (94.19%) covered.

[Coveralls] Submitting to https://coveralls.io/api/v1

Coveralls git error:

Cannot allocate memory - posix_spawnp /bin/sh
```
from [here](https://travis-ci.org/github/rubyzip/rubyzip/jobs/720594560)

**Comment by eregon** [comment]
Link: https://github.com/rubyzip/rubyzip/pull/450

Thanks for the report, we should take a look why we run out of memory while running those tests.
Probably a good start is to look at how much memory is used with VisualVM when running on JVM CE.
@bjfish Can you do that?

**Comment by bjfish** [comment]
@eregon Yes, I'll investigate this.

**Comment by bjfish** [comment]
@eregon I am able to recreate this now using a local VM that is setup similar to the `.travis.yml` file.  I saw nothing interesting in `visualvm`, `--memtracer`, or `free`, and `export TRUFFLERUBYOPT='--vm.Xmx4g'` did not seem to help.

I've gotten the error to resolve in the VM by changing this setting which I read about here: https://github.com/nodejs/node/issues/25382 :
Default
```
$ sysctl vm.overcommit_memory
vm.overcommit_memory = 0
```
Works with 1:
```
 $ sudo bash -c 'echo 1 > /proc/sys/vm/overcommit_memory'
vagrant@ubuntu-xenial:/vagrant_data/rubyzip$ sysctl vm.overcommit_memory
vm.overcommit_memory = 1
```

I am still investigating and I check if the test fails on TruffleRuby JVM and other Ubuntu versions.

**Comment by gogainda** [comment]
rubyzip fully functional on TruffleRuby now, I think it was related to Travis CI. Closing
