### ISSUE TITLE
internal errors in gsub

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2086]
Version: truffleruby 20.3.0-dev-06662f0c, like ruby 2.6.6, GraalVM CE Native [x86_64-linux]

I'm getting a lot of errors running some cucumber tests 

    Translated to internal error (RuntimeError)
    <internal:core> core/truffle/string_operations.rb:30:in `block in gsub_block_set_last_match'
    <internal:core> core/truffle/string_operations.rb:37:in `block in gsub_internal_block'
    <internal:core> core/truffle/string_operations.rb:95:in `gsub_internal_core'
    <internal:core> core/truffle/string_operations.rb:36:in `gsub_internal_block'
    <internal:core> core/truffle/string_operations.rb:28:in `gsub_block_set_last_match'
    <internal:core> core/string.rb:985:in `gsub'

https://github.com/petenorth/schools-experience/runs/1052428382?check_suite_focus=true

The commit I think might have been

https://github.com/oracle/truffleruby/commit/5e415b5dc0c847e926296be2d97323458e83668e#diff-4035ef60e37503285875ded59cd61e1f

Other examples have

      undefined method `upcase' for nil:NilClass
      Did you mean?  case (NoMethodError). followed by the same stacktrace

**Comment by eregon** [comment]
Full stacktrace:
```
  Scenario: Page contents                                   # features/candidates/bookings/cancelling_a_booking.feature:9
    When I visit the bookings cancellation link             # features/step_definitions/candidates/bookings/cancelling_a_booking_steps.rb:6
						<no message> (NullPointerException)
							from org.truffleruby.language.threadlocal.FindThreadAndFrameLocalStorageNode.getStorageFromFrame(FindThreadAndFrameLocalStorageNode.java:148)
							from org.truffleruby.language.threadlocal.FindThreadAndFrameLocalStorageNode.access$000(FindThreadAndFrameLocalStorageNode.java:26)
							from org.truffleruby.language.threadlocal.FindThreadAndFrameLocalStorageNode$StorageInFrameFinder.getStorage(FindThreadAndFrameLocalStorageNode.java:68)
							from org.truffleruby.language.threadlocal.FindThreadAndFrameLocalStorageNode.getStorageCached(FindThreadAndFrameLocalStorageNode.java:41)
							from org.truffleruby.language.threadlocal.FindThreadAndFrameLocalStorageNodeGen.execute(FindThreadAndFrameLocalStorageNodeGen.java:34)
							from org.truffleruby.core.kernel.TruffleKernelNodes$GetFrameAndThreadLocalVariable.executeGetValue(TruffleKernelNodes.java:184)
							from org.truffleruby.core.kernel.TruffleKernelNodesFactory$GetFrameAndThreadLocalVariableFactory$GetFrameAndThreadLocalVariableNodeGen.execute(TruffleKernelNodesFactory.java:664)
							from org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:34)
							from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:62)
							from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:33)
							from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
							from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:42)
							from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
							from org.truffleruby.language.LazyRubyNode.execute(LazyRubyNode.java:47)
							from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:60)
							from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:515)
						Translated to internal error (RuntimeError)
						<internal:core> core/truffle/string_operations.rb:30:in `block in gsub_block_set_last_match'
						<internal:core> core/truffle/string_operations.rb:37:in `block in gsub_internal_block'
						<internal:core> core/truffle/string_operations.rb:95:in `gsub_internal_core'
						<internal:core> core/truffle/string_operations.rb:36:in `gsub_internal_block'
						<internal:core> core/truffle/string_operations.rb:28:in `gsub_block_set_last_match'
						<internal:core> core/string.rb:985:in `gsub'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:348:in `block in json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:344:in `each'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:344:in `json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:331:in `to_json'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:309:in `block in json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:301:in `each'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:301:in `json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:283:in `to_json'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:309:in `block in json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:301:in `each'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:301:in `json_transform'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:283:in `to_json'
						/truffleruby-head/lib/json/lib/json/pure/generator.rb:242:in `generate'
						/truffleruby-head/lib/json/lib/json/common.rb:224:in `generate'
						./features/step_definitions/candidates/bookings/cancelling_a_booking_steps.rb:7:in `"I visit the bookings cancellation link"'
						features/candidates/bookings/cancelling_a_booking.feature:10:in `When I visit the bookings cancellation link'
```

**Comment by eregon** [comment]
The NullPointerException seems to mean `frame` was `null` in `getStorageFromFrame()`.
So `frame` must have been `null` in `getStorage()`.
But that's only called if the `callerFrame` has the same FrameDescriptor. And I would think same FrameDescriptor implies same depth, but maybe not?

@petenorth This seems to happen during `JSON.generate`. It would be useful if we could see which arguments are passed to `JSON.generate`.

@aardvark179 Could you take a look?

**Comment by petenorth** [comment]
Possibly related to #2156

**Comment by petenorth** [comment]
Closing as this as these cucumber tests have run successfully with

`truffleruby 21.1.0-dev-63052049, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]`
