### ISSUE TITLE
Savon gem test failure: can't modify frozen String

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2096]
## To reproduce
Run tests from latest https://github.com/savonrb/savon

```
1) Savon::Builder#to_s defaults to include the default envelope namespace of :env
     Failure/Error: messages << "<#{message} xsi:type=\"#{type.join(':')}\">#{message_content}</#{message}>"
     
     FrozenError:
       can't modify frozen String
     # ./lib/savon/builder.rb:157:in `<<'
     # ./lib/savon/builder.rb:157:in `block in serialized_messages'
     # ./lib/savon/builder.rb:153:in `each_pair'
     # ./lib/savon/builder.rb:153:in `serialized_messages'
     # ./lib/savon/builder.rb:179:in `body_message'
     # ./lib/savon/builder.rb:231:in `block (3 levels) in build_xml'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `call'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
     # ./lib/savon/builder.rb:231:in `block (2 levels) in build_xml'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `call'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
     # ./lib/savon/builder.rb:218:in `tag'
     # ./lib/savon/builder.rb:227:in `block in build_xml'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `call'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
     # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
     # ./lib/savon/builder.rb:218:in `tag'
     # ./lib/savon/builder.rb:225:in `build_xml'
     # ./lib/savon/builder.rb:41:in `build_document'
     # ./lib/savon/builder.rb:74:in `to_s'
     # ./spec/savon/softlayer_spec.rb:25:in `block (3 levels) in <top (required)>'
```

**Comment by gogainda** [comment]
From my perspective it _must_ fail, bc message is [frozen](https://github.com/savonrb/savon/blob/master/lib/savon/builder.rb#L157) but it doesn't for MRI Rubies

**Comment by bjfish** [comment]
I see the same failures when I ran the savon `master` branch in travis: https://travis-ci.org/github/bjfish/savon/builds/726324416. Also I ran the specs with MRI 2.6.6 and saw this same failure locally.

@gogainda I agree with you, in this case `messages` should be something like `messages = +""` to make sure it is not frozen.
