### ISSUE TITLE
ColorLS: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2097]
```colorls --gs``` fails with:
```
<internal:core> core/truffle/process_operations.rb:470:in `block (2 levels) in posix_spawnp': undefined method `<' for nil:NilClass (NoMethodError)

	from <internal:core> core/truffle/process_operations.rb:469:in `map'

	from <internal:core> core/truffle/process_operations.rb:469:in `block in posix_spawnp'

	from <internal:core> core/truffle/process_operations.rb:466:in `each_pair'

	from <internal:core> core/truffle/process_operations.rb:466:in `posix_spawnp'

	from <internal:core> core/truffle/process_operations.rb:439:in `spawn'

	from <internal:core> core/truffle/process_operations.rb:110:in `spawn'

	from <internal:core> core/io.rb:853:in `popen'

	from /home/travis/build/athityakumar/colorls/lib/colorls/git.rb:55:in `git_prefix'

	from /home/travis/build/athityakumar/colorls/lib/colorls/git.rb:9:in `status'

	from /home/travis/build/athityakumar/colorls/lib/colorls/core.rb:226:in `process_git_status_details'

	from /home/travis/build/athityakumar/colorls/lib/colorls/core.rb:22:in `initialize'

	from /home/travis/build/athityakumar/colorls/lib/colorls/flags.rb:48:in `new'

	from /home/travis/build/athityakumar/colorls/lib/colorls/flags.rb:48:in `block in process'

	from <internal:core> core/enumerable.rb:339:in `each_with_index'

	from /home/travis/build/athityakumar/colorls/lib/colorls/flags.rb:43:in `process'

	from /home/travis/build/athityakumar/colorls/exe/colorls:26:in `<top (required)>'

	from <internal:core> core/kernel.rb:402:in `load'

	from <internal:core> core/kernel.rb:402:in `load'

	from /home/travis/build/athityakumar/colorls/bin/colorls:29:in `<main>'

The command "colorls --gs" exited with 1.
```
taken from [here](https://travis-ci.org/github/athityakumar/colorls/jobs/726242476#L841)

**Comment by avdv** [comment]
The code to trigger this is:
```
IO.popen(['ls'], :err => :close, &:gets)
```
`:close` seems to be converted to `nil` on purpose => https://github.com/oracle/truffleruby/blob/master/src/main/ruby/truffleruby/core/truffle/process_operations.rb#L295-L296 but later is not properly handled.

**Comment by chrisseaton** [comment]
Looks like a completely missing feature - it's not implemented at the bottom in `truffleposix_posix_spawnp` either.

**Comment by bjfish** [comment]
This is now fixed at: https://github.com/oracle/truffleruby/commit/f736b219e5f387b2558414e2c3a8e8e99122ccbd

It appears the :close option in this scenario was not handled previously.
