### ISSUE TITLE
dentaku gem test failure: undefined method `round' for nil:NilClass

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2107]
Full [logs](https://travis-ci.org/github/rubysolo/dentaku/builds/731734232)
```
 Dentaku::Calculator evaluates an expression

     Failure/Error: expect(calculator.evaluate('(((695759/735000)^(1/(1981-1991)))-1)*1000').round(4)).to eq(5.5018)

     

     NoMethodError:

       undefined method `round' for nil:NilClass

     # ./spec/calculator_spec.rb:32:in `block (2 levels) in <top (required)>'
```

**Comment by eregon** [comment]
With dentaku 3.3.4,
```
$ ruby -rdentaku -e "calculator = Dentaku::Calculator.new; p calculator.evaluate('(((695759/735000)^(1/(1981-1991)))-1)*1000').round(4)"
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:34:in `**': TruffleRuby doesn't have a case for the org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen node with values of type BigDecimal(org.truffleruby.stdlib.bigdecimal.RubyBigDecimal) BigDecimal(org.truffleruby.stdlib.bigdecimal.RubyBigDecimal) org.truffleruby.language.NotProvided (TypeError)
	from org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen.executeAndSpecialize(BigDecimalNodesFactory.java:2469)
	from org.truffleruby.stdlib.bigdecimal.BigDecimalNodesFactory$PowerNodeFactory$PowerNodeGen.execute(BigDecimalNodesFactory.java:2411)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:41)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:63)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:538)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:34:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:32:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:120:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:32:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:67:in `block in evaluate!'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:132:in `store'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:59:in `evaluate!'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:49:in `evaluate'
	from -e:1:in `<main>'
```

So it seems BigDecimal#** does not support a BigDecimal exponent yet.

If we try using the `bigdecimal` C extension gem (`gem i bigdecimal`), then:
```
ruby -rdentaku -e "calculator = Dentaku::Calculator.new; p calculator.evaluate('(((695759/735000)^(1/(1981-1991)))-1)*1000').round(4)"
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:4531:in `VpAddSub': Missing LLVM builtin: llvm.usub.sat.i32 (IllegalStateException) (RuntimeError)
	from com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.x86.LLVMX86_MissingBuiltin.doMissing(LLVMX86_MissingBuiltin.java:50)
	from com.oracle.truffle.llvm.runtime.nodes.intrinsics.llvm.x86.LLVMX86_MissingBuiltinNodeGen.executeGeneric(LLVMX86_MissingBuiltinNodeGen.java:41)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMExpressionNode.executeI32(LLVMExpressionNode.java:86)
	from com.oracle.truffle.llvm.runtime.nodes.api.LLVMFrameNullerExpression.executeI32(LLVMFrameNullerExpression.java:117)
	from com.oracle.truffle.llvm.runtime.nodes.vars.LLVMWriteNodeFactory$LLVMWriteI32NodeGen.execute(LLVMWriteNodeFactory.java:359)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNode$InitializedBlock.doBlock(LLVMBasicBlockNode.java:176)
	from com.oracle.truffle.llvm.runtime.nodes.base.LLVMBasicBlockNodeFactory$InitializedBlockNodeGen.execute(LLVMBasicBlockNodeFactory.java:48)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNode.doDispatch(LLVMDispatchBasicBlockNode.java:97)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMDispatchBasicBlockNodeGen.executeGeneric(LLVMDispatchBasicBlockNodeGen.java:44)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNode.doRun(LLVMFunctionRootNode.java:85)
	from com.oracle.truffle.llvm.runtime.nodes.control.LLVMFunctionRootNodeGen.executeGeneric(LLVMFunctionRootNodeGen.java:45)
	from com.oracle.truffle.llvm.runtime.nodes.func.LLVMFunctionStartNode.execute(LLVMFunctionStartNode.java:88)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:538)
Translated to internal error
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:1044:in `BigDecimal_sub'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:3178:in `BigMath_s_log'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:2305:in `rmpd_power_by_big_decimal'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:2488:in `BigDecimal_power'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bigdecimal-2.0.0/ext/bigdecimal/bigdecimal.c:2562:in `BigDecimal_power_op'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `**'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:34:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:32:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:120:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/ast/arithmetic.rb:32:in `value'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:67:in `block in evaluate!'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:132:in `store'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:59:in `evaluate!'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/dentaku-3.3.4/lib/dentaku/calculator.rb:49:in `evaluate'
	from -e:1:in `<main>'
```

Which @aardvark179 is working on fixing.

**Comment by eregon** [comment]
With the fix by @aardvark179 to implement `llvm.usub.sat.i32`, it works with the bigdecimal gem:
```
$ gem i bigdecimal
$ ruby -rdentaku -e "calculator = Dentaku::Calculator.new; p calculator.evaluate('(((695759/735000)^(1/(1981-1991)))-1)*1000').round(4)"
0.55018e1
```

So maybe we should just use the bigdecimal gem C extension by default (#1975).

**Comment by bjfish** [comment]
The bigdecimal C extension is now used and this is fixed at: https://github.com/oracle/truffleruby/commit/aa11d31adb031302a3b9e04d95c0376858c86b72
