### ISSUE TITLE
danger gem test failure: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2118]
To reproduce:
```
git clone git@github.com:danger/danger.git  
cd danger
bundle install
bundle exec rake spec
```

```
 1) Danger::LocalGitRepo#new repo_logs with a non UTF-8 character encodes the string correctly
     Failure/Error: `git commit -m "#{invalid_encoded_string}"`
     
     ArgumentError:
       invalid byte sequence in UTF-8
     # <internal:core> core/truffle/regexp_operations.rb:16:in `search_region'
     # <internal:core> core/truffle/regexp_operations.rb:47:in `match'
     # <internal:core> core/regexp.rb:170:in `match?'
     # <internal:core> core/string.rb:1027:in `match?'
     # <internal:core> core/truffle/process_operations.rb:546:in `should_use_shell?'
     # <internal:core> core/truffle/process_operations.rb:176:in `parse'
     # <internal:core> core/truffle/process_operations.rb:108:in `spawn'
     # <internal:core> core/io.rb:853:in `popen'
     # <internal:core> core/kernel.rb:178:in ``'
     # ./spec/lib/danger/ci_sources/local_git_repo_spec.rb:91:in `block (6 levels) in <top (required)>'
     # ./spec/lib/danger/ci_sources/local_git_repo_spec.rb:28:in `block (2 levels) in run_in_repo'
     # <internal:core> core/dir.rb:310:in `chdir'
     # ./spec/lib/danger/ci_sources/local_git_repo_spec.rb:8:in `block in run_in_repo'
     # /Users/novoi/.rubies/truffleruby-dev/lib/mri/tmpdir.rb:93:in `mktmpdir'
     # ./spec/lib/danger/ci_sources/local_git_repo_spec.rb:7:in `run_in_repo'
     # ./spec/lib/danger/ci_sources/local_git_repo_spec.rb:88:in `block (5 levels) in <top (required)>'
```

**Comment by bjfish** [comment]
A small case to reproduce this:
```
% jt ruby -e 'a = "testing\xC2 a non UTF-8 string";puts `echo "#{a}"`'
<internal:core> core/truffle/regexp_operations.rb:16:in `search_region': invalid byte sequence in UTF-8 (ArgumentError)
	from <internal:core> core/truffle/regexp_operations.rb:47:in `match'
	from <internal:core> core/regexp.rb:170:in `match?'
	from <internal:core> core/string.rb:1027:in `match?'
	from <internal:core> core/truffle/process_operations.rb:546:in `should_use_shell?'
	from <internal:core> core/truffle/process_operations.rb:176:in `parse'
	from <internal:core> core/truffle/process_operations.rb:108:in `spawn'
	from <internal:core> core/io.rb:853:in `popen'
	from <internal:core> core/kernel.rb:178:in ``'
	from -e:1:in `<main>'
```
Expected:
```
% ruby -e 'a = "testing\xC2 a non UTF-8 string";puts `echo "#{a}"`'   
testing? a non UTF-8 string
```

**Comment by eregon** [comment]
Maybe the Regexp `/n` flag works here for `#should_use_shell?`

**Comment by bjfish** [comment]
This is fixed at: https://github.com/oracle/truffleruby/commit/4460362c343bee840cbefddc0d9dd8f7eb39c7df
