### ISSUE TITLE
diff-lcs gem test suit fails on truffleruby-head 

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2119]
it doesn't happen on truffleruby
https://github.com/halostatue/diff-lcs/runs/1183738413

**Comment by eregon** [comment]
```
<internal:core> core/truffle/feature_loader.rb:282:in `block in get_expanded_load_path': TruffleRuby doesn't have a case for the org.truffleruby.core.kernel.KernelNodesFactory$CanonicalizePathNodeFactory$CanonicalizePathNodeGen node with values of type Pathname(org.truffleruby.core.basicobject.RubyBasicObject) (TypeError)
	from org.truffleruby.core.kernel.KernelNodesFactory$CanonicalizePathNodeFactory$CanonicalizePathNodeGen.executeAndSpecialize(KernelNodesFactory.java:1099)
	from org.truffleruby.core.kernel.KernelNodesFactory$CanonicalizePathNodeFactory$CanonicalizePathNodeGen.execute(KernelNodesFactory.java:1082)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.methods.CatchForProcNode.execute(CatchForProcNode.java:38)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:63)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:520)
	from <internal:core> core/truffle/feature_loader.rb:282:in `map'
	from <internal:core> core/truffle/feature_loader.rb:282:in `get_expanded_load_path'
	from /home/runner/work/diff-lcs/diff-lcs/vendor/bundle/truffleruby/20.3.0-dev-dc6b6199/gems/rspec-core-3.9.2/lib/rspec/core/formatters.rb:182:in `built_in_formatter'
```

Looks like we're missing a `coerce_to_path` to convert the argument to a String, will fix.

**Comment by gogainda** [comment]
btw I notice this issue by looking into https://github.com/eregon/truffleruby-gem-tracker build status

**Comment by eregon** [comment]
Thanks, the issue is helpful, I didn't have time to look at it much this week.
