### ISSUE TITLE
json-schema test failure: InvalidAddressError

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2123]
Example: 
```
1) Error:
Draft1Test#test_format_ipv6:
IPAddr::InvalidAddressError: invalid address: 1111:2222:8888:99999:aaaa:cccc:eeee:ffff
    /Users/novoi/.rubies/truffleruby-dev/lib/mri/ipaddr.rb:598:in `initialize'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/formats/ip.rb:12:in `new'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/formats/ip.rb:12:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/format.rb:10:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:25:in `block in validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:23:in `each'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:23:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema.rb:33:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/properties_optional.rb:20:in `block in validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/properties_optional.rb:10:in `each'
    /Users/novoi/tmp/json-schema/lib/json-schema/attributes/properties_optional.rb:10:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:25:in `block in validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:23:in `each'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema/validator.rb:23:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/schema.rb:33:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/validator.rb:115:in `validate'
    /Users/novoi/tmp/json-schema/lib/json-schema/validator.rb:256:in `validate!'
    /Users/novoi/tmp/json-schema/lib/json-schema/validator.rb:273:in `fully_validate'
    /Users/novoi/tmp/json-schema/test/support/test_helper.rb:49:in `validation_errors'
    /Users/novoi/tmp/json-schema/test/draft1_test.rb:5:in `validation_errors'
    /Users/novoi/tmp/json-schema/test/support/test_helper.rb:43:in `refute_valid'
    /Users/novoi/tmp/json-schema/test/support/string_validation.rb:107:in `test_format_ipv6'
```
To reproduce: 
```
git clone git@github.com:ruby-json-schema/json-schema.git 
cd json-shcema
bundle install
bundle exec rake
```

**Comment by bjfish** [comment]
@gogainda I see this and other failures when I run the tests with `MRI 2.6.6`. It appears the current build matrix does not include 2.6.6: https://github.com/ruby-json-schema/json-schema/blob/765e6d8fdbfdaca1a42fa743f4621e757f9f6a03/.travis.yml

Both TruffleRuby and MRI 2.6.6 appear to result in `363 runs, 1543 assertions, 0 failures, 9 errors, 0 skips`.

**Comment by gogainda** [comment]
@bjfish so i guess it's not an issue of Truffleruby, so we can close it
