### ISSUE TITLE
Error in openssl 2 store verify

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2124]
Example: 
```
1) WebAuthn::AttestationStatement::AndroidSafetynet#valid? when the attestation certificate is not signed by Google fails

     Failure/Error:

       attestation_response

         .verify(nonce, trusted_certificates: root_certificates(aaguid: authenticator_data.aaguid), time: time)

     

     RuntimeError:

       Polyglot object 0x16 cannot be converted to i32 (LLVMPolyglotException)

       Translated to internal error

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:994:in `execute_without_conversion'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:994:in `block in rb_protect'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:993:in `capture_exception'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext.rb:993:in `rb_protect'

     # exception.c:32:in `rb_protect'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/openssl-2.0.9/ext/openssl/ossl.c:106:in `ossl_buf2str'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/openssl-2.0.9/ext/openssl/ossl_x509name.c:247:in `ossl_x509name_to_s_old'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/openssl-2.0.9/ext/openssl/ossl_x509name.c:287:in `ossl_x509name_to_s'

     # /home/travis/.rvm/rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `to_s'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/safety_net_attestation-0.4.0/lib/safety_net_attestation/x5c_key_finder.rb:22:in `from'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/safety_net_attestation-0.4.0/lib/safety_net_attestation/statement.rb:34:in `block in verify'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/jwt-2.2.2/lib/jwt/decode.rb:65:in `find_key'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/jwt-2.2.2/lib/jwt/decode.rb:39:in `verify_signature'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/jwt-2.2.2/lib/jwt/decode.rb:26:in `decode_segments'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/jwt-2.2.2/lib/jwt.rb:28:in `decode'

     # ./gemfiles/vendor/bundle/truffleruby/20.3.0-dev-c2f5cc7a/gems/safety_net_attestation-0.4.0/lib/safety_net_attestation/statement.rb:29:in `verify'

     # ./lib/webauthn/attestation_statement/android_safetynet.rb:29:in `valid_response?'

     # ./lib/webauthn/attestation_statement/android_safetynet.rb:12:in `valid?'

     # ./spec/webauthn/attestation_statement/android_safetynet_spec.rb:87:in `block (4 levels) in <top (required)>'

     # ./spec/webauthn/attestation_statement/android_safetynet_spec.rb:56:in `block (4 levels) in <top (required)>'

     # ./spec/spec_helper.rb:88:in `silence_warnings'

     # ./spec/webauthn/attestation_statement/android_safetynet_spec.rb:53:in `block (3 levels) in <top (required)>'
```
from [here](https://travis-ci.org/github/cedarcode/webauthn-ruby/jobs/736339202)

**Comment by bjfish** [comment]
The gemfile `openssl_2_0.gemfile` appears to no longer be tested.  I did run the tests for this and saw two failing examples:
```
rspec ./spec/webauthn/attestation_statement/packed_spec.rb:254 # Packed attestation #valid? x5c attestation when the certificate chain is invalid because a cert has expired fails
rspec ./spec/webauthn/attestation_statement/packed_spec.rb:245 # Packed attestation #valid? x5c attestation when the certificate chain is invalid because a cert hasn't yet started fails
```


I've written a spec which I think recreates the issue (third example):
```
require_relative '../../../../spec_helper'
require 'openssl'

describe "OpenSSL::X509::Name.verify" do
  it "returns true for valid certificate" do
    key = OpenSSL::PKey::RSA.new 2048
    cert = OpenSSL::X509::Certificate.new
    cert.version = 2
    cert.serial = 1
    cert.subject = OpenSSL::X509::Name.parse "/DC=org/DC=truffleruby/CN=TruffleRuby CA"
    cert.issuer = cert.subject
    cert.public_key = key.public_key
    cert.not_before = Time.now
    cert.not_after = cert.not_before + 365 * 24 * 60 * 60
    cert.sign key, OpenSSL::Digest::SHA1.new
    store = OpenSSL::X509::Store.new
    store.add_cert(cert)
    store.verify(cert).should == true
  end

  it "returns false for an expired certificate" do
    key = OpenSSL::PKey::RSA.new 2048
    cert = OpenSSL::X509::Certificate.new
    cert.version = 2
    cert.serial = 1
    cert.subject = OpenSSL::X509::Name.parse "/DC=org/DC=truffleruby/CN=TruffleRuby CA"
    cert.issuer = cert.subject
    cert.public_key = key.public_key
    cert.not_before = Time.now - 10
    cert.not_after = Time.now - 5
    cert.sign key, OpenSSL::Digest::SHA1.new
    store = OpenSSL::X509::Store.new
    store.add_cert(cert)
    store.verify(cert).should == false
  end

  it "returns false for an expired root certificate" do
    root_key = OpenSSL::PKey::RSA.new 2048
    root_cert = OpenSSL::X509::Certificate.new
    root_cert.version = 2
    root_cert.serial = 1
    root_cert.subject = OpenSSL::X509::Name.parse "/DC=org/DC=truffleruby/CN=TruffleRuby CA"
    root_cert.issuer = root_cert.subject
    root_cert.public_key = root_key.public_key
    root_cert.not_before = Time.now - 10
    root_cert.not_after = Time.now - 5

    ef = OpenSSL::X509::ExtensionFactory.new
    ef.subject_certificate = root_cert
    ef.issuer_certificate = root_cert
    root_cert.add_extension(ef.create_extension("basicConstraints","CA:TRUE",true))
    root_cert.add_extension(ef.create_extension("keyUsage","keyCertSign, cRLSign", true))
    root_cert.add_extension(ef.create_extension("subjectKeyIdentifier","hash",false))
    root_cert.add_extension(ef.create_extension("authorityKeyIdentifier","keyid:always",false))
    root_cert.sign(root_key, OpenSSL::Digest::SHA256.new)

    store = OpenSSL::X509::Store.new
    store.add_cert(root_cert)

    key = OpenSSL::PKey::RSA.new 2048
    cert = OpenSSL::X509::Certificate.new
    cert.version = 2
    cert.serial = 1
    cert.subject = OpenSSL::X509::Name.parse "/DC=org/DC=truffleruby/CN=TruffleRuby CA"
    cert.issuer =  root_cert.subject
    cert.public_key = key.public_key
    cert.not_before = Time.now
    cert.not_after = cert.not_before + 365 * 24 * 60 * 60
    ef = OpenSSL::X509::ExtensionFactory.new
    ef.subject_certificate = cert
    ef.issuer_certificate = root_cert
    cert.add_extension(ef.create_extension("keyUsage","digitalSignature", true))
    cert.add_extension(ef.create_extension("subjectKeyIdentifier","hash",false))
    cert.sign(root_key, OpenSSL::Digest::SHA256.new)

    store.add_cert(cert)
    store.verify(cert).should == false
  end
end
```

**Comment by eregon** [comment]
@gogainda The CI seems to pass on TruffleRuby in https://github.com/cedarcode/webauthn-ruby/pull/334, so I guess we can close this?

**Comment by gogainda** [comment]
@eregon yes we can close it.  It's passing because openssl 2.0 is not part of a test suit anymore

**Comment by eregon** [comment]
Actually I renamed the issue to track what @bjfish found in https://github.com/oracle/truffleruby/issues/2124#issuecomment-715489148, that still seems an issue (just not blocking webauthn-ruby anymore).

**Comment by eregon** [comment]
@bjfish Could you commit this spec and add tags for it?

**Comment by bjfish** [comment]
@eregon I've committed the spec above. It appears the third example had `CN=TruffleRuby CA` repeated as the subject. The behavior appears correct on TruffleRuby and no tags were necessary.

**Comment by eregon** [comment]
I think we can close this then, the issue has probably been fixed in Sulong, and it's for an older openssl gem release.
