### ISSUE TITLE
ruby-git test failure: undefined method `ord' for nil:NilClass

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2133]
Exception:
```
...........................#<Thread:0xa3b8@/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1024 run> terminated with exception:
Traceback (most recent call last):
	from /Users/novoi/tmp/ruby-git/lib/git/lib.rb:1025:in `block (2 levels) in command'
	from /Users/novoi/tmp/ruby-git/lib/git/lib.rb:1124:in `run_command'
	from <internal:core> core/string.rb:113:in `chomp'
<internal:core> core/string.rb:847:in `chomp!': undefined method `ord' for nil:NilClass (NoMethodError)
E
========================================================================================================================
/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1025:in `block (2 levels) in command'
/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1124:in `run_command'
<internal:core> core/string.rb:113:in `chomp'
<internal:core> core/string.rb:847:in `chomp!'
Error: test_diff_with_greek_encoding(TestDiffWithNonDefaultEncoding): NoMethodError: undefined method `ord' for nil:NilClass
========================================================================================================================
#<Thread:0xa438@/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1024 run> terminated with exception:
Traceback (most recent call last):
	from /Users/novoi/tmp/ruby-git/lib/git/lib.rb:1025:in `block (2 levels) in command'
	from /Users/novoi/tmp/ruby-git/lib/git/lib.rb:1124:in `run_command'
	from <internal:core> core/string.rb:113:in `chomp'
<internal:core> core/string.rb:847:in `chomp!': undefined method `ord' for nil:NilClass (NoMethodError)
E
========================================================================================================================
/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1025:in `block (2 levels) in command'
/Users/novoi/tmp/ruby-git/lib/git/lib.rb:1124:in `run_command'
<internal:core> core/string.rb:113:in `chomp'
<internal:core> core/string.rb:847:in `chomp!'
Error: test_diff_with_japanese_and_korean_encoding(TestDiffWithNonDefaultEncoding): NoMethodError: undefined method `ord' for nil:NilClass
========================================================================================================================
..................................................................................................
```

Hot to reproduce: 
```
git clone git@github.com:ruby-git/ruby-git.git
cd ruby-git
bundle install
bundle exec rake
```

**Comment by eregon** [comment]
It sounds like some bug in the `String#chomp!` logic, or some concurrent mutation of that String.

**Comment by eregon** [comment]
@bjfish Could you look into this?

**Comment by bjfish** [comment]
A minimal example to reproduce this:
```
a = "diff --git a/test1.txt b/test1.txt\nindex cf92142..95a9ae9 100644\n--- a/test1.txt\n+++ b/test1.txt\n@@ -1,4 +1,4 @@\n \xCB\xEF\xF1\xE5\xEC \xE9\xF0\xF3\xE8\xEC \xE4\xEF\xEB\xEF\xF1 \xF3\xE9\xF4\n-\xD6\xE8\xE3\xE7\xF4 \xEF\xF0\xEF\xF1\xF4\xE5\xF1\xE5 \xE9\xED \xE9\xE4\xE5\xF1\xE9\xED\xF4\n \xC7\xE9\xF3 \xE5\xEE \xF4\xEF\xF4\xE1 \xF3\xE8\xE1v\xE9\xF4\xE1\xF4\xE5\n \xCD\xEF \xE8\xF1\xE2\xE1\xED\xE9\xF4\xE1\xF3\n+\xD6\xE5\xE8\xE3\xE9\xE1\xF4 \xE8\xF1\xE2\xE1\xED\xE9\xF4\xE1\xF3 \xF1\xE5\xF0\xF1\xE9\xEC\xE9q\xE8\xE5\ndiff --git a/test2.txt b/test2.txt\nindex 87d9aa8..210763e 100644\n--- a/test2.txt\n+++ b/test2.txt\n@@ -1,3 +1,3 @@\n-\xB0㤤\xA4\xF2\xC0\xB8\xA4߽Ф\xB9\xA5\xB5\xA5\xF3\xA5ץ\xEB\xA5ƥ\xAD\xA5\xB9\xA5\xC8\n-\xA4\xB3\xA4\xEC\xA4\xCF1\xB9\xD4\xCCܤǤ\xB9\n-\xA4\xB3\xA4줬\xBAǸ\xE5\xA4ιԤǤ\xB9\n+\xC0̰\xCD\xC0\xBA \xC6\xC4\xC0\xCF\xC0̴\xD9\n+\xC0̰\xCD\xC0\xBA \xB5\xCE \xB9\xF8° \xC1\xD9\xC0Դϴ\xD9\n+\xC0̰\xCD\xC0\xCC \xB8\xB6\xC1\xF6\xB8\xB7 \xC1\xD9\xC0Դϴ\xD9\n"
p a.chomp
```

**Comment by bjfish** [comment]
This is now fixed at https://github.com/oracle/truffleruby/commit/e10f084a14c08ff4b7ba7e4a9089e27e6af2a39d.
