### ISSUE TITLE
ruby-git test failure: test_archive.rb:40

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2140]
```
F
========================================================================================================================
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'
     37:     assert(File.file?(f))
     38: 
     39:     f = @git.object('v2.6').archive(tempfile, :format => 'tgz', :prefix => 'test/')
  => 40:     assert(File.exist?(f))
     41: 
     42:     lines = Minitar::Input.open(Zlib::GzipReader.new(File.open(f, 'rb'))).each.to_a.map(&:full_name)
     43:     assert_match(%r{test/}, lines[1])
/Users/novoi/tmp/ruby-git/tests/units/test_archive.rb:40:in `test_archive'
Failure: test_archive(TestArchive): <false> is not true.
```
To reproduce:
```
git clone git@github.com:ruby-git/ruby-git.git
cd ruby-git
bundle install
bundle exec rake
```

ruby mri 2.6.6 works fine

**Comment by bjfish** [comment]
I have been unable to reproduce this error on the latest build. @gogainda can you still reproduce this error?

**Comment by gogainda** [comment]
@bjfish it works for me as well now, thanks for checking
