### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2159]
latest grape gem fails in multiple places with the same error : 
```
Failures:

  1) Grape::Middleware::Auth::Strategies Digest MD5 Auth authenticates if given valid creds
     [31mFailure/Error: builder.to_app[0m
     [31m[0m
     [31mArgumentError:[0m
     [31m  wrong number of arguments (given 2, expected 1)[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/head.rb:7:in `initialize'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/builder.rb:158:in `new'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/builder.rb:158:in `block in use'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/builder.rb:235:in `[]'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/builder.rb:235:in `block in to_app'[0m
     [36m# <internal:core> core/enumerable.rb:465:in `inject'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-2.2.3/lib/rack/builder.rb:235:in `to_app'[0m
     [36m# ./lib/grape/endpoint.rb:323:in `build_stack'[0m
     [36m# ./lib/grape/endpoint.rb:355:in `block in lazy_initialize!'[0m
     [36m# ./lib/grape/endpoint.rb:351:in `synchronize'[0m
     [36m# ./lib/grape/endpoint.rb:351:in `lazy_initialize!'[0m
     [36m# ./lib/grape/endpoint.rb:224:in `call'[0m
     [36m# ./lib/grape/router/route.rb:58:in `exec'[0m
     [36m# ./lib/grape/router.rb:116:in `process_route'[0m
     [36m# ./lib/grape/router.rb:72:in `block in identity'[0m
     [36m# ./lib/grape/router.rb:91:in `transaction'[0m
     [36m# ./lib/grape/router.rb:70:in `identity'[0m
     [36m# ./lib/grape/router.rb:55:in `block in call'[0m
     [36m# ./lib/grape/router.rb:132:in `with_optimization'[0m
     [36m# ./lib/grape/router.rb:54:in `call'[0m
     [36m# ./lib/grape/api/instance.rb:167:in `call'[0m
     [36m# ./lib/grape/api/instance.rb:71:in `call!'[0m
     [36m# ./lib/grape/api/instance.rb:66:in `call'[0m
     [36m# ./lib/grape/api.rb:68:in `call'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'[0m
     [36m# /home/travis/.rvm/gems/truffleruby-head/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'[0m
     [36m# /home/travis/.rvm/rubies/truffleruby-head/lib/mri/forwardable.rb:235:in `get'[0m
     [36m# ./spec/grape/middleware/auth/strategies_spec.rb:72:in `block (3 levels) in <top (required)>'[0m
```
full logs could be found [here](https://travis-ci.org/github/ruby-grape/grape/jobs/743741776)

**Comment by eregon** [comment]
@gogainda Thanks for the report.
I'm not sure what you use to copy-paste, but it seems to introduce an extra blank line which is rather noisy. Could you try to fix for new bug reports?

This seems to likely be an extra empty Hash passed to `initialize`, so probably we need the 2.7 semantics of `**hash` passing nothing to fix this + handling `ruby2_keywords`.
https://github.com/rack/rack/blob/1d70c73043e8fd41bf204ff794730aed2620d7a4/lib/rack/builder.rb#L148-L150

**Comment by eregon** [comment]
I'd guess this code causes this: https://github.com/ruby-grape/grape/blob/42489c243c78761238093c40f5af2b2bb9a05580/lib/grape/middleware/stack.rb#L35-L45
It uses `*args, **opts`-delegation, which is not correct in some cases on 2.7.
It should use `ruby2_keywords` instead.

**Comment by eregon** [comment]
Failures fixed by https://github.com/ruby-grape/grape/pull/2132 upstream.

For the remaining keyword arguments changes for 2.7, they are tracked in https://github.com/oracle/truffleruby/issues/2004.
