### ISSUE TITLE
commonmarker test failure: Member 'dfree' not found.

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2165]
```
1) Error:
TestDocNode#test_prepend_child:
RuntimeError: Member 'dfree' not found. (com.oracle.truffle.llvm.runtime.except.LLVMPolyglotException)
Translated to internal error
    /Users/novoi/tmp/commonmarker/ext/commonmarker/commonmarker.c:105:in `rb_parent_added'
    /Users/novoi/tmp/commonmarker/ext/commonmarker/commonmarker.c:667:in `rb_node_prepend_child'
    /Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `prepend_child'
    /Users/novoi/tmp/commonmarker/test/test_doc.rb:49:in `test_prepend_child'
```

https://github.com/gjtorikian/commonmarker/

It doesn't happen to MRI Ruby 2.6.6

**Comment by eregon** [comment]
Closing in favor of https://github.com/oracle/truffleruby/issues/2732 which has more details.
