### ISSUE TITLE
Why can't jt run rubocop?

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2188]
Is anyone able to figure out what I'm doing wrong here?

```
% gem install rubocop -v 0.66.0 
....
8 gems installed
% dev jt lint                   
$ rubocop _0.66.0_ lib/cext lib/truffle src/main/ruby/truffleruby src/test/ruby tool/docker.rb tool/jt.rb spec/truffle
Traceback (most recent call last):
	2: from /Users/chrisseaton/.gem/ruby/2.7.2/bin/rubocop:23:in `<main>'
	1: from /Users/chrisseaton/.rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
/Users/chrisseaton/.rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': can't find gem rubocop (= 0.66.0) with executable rubocop (Gem::GemNotFoundException)
FAILED (pid 41072 exit 1): rubocop _0.66.0_ lib/cext lib/truffle src/main/ruby/truffleruby src/test/ruby tool/docker.rb tool/jt.rb spec/truffle
% find ~/.gem | grep bin/rubocop
/Users/chrisseaton/.gem/ruby/2.7.2/bin/rubocop
```

**Comment by eregon** [comment]
What's `dev ruby -v` and `dev gem info rubocop`?
Maybe you need `dev gem install rubocop -v 0.66.0`? (I have no idea what `dev` does).

**Comment by chrisseaton** [comment]
I was rewriting this without using `dev`... and the problem went away. Sorry looks like an internal Shopify issue I'll figure it out.
