### ISSUE TITLE
Doorkeeper gem test failure: rb_exc_raise

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2231]
Haven't seen it before, I guess it's a new bug

```
Doorkeeper::OAuth::PasswordAccessTokenRequest with scopes when scopes_by_grant_type is configured for grant_type creates the token with scopes if scopes are valid and permitted for grant_type
       Failure/Error:
         expect do
           request.authorize
         end.to change { Doorkeeper::AccessToken.count }.by(1)
       
       ActiveRecord::StatementInvalid:
         SQLite3::SQLException: no such table: oauth_access_tokens
       # /Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1050:in `rb_exc_raise'
       # exception.c:28:in `rb_exc_raise'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/sqlite3-1.4.2/ext/sqlite3/exception.c:97:in `rb_sqlite3_raise'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/sqlite3-1.4.2/ext/sqlite3/statement.c:62:in `initialize'
       # /Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:50:in `block (2 levels) in exec_query'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:47:in `block in exec_query'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:697:in `block (2 levels) in log'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
       # <internal:core> core/thread.rb:91:in `handle_interrupt'
       # <internal:core> core/thread.rb:91:in `handle_interrupt'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
       # <internal:core> core/thread.rb:91:in `handle_interrupt'
       # <internal:core> core/thread.rb:91:in `handle_interrupt'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block in log'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activesupport-6.1.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract_adapter.rb:688:in `log'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/sqlite3/database_statements.rb:46:in `exec_query'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:308:in `block in execute_simple_calculation'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation.rb:868:in `skip_query_cache_if_necessary'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:308:in `execute_simple_calculation'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:269:in `perform_calculation'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:144:in `calculate'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/relation/calculations.rb:51:in `count'
       # /Users/novoi/.rubies/truffleruby-dev/lib/gems/gems/activerecord-6.1.1/lib/active_record/querying.rb:22:in `count'
       # ./spec/lib/oauth/password_access_token_request_spec.rb:170:in `block (5 levels) in <top (required)>'
       # ./spec/lib/oauth/password_access_token_request_spec.rb:168:in `block (4 levels) in <top (required)>'
       # ------------------
       # --- Caused by: ---
       # SQLite3::SQLException:
       #   no such table: oauth_access_tokens
       #   /Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1050:in `rb_exc_raise'
```

**Comment by eregon** [comment]
Does it work on CRuby? Maybe there is some setup before running those specs.

**Comment by gogainda** [comment]
it works for me with CRuby, started a job here https://travis-ci.org/github/doorkeeper-gem/doorkeeper/builds/755542985 to make sure that it's not related to my env

**Comment by gogainda** [comment]
Similar issue:
```
F

Failure:
AuthenticationWithScopedViewsTest#test_renders_the_scoped_view_if_turned_on_in_a_specific_controller [/home/runner/work/devise/devise/test/integration/authenticatable_test.rb:391]:
[Webrat::NotFoundError] exception expected, not
Class: <ActiveRecord::StatementInvalid>
Message: <"ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: users">
---Backtrace---
/home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1058:in `rb_exc_raise'
exception.c:28:in `rb_exc_raise'
sqlite3 (1.4.2) ext/sqlite3/exception.c:97:in `rb_sqlite3_raise'
sqlite3 (1.4.2) ext/sqlite3/statement.c:62:in `initialize'
/home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:39:in `initialize'
sqlite3 (1.4.2) lib/sqlite3/database.rb:147:in `prepare'
activerecord (6.1.1) lib/active_record/connection_adapters/sqlite3/database_statements.rb:50:in `block (2 levels) in exec_query'
activesupport (6.1.1) lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
activesupport (6.1.1) lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
activesupport (6.1.1) lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
activerecord (6.1.1) lib/active_record/connection_adapters/sqlite3/database_statements.rb:47:in `block in exec_query'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract_adapter.rb:697:in `block (2 levels) in log'
activesupport (6.1.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
<internal:core> core/thread.rb:94:in `handle_interrupt'
<internal:core> core/thread.rb:94:in `handle_interrupt'
activesupport (6.1.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
<internal:core> core/thread.rb:94:in `handle_interrupt'
<internal:core> core/thread.rb:94:in `handle_interrupt'
activesupport (6.1.1) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block in log'
activesupport (6.1.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract_adapter.rb:688:in `log'
activerecord (6.1.1) lib/active_record/connection_adapters/sqlite3/database_statements.rb:46:in `exec_query'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'
activerecord (6.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:95:in `select_rows'
activerecord (6.1.1) lib/active_record/relation/finder_methods.rb:320:in `block in exists?'
activerecord (6.1.1) lib/active_record/relation.rb:868:in `skip_query_cache_if_necessary'
activerecord (6.1.1) lib/active_record/relation/finder_methods.rb:320:in `exists?'
activerecord (6.1.1) lib/active_record/validations/uniqueness.rb:43:in `validate_each'
activemodel (6.1.1) lib/active_model/validator.rb:153:in `block in validate'
activemodel (6.1.1) lib/active_model/validator.rb:149:in `each'
activemodel (6.1.1) lib/active_model/validator.rb:149:in `validate'
activesupport (6.1.1) lib/active_support/callbacks.rb:427:in `block in make_lambda'
activesupport (6.1.1) lib/active_support/callbacks.rb:179:in `call'
minitest (5.14.3) lib/minitest/test.rb:211:in `with_info_handler'
minitest (5.14.3) lib/minitest/test.rb:93:in `run'
minitest (5.14.3) lib/minitest.rb:1029:in `run_one_method'
minitest (5.14.3) lib/minitest.rb:341:in `run_one_method'
minitest (5.14.3) lib/minitest.rb:328:in `block (2 levels) in run'
minitest (5.14.3) lib/minitest.rb:327:in `each'
minitest (5.14.3) lib/minitest.rb:327:in `block in run'
minitest (5.14.3) lib/minitest.rb:367:in `on_signal'
minitest (5.14.3) lib/minitest.rb:354:in `with_info_handler'
minitest (5.14.3) lib/minitest.rb:326:in `run'
railties (6.1.1) lib/rails/test_unit/line_filtering.rb:10:in `run'
minitest (5.14.3) lib/minitest.rb:164:in `block in __run'
minitest (5.14.3) lib/minitest.rb:164:in `map'
minitest (5.14.3) lib/minitest.rb:164:in `__run'
minitest (5.14.3) lib/minitest.rb:141:in `run'
minitest (5.14.3) lib/minitest.rb:68:in `block in autorun'
---------------

rails test /home/runner/work/devise/devise/test/integration/authenticatable_test.rb:388
```
from https://github.com/heartcombo/devise/pull/5341/checks?check_run_id=1818731436

**Comment by gogainda** [comment]
maybe something broken for  gem "sqlite3" > 1.4

**Comment by eregon** [comment]
That might be related to https://github.com/oracle/truffleruby/issues/2227

**Comment by bjfish** [comment]
@gogainda I was able to run devise successfully:
https://github.com/bjfish/devise/runs/1826301684?check_suite_focus=true

Could you please try running doorkeep again to see if this issue is still present?

**Comment by gogainda** [comment]
sure, will do it shortly

**Comment by gogainda** [comment]
@bjfish I confirm that the error is fixed now, thanks

**Comment by bjfish** [comment]
@gogainda Thanks!
