### ISSUE TITLE
bundler-audit gem test failure: comparison of Integer with Range failed (ArgumentError)

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2234]
```
Failures:

  1) CLI when auditing a bundle with insecure sources should print warnings about insecure sources
     Failure/Error:
             expect(subject).to include(%{
       Insecure Source URI found: git://github.com/rails/jquery-rails.git
       Insecure Source URI found: http://rubygems.org/
             }.strip)

       expected "<internal:core> core/numeric.rb:265:in `math_coerce_error': comparison of Integer with Range failed ...1:in `load'\n\tfrom /home/runner/work/bundler-audit/bundler-audit/bin/bundler-audit:3:in `<main>'\n" to include "Insecure Source URI found: git://github.com/rails/jquery-rails.git\nInsecure Source URI found: http://rubygems.org/"
       Diff:
       @@ -1,43 +1,85 @@
       -Insecure Source URI found: git://github.com/rails/jquery-rails.git\nInsecure Source URI found: http://rubygems.org/
       +<internal:core> core/numeric.rb:265:in `math_coerce_error': comparison of Integer with Range failed (ArgumentError)
       +	from <internal:core> core/numeric.rb:245:in `math_coerce'
       +	from <internal:core> core/numeric.rb:290:in `redo_compare'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/truffle/securerandom.rb:150:in `<'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/truffle/securerandom.rb:150:in `random_number'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:601:in `random'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:641:in `bind_random_port'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:820:in `block in lazy_initialize'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:813:in `synchronize'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:813:in `lazy_initialize'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:833:in `sender'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:522:in `block in fetch_resource'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1120:in `block (3 levels) in resolv'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1118:in `each'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1118:in `block (2 levels) in resolv'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1117:in `each'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1117:in `block in resolv'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1115:in `each'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:1115:in `resolv'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:517:in `fetch_resource'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:507:in `each_resource'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:404:in `each_address'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:116:in `block in each_address'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:115:in `each'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:115:in `each_address'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:102:in `getaddresses'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/mri/resolv.rb:51:in `getaddresses'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:253:in `internal_host?'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:241:in `internal_source?'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:175:in `block in scan_sources'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:170:in `map'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:170:in `scan_sources'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:142:in `scan'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/scanner.rb:113:in `report'
       +	from /home/runner/work/bundler-audit/bundler-audit/lib/bundler/audit/cli.rb:69:in `check'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/gems/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/gems/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/gems/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
       +	from /home/runner/.rubies/truffleruby-20.3.0/lib/gems/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
       +	from /home/runner/work/bundler-audit/bundler-audit/bin/bundle-audit:10:in `<top (required)>'
       +	from <internal:core> core/kernel.rb:401:in `load'
       +	from <internal:core> core/kernel.rb:401:in `load'
       +	from /home/runner/work/bundler-audit/bundler-audit/bin/bundler-audit:3:in `<main>'
     # ./spec/integration_spec.rb:62:in `block (3 levels) in <top (required)>'
```

Taken from : https://github.com/rubysec/bundler-audit/runs/1609982351
https://github.com/rubysec/bundler-audit/commit/d1f6213002a3ea9af2218c1c5375273d523937ed

**Comment by eregon** [comment]
This reproduces:
```
$ ruby -rsecurerandom -e 'p SecureRandom.random_number(1024..65535)'
<internal:core> core/numeric.rb:265:in `math_coerce_error': comparison of Integer with Range failed (ArgumentError)
	from <internal:core> core/numeric.rb:245:in `math_coerce'
	from <internal:core> core/numeric.rb:290:in `redo_compare'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/securerandom.rb:150:in `<'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/securerandom.rb:150:in `random_number'
	from -e:1:in `<main>'
```

Which means `SecureRandom.random_number` should support a Range argument.

In MRI, it seems to actually come from `Random::Formatter.random_number`, ``Random::Formatter` is a module included in `Random`  and in `SecureRandom`.
We should probably follow a similar design in TruffleRuby.

Currently we have `lib/truffle/securerandom.rb` but probably we should import a newer lib/securerandom.rb from MRI, and reapply our changes on top: https://github.com/oracle/truffleruby/commits/master/lib/truffle/securerandom.rb.
Although that on its own won't solve this specific issue, because `Random::Formatter.random_number` is defined in `random.c` in MRI.

**Comment by eregon** [comment]
I think a good start here would be to add `Random.singleton_class` and `Random::Formatter`
to https://github.com/oracle/truffleruby/blob/master/spec/truffle/methods_spec.rb, and try to match which methods are defined where.

**Comment by bjfish** [comment]
This is fixed at https://github.com/oracle/truffleruby/commit/2edfaa61d4fb2e144e487227b24928f049fd95d9, thanks.
