### ISSUE TITLE
TypeError: TruffleRuby doesn't have a case for ConstDefinedNode with values of type RubyClass java.lang.String Nil Boolean=true

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2240]
From https://github.com/ruby-next/ruby-next/runs/1790216003?check_suite_focus=true
```
bundler: failed to load command: mspec/bin/mspec (mspec/bin/mspec)
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.core.module.ModuleNodesFactory$ConstDefinedNodeFactory$ConstDefinedNodeGen node with values of type Class(org.truffleruby.core.klass.RubyClass) java.lang.String org.truffleruby.language.Nil java.lang.Boolean=true
	from org.truffleruby.core.module.ModuleNodesFactory$ConstDefinedNodeFactory$ConstDefinedNodeGen.executeAndSpecialize(ModuleNodesFactory.java:2794)
	from org.truffleruby.core.module.ModuleNodesFactory$ConstDefinedNodeFactory$ConstDefinedNodeGen.execute(ModuleNodesFactory.java:2775)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.arguments.CheckArityNode.execute(CheckArityNode.java:45)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.methods.CatchForMethodNode.execute(CatchForMethodNode.java:42)
	from org.truffleruby.language.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:33)
	from org.truffleruby.language.RubyRootNode.execute(RubyRootNode.java:61)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:592)
  <internal:core> core/module.rb:105:in `const_defined?'
  /home/runner/bundle/truffleruby/21.1.0-dev-93211d3f/gems/ice_nine-0.11.2/lib/ice_nine/freezer.rb:87:in `const_lookup'
```

Coming from https://github.com/dkubb/ice_nine/blob/2380ec33ef9c3302d0bdf6fb076a5fa6ec9bdc17/lib/ice_nine/freezer.rb#L87

Can be reproduced with `jt ruby -e 'p String.const_defined?(:Foo, nil)'`.
Reported by @ssnickolay

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/5c8578a9f120923c76d84d75fdd6ea3356b97187.
