### ISSUE TITLE
Resolv.getaddress broken

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2242]
I'm experiencing the following issue in truffleruby 20.3 . Given I haven't seen any closed issue for it, I assume it's still so upstream:

```ruby
require "resirb(main):001:0> require "resolv"
=> true
irb(main):002:0> Resolv.getaddress("google.com")
Traceback (most recent call last):
       16: from /usr/local/lib/mri/resolv.rb:1117:in `each'
       15: from /usr/local/lib/mri/resolv.rb:1118:in `block (2 levels) in resolv'
       14: from /usr/local/lib/mri/resolv.rb:1118:in `each'
       13: from /usr/local/lib/mri/resolv.rb:1120:in `block (3 levels) in resolv'
       12: from /usr/local/lib/mri/resolv.rb:522:in `block in fetch_resource'
       11: from /usr/local/lib/mri/resolv.rb:833:in `sender'
       10: from /usr/local/lib/mri/resolv.rb:813:in `lazy_initialize'
        9: from /usr/local/lib/mri/resolv.rb:813:in `synchronize'
        8: from /usr/local/lib/mri/resolv.rb:820:in `block in lazy_initialize'
        7: from /usr/local/lib/mri/resolv.rb:641:in `bind_random_port'
        6: from /usr/local/lib/mri/resolv.rb:601:in `random'
        5: from /usr/local/lib/truffle/securerandom.rb:150:in `random_number'
        4: from /usr/local/lib/truffle/securerandom.rb:150:in `<'
        3: from <internal:core> core/numeric.rb:290:in `redo_compare'
        2: from <internal:core> core/numeric.rb:245:in `math_coerce'
        1: from <internal:core> core/numeric.rb:265:in `math_coerce_error'
ArgumentError (comparison of Integer with Range failed)
```

**Comment by gogainda** [comment]
'comparison of Integer with Range failed' I think I saw it before

**Comment by eregon** [comment]
Yes, it's the same root cause as https://github.com/oracle/truffleruby/issues/2234.
I'll keep this one open though to make sure it also gets solved by implementing `SecureRandom.random_number(Range)`.

**Comment by HoneyryderChuck** [comment]
Great to hear it's already known. FYI [I added some patches to httpx in order to run CI under 20.3](https://gitlab.com/honeyryderchuck/httpx/-/jobs/997079515), and most (not all) of the errors are due to this bug.

**Comment by bjfish** [comment]
@HoneyryderChuck This is fixed at https://github.com/oracle/truffleruby/commit/2edfaa61d4fb2e144e487227b24928f049fd95d9. Let us know if you see any other issues, thanks.
