### ISSUE TITLE
sqlite3-ruby gem test failure

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2245]
```
  1) Failure:
TC_Integration_Aggregate#test_create_aggregate_handler_with_exception_step [/Users/novoi/tmp/sqlite3-ruby/test/test_integration_aggregate.rb:275]:
[TC_Integration_Aggregate::CustomException] exception expected, not
Class: <SQLite3::SQLException>
Message: <"Ruby Exception occured">
---Backtrace---
/Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1058:in `rb_exc_raise'
exception.c:28:in `rb_exc_raise'
/Users/novoi/tmp/sqlite3-ruby/ext/sqlite3/exception.c:97:in `rb_sqlite3_raise'
/Users/novoi/tmp/sqlite3-ruby/ext/sqlite3/statement.c:189:in `step'
/Users/novoi/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:39:in `step'
/Users/novoi/tmp/sqlite3-ruby/lib/sqlite3/resultset.rb:108:in `next'
/Users/novoi/tmp/sqlite3-ruby/lib/sqlite3/database.rb:364:in `block in get_first_value'
/Users/novoi/tmp/sqlite3-ruby/lib/sqlite3/database.rb:340:in `query'
/Users/novoi/tmp/sqlite3-ruby/lib/sqlite3/database.rb:363:in `get_first_value'
/Users/novoi/tmp/sqlite3-ruby/test/test_integration_aggregate.rb:276:in `block in test_create_aggregate_handler_with_exception_step'
```

**Comment by eregon** [comment]
That might be related to https://github.com/oracle/truffleruby/issues/2227

**Comment by bjfish** [comment]
A smaller reproduction of the issue is here:
```

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'sqlite3', '~> 1.3', '>= 1.3.11'
end

require "sqlite3"

db = SQLite3::Database.new(":memory:")
db.transaction do
      db.execute "create table foo ( a integer primary key, b text, c integer )"
      db.execute "insert into foo ( b, c ) values ( 'foo', 10 )"
end

class CustomException < Exception
end

db.create_aggregate( "raiseexception", 1 ) do
    step do |ctx,a|
      puts "in step"
      raise CustomException.new( "bogus step aggregate handler" )
    end

    finalize do |ctx|
      puts "in finalize"
      raise CustomException.new( "bogus finalize aggregate handler" )
    end
  end

begin
  db.get_first_value( "select raiseexception(a) from foo")
rescue Exception => e
  p e
ensure
  db.close
end
```
Expected 
```
in step
#<CustomException: bogus step aggregate handler>
```
Actual
```
in step
#<SQLite3::SQLException: Ruby Exception occured>
```

Analysis
I've traced this and it appears this branch is taken on MRI but not on TruffleRuby:
https://github.com/sparklemotion/sqlite3-ruby/blob/d94c42b0b8e5005ee28cde75a58e15ea5670d1c4/ext/sqlite3/statement.c#L128-L135

I suspect this call should be setting `rb_errinfo`:
https://github.com/sparklemotion/sqlite3-ruby/blob/d94c42b0b8e5005ee28cde75a58e15ea5670d1c4/ext/sqlite3/aggregator.c#L140

Another thing I noticed, MRI's value for exc_status there is `6` and ours was `1`.

@aardvark179 Maybe you could look at this one as it appears similar to #2227?

**Comment by aardvark179** [comment]
Sadly this isn't the `rb_errinfo` problem. We are getting an error result back from the `sqlite3_step` call, and I'm not quite sure why we're seeing this particular difference in behaviour.
