### ISSUE TITLE
Nokogiri failure: does not contain bitecode

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2246]
```
Run bundle exec rake
/home/runner/.rubies/truffleruby-head/bin/truffleruby -I"lib:lib:test" /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/browser_test.rb" "test/middleware_test.rb" "test/rails_test.rb" "test/unit/accept_language_test.rb" "test/unit/adobe_air_test.rb" "test/unit/aliases_test.rb" "test/unit/alipay_test.rb" "test/unit/android_app_test.rb" "test/unit/android_test.rb" "test/unit/blackberry_test.rb" "test/unit/bots_test.rb" "test/unit/chrome_test.rb" "test/unit/console_test.rb" "test/unit/device_test.rb" "test/unit/duck_duck_go_test.rb" "test/unit/edge_test.rb" "test/unit/electron_test.rb" "test/unit/facebook_test.rb" "test/unit/firefox_test.rb" "test/unit/generic_test.rb" "test/unit/google_search_app_test.rb" "test/unit/huawei_browser_test.rb" "test/unit/instagram_test.rb" "test/unit/internet_explorer_test.rb" "test/unit/ios_app_test.rb" "test/unit/ios_test.rb" "test/unit/kai_os_test.rb" "test/unit/kindle_test.rb" "test/unit/maxthon_test.rb" "test/unit/meta_test.rb" "test/unit/micro_messenger_test.rb" "test/unit/miui_browser_test.rb" "test/unit/nokia_test.rb" "test/unit/opera_test.rb" "test/unit/otter_test.rb" "test/unit/platform_test.rb" "test/unit/proxy_test.rb" "test/unit/qq_test.rb" "test/unit/safari_test.rb" "test/unit/samsung_browser_test.rb" "test/unit/snapchat_test.rb" "test/unit/sougou_browser_test.rb" "test/unit/sputnik_test.rb" "test/unit/uc_browser_test.rb" "test/unit/weibo_test.rb" "test/unit/windows_phone_test.rb" "test/unit/windows_test.rb" "test/unit/yandex_test.rb" 
Coverage report generated for Unit Tests to /home/runner/work/browser/browser/coverage. 842 / 1392 LOC (60.49%) covered.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
/home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `gem_original_require': Toplevel executable /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri/2.7/nokogiri.so does not contain bitcode (com.oracle.truffle.llvm.runtime.except.LLVMParserException) (RuntimeError)
Translated to internal error
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/nokogiri-1.11.1-x86_64-linux/lib/nokogiri.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/loofah-2.9.0/lib/loofah.rb:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rails-html-sanitizer-1.3.0/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/sanitize_helper.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/text_helper.rb:34:in `<module:TextHelper>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/text_helper.rb:31:in `<module:Helpers>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/text_helper.rb:8:in `<module:ActionView>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/text_helper.rb:6:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/form_tag_helper.rb:21:in `<module:FormTagHelper>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/form_tag_helper.rb:17:in `<module:Helpers>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/form_tag_helper.rb:11:in `<module:ActionView>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/form_tag_helper.rb:9:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers/form_helper.rb:6:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers.rb:53:in `<module:Helpers>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers.rb:6:in `<module:ActionView>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/helpers.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view/base.rb:7:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies/autoload.rb:72:in `block in eager_load!'
	from <internal:core> core/hash.rb:403:in `block in each_value'
	from <internal:core> core/hash.rb:403:in `each_pair'
	from <internal:core> core/hash.rb:403:in `each_value'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies/autoload.rb:72:in `eager_load!'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/actionview-6.1.1/lib/action_view.rb:92:in `eager_load!'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/application/finisher.rb:134:in `eager_load!'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/application/finisher.rb:134:in `each'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:228:in `block in tsort_each'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:347:in `each'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:347:in `call'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:347:in `each_strongly_connected_component'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:226:in `tsort_each'
	from /home/runner/.rubies/truffleruby-head/lib/mri/tsort.rb:205:in `tsort_each'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/railties-6.1.1/lib/rails/railtie.rb:207:in `method_missing'
	from /home/runner/work/browser/browser/test/sample_app.rb:55:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
	from /home/runner/work/browser/browser/test/middleware_test.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/lib/rake/rake_test_loader.rb:5:in `select'
	from /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/lib/rake/rake_test_loader.rb:5:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" /home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/browser_test.rb" "test/middleware_test.rb" "test/rails_test.rb" "test/unit/accept_language_test.rb" "test/unit/adobe_air_test.rb" "test/unit/aliases_test.rb" "test/unit/alipay_test.rb" "test/unit/android_app_test.rb" "test/unit/android_test.rb" "test/unit/blackberry_test.rb" "test/unit/bots_test.rb" "test/unit/chrome_test.rb" "test/unit/console_test.rb" "test/unit/device_test.rb" "test/unit/duck_duck_go_test.rb" "test/unit/edge_test.rb" "test/unit/electron_test.rb" "test/unit/facebook_test.rb" "test/unit/firefox_test.rb" "test/unit/generic_test.rb" "test/unit/google_search_app_test.rb" "test/unit/huawei_browser_test.rb" "test/unit/instagram_test.rb" "test/unit/internet_explorer_test.rb" "test/unit/ios_app_test.rb" "test/unit/ios_test.rb" "test/unit/kai_os_test.rb" "test/unit/kindle_test.rb" "test/unit/maxthon_test.rb" "test/unit/meta_test.rb" "test/unit/micro_messenger_test.rb" "test/unit/miui_browser_test.rb" "test/unit/nokia_test.rb" "test/unit/opera_test.rb" "test/unit/otter_test.rb" "test/unit/platform_test.rb" "test/unit/proxy_test.rb" "test/unit/qq_test.rb" "test/unit/safari_test.rb" "test/unit/samsung_browser_test.rb" "test/unit/snapchat_test.rb" "test/unit/sougou_browser_test.rb" "test/unit/sputnik_test.rb" "test/unit/uc_browser_test.rb" "test/unit/weibo_test.rb" "test/unit/windows_phone_test.rb" "test/unit/windows_test.rb" "test/unit/yandex_test.rb" ]
/home/runner/work/browser/browser/vendor/bundle/truffleruby/21.1.0-dev-13ba0dac/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:400:in `load'
<internal:core> core/kernel.rb:400:in `load'
<internal:core> core/kernel.rb:400:in `load'
<internal:core> core/kernel.rb:400:in `load'
<internal:core> core/kernel.rb:400:in `load'
<internal:core> core/kernel.rb:400:in `load'
/home/runner/.rubies/truffleruby-head/bin/bundle:23:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
Error: Process completed with exit code 1.
```
from : https://github.com/fnando/browser/pull/511/checks?check_run_id=1823367840

Github Action config:
```
name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    name: Tests with Ruby ${{ matrix.ruby }} and ${{ matrix.gemfile }}
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "2.6", "2.5", "truffleruby-head"]
        gemfile:
          - Gemfile
          - gemfiles/rails5.gemfile
          - gemfiles/rails6.gemfile

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles(matrix.gemfile) }}
          restore-keys: >
            ${{ runner.os }}-${{ matrix.ruby }}-gems-${{ hashFiles(matrix.gemfile) }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install gem dependencies
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle update --jobs 4 --retry 3

      - name: Run Tests
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: |
          bundle exec rake
```

**Comment by eregon** [comment]
Due to a Bundler bug: https://github.com/rubygems/rubygems/issues/4330

**Comment by eregon** [comment]
Fixed merged in Bundler, there should be a release next week:
https://github.com/rubygems/rubygems/pull/4333#issuecomment-772627912

I'll already close so I don't forget.

**Comment by eregon** [comment]
Bundler 2.2.9 was released with that fix: https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.9
