### ISSUE TITLE
iodine issue: External LLVMFunction pthread_atfork cannot be found

### ISSUE THREAD

**Issue by AlexeyMatskevich** [oracle/truffleruby#2251]
```
RuntimeError: External LLVMFunction pthread_atfork cannot be found.
  <internal:core> core/kernel.rb:293:in `require_relative'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/lib/iodine.rb:6:in `<top (required)>'
  <internal:core> core/kernel.rb:234:in `gem_original_require'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/iodine-0.7.43/exe/iodine:4:in `<top (required)>'
  <internal:core> core/kernel.rb:401:in `load'
  <internal:core> core/kernel.rb:401:in `load'
  /home/aleksei/.asdf/installs/ruby/truffleruby+graalvm-20.3.0/bin/iodine:23:in `<top (required)>'
  <internal:core> core/kernel.rb:401:in `load'
  <internal:core> core/kernel.rb:401:in `load'

[ [ SubstrateSegfaultHandler caught a segfault. ] ]
```
To reproduce:
```
gem install iodine
iodine
```

**Comment by eregon** [comment]
Thanks for the report.

I can reproduce.
This might be caused by not linking to libpthread, but actually it seems like it is linked to it:
```
$ gem i iodine

$ iodine --experimental-options --cexts-log-load --help
<internal:core> core/kernel.rb:293:in `require_relative': External LLVMFunction pthread_atfork cannot be found. (RuntimeError)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/iodine-0.7.43/lib/iodine.rb:6:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/iodine-0.7.43/exe/iodine:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:400:in `load'
	from <internal:core> core/kernel.rb:400:in `load'
	from /home/eregon/.rubies/truffleruby-dev/bin/iodine:23:in `<main>'

$  ldd /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/iodine-0.7.43/lib/iodine/iodine.so
	linux-vdso.so.1 (0x00007ffcef965000)
	libtruffleruby.so => /home/eregon/.rubies/truffleruby-dev/lib/cext/libtruffleruby.so (0x00007fda8ad56000)
	libgraalvm-llvm.so.1 => /home/eregon/.rubies/truffleruby-dev/lib/sulong/native/lib/libgraalvm-llvm.so.1 (0x00007fda8ad49000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007fda8ac8e000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fda8a9a1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fda8a7d7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fda8b0bf000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fda8a7b5000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fda8a799000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fda8a792000)

$ nm /lib64/libpthread.so.0 | grep pthread_atfork
0000000000011ba0 t .annobin___dyn_pthread_atfork.end
0000000000011b90 t .annobin___dyn_pthread_atfork.start
0000000000011b90 t .annobin_old_pthread_atfork.c
0000000000011ba0 t .annobin_old_pthread_atfork.c_end
0000000000007b15 t .annobin_old_pthread_atfork.c_end.exit
0000000000007b15 t .annobin_old_pthread_atfork.c_end.hot
0000000000007b15 t .annobin_old_pthread_atfork.c_end.startup
0000000000007b15 t .annobin_old_pthread_atfork.c_end.unlikely
0000000000007b15 t .annobin_old_pthread_atfork.c.exit
0000000000007b15 t .annobin_old_pthread_atfork.c.hot
0000000000007b15 t .annobin_old_pthread_atfork.c.startup
0000000000007b15 t .annobin_old_pthread_atfork.c.unlikely
0000000000011b90 t __dyn_pthread_atfork
0000000000011b90 T pthread_atfork@GLIBC_2.2.5
```

I think this is a Sulong or NFI issue, so I'll move the issue to oracle/graal.
