### ISSUE TITLE
NoMethodError when using RubyContext#send()

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2258]
**truffleruby 21.1.0-dev-d7ae4d2a, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]**

```
     NoMethodError:
       undefined method `singleton_method_added' for #<#<Class:0xd6d18>:0xd6d28> when using RubyContext#send() which ignores #method_missing
       Did you mean?  singleton_method
                      singleton_methods
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/evaluator.rb:73:in `define_method'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/evaluator.rb:73:in `define_attribute'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/evaluator.rb:20:in `block in initialize'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/evaluator.rb:19:in `each'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/evaluator.rb:19:in `initialize'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/factory.rb:36:in `run'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/factory_runner.rb:28:in `run'
     # /usr/local/bundle/gems/factory_bot-5.1.1/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `create'
     # ./spec/controllers/schools/placement_dates/subject_selections_controller_spec.rb:6:in `school'
     # <internal:core> core/hash.rb:231:in `fetch'
     # <internal:core> core/hash.rb:231:in `fetch'
     # <internal:core> core/array.rb:903:in `reverse_each'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # /usr/local/lib/mri/bundler/cli/exec.rb:63:in `kernel_load'
     # /usr/local/lib/mri/bundler/cli/exec.rb:28:in `run'
     # /usr/local/lib/mri/bundler/cli.rb:476:in `exec'
     # /usr/local/lib/mri/bundler/cli.rb:30:in `dispatch'
     # /usr/local/lib/mri/bundler/cli.rb:24:in `start'
     # /usr/local/lib/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /usr/local/lib/mri/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /usr/local/lib/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
```

**Comment by bjfish** [comment]
@eregon This may be related to the recent change: https://github.com/oracle/truffleruby/commit/c11a54683899cdf28d66d1bf037894ee8f23b5c2

**Comment by eregon** [comment]
Thanks for the report, I'll look at it Monday.
It sounds like that singleton class somehow undefines `singleton_method_added`.

**Comment by eregon** [comment]
The actual semantics are to call `method_missing` in that case, which I'm not sure if intended in `factory_bot` (I filed an issue upstream).
There is also a delegation bug in `factory_bot`, which is problematic once `method_missing` is called. I made a PR to fix that upstream.
