### ISSUE TITLE
Strange behavior in exception handling when using ActiveRecord with sqlite

### ISSUE THREAD

**Issue by ivoanjo** [oracle/truffleruby#2276]
Hello again 👋 . As usual, I'm trying to run the [`dd-trace`](https://github.com/DataDog/dd-trace-rb) test suite on TruffleRuby (with the ultimate goal being to have it on by default in CI -- so that we don't regress).

The following issue was extracted from an issue originally in <https://github.com/DataDog/dd-trace-rb/blob/master/spec/ddtrace/contrib/active_record/multi_db_spec.rb>.

Testcase:

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activerecord', '= 6.1.3'
  gem 'sqlite3', '~> 1.4.1'
end

require 'active_record'

puts RUBY_DESCRIPTION

class Widget < ActiveRecord::Base
end

Widget.establish_connection(adapter: 'sqlite3', database: ':memory:')

puts \
  begin
    Widget.count
  rescue ActiveRecord::StatementInvalid
    puts "Rescuing ActiveRecord::StatementInvalid"
    Widget.connection.create_table 'widgets', force: :cascade do |t|
      t.string   'title'
      t.datetime 'created_at', null: false
      t.datetime 'updated_at', null: false
    end

    puts "Created table!"
    Widget.count
  end
```

Behavior in MRI:

```
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
Rescuing ActiveRecord::StatementInvalid
Created table!
0
```

Behavior in TruffleRuby:

```
truffleruby 21.0.0.2, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin]
Rescuing ActiveRecord::StatementInvalid
/Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:346:in `table_structure': ActiveRecord::StatementInvalid: Could not find table 'widgets' (ActiveRecord::StatementInvalid)
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:104:in `block in columns'
	from <internal:core> core/hash.rb:227:in `fetch'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:103:in `columns'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns_hash'
	from <internal:core> core/hash.rb:227:in `fetch'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns_hash'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:553:in `load_schema!'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/attributes.rb:250:in `load_schema!'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:539:in `block in load_schema'
	from /Users/ivo.anjo/.rvm/rubies/truffleruby-21.0.0.2/lib/mri/monitor.rb:235:in `mon_synchronize'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:536:in `load_schema'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:392:in `columns_hash'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/query_methods.rb:1313:in `arel_column'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:280:in `aggregate_column'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:299:in `execute_simple_calculation'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:269:in `perform_calculation'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:144:in `calculate'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:51:in `count'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/querying.rb:22:in `count'
	from repro-activerecord.rb:21:in `<main>'
/Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:346:in `table_structure': Could not find table 'widgets' (ActiveRecord::StatementInvalid)
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:116:in `columns'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:104:in `block in columns'
	from <internal:core> core/hash.rb:227:in `fetch'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:103:in `columns'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:112:in `block in columns_hash'
	from <internal:core> core/hash.rb:227:in `fetch'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/connection_adapters/schema_cache.rb:111:in `columns_hash'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:553:in `load_schema!'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/attributes.rb:250:in `load_schema!'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:539:in `block in load_schema'
	from /Users/ivo.anjo/.rvm/rubies/truffleruby-21.0.0.2/lib/mri/monitor.rb:235:in `mon_synchronize'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:536:in `load_schema'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/model_schema.rb:392:in `columns_hash'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/query_methods.rb:1313:in `arel_column'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:280:in `aggregate_column'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:299:in `execute_simple_calculation'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:269:in `perform_calculation'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:144:in `calculate'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/relation/calculations.rb:51:in `count'
	from /Users/ivo.anjo/.rvm/gems/truffleruby-21.0.0.2/gems/activerecord-6.1.3/lib/active_record/querying.rb:22:in `count'
	from repro-activerecord.rb:21:in `<main>'
```

Analysis:

This came from a test that was using this approach of "probe if the `widgets` table exists, and if not, create it". This works fine on MRI, but on TruffleRuby, it seems like the exception state is not correctly reset, so once `create_table` gets called in the exception handler, then a new `ActiveRecord::StatementInvalid` seems to show up again, which breaks the code.

Moving the table creation out of the exception handler fixes this, so this seems to be triggered by specifically running the code in the handler.

**Comment by eregon** [comment]
This seems a duplicate of https://github.com/oracle/truffleruby/issues/2245 and related to https://github.com/oracle/truffleruby/issues/2227.
In short, it should already be fixed on `master`, can you try nightly builds of TruffleRuby?

**Comment by ivoanjo** [comment]
Yeap, both my reproduction above as well as the original spec in `ddtrace` work in nightly -- `truffleruby 21.1.0-dev-3414643e, like ruby 2.7.2, GraalVM CE Native [x86_64-darwin`.

Closing!

**Comment by eregon** [comment]
Great!
