### ISSUE TITLE
Simple redis not working?

### ISSUE THREAD

**Issue by LillianZ** [oracle/truffleruby#2326]
The following is functional on MRI but not TR:
``` ruby
require 'redis'
redis = Redis.new
redis.ping
```

I also tried other hosts/ports/urls/commands, with the same results. I'm trying to benchmark Redis, so if you have code / a configuration that works, please share. :)

The error was:
```
truffleruby 21.1.0-dev-972a0521, like ruby 2.7.2, GraalVM CE JVM [x86_64-darwin]
/Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:156:in `connect_addrinfo': undefined method `wait_writable' for #<Redis::Connection::TCPSocket:fd 25> (NoMethodError)
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:192:in `block in connect'
	from <internal:core> core/enumerable.rb:354:in `each_with_index'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:190:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:304:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:354:in `establish_connection'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:112:in `block in connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:313:in `with_reconnect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:111:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:386:in `ensure_connected'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:172:in `block in ping'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:237:in `block (2 levels) in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:236:in `block in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:233:in `mon_synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:171:in `ping'
	from bench/micro/redis_bench.rb:8:in `<main>'
<internal:core> core/errno.rb:48:in `handle': unknown error - Operation now in progress - connect(2) (IO::EINPROGRESSWaitWritable)
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:53:in `block in write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:67:in `wrap_write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:53:in `write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/socket.rb:359:in `connect_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:154:in `connect_addrinfo'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:192:in `block in connect'
	from <internal:core> core/enumerable.rb:354:in `each_with_index'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:190:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:304:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:354:in `establish_connection'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:112:in `block in connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:313:in `with_reconnect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:111:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:386:in `ensure_connected'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:172:in `block in ping'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:237:in `block (2 levels) in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:236:in `block in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:233:in `mon_synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:171:in `ping'
	from bench/micro/redis_bench.rb:8:in `<main>'
<internal:core> core/errno.rb:48:in `handle': Operation now in progress - connect(2) (Errno::EINPROGRESS)
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:53:in `block in write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:67:in `wrap_write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/truffle/error.rb:53:in `write_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/truffle/socket/socket.rb:359:in `connect_nonblock'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:154:in `connect_addrinfo'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:192:in `block in connect'
	from <internal:core> core/enumerable.rb:354:in `each_with_index'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:190:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:304:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:354:in `establish_connection'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:112:in `block in connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:313:in `with_reconnect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:111:in `connect'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:386:in `ensure_connected'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:172:in `block in ping'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:237:in `block (2 levels) in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:236:in `block in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:233:in `mon_synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
	from /Users/lillianzhang/src/github.com/Shopify/graal/sdk/mxbuild/darwin-amd64/GRAALVM_59AD9B8DBA_JAVA11/graalvm-59ad9b8dba-java11-21.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/redis-4.2.5/lib/redis.rb:171:in `ping'
	from bench/micro/redis_bench.rb:8:in `<main>'
```

**Comment by eregon** [comment]
I can reproduce.

This part definitely seems an issue:
```
redis-4.2.5/lib/redis/connection/ruby.rb:156:in `connect_addrinfo': undefined method `wait_writable' for #<Redis::Connection::TCPSocket:fd 9> (NoMethodError)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:192:in `block in connect'
	from <internal:core> core/enumerable.rb:354:in `each_with_index'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:190:in `connect'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/connection/ruby.rb:304:in `connect'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:354:in `establish_connection'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:112:in `block in connect'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:313:in `with_reconnect'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:111:in `connect'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:386:in `ensure_connected'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:238:in `block in process'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:325:in `logging'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:237:in `process'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis/client.rb:131:in `call'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis.rb:172:in `block in ping'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `block in synchronize'
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/monitor.rb:237:in `block (2 levels) in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/monitor.rb:236:in `block in mon_synchronize'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from <internal:core> core/thread.rb:94:in `handle_interrupt'
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/monitor.rb:233:in `mon_synchronize'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis.rb:69:in `synchronize'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/redis-4.2.5/lib/redis.rb:171:in `ping'
	from -e:1:in `<main>'
```

FWIW there is a somewhat similar error on CRuby when there is no `redis-server` around. Of course `redis-server` needs to be started before.

**Comment by eregon** [comment]
It works with:
```
ruby -rredis -rio/wait -e 'r=Redis.new; p r; p r.ping'
```

On CRuby it seems `require 'socket'` also requires `io/wait` (but not on TruffleRuby):
```
$ ruby --disable-gems -e 'puts $"; p IO.instance_method(:wait_writable).owner'         
enumerator.so
thread.rb
rational.so
complex.so
ruby2_keywords.rb
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `instance_method': undefined method `wait_writable' for class `IO' (NameError)


$ ruby --disable-gems -rsocket -e 'puts $"; p IO.instance_method(:wait_writable).owner'
enumerator.so
thread.rb
rational.so
complex.so
ruby2_keywords.rb
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/enc/encdb.so
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/enc/trans/transdb.so
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/socket.so
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/x86_64-linux/io/wait.so
/home/eregon/.rubies/ruby-2.7.2/lib/ruby/2.7.0/socket.rb
IO
```

**Comment by LillianZ** [comment]
tysm!!!!!!!!  I am very admiring of your investigative/debugging skills.
