### ISSUE TITLE
wrong argument type PG::TypeMapByClass (expected Data)

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2331]
**truffleruby 21.1.0-dev-97019acc, like ruby 2.7.2, GraalVM CE Native [x86_64-linux]**

Started getting this error in a CI job (runs fine on previous TruffleRuby releases that are tested in the CI job).

This is the CI job, had to run a docker compose command into the foreground (rather than -d) to see the error and then cancel job as it waits for a docker compose container to exit successfully.

https://github.com/petenorth/schools-experience/runs/2368972570?check_suite_focus=true

```
db-tasks_1           | wrong argument type PG::TypeMapByClass (expected Data)
db-tasks_1           | Couldn't create 'school_experience' database. Please check your configuration.
db-tasks_1           | rake aborted!
db-tasks_1           | TypeError: wrong argument type PG::TypeMapByClass (expected Data)
db-tasks_1           | object.c:44:in `rb_check_type'
db-tasks_1           | /usr/local/bundle/gems/pg-1.2.2/ext/pg_connection.c:3924:in `pgconn_type_map_for_queries_set'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:807:in `add_pg_encoders'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:224:in `initialize'
db-tasks_1           | /usr/local/bundle/gems/activerecord-postgis-adapter-5.2.2/lib/active_record/connection_adapters/postgis_adapter.rb:62:in `initialize'
db-tasks_1           | /usr/local/bundle/gems/activerecord-postgis-adapter-5.2.2/lib/active_record/connection_adapters/postgis/create_connection.rb:40:in `postgis_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/connection_handling.rb:90:in `connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
db-tasks_1           | /usr/local/bundle/gems/activerecord-postgis-adapter-5.2.2/lib/active_record/connection_adapters/postgis/postgis_database_tasks.rb:25:in `create'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
db-tasks_1           | /usr/local/bundle/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <top (required)>'
db-tasks_1           | <internal:core> core/thread.rb:94:in `handle_interrupt'
db-tasks_1           | <internal:core> core/thread.rb:94:in `handle_interrupt'
db-tasks_1           | <internal:core> core/thread.rb:94:in `handle_interrupt'
db-tasks_1           | <internal:core> core/thread.rb:94:in `handle_interrupt'
db-tasks_1           | /usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | <internal:core> core/kernel.rb:400:in `load'
db-tasks_1           | /usr/local/bin/bundle:42:in `<main>'
db-tasks_1           | Tasks: TOP => db:create
db-tasks_1           | (See full trace by running task with --trace)
```

**Comment by eregon** [comment]
@aardvark179 Could you investigate? It might be related to https://github.com/oracle/truffleruby/issues/2307#issuecomment-820536576 / https://github.com/oracle/truffleruby/commit/ea82ff0eeb4ced054ccefa320b7bc7160a6b00a0

**Comment by aardvark179** [comment]
Yes it does look related. There is a flag on typed data objects that is checked by `RTYPEDDATA_P` on MRI, and I assume is only set in _some_ circumstances, but I haven't worked out when it is or isn't set yet.

**Comment by eregon** [comment]
@aardvark179 I think only *typed* data causes `TypeError` for ``rb_check_type`:
https://github.com/ruby/ruby/blob/93420d34aaf8c30f11a66dd08eb186da922c831d/include/ruby/internal/value_type.h#L337-L341
https://github.com/ruby/ruby/blob/93420d34aaf8c30f11a66dd08eb186da922c831d/error.c#L994
Links from https://github.com/oracle/truffleruby/issues/2307#issue-848554420

So I think we should check with`Truffle::CExt::DATA_TYPE` (only set for typed data) rather than `DATA_HOLDER` (which is set for both RData and RTypedData).

**Comment by aardvark179** [comment]
Yes, I think so too. The CAPI specs don't cover this area well enough, so I think it's worth adding some more.

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/a7a4b849224d9102484895d3521fcb2ebcc35067 by @aardvark179

**Comment by petenorth** [comment]
Confirmed, thanks.
