### ISSUE TITLE
--backtraces-raise is broken

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2335]
```
% bundle exec ruby --experimental-options --backtraces-raise -e 'loop { raise }'
Error while formatting Ruby exception:
<internal:core> core/pre.rb:134:in `method_missing': undefined method `get_formatted_backtrace' for #<Module:0x8> (could not find formatter NO_METHOD_ERROR) (NoMethodError)
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
...
Original Ruby exception:
<internal:core> core/pre.rb:134:in `method_missing': undefined method `get_formatted_backtrace' for #<Module:0x8> (could not find formatter NO_METHOD_ERROR) (NoMethodError)
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
	from <internal:core> core/pre.rb:134:in `method_missing'
...
```

It's not tested - maybe we should be testing some of these options,

**Comment by eregon** [comment]
Just `jt ruby --experimental-options --backtraces-raise -e 'raise'` reproduces it.
Part of the issue is
```
	from <internal:core> core/pre.rb:134:in `throw_stack_overflow_error'
```
We intentionally throw a crafted StackOverflowError to initialize all related classes properly (kind of related to https://github.com/oracle/truffleruby/issues/1743).

**Comment by eregon** [comment]
On `--native` it works fine, because we don't throw that StackOverflowError (all classes are initialized at build time anyway):
```
$ ruby --experimental-options --backtraces-raise -e 'raise rescue nil'
raise: <internal:core> core/exception.rb:109:in `full_message':  (RuntimeError)
	from <internal:core> core/truffle/exception_operations.rb:180:in `get_formatted_backtrace'
	from -e:1:in `raise'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/ca823dac960e684e3c47b3d284e0b944b772fdab along with specs and a couple additional fixes to only print the relevant part of the stacktrace (and not internals of formatting the exception backtrace)
