### ISSUE TITLE
Error running Optcarrot with coverage enabled

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2367]
```
% ruby --coverage -I ../benchmark-ips/lib bin/optcarrot-bench

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

class org.truffleruby.core.inlined.InlinedIndexSetNodeGen cannot be cast to class org.truffleruby.core.array.AssignableNode (org.truffleruby.core.inlined.InlinedIndexSetNodeGen and org.truffleruby.core.array.AssignableNode are in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @36aa7bc2) (java.lang.ClassCastException)
	from org.truffleruby.parser.BodyTranslator.toAssignableNode(BodyTranslator.java:1772)
	from org.truffleruby.parser.BodyTranslator.toAssignableNodes(BodyTranslator.java:1743)
	from org.truffleruby.parser.BodyTranslator.visitMultipleAsgnNode(BodyTranslator.java:2207)
	from org.truffleruby.parser.BodyTranslator.visitMultipleAsgnNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.MultipleAsgnParseNode.accept(MultipleAsgnParseNode.java:58)
	from org.truffleruby.parser.Translator.translateNodeOrNil(Translator.java:126)
	from org.truffleruby.parser.BodyTranslator.visitBlockNode(BodyTranslator.java:474)
	from org.truffleruby.parser.BodyTranslator.visitBlockNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.BlockParseNode.accept(BlockParseNode.java:55)
	from org.truffleruby.parser.BodyTranslator.visitIfNode(BodyTranslator.java:1899)
	from org.truffleruby.parser.BodyTranslator.visitIfNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.IfParseNode.accept(IfParseNode.java:66)
	from org.truffleruby.parser.Translator.translateNodeOrNil(Translator.java:126)
	from org.truffleruby.parser.BodyTranslator.visitBlockNode(BodyTranslator.java:474)
	from org.truffleruby.parser.BodyTranslator.visitBlockNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.BlockParseNode.accept(BlockParseNode.java:55)
	from org.truffleruby.parser.Translator.translateNodeOrNil(Translator.java:126)
	from org.truffleruby.parser.MethodTranslator.compileMethodBody(MethodTranslator.java:391)
	from org.truffleruby.parser.MethodTranslator.translateMethodNode(MethodTranslator.java:411)
	from org.truffleruby.parser.MethodTranslator.lambda$buildMethodNodeCompiler$2(MethodTranslator.java:422)
	from org.truffleruby.collections.CachedSupplier.get(CachedSupplier.java:30)
	from org.truffleruby.language.methods.LiteralMethodDefinitionNode.materializeInstrumentableNodes(LiteralMethodDefinitionNode.java:98)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.materializeSyntaxNodes(InstrumentationHandler.java:1895)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.materialize(InstrumentationHandler.java:1812)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.visit(InstrumentationHandler.java:1773)
	from org.graalvm.truffle/com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:399)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.visit(InstrumentationHandler.java:1800)
	from org.graalvm.truffle/com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:388)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.visit(InstrumentationHandler.java:1800)
	from org.graalvm.truffle/com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:399)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.visit(InstrumentationHandler.java:1800)
	from org.graalvm.truffle/com.oracle.truffle.api.nodes.NodeUtil.forEachChild(NodeUtil.java:388)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$Visitor.visit(InstrumentationHandler.java:1800)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1112)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.visitRoot(InstrumentationHandler.java:1077)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.onLoad(InstrumentationHandler.java:189)
	from org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.onLoad(InstrumentAccessor.java:205)
	from jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.createClonedCallTarget(GraalTruffleRuntime.java:644)
	from jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.createCallTarget(GraalTruffleRuntime.java:636)
	from org.truffleruby.parser.BodyTranslator.compileClassNode(BodyTranslator.java:1080)
	from org.truffleruby.parser.BodyTranslator.openModule(BodyTranslator.java:1040)
	from org.truffleruby.parser.BodyTranslator.visitClassNode(BodyTranslator.java:1096)
	from org.truffleruby.parser.BodyTranslator.visitClassNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.ClassParseNode.accept(ClassParseNode.java:75)
	from org.truffleruby.parser.Translator.translateNodeOrNil(Translator.java:126)
	from org.truffleruby.parser.BodyTranslator.compileClassNode(BodyTranslator.java:1054)
	from org.truffleruby.parser.BodyTranslator.openModule(BodyTranslator.java:1040)
	from org.truffleruby.parser.BodyTranslator.visitModuleNode(BodyTranslator.java:2185)
	from org.truffleruby.parser.BodyTranslator.visitModuleNode(BodyTranslator.java:276)
	from org.truffleruby.parser.ast.ModuleParseNode.accept(ModuleParseNode.java:68)
	from org.truffleruby.parser.Translator.translateNodeOrNil(Translator.java:126)
	from org.truffleruby.parser.TranslatorDriver.lambda$parse$1(TranslatorDriver.java:275)
	from org.truffleruby.debug.MetricsProfiler.callWithMetrics(MetricsProfiler.java:40)
	from org.truffleruby.parser.TranslatorDriver.parse(TranslatorDriver.java:268)
	from org.truffleruby.language.loader.CodeLoader.parse(CodeLoader.java:68)
	from org.truffleruby.RubyLanguage.parse(RubyLanguage.java:460)
	from org.truffleruby.RubyLanguage.parse(RubyLanguage.java:120)
	from org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$ParsingRequest.parse(TruffleLanguage.java:857)
	from org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage.parse(TruffleLanguage.java:1511)
	from org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.parse(LanguageAccessor.java:311)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseImpl(PolyglotSourceCache.java:94)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.access$300(PolyglotSourceCache.java:56)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache$WeakCache.lookup(PolyglotSourceCache.java:223)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSourceCache.parseCached(PolyglotSourceCache.java:80)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:371)
	from org.graalvm.truffle/com.oracle.truffle.polyglot.EngineAccessor$EngineImpl.parseForLanguage(EngineAccessor.java:246)
	from org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parseInternal(TruffleLanguage.java:2480)
	from org.truffleruby.language.loader.CodeLoader.parseTopLevelWithCache(CodeLoader.java:54)
	from org.truffleruby.language.loader.RequireNode.parseAndCall(RequireNode.java:223)
	from org.truffleruby.language.loader.RequireNode.doRequire(RequireNode.java:197)
	from org.truffleruby.language.loader.RequireNode.requireConsideringAutoload(RequireNode.java:126)
	from org.truffleruby.language.loader.RequireNode.lambda$requireWithMetrics$0(RequireNode.java:79)
	from org.truffleruby.debug.MetricsProfiler.callWithMetrics(MetricsProfiler.java:40)
	from org.truffleruby.language.loader.RequireNode.requireWithMetrics(RequireNode.java:76)
	from org.truffleruby.language.loader.RequireNode.require(RequireNode.java:68)
	from org.truffleruby.language.loader.RequireNodeGen.executeRequire(RequireNodeGen.java:30)
	from org.truffleruby.core.kernel.KernelNodes$LoadFeatureNode.loadFeature(KernelNodes.java:332)
	from org.truffleruby.core.kernel.KernelNodesFactory$LoadFeatureNodeFactory$LoadFeatureNodeGen.execute(KernelNodesFactory.java:814)
	from org.truffleruby.language.RubyNodeWrapper.execute(RubyNodeWrapper.java:45)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:43)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:45)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:36)
	from org.truffleruby.language.RubyNodeWrapper.execute(RubyNodeWrapper.java:45)
	from org.truffleruby.language.RubyMethodRootNode.execute(RubyMethodRootNode.java:62)
	from jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:617)
/Users/chrisseaton/Documents/optcarrot/lib/optcarrot/rom.rb:10:in `require_relative'
	from /Users/chrisseaton/Documents/optcarrot/lib/optcarrot/rom.rb:10:in `<class:ROM>'
	from /Users/chrisseaton/Documents/optcarrot/lib/optcarrot/rom.rb:3:in `<module:Optcarrot>'
	from /Users/chrisseaton/Documents/optcarrot/lib/optcarrot/rom.rb:1:in `<top (required)>'
	from <internal:core> core/kernel.rb:293:in `require_relative'
	from /Users/chrisseaton/Documents/optcarrot/lib/optcarrot.rb:7:in `<top (required)>'
	from <internal:core> core/kernel.rb:293:in `require_relative'
	from bin/optcarrot-bench:4:in `<main>'
```

**Comment by eregon** [comment]
Can be reproduced with `jt ruby --coverage bench/optcarrot/fixed-workload.rb`
