### ISSUE TITLE
`Dir.mkdir` doesn't handle  `Pathname`'s

### ISSUE THREAD

**Issue by deivid-rodriguez** [oracle/truffleruby#2397]
On CRuby 2.7.3:

```
$ ruby -v -rpathname -e 'Dir.mkdir(Pathname.new("foo"))'
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
```

On truffleruby-dev:

```
$ ruby -v -rpathname -e 'Dir.mkdir(Pathname.new("foo"))'
truffleruby 21.3.0-dev-8f9385a9, like ruby 2.7.3, GraalVM CE Native [x86_64-linux]
<internal:core> core/type.rb:287:in `convert_type': no implicit conversion of Pathname into String (TypeError)
	from <internal:core> core/type.rb:267:in `rb_convert_type'
	from <internal:core> core/kernel.rb:171:in `StringValue'
	from <internal:core> core/exception.rb:380:in `new'
	from <internal:core> core/errno.rb:48:in `handle'
	from <internal:core> core/dir.rb:306:in `mkdir'
	from -e:1:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
Thanks!
