### ISSUE TITLE
External LLVMFunction __strspn_c1 cannot be found. 

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2406]
Am using this Docker image 

[flavorjones/truffleruby:21.2.0](https://hub.docker.com/layers/flavorjones/truffleruby/21.2.0-buster/images/sha256-599f039d22b784eb6f665cfe7fc203082a9c8642558588c35ebf0218a7064ccb?context=explore)

Which is based on I think these Dockerfiles

https://github.com/flavorjones/truffleruby/tree/master/tool/dockerfiles

And am encountering this issue
```
   RuntimeError:
       External LLVMFunction __strspn_c1 cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException)
       Translated to internal error
     # date_strftime.c:540:in `date_strftime_with_tmx'
     # date_strftime.c:631:in `date_strftime'
     # date_core.c:6621:in `date_strftime_alloc'
     # date_core.c:6967:in `strftimev'
     # date_core.c:8442:in `iso8601_timediv'
     # date_core.c:8466:in `dt_lite_iso8601'
     # /usr/local/lib/truffle/truffle/cext_ruby.rb:41:in `xmlschema'
     # ./app/services/candidates/registrations/registration_session.rb:145:in `to_json'
     # ./app/services/candidates/registrations/registration_store.rb:63:in `serialize'
     # ./app/services/candidates/registrations/registration_store.rb:28:in `store!'
     # ./app/controllers/concerns/candidates/registrations/current_registration.rb:14:in `persist'
     # ./app/controllers/candidates/registrations/background_checks_controller.rb:11:in `create'
     # /usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
     # /usr/local/bundle/gems/bullet-6.1.0/lib/bullet/rack.rb:15:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/tempfile_reaper.rb:17:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/etag.rb:27:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/conditional_get.rb:40:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:269:in `context'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/session/abstract/id.rb:263:in `call'
     # /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:38:in `call_app'
     # /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `block in call'
     # /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/rack/logger.rb:26:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
     # /usr/local/bundle/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
     # /usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'
     # /usr/local/bundle/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
     # /usr/local/bundle/gems/railties-5.2.4.1/lib/rails/engine.rb:524:in `call'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /usr/local/bundle/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # /usr/local/bundle/gems/rails-controller-testing-1.0.4/lib/rails/controller/testing/integration.rb:13:in `post'
     # ./spec/controllers/candidates/registrations/background_checks_controller_spec.rb:40:in `block (4 levels) in <top (required)>'
     # <internal:core> core/array.rb:902:in `reverse_each'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
     # /usr/local/lib/mri/bundler/cli/exec.rb:63:in `kernel_load'
     # /usr/local/lib/mri/bundler/cli/exec.rb:28:in `run'
     # /usr/local/lib/mri/bundler/cli.rb:476:in `exec'
     # /usr/local/lib/mri/bundler/cli.rb:30:in `dispatch'
     # /usr/local/lib/mri/bundler/cli.rb:24:in `start'
     # /usr/local/lib/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /usr/local/lib/mri/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /usr/local/lib/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # <internal:core> core/kernel.rb:400:in `load'
     # <internal:core> core/kernel.rb:400:in `load'
```
Interestingly using [flavorjones/truffleruby:latest](https://hub.docker.com/layers/flavorjones/truffleruby/latest/images/sha256-599f039d22b784eb6f665cfe7fc203082a9c8642558588c35ebf0218a7064ccb?context=explore) I don't see the issue.

https://github.com/petenorth/schools-experience/actions/runs/1053463812

**Comment by eregon** [comment]
Can be reproduced with:
```
$ docker pull ghcr.io/flavorjones/truffleruby:21.2.0
$ docker run --rm -it ghcr.io/flavorjones/truffleruby:21.2.0 ruby -rdate -e 'p DateTime.now'
date_strftime.c:540:in `date_strftime_with_tmx': External LLVMFunction __strspn_c1 cannot be found. (com.oracle.truffle.llvm.runtime.except.LLVMLinkerException) (RuntimeError)
Translated to internal error
	from date_strftime.c:631:in `date_strftime'
	from date_core.c:6621:in `date_strftime_alloc'
	from date_core.c:6967:in `strftimev'
	from date_core.c:8241:in `dt_lite_to_s'
	from /usr/local/lib/truffle/truffle/cext_ruby.rb:41:in `to_s'
	from <internal:core> core/type.rb:539:in `rb_obj_as_string'
	from /usr/local/lib/truffle/truffle/cext.rb:1715:in `rb_obj_as_string'
	from object.c:78:in `rb_obj_as_string'
	from printf.c:37:in `rb_value_to_str'
	from printf.c:76:in `rb_tr_fprintf_value'
	from printf.c:88:in `rb_enc_vsprintf'
	from printf.c:102:in `rb_enc_sprintf'
	from date_core.c:6576:in `mk_inspect'
	from date_core.c:6599:in `d_lite_inspect'
	from /usr/local/lib/truffle/truffle/cext_ruby.rb:41:in `inspect'
	from <internal:core> core/post.rb:94:in `block in p'
	from <internal:core> core/post.rb:94:in `each'
	from <internal:core> core/post.rb:94:in `p'
	from -e:1:in `<main>'
```

**Comment by eregon** [comment]
And indeed it does not happen on `nightly`, most likely because those builds are done on Ubuntu 20.04, which is more recent than releases which are done on Oracle Linux 6.
```
$ docker run --rm -it ghcr.io/flavorjones/truffleruby:nightly ruby -rdate -e 'p DateTime.now'
#<DateTime: 2021-07-21T19:11:29+00:00 ((2459417j,69089s,239708029n),+0s,2299161j)>
```

> Interestingly using flavorjones/truffleruby:latest I don't see the issue.

I guess you mean `:nightly` and not `:latest`, right?

**Comment by eregon** [comment]
A workaround until this is fixed is to explicitly install the `date` gem (or to use `nightly`):
```
$ podman run --rm -it ghcr.io/flavorjones/truffleruby:21.2.0 bash -c "gem i date && ruby -rdate -e 'p DateTime.now'"
Fetching date-3.1.1.gem
Building native extensions. This could take a while...
Successfully installed date-3.1.1
1 gem installed
#<DateTime: 2021-07-21T21:00:09+00:00 ((2459417j,75609s,417514186n),+0s,2299161j)>
```

**Comment by petenorth** [comment]
The base image that I don't see the issue on is  `flavorjones/truffleruby:nightly-buster-slim` 

into which additional packages are added

`RUN apt-get update && apt-get install -y curl gnupg2 git libpq-dev shared-mime-info`

**Comment by eregon** [comment]
Yeah that's based on nightly builds so those don't have the issues because they are built on a newer distribution, Ubuntu 20.04: https://github.com/flavorjones/truffleruby/blob/master/tool/dockerfiles/nightly.dockerfile#L6

**Comment by eregon** [comment]
Fix in https://github.com/oracle/truffleruby/commit/b37e09e842116044db8ad8adbc3f7fc7812cc6f4

**Comment by petenorth** [comment]
Didn't spot the 21.2.0.1 release .

Did a run of the failing pipeline with the flavorjones Docker image for 21.2.0, 21.2.0.1 and nightly-slim .

https://github.com/petenorth/schools-experience/runs/3364455234?check_suite_focus=true

21.2.0 has errors
21.2.0.1 succeeds

**Comment by eregon** [comment]
Looks like I forgot to reply here.

Yes, this is fixed and we got a release for it: https://github.com/oracle/truffleruby/releases/tag/vm-21.2.0.1
Also in ruby-install/ruby-build/RVM.
