### ISSUE TITLE
Addressable specs pass on truffleruby-21.1 but not on truffleruby-21.2

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2408]
From https://github.com/ruby/setup-ruby/issues/208

**Comment by eregon** [comment]
Locally on Linux,

with just:
```
git clone
bundle install
bundle exec rake spec
```
it passes.

But with BUNDLE_WITHOUT from https://github.com/sporkmonger/addressable/blob/a079a52ba5a5cb43cadd5edaa684ee6874dafaa8/.github/workflows/test.yml#L51:
```
export BUNDLE_WITHOUT=development:coverage
bundle install
bundle exec rake spec
```
then it does fail like in CI (https://github.com/dentarg/addressable/runs/3168756143?check_suite_focus=true).

**Comment by eregon** [comment]
BTW it seems fairly when it errors, which seems due to RSpec using Ripper:
```
ripper.y:13032:in `ripper_parse0'
/home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1526:in `rb_ensure'
exception.c:97:in `rb_ensure'
ripper.y:13070:in `ripper_parse'
/home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:41:in `parse'
/home/eregon/.rubies/truffleruby-dev/lib/mri/ripper/sexp.rb:33:in `sexp'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.10.2/lib/rspec/support/source.rb:55:in `ast'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-support-3.10.2/lib/rspec/support/source.rb:71:in `nodes_by_line_number'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:118:in `location_nodes_at_beginning_line'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:96:in `expression_node'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:88:in `line_range_of_location_nodes_in_expression'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:57:in `line_range_of_expression'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:42:in `expression_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/snippet_extractor.rb:31:in `extract_expression_lines_at'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:231:in `read_failed_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:166:in `failure_slash_error_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:153:in `block in failure_lines'
<internal:core> core/kernel.rb:509:in `tap'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:152:in `failure_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:34:in `colorized_message_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:253:in `formatted_message_and_backtrace'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:88:in `fully_formatted_lines'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/exception_presenter.rb:80:in `fully_formatted'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/notifications.rb:200:in `fully_formatted'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples'
<internal:core> core/enumerable.rb:354:in `each_with_index'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:209:in `block in notify'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `each'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:208:in `notify'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:178:in `block in finish'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:194:in `close_after'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:174:in `finish'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:76:in `report'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
```

**Comment by eregon** [comment]
Smaller reproducer:
```
$ bundle exec rspec ./spec/addressable/idna_spec.rb

Could not load native IDN implementation.
....F.............................

Failures:

  1) Addressable::IDNA when using the pure-Ruby implementation it should behave like converting from unicode to ASCII should convert 'www.Iñtërnâtiônàlizætiøn.com' correctly
     Failure/Error:
       expect(Addressable::IDNA.to_ascii(
         "www.I\xC3\xB1t\xC3\xABrn\xC3\xA2ti\xC3\xB4" +
         "n\xC3\xA0liz\xC3\xA6ti\xC3\xB8n.com"
       )).to eq("www.xn--itrntinliztin-vdb0a5exd8ewcye.com")
     
       expected: "www.xn--itrntinliztin-vdb0a5exd8ewcye.com"
            got: "www.xn--internationaliztin-2ub67ax77adbdo1k.com"
     
       (compared using ==)
     Shared Example Group: "converting from unicode to ASCII" called from ./spec/addressable/idna_spec.rb:266
     # ./spec/addressable/idna_spec.rb:44:in `block (2 levels) in <top (required)>'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/cli/exec.rb:63:in `kernel_load'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/cli/exec.rb:28:in `run'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/cli.rb:476:in `exec'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/cli.rb:30:in `dispatch'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/cli.rb:24:in `start'
     # /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /home/eregon/.rubies/truffleruby-dev/lib/mri/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'

Finished in 1.65 seconds (files took 0.52249 seconds to load)
34 examples, 1 failure

Failed examples:

rspec ./spec/addressable/idna_spec.rb:42 # Addressable::IDNA when using the pure-Ruby implementation it should behave like converting from unicode to ASCII should convert 'www.Iñtërnâtiônàlizætiøn.com' correctly
```

**Comment by eregon** [comment]
I reduced that spec to just:
```ruby
# frozen_string_literal: true

require "spec_helper"
require "addressable/idna"

shared_examples_for "converting from unicode to ASCII" do
  it "should convert 'www.google.com' correctly" do
    expect(Addressable::IDNA.to_ascii("www.google.com")).to eq("www.google.com")
  end

  it "should convert 'www.Iñtërnâtiônàlizætiøn.com' correctly" do
    "www.Iñtërnâtiônàlizætiøn.com"
    expect(Addressable::IDNA.to_ascii(
      "www.I\xC3\xB1t\xC3\xABrn\xC3\xA2ti\xC3\xB4" +
      "n\xC3\xA0liz\xC3\xA6ti\xC3\xB8n.com"
    )).to eq("www.xn--itrntinliztin-vdb0a5exd8ewcye.com")
  end

  # it "should convert 'www.Iñtërnâtiônàlizætiøn.com' correctly" do
  #   expect(Addressable::IDNA.to_ascii(
  #     "www.In\xCC\x83te\xCC\x88rna\xCC\x82tio\xCC\x82n" +
  #     "a\xCC\x80liz\xC3\xA6ti\xC3\xB8n.com"
  #   )).to eq("www.xn--itrntinliztin-vdb0a5exd8ewcye.com")
  # end
end

describe Addressable::IDNA, "when using the pure-Ruby implementation" do
  before do
    Addressable.send(:remove_const, :IDNA)
    load "addressable/idna/pure.rb"
  end

  it_should_behave_like "converting from unicode to ASCII"

  require "fiber"

  it "should not blow up inside fibers" do
    f = Fiber.new do
      # This causes the failure
      Addressable.send(:remove_const, :IDNA)
      load "addressable/idna/pure.rb"
    end
    f.resume
  end
end
```

The
```ruby
      Addressable.send(:remove_const, :IDNA)
      load "addressable/idna/pure.rb"
```
in the Fiber seems to somehow cause the error.

BTW, this spec removes the IDNA constant and reloads the file for *every* example/`it`, is that intended @sporkmonger?

**Comment by dentarg** [comment]
> BTW, this spec removes the IDNA constant and reloads the file for _every_ example/`it` (36 times for ./spec/addressable/idna_spec.rb)

I can only speculate, but seeing Addressable is an old code base and [the `:remove_const` thing was added 10 years ago](https://github.com/sporkmonger/addressable/commit/3db3329f02f675d45cccf45220de019f5d9391b5#diff-11298fc266939df0611b1b5ed71264a59b5fa67864611588258c87d1ecdd4571R201), I'm guessing it was one way to solve the problem at hand then and no more thought has been given to it :). If there's a better way of doing we can update the specs with it.

**Comment by eregon** [comment]
The issue is caused by those `Addressable.send(:remove_const, :IDNA)` + `load "addressable/idna/pure.rb"`.
What happens then is the `COMPOSITION_TABLE` during the second `load` might actually still refer to the `COMPOSITION_TABLE` from the first load, because it's read from the first load Addressable::IDNA.
That's a bug in TruffleRuby. It doesn't seem a great idea to reload a file 36 times in specs, but according to Ruby semantics it should work (although it's obviously slow, reloads the Marshal file 36 times, etc).

During parsing TruffleRuby already sets up a "constants scope" called `LexicalScope`, and store the value of the module there.
The value is updated during the second `load`, but there is likely some caching going on which does not notice the update.
Recently we cache the result of the parser, which is why this is a new bug.
Without caching the parser result the second load would be like loading a different file anew and avoid the issue.

```
# [:name, size, object_id]
load [1, true]
[:COMPOSITION_TABLE, 918, 180344]
241
load [2, true]
[:COMPOSITION_TABLE, 918, 180344]
usage
[:COMPOSITION_TABLE, 0, 340744]
```

**Comment by eregon** [comment]
I'm going to fix this by not caching the 2nd and later loads of the same file in a context, and adding a check that the LexicalScope's module is never overridden with another module. With that it works fine, the PR should land soon.

**Comment by eregon** [comment]
I realized there is also a way to trigger this without reloading a file with something like:
```
$ jt ruby -e '2.times { module M; A=Object.new; p A; end; Object.send :remove_const, :M }'
#<Object:0x88>
Overriding module for static LexicalScope, old=M@411291e5, new=M@6e28bb87 (com.oracle.truffle.api.CompilerDirectives.ShouldNotReachHere)
	from org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:557)
	from org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:503)
	from org.truffleruby.language.LexicalScope.unsafeSetLiveModule(LexicalScope.java:54)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.prepareLexicalScope(ModuleBodyDefinitionNode.java:86)
	from org.truffleruby.language.methods.ModuleBodyDefinitionNode.createMethod(ModuleBodyDefinitionNode.java:61)
	from org.truffleruby.language.objects.RunModuleDefinitionNode.execute(RunModuleDefinitionNode.java:37)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:70)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:33)
	from org.truffleruby.language.RubyProcRootNode.execute(RubyProcRootNode.java:60)
	from org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
<internal:core> core/integer.rb:148:in `block in <main>'
	from <internal:core> core/integer.rb:148:in `times'
	from -e:1:in `<main>'
```
So at least it's an error now (before it would show twice the same object).
Hopefully nobody writes such code, but if somebody does they'll see an error.

A possible fix might be to not use any static LexicalScope inside module bodies, and on `def` for methods, we would check if the LexicalScope (from the frame's InternalMethod) is the expected one, if not copy (would need `cloneUninitialized()`) the CallTarget and change the LexicalScope stored in it. The static LexicalScope could then be stored in e.g. the RootNode of the CallTarget, and that could still fold in single-context mode with PE, but it would not be great in interpreter (could potentially read from the frame's InternalMethod in interpreter instead).
Potentially we could also reparse a method body if the LexicalScope is different, but that would mean we need to keep the JRuby AST around just for that.

Could also try to use Assumptions for this, and speculate the LexicalScope of a method will be the one expected when parsing, if not invalidate and have the constant lookup nodes then use dynamic constant lookup (slower, from the frame's InternalMethod).
