### ISSUE TITLE
An internal exception escaped out of the interpreter while running rubocop test

### ISSUE THREAD

**Issue by jaimerave** [oracle/truffleruby#2412]
Running `bundle exec rspec spec/rubocop/cop/style/format_string_token_spec.rb` generates the following error:

```
rubocop git:(master) bundle exec rspec spec/rubocop/cop/style/format_string_token_spec.rb 
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 50003
.

Finished in 3.82 seconds (files took 8.55 seconds to load)
2 examples, 0 failures

Randomized with seed 50003


truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

Index 14 out of bounds for length 3 (java.lang.ArrayIndexOutOfBoundsException)
	from org.joni.Regex.nameToBackrefNumber(Regex.java:247)
	from org.truffleruby.core.regexp.MatchDataNodes$GetIndexNode.getBackRef(MatchDataNodes.java:416)
	from org.truffleruby.core.regexp.MatchDataNodes$GetIndexNode.getIndexSymbolSingleMatch(MatchDataNodes.java:316)
	from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexNodeFactory$GetIndexNodeGen.executeAndSpecialize(MatchDataNodesFactory.java:540)
	from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexNodeFactory$GetIndexNodeGen.execute(MatchDataNodesFactory.java:453)
	from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:53)
	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:652)
/Users/jTorres/Projects/rubocop/lib/rubocop/cop/utils/format_string.rb:51:in `[]'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/utils/format_string.rb:51:in `initialize'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/utils/format_string.rb:113:in `block in parse'
	from <internal:core> core/string.rb:257:in `scan'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/utils/format_string.rb:113:in `parse'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/utils/format_string.rb:94:in `format_sequences'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/style/format_string_token.rb:145:in `token_ranges'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/style/format_string_token.rb:129:in `tokens'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/style/format_string_token.rb:157:in `collect_detections'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/style/format_string_token.rb:76:in `on_str'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:98:in `each'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:69:in `on_str'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:159:in `block in on_send'
	from <internal:core> core/enumerable.rb:354:in `each_with_index'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:156:in `on_send'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:71:in `on_send'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `each'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:71:in `on_pair'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `each'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:71:in `on_hash'
	from /Users/jTorres/Projects/rubocop-ast/lib/rubocop/ast/traversal.rb:20:in `walk'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/commissioner.rb:86:in `investigate'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/team.rb:155:in `investigate_partial'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/cop/team.rb:83:in `investigate'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/rspec/cop_helper.rb:50:in `_investigate'
	from /Users/jTorres/Projects/rubocop/lib/rubocop/rspec/expect_offense.rb:120:in `expect_offense'
	from /Users/jTorres/Projects/rubocop/spec/rubocop/cop/style/format_string_token_spec.rb:203:in `block (2 levels) in <top (required)>'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:627:in `run_around_example_hooks_for'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
	from <internal:core> core/kernel.rb:376:in `load'
	from <internal:core> core/kernel.rb:376:in `load'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/bin/rspec:23:in `<top (required)>'
	from <internal:core> core/kernel.rb:376:in `load'
	from <internal:core> core/kernel.rb:376:in `load'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli/exec.rb:28:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:476:in `exec'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:30:in `dispatch'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:24:in `start'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
	from <internal:core> core/kernel.rb:376:in `load'
	from <internal:core> core/kernel.rb:376:in `load'
	from /Users/jTorres/.rbenv/versions/truffleruby-dev/bin/bundle:42:in `<main>'
```

This is with `truffleruby 21.3.0-dev-a2dc7291, like ruby 2.7.3, GraalVM CE Native [x86_64-darwin]`

**Comment by eregon** [comment]
Thanks for the report, I can reproduce.

**Comment by eregon** [comment]
The full Regexp is:
```ruby
/           % (?<type>%)
          | % (?<flags>(?-mix:[ #0+-]|(?-mix:(\d+)\$))*)
            (?:
              (?: (?-mix:(?<width>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:\.(?<precision>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:<(?<name>\w+)>)?
                | (?-mix:(?<width>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:<(?<name>\w+)>) (?-mix:\.(?<precision>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))?
                | (?-mix:<(?<name>\w+)>) (?<more_flags>(?-mix:[ #0+-]|(?-mix:(\d+)\$))*) (?-mix:(?<width>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:\.(?<precision>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))?
              ) (?-mix:(?<type>[bBdiouxXeEfgGaAcps]))
              | (?-mix:(?<width>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:\.(?<precision>(?-mix:\d+|(?-mix:\*(?-mix:(\d+)\$)?))))? (?-mix:\{(?<name>\w+)\})
            )/x
```
from https://github.com/rubocop/rubocop/blob/39fcf1c5684915adad4a9ab8babb93f37367fba8/lib/rubocop/cop/utils/format_string.rb#L18
And the access is `match[:width]`.

I see that TRegex reports it has `numberOfCaptureGroups = 3`, but I guess it should be a higher number since there is at least `type, flags, width, precision, name` named capture groups.
What's special though is this Regexp also has unnamed/numbered captured groups, which is probably the cause of this issue (the `(\d+)`).
@jirkamarsik Could you investigate? This error does not happen with Joni.

**Comment by jirkamarsik** [comment]
When you mix named and unnamed capture groups in a single regex, the unnamed capture groups cease to be capture groups and function as the non-capturing groups `(?:...)`. The issue was with the line comment character (`#`) appearing inside a character class. The first pass that identifies all the capture groups in the regex uses a stripped down parser and that parser omitted the case when `#` appears in a character class and therefore does not signal a line break. I have a patch ready that fixes this.

I have also extended TRegex's coverage so that we now support regular expressions with multiple named capture groups sharing the same name, unless these capture groups are being referenced in a backreference. This should result in improved performance for regexps such as the example given above.
