### ISSUE TITLE
The --regexp-instrument-creation errors out printing statistics

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2414]
While looking into regular expression performance, I came across some options that looked like they could be helpful. Unfortunately, the `--regexp-instrument-creation` throws an exception when printing out its statistics due to a regexp key (a `Rope`) having an `ASCII-8BIT` encoding, which we can't convert to a Java string.:

```
> jt ruby --regexp-instrument-creation -e 'p :hi'
Using TruffleRuby with Graal: mxbuild/truffleruby-jvm-ce
$ /home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm-ce/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=/home/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/src/main/ruby/truffleruby \
  --regexp-instrument-creation \
  -e \
  'p :hi'
:hi
--------------------
Regular expression statistics
--------------------
  Compilation

truffleruby: Unexpected internal exception in at_exit,
please report it to https://github.com/oracle/truffleruby/issues.

Cannot return a Charset for the BINARY Ruby Encoding (java.lang.UnsupportedOperationException)
	from org.truffleruby.core.encoding.EncodingManager.charsetForEncoding(EncodingManager.java:295)
	from org.truffleruby.core.rope.RopeOperations.decode(RopeOperations.java:247)
	from org.truffleruby.core.rope.Rope.toString(Rope.java:180)
	from org.truffleruby.core.regexp.RegexpCacheKey.toString(RegexpCacheKey.java:51)
	from org.truffleruby.core.regexp.TruffleRegexpNodes$RegexpStatsNode.fillinInstrumentData(TruffleRegexpNodes.java:341)
	from org.truffleruby.core.regexp.TruffleRegexpNodes$CompilationStatsArrayNode.buildStatsArray(TruffleRegexpNodes.java:356)
	from org.truffleruby.core.regexp.TruffleRegexpNodesFactory$CompilationStatsArrayNodeFactory$CompilationStatsArrayNodeGen.executeAndSpecialize(TruffleRegexpNodesFactory.java:463)
	from org.truffleruby.core.regexp.TruffleRegexpNodesFactory$CompilationStatsArrayNodeFactory$CompilationStatsArrayNodeGen.execute(TruffleRegexpNodesFactory.java:450)
	from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:53)
	from jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:652)
<internal:core> core/truffle/regexp_operations.rb:158:in `compilation_stats_array'
	from <internal:core> core/truffle/regexp_operations.rb:158:in `compilation_stats'
	from <internal:core> core/truffle/regexp_operations.rb:170:in `print_stats'
	from <internal:core> core/truffle/regexp_operations.rb:59:in `block (2 levels) in <module:RegexpOperations>'
```

**Comment by nirvdrum** [comment]
With a local modification, I've seen that all of the regexp keys with an `ASCII-8BIT` encoding could be represented as ASCII-only strings with the `US-ASCII` encoding. We don't generally make that change when decoding ropes because we can't be sure that bytes < 128 actually correspond to an ASCII character. So, instead we throw an exception indicating the `Rope` instance can't be converted to a `java.lang.String`.

**Comment by eregon** [comment]
`rope.toString()` should not be used, it's only allowed for debugging.
`RopeOperations.decodeOrEscapeBinaryRope(rope)` should be used instead.

**Comment by eregon** [comment]
That said, it seems bad in the debugger if rope.toString() throws, so we should use `RopeOperations.decodeOrEscapeBinaryRope(Rope rope, byte[] bytes)` in `Rope#toString`.
One issue though is that calls `rope.isAsciiOnly()` and that has side effects for NativeRope.

**Comment by nirvdrum** [comment]
Thanks. `RopeOperations.decodeRope` handles the conversion. I was using `RopeOperations.decode`.
