### ISSUE TITLE
Rubocop test fails under Truffleruby if a folder is named "{}"

### ISSUE THREAD

**Issue by jaimerave** [oracle/truffleruby#2425]
Using truffleruby 21.3.0-dev-153f8166, like ruby 2.7.3, GraalVM CE Native [x86_64-darwin].
```
bundle exec rspec spec/rubocop/target_finder_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 59623
......................F..............................

Failures:

  1) RuboCop::TargetFinder#find_files works also if a folder is named "{}"
     Failure/Error: expect(found_basenames).to include('ruby4.rb')
       expected ["ruby3.rb"] to include "ruby4.rb"
     # ./spec/rubocop/target_finder_spec.rb:433:in `block (3 levels) in <top (required)>'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (4 levels) in <top (required)>'
     # <internal:core> core/dir.rb:290:in `chdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:30:in `block (3 levels) in <top (required)>'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/tmpdir.rb:89:in `mktmpdir'
     # ./lib/rubocop/rspec/shared_contexts.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli/exec.rb:63:in `kernel_load'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli/exec.rb:28:in `run'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:476:in `exec'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:30:in `dispatch'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/cli.rb:24:in `start'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/mri/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /Users/jTorres/.rbenv/versions/truffleruby-dev/lib/gems/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # <internal:core> core/kernel.rb:376:in `load'
     # <internal:core> core/kernel.rb:376:in `load'

Finished in 5.68 seconds (files took 6.72 seconds to load)
53 examples, 1 failure

Failed examples:

rspec ./spec/rubocop/target_finder_spec.rb:423 # RuboCop::TargetFinder#find_files works also if a folder is named "{}"

Randomized with seed 59623
```

It works fine with Ruby 2.7.4

**Comment by eregon** [comment]
@bjfish Could you investigate?
I guess it's about Dir.glob or so not escaping those.

**Comment by bjfish** [comment]
Yes, it appears to be an issue with `ruby -e 'p Dir.glob("\\{}/*")'` not finding the files in a directory named `{}`.  This relates to internal issue GR-28734.

**Comment by bjfish** [comment]
@jaimerave This is now fixed at https://github.com/oracle/truffleruby/commit/d772ae7b4a9a72cfbc4797ab4ef1449040c1b2eb and should be included in the next truffleruby-head build. Please let me know if you see any more issues.

**Comment by jaimerave** [comment]
@bjfish thanks! is working great, all the tests are passing now.
