### ISSUE TITLE
sprintf error

### ISSUE THREAD

**Issue by petenorth** [oracle/truffleruby#2451]
truffleruby 21.3.0-dev-5e49a731, like ruby 2.7.4, GraalVM CE Native [x86_64-linux]

Started seeing this 

```
     TypeError:
       TruffleRuby doesn't have a case for the org.truffleruby.core.format.write.bytes.WritePaddedBytesNodeGen node with values of type java.lang.Integer=8 java.lang.Integer=-1 [B
       	from org.truffleruby.core.format.write.bytes.WritePaddedBytesNodeGen.executeAndSpecialize(WritePaddedBytesNodeGen.java:90)
       	from org.truffleruby.core.format.write.bytes.WritePaddedBytesNodeGen.execute(WritePaddedBytesNodeGen.java:56)
       	from org.truffleruby.core.format.control.SequenceNode.execute(SequenceNode.java:29)
       	from org.truffleruby.core.format.FormatRootNode.execute(FormatRootNode.java:60)
       	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:650)
     # <internal:core> core/string.rb:1436:in `sprintf'
     # <internal:core> core/string.rb:1436:in `%'
```

https://github.com/petenorth/schools-experience/runs/3729226773?check_suite_focus=true

From https://github.com/petenorth/schools-experience/blob/58a3e32fb82a69fdcbd6954e4a42da4c322fe9c0/app/services/bookings/gitis/event_logger.rb#L26

**Comment by gogainda** [comment]
related to https://github.com/oracle/truffleruby/issues/2436

**Comment by eregon** [comment]
@aardvark179 Could you take a look?

**Comment by petenorth** [comment]
This seems to have been fixed in

truffleruby 22.0.0-dev-641865bc, like ruby 2.7.4, GraalVM CE Native [x86_64-linux]
