### ISSUE TITLE
Core file paths aren't clickable in a terminal

### ISSUE THREAD

**Issue by chrisseaton** [oracle/truffleruby#2537]
```
<internal:core> core/string.rb:354:in `encode!': wrong number of arguments (given 3, expected 0) (ArgumentError)
        from <internal:core> core/string.rb:431:in `encode'
        from <internal:core> core/array.rb:589:in `join'
        from <internal:core> core/posix.rb:132:in `attach_function_eagerly'
        from <internal:core> core/posix.rb:98:in `getpid'
```

Is it possible to turn on full or relative paths, so I can click these paths in my terminals?

**Comment by eregon** [comment]
They are designed to:
* Always look the same, so the backtrace are consistent and can be tested meaningfully
* Clickable in IntelliJ

If we'd just print an absolute paths like in the past, we'd e.g. break tests relying in backtrace and various gems which might rely on the `<internal:` prefix.

File paths are never clickable in my terminal (Gnome Terminal), so I'm not sure what you expect.
If you mean selection, then `core/string.rb` gets selected for me.

**Comment by chrisseaton** [comment]
In VSCode I can click on Ruby file's mentioned in terminal output to open them. That doesn't work with core, as VSCode thinks the file doesn't exist (as it doesn't at this location) so doesn't make it clickable.

<img width="1294" alt="Screenshot 2021-11-23 at 12 36 57" src="https://user-images.githubusercontent.com/341094/143025357-a62d72eb-9add-42d5-a361-d3c3a5bde4c9.png">

**Comment by eregon** [comment]
I see, then we could try `<internal:core> relative path from initial CWD` or `<internal:core> absolute path`.
The latter might be fairly long and hard to read.
The former depends on initial CWD, which can be weird (e.g., the relative path might include `..`).

They are both not stable paths (depends on CWD or location of the truffleruby checkout), hence the current approach seems best by default, notably for tests and issue reports (if they were absolute paths from another machine then we couldn't click them in IntelliJ), but we could have an option to enable one of those variants.

Absolute paths seems easier to implement (as an option), PR welcome.
I think it would be better if we could teach VSCode to search harder like IntelliJ does, because that means e.g. you can click on backtraces from other people and not just runs on the current machine.
