### ISSUE TITLE
The require statement cannot be run in java context eval(  )

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [oracle/truffleruby#2540]
my java code:
```java
             URL TestInterFaceImp = PolyglotDebug.class.getResource("TestInterFaceImp.rb");
            Source TestInterFaceImpSrc = Source.newBuilder("ruby", TestInterFaceImp).build();
            Value eval = ctx.eval(TestInterFaceImpSrc);
            TestInterFace tf2= eval. as(TestInterFace.class);
            tf2.m2("ddd");
```
TestInterFace.java
```java

public interface  TestInterFace   { 
    String a="1";
    public  void m1();
    public  void m2(String a);

}

```

ruby code:

```ruby
require "testImport" #import  testImport.rb
 
def m1()
  
end



  def m2(a)
 
  end

```

testImport.rb code
```ruby
module Test
  def method
    
  end
end
```

files in target/ 
![image](https://user-images.githubusercontent.com/57204004/143162945-8d90b2b1-89fd-44f4-940d-43f7240cf4af.png)

when i run code. i get a error 

```bash
Exception in thread "main" cannot load such file -- testImport (LoadError)
	at <ruby> Kernel#raise(resource:/truffleruby/core/kernel.rb:674:18847-18949)
	at <ruby> Kernel#gem_original_require(resource:/truffleruby/core/kernel.rb:236:7388-7444)
	at <ruby> Kernel#require(../../../lib/jvm/graalvm-ee-java8-21.3.0/jre/languages/ruby/lib/mri/rubygems/core_ext/kernel_require.rb:83:2509-2547)
	at <ruby> UnboundMethod#bind_call(resource:/truffleruby/core/unbound_method.rb:18:553-586)
	at <ruby> Kernel#require(resource:/truffleruby/core/kernel.rb:272:8832-8875)
	at <ruby> <top (required)>(polyglot-debug/target/classes/org/graalvm/demos/TestInterFaceImp.rb:1:0-19)
	at <ruby> parsing-request(Unknown)
	at org.graalvm.polyglot.Context.eval(Context.java:379)
Context.java:379
	at org.graalvm.demos.PolyglotDebug.main(PolyglotDebug.java:91)
PolyglotDebug.java:91
```

how to fix it ? please help me .

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Does the context have to execute(eval) the imported ruby ​​file before it can be used

**Comment by eregon** [comment]
`require 'file.rb'` never looks in the current working directory in Ruby, you need either `require_relative` or `require './file.rb'` (only works with the correct working directory of course).

In general you should probably put both files in the jar or both files on the filesystem for simplicity.
I would avoid putting Ruby files in the `.jar` as that's simpler if it's not necessary (there is no way currently to `require` a file inside a jar in TruffleRuby).

**Comment by YU5Z8X2CvH1fv4ep** [comment]
ok ! thanks for your team!
