### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2545]
MRI Ruby :
```
 ~ % ruby -e 'key = "\x00"*2; key[0] = [0xB9].pack("C*"); key[1] = [0xB9].pack("C*"); puts key.encoding'
ASCII-8BIT
 ~ % ruby -e 'key = "\x00"*2; key[1] = [0xB9].pack("C*"); key[0] = [0xB9].pack("C*"); puts key.encoding'
ASCII-8BIT
```

Truffleruby latest:
```
 ~ % ruby -e 'key = "\x00"*2; key[1] = [0xB9].pack("C*"); key[0] = [0xB9].pack("C*"); puts key.encoding'
<internal:core> core/truffle/string_operations.rb:344:in `assign_index': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from <internal:core> core/string.rb:965:in `[]='
	from -e:1:in `<main>'
~ % ruby -e 'key = "\x00"*2; key[0] = [0xB9].pack("C*"); key[1] = [0xB9].pack("C*"); puts key.encoding'
ASCII-8BIT
```

**Comment by eregon** [comment]
It looks like `String#[]=` should negotiate an encoding and not just check there are compatible.
`key = "\x00"*2` is UTF-8, `[0xB9].pack("C*")` is BINARY.

Not clear why one of the orders works.
@bjfish Can you take a look?

**Comment by bjfish** [comment]
@gogainda This is now fixed at: https://github.com/oracle/truffleruby/commit/ebdab9d81b10998c6f692581568451277020e466. Thanks!
