### ISSUE TITLE
cext.rb:978:in `rb_path_to_class': TypeError

### ISSUE THREAD

**Issue by dogweather** [oracle/truffleruby#2563]
I get this error when trying to run a Rails 6.1.4.4 app via either `rails console` or `rails server`. Using Truffle Ruby 21.3.0.

```
/Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/truffle/truffle/cext.rb:978:in `rb_path_to_class': TypeError (TypeError)
	from class.c:54:in `rb_path2class'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/digest-3.1.0/ext/digest/digest.h:57:in `rb_digest_namespace'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/digest-3.1.0/ext/digest/sha2/sha2init.c:43:in `Init_sha2'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/digest-3.1.0/lib/digest/sha2/loader.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/digest-3.1.0/lib/digest/sha2.rb:14:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/sprockets-3.7.2/lib/sprockets/digest_utils.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/sprockets-3.7.2/lib/sprockets/cache.rb:2:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/sprockets-3.7.2/lib/sprockets.rb:3:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/sprockets-rails-3.4.2/lib/sprockets/railtie.rb:6:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `block in require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:332:in `require'
	from /Users/robb/src/PublicLaw/website/config/application.rb:16:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/command/actions.rb:22:in `require_application!'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/commands/console/console_command.rb:101:in `perform'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'
	from /Users/robb/.rbenv/versions/truffleruby-21.3.0/lib/gems/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from bin/rails:6:in `<main>'
```

**Comment by eregon** [comment]
This is already fixed on master, same as https://github.com/oracle/truffleruby/issues/2511#issuecomment-966993472, you can try `truffleruby-dev` (see the README).
(`rb_path_to_class` somewhat surprisingly can also return modules, the logic in 21.3 allowed only classes)

**Comment by dogweather** [comment]
Thanks!
