### ISSUE TITLE
Random gives different values when range passed as float

### ISSUE THREAD

**Issue by sudeeptarlekar** [oracle/truffleruby#2612]
Facing few issues in truffleruby and random behavior is not same in MRI and truffle

```
# Ruby 2.7.0
=> random = Random.new(12_345)
=> random.rand(0...100)
98
=> random.rand(0...100)
29
=> random.rand(0...100)
1

# truffleruby-head
=> random = Random.new(12_345)
=> random.rand(0...100)
98
=> random.rand(0...100)
29
=> random.rand(0...100)
1
```

When max range is passed as `0.0...100.0` or `0.0...100` observed strange behaviour

```
# Ruby 2.7.0
=> random = Random.new(12_345)
=> random.rand(0.0...100.0)
92.96160928171479
=> random.rand(0.0...100.0)
31.63755545817859
=> random.rand(0.0...100.0)
18.391881167709446

# truffleruby-head
=> random = Random.new(12_345)
=> random.rand(0.0...100.0)
0.0
=> random.rand(0.0...100.0)
0.0
=> random.rand(0.0...100.0)
0.0
```

Is this expected or am I missing something here?

Feel free to close if this is irrelevant or duplicate. Thanks in advance

**Comment by eregon** [comment]
This is a bug, thank you for the report.
It seems the issue is in the `Random#.rand(float1...float2)` case, which was probably missed due to being rarely used and probably not well tested.

**Comment by sudeeptarlekar** [comment]
Also observed

```
=> [].sample(random: Random.new(12_345))

<internal:core> core/truffle/random_operations.rb:51:in `invalid_argument': invalid argument - negative limit: 0 (ArgumentError)
	from <internal:core> core/truffle/random_operations.rb:55:in `rand_int'
	from <internal:core> core/truffle/random_operations.rb:24:in `random'
	from <internal:core> core/random.rb:98:in `rand'
	from <internal:core> core/array.rb:1018:in `rand'
	from <internal:core> core/array.rb:1053:in `sample'
	from (irb):1:in `<top (required)>'
	from <internal:core> core/kernel.rb:407:in `loop'
	from <internal:core> core/throw_catch.rb:36:in `catch'
	from <internal:core> core/throw_catch.rb:36:in `catch'
	from /home/starlekar/.rbenv/versions/truffleruby-head/lib/gems/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from <internal:core> core/kernel.rb:376:in `load'
	from <internal:core> core/kernel.rb:376:in `load'
	from /home/starlekar/.rbenv/versions/truffleruby-head/bin/irb:42:in `<main>'
```

**Comment by bjfish** [comment]
The `Array#sample` issue is fixed at https://github.com/oracle/truffleruby/commit/25398cfaa7db38eabbc9a535b445d44b5aa5f449.
