### ISSUE TITLE
missing LLVM builtin: llvm.x86.ssse3.pshuf.b.128 (com.oracle.truffle.llvm.runtime.LLVMUnsupportedException)

### ISSUE THREAD

**Issue by ntkme** [oracle/truffleruby#2640]
google-protobuf-3.20.0 crashes on truffleruby-head.

https://github.com/ruby/truffleruby-dev-builder/releases/download/v20220406.081127/truffleruby-head-macos-latest.tar.gz

```
2022-04-08T06:21:55.2815620Z Ruby Thread id=34 from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:17 terminated with internal error: (java.lang.RuntimeException)
2022-04-08T06:21:55.2816700Z 	from org.truffleruby.core.thread.ThreadManager.printInternalError(ThreadManager.java:336)
2022-04-08T06:21:55.2817580Z 	from org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:324)
2022-04-08T06:21:55.2819370Z 	from org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:292)
2022-04-08T06:21:55.2820260Z 	from java.lang.Thread.run(Thread.java:829)
2022-04-08T06:21:55.2821060Z 	from com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:52)
2022-04-08T06:21:55.2821860Z 	from com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:105)
2022-04-08T06:21:55.2822740Z 	from com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:136)
2022-04-08T06:21:55.2823640Z 	from com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:127)
2022-04-08T06:21:55.2824740Z 	from org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:659)
2022-04-08T06:21:55.2825830Z /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/async.rb:54:in `wait'
2022-04-08T06:21:55.2826920Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/async.rb:54:in `block in await'
2022-04-08T06:21:55.2828010Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/async.rb:53:in `synchronize'
2022-04-08T06:21:55.2829180Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/async.rb:53:in `await'
2022-04-08T06:21:55.2830190Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/host.rb:142:in `await'
2022-04-08T06:21:55.2831270Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/host.rb:43:in `compile_request'
2022-04-08T06:21:55.2832320Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded.rb:199:in `compile_string'
2022-04-08T06:21:55.2833540Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded.rb:45:in `compile_string'
2022-04-08T06:21:55.2834830Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/spec/sass/value/argument_list_spec.rb:65:in `block (3 levels) in <top (required)>'
2022-04-08T06:21:55.2836030Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/matchers/built_in/raise_error.rb:59:in `matches?'
2022-04-08T06:21:55.2837360Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
2022-04-08T06:21:55.2838650Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
2022-04-08T06:21:55.2840100Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
2022-04-08T06:21:55.2841130Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
2022-04-08T06:21:55.2842030Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-expectations-3.11.0/lib/rspec/expectations/expectation_target.rb:139:in `to'
2022-04-08T06:21:55.2842800Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/spec/sass/value/argument_list_spec.rb:64:in `block (2 levels) in <top (required)>'
2022-04-08T06:21:55.2843780Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `instance_exec'
2022-04-08T06:21:55.2844620Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `block in run'
2022-04-08T06:21:55.2845930Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
2022-04-08T06:21:55.2846840Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
2022-04-08T06:21:55.2847790Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
2022-04-08T06:21:55.2848650Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
2022-04-08T06:21:55.2849490Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
2022-04-08T06:21:55.2850340Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
2022-04-08T06:21:55.2851350Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
2022-04-08T06:21:55.2852200Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
2022-04-08T06:21:55.2853060Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
2022-04-08T06:21:55.2853900Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
2022-04-08T06:21:55.2854740Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
2022-04-08T06:21:55.2855670Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
2022-04-08T06:21:55.2856530Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
2022-04-08T06:21:55.2857700Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
2022-04-08T06:21:55.2858640Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
2022-04-08T06:21:55.2859630Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
2022-04-08T06:21:55.2860460Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
2022-04-08T06:21:55.2861290Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
2022-04-08T06:21:55.2862100Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
2022-04-08T06:21:55.2863400Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
2022-04-08T06:21:55.2864350Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
2022-04-08T06:21:55.2865120Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
2022-04-08T06:21:55.2865890Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/rspec-core-3.11.0/exe/rspec:4:in `<main>'
2022-04-08T06:21:55.2866290Z Caused by:
2022-04-08T06:21:55.2866810Z missing LLVM builtin: llvm.x86.ssse3.pshuf.b.128 (com.oracle.truffle.llvm.runtime.LLVMUnsupportedException)
2022-04-08T06:21:55.2888910Z /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/third_party/utf8_range/range2-sse.c:66:in `utf8_range2'
2022-04-08T06:21:55.2890330Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/ruby-upb.h:2025:in `decode_msg'
2022-04-08T06:21:55.2891630Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/ruby-upb.c:570:in `decode_msg'
2022-04-08T06:21:55.2893060Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/ruby-upb.c:570:in `decode_msg'
2022-04-08T06:21:55.2900300Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/ruby-upb.c:1302:in `upb_Decode'
2022-04-08T06:21:55.2901600Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/vendor/bundle/truffleruby/3.0.2.16/gems/google-protobuf-3.20.0/ext/google/protobuf_c/message.c:986:in `Message_decode'
2022-04-08T06:21:55.2905310Z 	from /Users/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:41:in `decode'
2022-04-08T06:21:55.2906360Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:19:in `block (2 levels) in initialize'
2022-04-08T06:21:55.2907320Z 	from <internal:core> core/kernel.rb:407:in `loop'
2022-04-08T06:21:55.2908280Z 	from /Users/runner/work/sass-embedded-host-ruby/sass-embedded-host-ruby/lib/sass/embedded/dispatcher.rb:18:in `block in initialize'
```

**Comment by ntkme** [comment]
Looks like it is thrown from here due to lack of `sse3` support?

https://github.com/oracle/graal/blob/8fd55430939bf4b1a9cf0b1d3ad9f17a42d04450/sulong/projects/com.oracle.truffle.llvm.parser.factories/src/com/oracle/truffle/llvm/parser/factories/BasicNodeFactory.java#L1727

**Comment by ntkme** [comment]
It is introduced by google-protobuf updating utf8_range library: https://github.com/protocolbuffers/protobuf/commit/349d74d92e8268c41fbb726b0a8292d588c63e20#diff-4d00540ada044635f25b301c6d4b9ba72a3a29f32d8e840604a26731e2d81b2d

Downgrade to google-protobuf-3.19.4 works.

**Comment by ntkme** [comment]
https://github.com/protocolbuffers/protobuf/blob/85aa87cbc95edfa63df159eec5536e1d39781f11/third_party/utf8_range/utf8_range.h#L2

**Comment by eregon** [comment]
Thank you for the report.
This is an issue of Sulong which does not handle these SSE3 builtins yet, I've filed https://github.com/oracle/graal/issues/4480
If you can write reproduction instructions there that would be useful.

**Comment by eregon** [comment]
Note, PR to workaround this issue: https://github.com/protocolbuffers/protobuf/pull/9769
We might want to undo that when Sulong supports SSE3, but unsure at this point as it might not be any faster with emulating SSE3.

**Comment by eregon** [comment]
This was fixed in graal (see https://github.com/oracle/graal/issues/4480), and it will be fixed on the next graal import (next week).

**Comment by eregon** [comment]
This is fixed on master now.
