### ISSUE TITLE
Loofah test suite failing on truffleruby-head

### ISSUE THREAD

**Issue by flavorjones** [oracle/truffleruby#2649]
Sometime between these two versions:

- success: `truffleruby 22.2.0-dev-0b02c3cb` (see https://github.com/flavorjones/loofah/runs/6135216946?check_suite_focus=true)
- failure: `truffleruby 22.2.0-dev-a6d2e0bb` (see https://github.com/flavorjones/loofah/runs/6211940003?check_suite_focus=true)

the test suite for [Loofah](https://github.com/flavorjones/loofah) started failing, mostly with this error message:

```
Loofah::HTML::DocumentFragment::bad scrub method#test_0001_raise a ScrubberNotFound exception:
ArgumentError: not enough arguments for required
    /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext.rb:1091:in `rb_exc_raise'
    exception.c:29:in `rb_exc_raise'
    /home/runner/.rubies/truffleruby-head/lib/cext/include/truffleruby/truffleruby.h:234:in `rb_html_document_s_new'
    /home/runner/.rubies/truffleruby-head/lib/truffle/truffle/cext_ruby.rb:[41](https://github.com/flavorjones/loofah/runs/6211940003?check_suite_focus=true#step:4:41):in `new'
    /home/runner/work/loofah/loofah/lib/loofah/html/document_fragment.rb:19:in `parse'
    /home/runner/work/loofah/loofah/test/unit/test_scrubbers.rb:8:in `test_0001_raise a ScrubberNotFound exception'
```

If I have some time this morning I'll try to git-bisect it (it's about 27 commits from 0b02c3cb..a6d2e0bb).

**Comment by flavorjones** [comment]
Git bisect reveals 3a8f5196e6a51dc6143ba3d480a984d1cb1e09e5 is the first bad commit.

Tagging @aardvark179 for awareness.

```
commit 3a8f5196e6a51dc6143ba3d480a984d1cb1e09e5
Author: Duncan MacGregor <duncan.macgregor@oracle.com>
Date:   Thu Feb 24 13:17:21 2022 +0000

    Refactor C processing of Ruby args for constant argument descriptors.

 lib/cext/include/truffleruby/truffleruby.h | 92 ++++++++++++------------------
 src/main/c/cext/args.c                     | 44 ++++++++++++++
 2 files changed, 81 insertions(+), 55 deletions(-)
```

**Comment by aardvark179** [comment]
Thanks for that, I'll take a look.

**Comment by flavorjones** [comment]
Reproduced this on the Nokogiri test suite (which Loofah depends on and subclasses heavily) using 22.2.0-dev-dc3fc7ef:

```
ArgumentError: not enough arguments for required
    /home/flavorjones/code/oss/truffleruby-ws/graal/sdk/mxbuild/linux-amd64/GRAALVM_67F33FC705_JAVA11/graalvm-67f33fc705-java11-22.2.0-dev/languages/ruby/lib/truffle/truffle/cext.rb:1091:in `rb_exc_raise'
    exception.c:29:in `rb_exc_raise'
    /home/flavorjones/code/oss/truffleruby-ws/graal/sdk/mxbuild/linux-amd64/GRAALVM_67F33FC705_JAVA11/graalvm-67f33fc705-java11-22.2.0-dev/languages/ruby/lib/cext/include/truffleruby/truffleruby.h:234:in `new'
    /home/flavorjones/code/oss/truffleruby-ws/graal/sdk/mxbuild/linux-amd64/GRAALVM_67F33FC705_JAVA11/graalvm-67f33fc705-java11-22.2.0-dev/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `new'
    /home/flavorjones/code/oss/nokogiri/lib/nokogiri/xml/builder.rb:312:in `initialize'
    /home/flavorjones/code/oss/nokogiri/test/namespaces/test_namespaces_in_builder_doc.rb:10:in `setup'
```

**Comment by aardvark179** [comment]
Looks like this has uncovered an entirely separate bug. One of the argument counts appears to have been accidentally overwritten by `VALUE`, the post argument count has some marker bits I recognise. I'll track down what's doing this.

**Comment by aardvark179** [comment]
Found the problem. Testing a fix in CI at the moment.

**Comment by aardvark179** [comment]
The fix for this has now been merged to master.

**Comment by flavorjones** [comment]
Thank you!
