### ISSUE TITLE
Cannot load OpenSSL on Fedora 36+

### ISSUE THREAD

**Issue by headius** [oracle/truffleruby#2660]
I am running Fedora 36, which has switched to shipping OpenSSL 3 by default. I have been unable to get TruffleRuby to install with working openssl support.

Installing through RVM does not seem to build the extension correctly, or else it is having trouble finding libssl after built:

```
$ ruby -v
truffleruby 22.1.0, like ruby 3.0.2, GraalVM CE Native [x86_64-linux]

$ ruby -ropenssl -e 1
<internal:core> core/kernel.rb:260:in `require': you may need to install the system OpenSSL library libssl - see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-libssl.md (libcrypto.so.1.0.0: cannot open shared object file: No such file or directory) (RuntimeError)
	from /home/headius/projects/truffleruby-22.1.0-linux-amd64/lib/mri/openssl.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:260:in `require'
```

A tarball of the release produces the same error, even after forcing the openssl extension to reinstall pointing at a compatible version of OpenSSL. The following session uses the OPENSSL_PREFIX environment variable suggested by @eregon on Twitter.

```
[] ~/projects/truffleruby-22.1.0-linux-amd64 $ ls ~/.rvm/usr/lib
engines  libcrypto.a  libcrypto.so  libcrypto.so.1.0.0  libssl.a  libssl.so  libssl.so.1.0.0  pkgconfig

[] ~/projects/truffleruby-22.1.0-linux-amd64 $ OPENSSL_PREFIX=/home/headius/.rvm/usr lib/truffle/post_install_hook.sh
Recompiling the OpenSSL C extension (against the installed libssl)
checking for openssl/ssl.h... yes
creating Makefile
compiling openssl_missing.c
compiling ossl.c
compiling ossl_asn1.c
compiling ossl_bio.c
compiling ossl_bn.c
compiling ossl_cipher.c
compiling ossl_config.c
compiling ossl_digest.c
compiling ossl_engine.c
compiling ossl_hmac.c
compiling ossl_kdf.c
compiling ossl_ns_spki.c
compiling ossl_ocsp.c
compiling ossl_pkcs12.c
compiling ossl_pkcs7.c
compiling ossl_pkey.c
compiling ossl_pkey_dh.c
compiling ossl_pkey_dsa.c
compiling ossl_pkey_ec.c
compiling ossl_pkey_rsa.c
compiling ossl_rand.c
compiling ossl_ssl.c
compiling ossl_ssl_session.c
compiling ossl_ts.c
compiling ossl_x509.c
compiling ossl_x509attr.c
compiling ossl_x509cert.c
compiling ossl_x509crl.c
compiling ossl_x509ext.c
compiling ossl_x509name.c
compiling ossl_x509req.c
compiling ossl_x509revoked.c
compiling ossl_x509store.c
linking shared-object openssl.so
TruffleRuby was successfully installed in /home/headius/projects/truffleruby-22.1.0-linux-amd64

[] ~/projects/truffleruby-22.1.0-linux-amd64 $ ruby -ropenssl -e 1
<internal:core> core/kernel.rb:260:in `require': you may need to install the system OpenSSL library libssl - see https://github.com/oracle/truffleruby/blob/master/doc/user/installing-libssl.md (libcrypto.so.1.0.0: cannot open shared object file: No such file or directory) (RuntimeError)
	from /home/headius/projects/truffleruby-22.1.0-linux-amd64/lib/mri/openssl.rb:13:in `<top (required)>'
	from <internal:core> core/kernel.rb:260:in `require'
```

**Comment by bjfish** [comment]
A related CRuby issue is here: https://bugs.ruby-lang.org/issues/18658

The internal issue for this is: GR-38028

**Comment by eregon** [comment]
I'm looking into this and adding a Docker test for it and docs.
On truffleruby-dev there is a clear message when libssl 3 is used:
```
checking for OpenSSL version >= 1.0.1 and < 3.0.0... -------------------- no
```

**Comment by eregon** [comment]
On Fedora 36, it is possible to install `openssl1.1-devel openssl1.1`, instead of the `openssl-devel openssl` (which is v3).

I think that's not a possibility on Ubuntu 22.04 though (looking at the package list and https://askubuntu.com/questions/1403837/how-do-i-use-openssl-1-1-1-in-ubuntu-22-04).
And of course it's not an option if some other package is installed/needed and depends on openssl3.

We plan to update the OpenSSL C extension to 3.0.0 so for future TruffleRuby releases so one can just use a system libssl 3.

**Comment by eregon** [comment]
I've tried in fedora:36, with the system libssl3 installed, and manually installing openssl 1.1 and that works (i.e., `bin/gem install path` works) with truffleruby 22.1.0.

One thing to note though is it's important to not have already run `lib/truffle/post_install_hook.sh` with libssl3 before as there is caching going on (I'll remove that on master for when OPENSSL_PREFIX is set).
In my case the incorrect caching showed up as an error like:
```
compiling ossl_x509store.c
ossl_ts.c:819:5: error: incomplete definition of type 'struct TS_verify_ctx'
    TS_VERIFY_CTS_set_certs(ctx, x509inter);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:239:52: note: expanded from macro 'TS_VERIFY_CTS_set_certs'
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
                                              ~~~~~^
/prefix/openssl/include/openssl/ts.h:464:16: note: forward declaration of 'struct TS_verify_ctx'
typedef struct TS_verify_ctx TS_VERIFY_CTX;
               ^
1 error generated.
```

Your error is also strange (libcrypto.so.1.0.0: cannot open shared object file: No such file or directory), i.e. it's libcrypto missing and not libssl missing, I wonder if that could be RVM having built/installed openssl not properly.
Showing `ldd lib/mri/openssl.so` could help to find out.
Here is the working one I have:
```
$ ldd lib/mri/openssl.so 
	linux-vdso.so.1 (0x00007ffd8facb000)
	libgraalvm-llvm.so.1 => not found
	libssl.so.1.1 => /prefix/openssl/lib/libssl.so.1.1 (0x00007f4a0dd13000)
	libcrypto.so.1.1 => /prefix/openssl/lib/libcrypto.so.1.1 (0x00007f4a0da2c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4a0d82a000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f4a0d810000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a0de31000)
```

Here are the commands I used to compile openssl manually (mostly from https://linuxpip.org/install-openssl-linux/):
```
dnf group install 'Development Tools'
dnf install perl-core zlib-devel wget -y
cd
mkdir src
cd src/
wget https://www.openssl.org/source/openssl-1.1.1m.tar.gz
tar -xf openssl-1.1.1m.tar.gz
cd openssl-1.1.1m
./config --prefix=/prefix/openssl -Wl,-rpath=/prefix/openssl/lib --openssldir=/prefix/openssl/ssl shared zlib
make -j8
make -j8 install
cd /prefix/openssl/
bin/openssl version
cd /prefix/openssl/ssl
ls /etc/pki/tls/cert.pem
mv certs/ certs.old
ln -s /etc/pki/tls/certs .
ln -s /etc/pki/tls/cert.pem cert.pem

cd
cd src/
wget 'https://github.com/oracle/truffleruby/releases/download/vm-22.1.0/truffleruby-22.1.0-linux-amd64.tar.gz'
tar xf truffleruby-22.1.0-linux-amd64.tar.gz 
cd truffleruby-22.1.0-linux-amd64
OPENSSL_PREFIX=/prefix/openssl ./lib/truffle/post_install_hook.sh 
bin/gem i path
ldd lib/mri/openssl.so 
```

**Comment by eregon** [comment]
Documentation added in fdecea5e45a82bbea2e1ed77cc646c7dc140b2fd, I'll close this as it works on Fedora 36 either with `openssl1.1-devel` or by building openssl 1.1.0 manually with the instructions above.

**Comment by eregon** [comment]
truffleruby-dev and the next release 22.2 support OpenSSL 3 and so can simply be compiled against the system openssl on Fedora 36/Ubuntu 22.04.
