### ISSUE TITLE
Commonmarker: Member `dfree` not found

### ISSUE THREAD

**Issue by Th3-M4jor** [oracle/truffleruby#2732]
This Error does not occur when using MRI 3.0.3

```
home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/ext/commonmarker/commonmarker.c:535:in `rb_node_insert_before': Member 'dfree' not found. (Polyglot::ForeignException)
        from /home/spartan364/.rvm/rubies/truffleruby-22.2.0/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
        from /home/spartan364/.rvm/rubies/truffleruby-22.2.0/lib/truffle/truffle/cext_ruby.rb:41:in `CommonMarker::Node#insert_before'
        from ./markdown_test.rb:12:in `block in <main>'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:16:in `CommonMarker::Node#walk'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:18:in `block in CommonMarker::Node#walk'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:72:in `CommonMarker::Node#each'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:17:in `CommonMarker::Node#walk'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:18:in `block in CommonMarker::Node#walk'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:72:in `CommonMarker::Node#each'
        from /home/spartan364/.rvm/gems/truffleruby-22.2.0/gems/commonmarker-0.23.5/lib/commonmarker/node.rb:17:in `CommonMarker::Node#walk'
        from ./markdown_test.rb:7:in `<main>'
```

Minimal reproduction:
```ruby
require "commonmarker"

doc = CommonMarker.render_doc("# this is a test string")

doc.walk do |node|
  if node.type == :text
    node.insert_before(node)
  end
end
```

Note: This is a duplicate of #2165, however it is a 2 year old issue. As such, I am opening a separate issue rather than asking for an update there.

Update: Tested with `truffleruby 22.3.0-dev-76cfbe8d`, same result.

**Comment by eregon** [comment]
Let's track this in https://github.com/oracle/truffleruby/issues/2830
