### ISSUE TITLE
the given string is not compatible to the expected encoding "US_ASCII"

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2749]
given code:
```
puts      [49, 46, 50].pack('c*').encode("us-ascii")
          .encode(xml: :text)
          .gsub("\u{000D}", '&#xD;') # Carriage Return
          .gsub("\u{000A}", '&#xA;') # Line Feed
          .gsub("\u{0085}", '&#x85;') # Next Line
          .gsub("\u{2028}", '&#x2028;') #
```
fails with:
```
the given string is not compatible to the expected encoding "US_ASCII", did you forget to convert it? (java.lang.IllegalArgumentException)
	from com.oracle.truffle.api.strings.InternalErrors.wrongEncoding(InternalErrors.java:91)
	from com.oracle.truffle.api.strings.AbstractTruffleString.looseCheckEncoding(AbstractTruffleString.java:354)
	from com.oracle.truffle.api.strings.TruffleString$ByteIndexOfStringNode.indexOfString(TruffleString.java:3876)
	from com.oracle.truffle.api.strings.TruffleStringFactory$ByteIndexOfStringNodeGen.execute(TruffleStringFactory.java:3488)
	from com.oracle.truffle.api.strings.TruffleString$ByteIndexOfStringNode.execute(TruffleString.java:3841)
	from org.truffleruby.core.string.StringNodes$StringByteIndexNode.stringByteIndex(StringNodes.java:3878)
	from org.truffleruby.core.string.StringNodesFactory$StringByteIndexNodeFactory$StringByteIndexNodeGen.execute(StringNodesFactory.java:12579)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:37)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:45)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:45)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:37)
	from org.truffleruby.language.RubyMethodRootNode.execute(RubyMethodRootNode.java:65)
<internal:core> core/truffle/string_operations.rb:288:in `byte_index'
	from <internal:core> core/truffle/string_operations.rb:108:in `gsub_string_matches'
	from <internal:core> core/truffle/string_operations.rb:74:in `gsub_internal_matches'
	from <internal:core> core/string.rb:850:in `gsub'
	from test-str.rb:1:in `<main>'
```

**Comment by eregon** [comment]
Thanks for the report.
Here is a slightly clearer repro:
```
s = [49, 46, 50].pack('c*').encode("us-ascii")
s = s.encode(xml: :text)
s = s.gsub("\u{000D}", '&#xD;') # Carriage Return
s = s.gsub("\u{000A}", '&#xA;') # Line Feed
s = s.gsub("\u{0085}", '&#x85;') # Next Line
s = s.gsub("\u{2028}", '&#x2028;') #
puts s
```
It fails on line 5 and 6.
