### ISSUE TITLE
Implement rb_warning_category_enabled_p

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#2764]
It seems used by Ripper, when Ripper parses pattern matching.

Backtrace:
```
 38) Error:
SyntaxTree::InterfaceTest#test_fndptn_9:
RuntimeError: Neutered Exception Polyglot::ForeignException: External LLVMFunction rb_warning_category_enabled_p cannot be found.
    ripper.c:6157:in `ripper_yyparse'
    ripper.y:13684:in `ripper_parse0'
    /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1563:in `<unknown>'
    /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1563:in `CExt#rb_ensure'
    exception.c:97:in `rb_ensure'
    ripper.y:13714:in `ripper_parse'
    /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
    /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:41:in `Ripper#parse'
    /home/eregon/code/syntax_tree/lib/syntax_tree.rb:49:in `SyntaxTree.parse'
    /home/eregon/code/syntax_tree/test/interface_test.rb:17:in `SyntaxTree::InterfaceTest#test_fndptn_9'
```
From https://github.com/ruby-syntax-tree/syntax_tree/issues/168#issuecomment-1282790139

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/bacad37e69c67409c69059620e827a1ee898fe26
