### ISSUE TITLE
`iconv` gem fails on require: Cannot read member 'dfree' (Polyglot::ForeignException)

### ISSUE THREAD

**Issue by brauliobo** [oracle/truffleruby#2771]
Sample script:
```ruby
require 'bundler/inline'
gemfile true do
  gem 'iconv'
  gem 'oj'
end

Oj.mimic_JSON
```
Running it causes the error:
```
braulio @ bhavapower ➜  test  ruby oj-test.rb    
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Resolving dependencies...
Using bundler 2.2.32
Using oj 3.6.11
Using iconv 1.0.8
/home/braulio/.rvm/gems/truffleruby-22.3.0/gems/iconv-1.0.8/ext/iconv/iconv.c:380:in `check_iconv': Cannot read member 'dfree' (Polyglot::ForeignException)
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/iconv-1.0.8/ext/iconv/iconv.c:737:in `iconv_initialize'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/truffle/truffle/cext_ruby.rb:41:in `Iconv#initialize'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/truffle/truffle/cext.rb:903:in `CExt#rb_funcall'
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/oj-3.6.11/ext/oj/oj.c:1461:in `iconv_encoder'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/truffle/truffle/cext.rb:1559:in `<unknown>'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/truffle/truffle/cext.rb:1559:in `CExt#rb_rescue'
        from exception.c:103:in `rb_rescue'
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/oj-3.6.11/ext/oj/oj.c:1512:in `Init_oj'
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/oj-3.6.11/lib/oj.rb:21:in `<unknown>'
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/oj-3.6.11/lib/oj.rb:21:in `Kernel#gem_original_require'
        from /home/braulio/.rvm/gems/truffleruby-22.3.0/gems/oj-3.6.11/lib/oj.rb:21:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `Kernel#gem_original_require'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/runtime.rb:60:in `block (2 levels) in Bundler::Runtime#require'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/runtime.rb:55:in `Array#each'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/runtime.rb:55:in `block in Bundler::Runtime#require'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/runtime.rb:44:in `Array#each'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/runtime.rb:44:in `Bundler::Runtime#require'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/inline.rb:71:in `block in Object#gemfile'
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/settings.rb:131:in `Bundler::Settings#temporary'      
        from /home/braulio/.rvm/rubies/truffleruby-22.3.0/lib/mri/bundler/inline.rb:55:in `Object#gemfile'
        from oj-test.rb:2:in `<main>'
```

Benchmark of MRI's Nokogiri (homepage) and Oj (json) against standard JSON from TruffleRuby

1) TruffleRuby (10s warmup):
```
Warming up --------------------------------------
            homepage    31.000  i/100ms 
                json   801.000  i/100ms
Calculating -------------------------------------
            homepage    489.534  (±10.4%) i/s -      2.449k in   5.071474s
                json     14.457k (±31.1%) i/s -     65.682k in   5.008783s
```

2) MRI:
```
Warming up --------------------------------------
            homepage    54.000  i/100ms 
                json     6.371k i/100ms 
Calculating -------------------------------------
            homepage    543.200  (± 5.7%) i/s -      2.754k in   5.093684s
                json     63.778k (± 1.5%) i/s -    324.921k in   5.095616s
```

**Comment by brauliobo** [comment]
> Thanks for the report, we'll look into it.
> 
> I'm curious, is there any reason to use `iconv` nowadays (especially as a gem and not using the default gem)? It feels redundant with `String#encode`.

it seems iconv is a dependency of iconv, not sure why they rely on it

**Comment by eregon** [comment]
@brauliobo Recent `oj` releases don't rely on `iconv` anymore (as far as I can see):
https://github.com/ohler55/oj/blob/develop/oj.gemspec
https://github.com/search?q=repo%3Aohler55%2Foj%20iconv&type=code

`oj` [3.6.11](https://github.com/ohler55/oj/releases/tag/v3.6.11) is too old, it's from 2018, that version won't work on TruffleRuby anyway, so the solution here is to update to a more recent `oj`.

I leave this open because we'll want to still try to get the [`iconv`](https://github.com/ruby/iconv) gem to work on TruffleRuby.

**Comment by eregon** [comment]
To reproduce the error:
```
$ gem i iconv
$ ruby -riconv -e 'p Iconv.new("ASCII//TRANSLIT", "UTF-8")'
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/iconv-1.0.8/ext/iconv/iconv.c:380:in `check_iconv': Cannot read member 'dfree' (Polyglot::ForeignException)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/iconv-1.0.8/ext/iconv/iconv.c:737:in `iconv_initialize'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext_ruby.rb:41:in `Iconv#initialize'
	from -e:1:in `<main>'
```

(the old oj caller is https://github.com/ohler55/oj/blob/v3.6.11/ext/oj/oj.c#L1467)
