### ISSUE TITLE
RMagick gem installation error: "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"

### ISSUE THREAD

**Issue by rootcfg** [oracle/truffleruby#2779]
```
current directory: /Users/user/.rvm/gems/truffleruby-head/gems/rmagick-5.0.0/ext/RMagick
/Users/user/.rvm/rubies/truffleruby-head/bin/ruby -I /Users/user/.rvm/rubies/truffleruby-head/lib/mri -r ./siteconf20221109-49641-jyhgum.rb extconf.rb
checking for brew... yes
checking for Ruby version >= 2.3.0... yes
checking for pkg-config... yes
checking for forced use of ImageMagick 6... no
checking for outdated ImageMagick version (<= 6.7.7)... no
checking for /Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang... yes
/Users/user/.rvm/rubies/truffleruby-head/lib/mri/mkmf.rb:545:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

Contents of mkmf.log:
find_executable: checking for brew... -------------------- yes

--------------------

assert_minimum_ruby_version!: checking for Ruby version >= 2.3.0... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

determine_imagemagick_package: checking for forced use of ImageMagick 6... -------------------- no

--------------------

assert_has_dev_libs!: checking for outdated ImageMagick version (<= 6.7.7)... -------------------- no

Detected ImageMagick version: 7.1.0
--------------------

find_executable: checking for /Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang... -------------------- yes

--------------------

"/Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang -o conftest -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/backward -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include -I. -I/usr/local/opt/imagemagick@6/include -Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.1.0-52/include/ImageMagick-7   -Werror=implicit-function-declaration -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-incompatible-pointer-types -Wno-format-invalid-specifier -Wno-format-extra-args -ferror-limit=500 conftest.c  -L. -L/usr/local/opt/imagemagick@6/lib -L/usr/local/Cellar/imagemagick/7.1.0-52/lib -lMagickCore-7.Q16HDRI -Wl,-rpath,/usr/local/Cellar/imagemagick/7.1.0-52/lib    -L/usr/local/Cellar/imagemagick/7.1.0-52/lib -lMagickCore-7.Q16HDRI  -lgraalvm-llvm    -L/Users/user/.rvm/rubies/truffleruby-head/lib/cext -rpath /Users/user/.rvm/rubies/truffleruby-head/lib/cext -ltruffleruby -rpath /Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/lib"
In file included from conftest.c:1:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby.h:38:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/ruby.h:15:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/internal/config.h:147:
/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/truffleruby/truffleruby-pre.h:61:2: error: "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
#error "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
 ^
1 error generated.
In file included from conftest.c:1:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby.h:38:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/ruby.h:15:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/internal/config.h:147:
/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/truffleruby/truffleruby-pre.h:61:2: error: "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
#error "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
 ^
1 error generated.
Process failed: #<Process::Status: pid 49872 exit 1>
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */


   from /Users/user/.rvm/rubies/truffleruby-head/lib/mri/mkmf.rb:639:in `try_link0'
   from /Users/user/.rvm/rubies/truffleruby-head/lib/mri/mkmf.rb:657:in `try_link'
   from extconf.rb:106:in `configure_compile_options'
   from extconf.rb:46:in `initialize'
   from extconf.rb:441:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
   --with-opt-dir
   --without-opt-dir
   --with-opt-include
   --without-opt-include=${opt-dir}/include
   --with-opt-lib
   --without-opt-lib=${opt-dir}/lib
   --with-make-prog
   --without-make-prog
   --srcdir=.
   --curdir
   --ruby=/Users/user/.rvm/rubies/truffleruby-head/bin/ruby

Contents of mkmf.log:
find_executable: checking for brew... -------------------- yes

--------------------

assert_minimum_ruby_version!: checking for Ruby version >= 2.3.0... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------

determine_imagemagick_package: checking for forced use of ImageMagick 6... -------------------- no

--------------------

assert_has_dev_libs!: checking for outdated ImageMagick version (<= 6.7.7)... -------------------- no

Detected ImageMagick version: 7.1.0
--------------------

find_executable: checking for /Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang... -------------------- yes

--------------------

"/Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/bin/graalvm-native-clang -o conftest -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/backward -I/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include -I. -I/usr/local/opt/imagemagick@6/include -Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.1.0-52/include/ImageMagick-7   -Werror=implicit-function-declaration -Wno-int-conversion -Wno-int-to-pointer-cast -Wno-incompatible-pointer-types -Wno-format-invalid-specifier -Wno-format-extra-args -ferror-limit=500 conftest.c  -L. -L/usr/local/opt/imagemagick@6/lib -L/usr/local/Cellar/imagemagick/7.1.0-52/lib -lMagickCore-7.Q16HDRI -Wl,-rpath,/usr/local/Cellar/imagemagick/7.1.0-52/lib    -L/usr/local/Cellar/imagemagick/7.1.0-52/lib -lMagickCore-7.Q16HDRI  -lgraalvm-llvm    -L/Users/user/.rvm/rubies/truffleruby-head/lib/cext -rpath /Users/user/.rvm/rubies/truffleruby-head/lib/cext -ltruffleruby -rpath /Users/user/.rvm/rubies/truffleruby-head/lib/sulong/native/lib"
In file included from conftest.c:1:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby.h:38:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/ruby.h:15:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/internal/config.h:147:
/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/truffleruby/truffleruby-pre.h:61:2: error: "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
#error "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
 ^
1 error generated.
In file included from conftest.c:1:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby.h:38:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/ruby.h:15:
In file included from /Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/ruby/internal/config.h:147:
/Users/user/.rvm/rubies/truffleruby-head/lib/cext/include/truffleruby/truffleruby-pre.h:61:2: error: "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
#error "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
 ^
1 error generated.
Process failed: #<Process::Status: pid 49872 exit 1>
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/user/.rvm/gems/truffleruby-head/extensions/x86_64-darwin/3.0.3.14/rmagick-5.0.0/mkmf.log

extconf failed, exit code 1
```

**Comment by slimdave** [comment]
I have the same - Apple silicon, truffleruby-22.3.0.

**Comment by eregon** [comment]
Thanks for the report.
The error says:
```
#error "TRUFFLERUBY_ABI_VERSION must be defined when compiling native extensions. Does the extension override CPPFLAGS or DEFS?"
```

And indeed it looks like rmagick overrides CPPFLAGS blindly, which is pretty bad because CPPFLAGS is not empty by default, even on CRuby:
https://github.com/rmagick/rmagick/blob/2ffce591bacc41566bb01be1bc28674f4a5cdf07/ext/RMagick/extconf.rb#L102
This will need to be fixed upstream.

**Comment by eregon** [comment]
PR to RMagick: https://github.com/rmagick/rmagick/pull/1365

**Comment by eregon** [comment]
PR merged, now just waiting for a release of rmagick so I'll close this.

**Comment by slimdave** [comment]
Thanks @eregon
