### ISSUE TITLE
Openssl test suit is slower on MacOs

### ISSUE THREAD

**Issue by gogainda** [oracle/truffleruby#2800]
Because of it some test are failing with time out error:
```
1) Error: test_engines_free(OpenSSL::TestEngine): Timeout::Error: execution of assert_separately expired
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:76:in `with_openssl'
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:8:in `test_engines_free'
      5: 
      6: class OpenSSL::TestEngine < OpenSSL::TestCase
      7:   def test_engines_free # [ruby-dev:44173]
  =>  8:     with_openssl <<-'end;'
      9:       OpenSSL::Engine.load("openssl")
     10:       OpenSSL::Engine.engines
     11:       OpenSSL::Engine.engines
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'

2) Error: test_openssl_engine_builtin(OpenSSL::TestEngine): Timeout::Error: execution of assert_separately expired
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:76:in `with_openssl'
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:16:in `test_openssl_engine_builtin'
     13:   end
     14: 
     15:   def test_openssl_engine_builtin
  => 16:     with_openssl <<-'end;'
     17:       orig = OpenSSL::Engine.engines
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:76:in `with_openssl'
/Users/runner/work/openssl/openssl/test/openssl/test_engine.rb:36:in `test_openssl_engine_id_name_inspect'
     33:   end
     34: 
     35:   def test_openssl_engine_id_name_inspect
  => 36:     with_openssl <<-'end;'
     37:       engine = get_engine
     38:       assert_equal("openssl", engine.id)
     39:       assert_not_nil(engine.name)
<internal:core> core/throw_catch.rb:36:in `catch'
<internal:core> core/throw_catch.rb:36:in `catch'

Omissions:
1) Omission: <OpenSSL::TestBN#test_ractor> requires Ractor [test_ractor(OpenSSL::TestBN)]
<internal:core> core/throw_catch.rb:36:in `catch'

Finished in 123.841951 seconds.
-------------------------------------------------------------------------------
521 tests, 4276 assertions, 0 failures, 6 errors, 0 pendings, 1 omissions, 0 notifications
98.8462% passed
-------------------------------------------------------------------------------
4.21 tests/s, 34.53 assertions/s
```

on ubuntu  it's 119 assertions per second 
Failed run https://github.com/gogainda/openssl/actions/runs/3591602314/jobs/6046327917

**Comment by eregon** [comment]
For comparison on CRuby: 205.53 assertions/s, 21s on Ubuntu, 174.05 assertions/s, 25s on macOS.
On TruffleRuby:119.79 assertions/s, 42s on Ubuntu, 34.53 assertions/s, 138s on macOS (~3x slower on macOS).
So macOS slower on CRuby too but not as much.

I think this is at least partly an issue of GitHub Actions macOS runners being significantly slower and with less resources (e.g. slower CPU, slower IO, etc), I've seen that with CRuby on ruby/spec too for example.

Those failures are all `execution of assert_separately expired`, so it probably means starting a subprocess on macOS is quite significantly slower.
The default is a 10s timeout in https://github.com/gogainda/openssl/blob/6f33da925bc976f0f36ae90a5f7f53805dd0d7d6/test/openssl/envutil.rb#L15
It would probably make sense to increase this timeout for TruffleRuby at least on macOS.

We should verify whether this could be a slowdown of TruffleRuby startup on macOS, for that we'd need someone with macOS and Linux installed on the same machine and running with the same architecture for both.
For instance we could try `for in in {1..10}; do time truffleruby -e 'require "openssl"'; done`.

**Comment by eregon** [comment]
I investigated this with @andrykonchin.
First it only happens with libssl < 3, because on libssl >= 3 that test is skipped by https://github.com/ruby/openssl/blob/c282090b5bc4e78d263552b5f90d6b86eea63a33/test/openssl/test_engine.rb#L4
That's why those tests like `test_openssl_engine_builtin` are not even run on Ubuntu 22.04, because that uses libssl 3.

What seems to happen is that this `with_openssl` helper recursively requires the test file in https://github.com/ruby/openssl/blob/c282090b5bc4e78d263552b5f90d6b86eea63a33/test/openssl/test_engine.rb#L77 which basically leads to running that testcase inside that testcase inside that testcase, etc.
It's unclear why it doesn't happen on CRuby, and probably requires quite a bit of investigation, it might "work" accidentally.
But nevertheless this seems very brittle and messy, hence the best here seems to fix those tests to require a separate file to define the `Utils` module and avoid the recursive require on the test file itself.

Another thing is we currently prefer openssl@1.1 for Homebrew on macOS, we should probably try `@3` first, so it's just openssl 3 by default for TruffleRuby like for CRuby with ruby-build.
https://github.com/oracle/truffleruby/blob/0cb9ed5cf5dbdafc6e88ad0b1345c5fc04439fad/lib/truffle/truffle/openssl-prefix.rb#L12

**Comment by andrykonchin** [comment]
I've prepared a tiny fix for ruby/openssl to make specs run on TruffleRuby - https://github.com/ruby/openssl/pull/589.

There are two mechanisms in openssl's tests to prevent auto-running tests in a forked process:
- by disabling it explicitly by manipulating a test runner (it was repaired in the fix)
- by raising an exception after completing a test case

The first one was broken (on CRuby as well).

The second find works on CRuby well but is broken on TruffleRuby.

`test-unit` auto-run tests if there is no any not-caught exception in a `at_exit` hook:
https://github.com/test-unit/test-unit/blob/b528ea0214ec9ea8c08233247eba3acaac2cb152/lib/test/unit.rb#L515-L521

`openssl`'s test helper `assert_separately` raises SystemError exception (in a forked process) with `exit` call (in the `END {}` section)
https://github.com/ruby/openssl/blob/master/test/openssl/envutil.rb#L190-L199
and disables auto-running specs.

A simplified example that reproduce the issue on TruffleRuby:

```ruby
at_exit { puts "$! #{$!.inspect}" }

END {
  exit
}
```

Results:
```
ruby -v
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-darwin21]
ruby end.rb
$! #<SystemExit: exit>

ruby -v
truffleruby 23.0.0-dev-0d398ebd, like ruby 3.1.3, Interpreted JVM [x86_64-darwin]
ruby end.rb
$! nil
```

**Comment by andrykonchin** [comment]
The issue is fixed and there are no timeouts:

```
rake
/usr/bin/make install target_prefix=
/usr/bin/install -c -m 0755 openssl.bundle openssl/lib
cp tmp/x86_64-darwin21/openssl/3.1.3/openssl.bundle tmp/x86_64-darwin21/stage/lib/openssl.bundle
truffleruby -I./lib -ropenssl -ve'puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION'
truffleruby 23.0.0-dev-0d398ebd, like ruby 3.1.3, Interpreted JVM [x86_64-darwin]
OpenSSL 1.1.1s  1 Nov 2022
OpenSSL 1.1.1s  1 Nov 2022
Loaded suite gems/gems/rake-13.0.6/lib/rake/rake_test_loader
Started
............................................................................................................................................................................
............................................................................................................................................................................
............................................................................................................................................................................
....O
============================================================================================================================================================================
Omission: <OpenSSL::TestBN#test_ractor> requires Ractor [test_ractor(OpenSSL::TestBN)]
<internal:core> core/throw_catch.rb:36:in `catch'
============================================================================================================================================================================

Finished in 55.36278 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
521 tests, 4299 assertions, 0 failures, 0 errors, 0 pendings, 1 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
9.41 tests/s, 77.65 assertions/s
```
