### ISSUE TITLE
Cannot read truffle object has members

### ISSUE THREAD

**Issue by tisonkun** [oracle/truffleruby#2811]
### Reproduce

GraalVM version: 22.3.0

```shell
git clone https://github.com/korandoru/trufflebf
mvn clean package -DskipTests
gu install -L trufflebf-component/bf-component.jar 
gu install ruby
ruby --experimental-options --single-threaded --polyglot --jvm interop.rb
```

where `interop.rb`:

```ruby
add = Polyglot.eval('bf', '>[-<+>]<')
res = add.call([42, 21], 0)
p res
p res['data']
p res['dp']
p res['data'][res['dp']]
```

You can debug the `res` return object. Previously it can be read members correctly, but now it always a string and access to `data` returns `'data'`:

```
"BFObject{dp=0, ip=8, data=[63, 0], ins=>[-<+>]<}"
"data"
"dp"
nil
```

expected:

```
...
[63, 0]
0
63
```

**Comment by tisonkun** [comment]
I don't know whether it's because I export these messages:

```java
@ExportLibrary(InteropLibrary.class)
public class BFObject implements TruffleObject {
    ....

    @ExportMessage
    @SuppressWarnings("unused")
    boolean isString() {
        return true;
    }

    @ExportMessage
    @SuppressWarnings("unused")
    String asString() {
        return toString();
    }

    @ExportMessage
    @SuppressWarnings("unused")
    Object toDisplayString(boolean allowSideEffects) {
        return toString();
    }

    @Override
    @CompilerDirectives.TruffleBoundary
    public String toString() {
        return "BFObject{" +
                "dp=" + dp +
                ", ip=" + ip +
                ", data=" + Arrays.toString(data.data) +
                ", ins=" + ins.ins +
                '}';
    }
}
```

but the Java interop seems work well:

```java
package examples;

import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.*;

public class Interop {
    private static final String BF = "bf";
    public static void main(String[] args) {
        System.out.print("Your name: ");
        Context context = Context.newBuilder(BF)
            .allowAllAccess(true)
            .in(System.in).out(System.out)
            .build();
        Value value = context.eval(BF, ">+[++++++++++>,----------]");
        Value state = value.execute();
        Value data = state.getMember("data");

        System.out.print("Hello ");
        int i = 2;
        char ch = (char)data.getArrayElement(i).asLong();
        while (ch > 0) {
            System.out.print(ch);
            i = i + 1;
            ch = (char)data.getArrayElement(i).asLong();
        }
        System.out.println("!");
        System.out.println(state.asString());
    }
}
```

**Comment by eregon** [comment]
OK I can guess what happens now.
`res` is a `BFObject`. That has isString=true and it seems treated primarily as a String.
And so it behaves like
```ruby
res = "BFObject{dp=0, ip=8, data=[63, 0], ins=>[-<+>]<}"
p res['data'] # => "data"
p res['dp'] # => "dp"
p res['data'][res['dp']] # => nil
```
i.e., `[]` uses String#[].

String should have the least precedence according to https://github.com/oracle/truffleruby/blob/master/src/main/java/org/truffleruby/language/objects/ForeignClassNode.java though, so I'll check what's happening.

**Comment by eregon** [comment]
I get this when trying to install the component (on truffleruby master):
```
$ gu install -L trufflebf-component/bf-component.jar
Processing Component archive: trufflebf-component/bf-component.jar
Installation of trufflebf-component/bf-component.jar failed: Symbolic link ../languages/bf/bin/bf is broken
Error: Symbolic link ../languages/bf/bin/bf is broken
```

**Comment by eregon** [comment]
I got it working by building trufflebf with GraalVM 22.3 in PATH.
So:
```ruby
p res
p res.class
p res.class.ancestors
```
shows
```
"BFObject{dp=0, ip=8, data=[63, 0], ins=>[-<+>]<}"
Polyglot::ForeignString
[Polyglot::ForeignString, Polyglot::StringTrait, Polyglot::ForeignObject, Polyglot::ObjectTrait, Object, Kernel, BasicObject]
```

Which is expected.
The BFObject has both the String and members traits. In Ruby every objects is considered to have members, and so the String trait has priority (it's more specific), hence String#[] is used for `res[name]` and not readMember().

**Comment by eregon** [comment]
I commented out isString/asString in BFObject.
Then:
```ruby
add = Polyglot.eval('bf', '>[-<+>]<')
res = add.call([42, 21], 0)

p res
p res.class
p res.class.ancestors

p res['data']
p res['dp']
p res['data'][res['dp']]
```
causes
```
Null receiver values are not supported by libraries. (java.lang.NullPointerException)
	from com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:528)
	from com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
	from org.truffleruby.language.objects.ForeignClassNodeGen.executeAndSpecialize(ForeignClassNodeGen.java:105)
	from org.truffleruby.language.objects.ForeignClassNodeGen.execute(ForeignClassNodeGen.java:62)
	from org.truffleruby.language.objects.MetaClassNode.metaClassForeign(MetaClassNode.java:127)
	from org.truffleruby.language.objects.MetaClassNodeGen.executeAndSpecialize(MetaClassNodeGen.java:262)
	from org.truffleruby.language.objects.MetaClassNodeGen.execute(MetaClassNodeGen.java:119)
	from org.truffleruby.language.dispatch.DispatchNode.dispatchInternal(DispatchNode.java:297)
	from org.truffleruby.language.dispatch.DispatchNode.dispatch(DispatchNode.java:285)
	from org.truffleruby.language.dispatch.RubyCallNode.doCall(RubyCallNode.java:177)
	from org.truffleruby.language.dispatch.RubyCallNode.execute(RubyCallNode.java:133)
	from org.truffleruby.language.control.FrameOnStackNode.execute(FrameOnStackNode.java:34)
	from org.truffleruby.language.methods.CatchBreakNode.execute(CatchBreakNode.java:41)
	from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:43)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:37)
	from org.truffleruby.language.RubyMethodRootNode.execute(RubyMethodRootNode.java:65)
<internal:core> core/truffle/polyglot.rb:507:in `instance_variables'
	from <internal:core> core/truffle/interop_operations.rb:142:in `pairs_from_object'
	from <internal:core> core/truffle/interop_operations.rb:100:in `foreign_inspect_nonrecursive'
	from <internal:core> core/truffle/polyglot.rb:460:in `block in inspect'
	from <internal:core> core/truffle/thread_operations.rb:75:in `detect_recursion'
	from <internal:core> core/truffle/polyglot.rb:459:in `inspect'
	from <internal:core> core/post.rb:80:in `block in p'
	from <internal:core> core/post.rb:80:in `each'
	from <internal:core> core/post.rb:80:in `p'
	from interop.rb:4:in `<main>'
```

That is because of https://github.com/korandoru/trufflebf/blob/b584a4cd02f587a18bf9a30ca249d0824acb2fd7/trufflebf-language/src/main/java/io/korandoru/trufflebf/language/BFObject.java#L71. `null` is not an allowed return value for `getMembers()` or interop in general.

If we comment out the `p res` line then it works as expected:
```
Polyglot::ForeignObject
[Polyglot::ForeignObject, Polyglot::ObjectTrait, Object, Kernel, BasicObject]
#<Polyglot::ForeignArray:0x985696 [63, 0]>
0
63
```

So:
* BFObject must not implement isString/asString, it's not primarily a String but an object with members
* BFObject#getMembers() must not return null but from the javadocs:
  ```
   The returned value must return <code>true</code> for
     {@link #hasArrayElements(Object)} and every array element must be of type
     {@link #isString(Object) string}.
  ```

Then it just works.

**Comment by tisonkun** [comment]
@eregon Thanks for your help! Resolved with https://github.com/korandoru/trufflebf/commit/3b3ab70a0e6760f820c43abf0351dadb529bceba.

**Comment by eregon** [comment]
That works nicely:
```
p res # =>
#<Polyglot::ForeignObject:0x5cf8edcf dp=0, ip=8, ins=[...], data=[...]>
```

As a small note, `res['data']` can be replaced by the shorter `res.data` (same for `res.dp`).
