### ISSUE TITLE
`result_array': coverage measurement is not enabled (RuntimeError)

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#2814]
Running tests with coverage via `simplecov` is [breaking under truffleruby](https://gitlab.com/os85/cel-ruby/-/jobs/3525544502):

```
/opt/truffleruby-22.3.0/lib/truffle/coverage.rb:22:in `result_array': coverage measurement is not enabled (RuntimeError)
	from /opt/truffleruby-22.3.0/lib/truffle/coverage.rb:22:in `peek_result'
	from /opt/truffleruby-22.3.0/lib/truffle/coverage.rb:16:in `result'
	from /builds/os85/cel-ruby/vendor/truffleruby/3.0.3.22.3.0/gems/simplecov-0.22.0/lib/simplecov.rb:400:in `adapt_coverage_result'
	from /builds/os85/cel-ruby/vendor/truffleruby/3.0.3.22.3.0/gems/simplecov-0.22.0/lib/simplecov.rb:389:in `process_coverage_result'
```

**Comment by andrykonchin** [comment]
Looks like the issue is caused by another problem:

```
Error message: undefined method `running?' for Coverage:Module
```

It's reported here https://github.com/oracle/truffleruby/issues/2813 so you can track progress in that issue.

**Comment by andrykonchin** [comment]
Fixed.
