### ISSUE TITLE
Symbol literal with invalid encoding crashes the VM

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2849]
While investigating #2848, I tried constructing a symbol with an invalid byte sequence. Doing so propagates an NPE and crashes the VM. It looks like a bootstrapping issue:

```
> jt ruby -e ':"\xAE"'
Using TruffleRuby with Graal: mxbuild/truffleruby-jvm-ce-ntl
$ /Users/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/mxbuild/truffleruby-jvm-ce-ntl/languages/ruby/bin/ruby \
  --experimental-options \
  --core-load-path=/Users/nirvdrum/dev/workspaces/truffleruby-ws/truffleruby/src/main/ruby/truffleruby \
  -e \
  ':"\xAE"'
Exception while loading core library:
Error while formatting Ruby exception:
java.lang.NullPointerException
	at org.truffleruby.core.basicobject.BasicObjectNodes$MethodMissingNode.lastCallWasSuper(BasicObjectNodes.java:586)
	at org.truffleruby.core.basicobject.BasicObjectNodes$MethodMissingNode.buildMethodMissingException(BasicObjectNodes.java:521)
	at org.truffleruby.core.basicobject.BasicObjectNodes$MethodMissingNode.methodMissing(BasicObjectNodes.java:497)
	at org.truffleruby.core.basicobject.BasicObjectNodesFactory$MethodMissingNodeFactory$MethodMissingNodeGen.executeAndSpecialize(BasicObjectNodesFactory.java:2098)
	at org.truffleruby.core.basicobject.BasicObjectNodesFactory$MethodMissingNodeFactory$MethodMissingNodeGen.execute(BasicObjectNodesFactory.java:2081)
	at org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.IndirectCallNode$1.call(IndirectCallNode.java:91)
	at org.truffleruby.language.methods.CallInternalMethodNode.callUncached(CallInternalMethodNode.java:83)
	at org.truffleruby.language.methods.CallInternalMethodNodeGen$Uncached.execute(CallInternalMethodNodeGen.java:384)
	at org.truffleruby.language.dispatch.DispatchNode.dispatchInternal(DispatchNode.java:318)
	at org.truffleruby.language.dispatch.DispatchNode$Uncached.dispatch(DispatchNode.java:436)
	at org.truffleruby.language.dispatch.DispatchNode.callMethodMissing(DispatchNode.java:330)
	at org.truffleruby.language.dispatch.DispatchNode.dispatchInternal(DispatchNode.java:309)
	at org.truffleruby.language.dispatch.DispatchNode$Uncached.dispatch(DispatchNode.java:436)
	at org.truffleruby.language.dispatch.DispatchNode.dispatch(DispatchNode.java:280)
	at org.truffleruby.language.dispatch.DispatchNode.call(DispatchNode.java:126)
	at org.truffleruby.language.backtrace.BacktraceFormatter.printRubyExceptionOnEnvStderr(BacktraceFormatter.java:135)
	at org.truffleruby.core.CoreLibrary.loadRubyCoreLibraryAndPostBoot(CoreLibrary.java:785)
	at org.truffleruby.RubyContext.initialize(RubyContext.java:257)
	at org.truffleruby.RubyLanguage.initializeContext(RubyLanguage.java:463)
	at org.truffleruby.RubyLanguage.initializeContext(RubyLanguage.java:137)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3552)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:280)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:710)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1471)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:400)
	at org.truffleruby.launcher.RubyLauncher.runContext(RubyLauncher.java:308)
	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:254)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:129)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
Caused by: Attached Guest Language Frames (1)
Original Ruby exception:
(exception java.lang.NullPointerException null org.truffleruby.core.basicobject.BasicObjectNodes$MethodMissingNode.lastCallWasSuper(BasicObjectNodes.java:586)
	from <internal:core> core/array.rb:1284:in `<class:Array>'
	from <internal:core> core/array.rb:37:in `<top (required)>'

truffleruby: an exception escaped out of the interpreter - this is an implementation bug
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.CompilerDirectives$ShouldNotReachHere: couldn't load the core library
	at org.graalvm.truffle/com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:574)
	at org.truffleruby.core.CoreLibrary.loadRubyCoreLibraryAndPostBoot(CoreLibrary.java:786)
	at org.truffleruby.RubyContext.initialize(RubyContext.java:257)
	at org.truffleruby.RubyLanguage.initializeContext(RubyLanguage.java:463)
	at org.truffleruby.RubyLanguage.initializeContext(RubyLanguage.java:137)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3552)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:280)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:710)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1471)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:400)
	at org.truffleruby.launcher.RubyLauncher.runContext(RubyLauncher.java:308)
	at org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:254)
	at org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:129)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
Caused by: org.truffleruby.language.control.RaiseException: undefined method `unshift' for class `Array'
Internal GraalVM error, please report at https://github.com/oracle/graal/issues/.
```

**Comment by nirvdrum** [comment]
This was my mistake. I had `JT_ENV` set to a configuration I hadn't built yet. Perhaps the error message could be clearer in that case, but that'd be a separate issue. Working with the correct configuration, the above code now looks like:

```
> jt ruby -e ':"\xAE"'
  ':"\xAE"'
truffleruby: invalid encoding symbol (EncodingError)
```
