### ISSUE TITLE
Java exception leaking out in `Array#[]=` with overflowed index

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2920]
I'm working on refreshing our tags for the MRI tests. While doing so, I ran into a situation where a Java exception is escaping into Ruby. I don't think this particular example is really something that's problematic, only that it suggests we're missing some exception handling somewhere.

```ruby
LONGP = [127, 63, 31, 15, 7].map {|x| 2**x-1 }.find do |x|
  begin
    [].first(x)
  rescue ArgumentError
    true
  rescue RangeError
    false
  end
end

puts "Bad index: #{LONGP}"
Puts [0][LONGP] = [2]
```

```
> jt ruby bad-array.rb
Bad index: 2147483647

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

-2147483648 (java.lang.NegativeArraySizeException)
        from org.truffleruby.core.array.library.ObjectArrayStore$ObjectArrayAllocator.allocate(ObjectArrayStore.java:230)
        from org.truffleruby.core.array.library.ObjectArrayStore$ObjectArrayAllocator.allocate(ObjectArrayStore.java:226)
        from org.truffleruby.core.array.library.IntegerArrayStore$AllocateForNewValue.allocateForNewValue(IntegerArrayStore.java:276)
        from org.truffleruby.core.array.library.IntegerArrayStoreGen$ArrayStoreLibraryExports$Cached.allocateForNewValueAndSpecialize(IntegerArrayStoreGen.java:721)
        from org.truffleruby.core.array.library.IntegerArrayStoreGen$ArrayStoreLibraryExports$Cached.allocateForNewValue(IntegerArrayStoreGen.java:696)
        from org.truffleruby.core.array.ArrayWriteNormalizedNode.writeBeyondPrimitive(ArrayWriteNormalizedNode.java:87)
        from org.truffleruby.core.array.ArrayWriteNormalizedNodeGen.executeAndSpecialize(ArrayWriteNormalizedNodeGen.java:471)
        from org.truffleruby.core.array.ArrayWriteNormalizedNodeGen.executeWrite(ArrayWriteNormalizedNodeGen.java:237)
        from org.truffleruby.core.array.ArrayNodes$SetIndexNode.set(ArrayNodes.java:358)
        from org.truffleruby.core.array.ArrayNodesFactory$SetIndexNodeFactory$SetIndexNodeGen.executeAndSpecialize(ArrayNodesFactory.java:2039)
        from org.truffleruby.core.array.ArrayNodesFactory$SetIndexNodeFactory$SetIndexNodeGen.execute(ArrayNodesFactory.java:2014)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
bad-array.rb:12:in `[]='
        from bad-array.rb:12:in `<main>'
```

**Comment by eregon** [comment]
This one is interesting.
The test is:
```ruby
  def test_sized_queue_initialized
    assert_raise(TypeError) {
      SizedQueue.allocate.push(nil)
    }
  end
```

That's basically undefined behavior, it's invalid to call `allocate` and no `initialize*` after and use a method on it.

There are 3 solutions:
1. Keep this as a fatal exception, because this is very broken code anyway. And have `jt retag` not try to remove `exclude` for this, e.g. mark this as a "fatal exclude" or "broken test exclude"
2. We could do `new RubySizedQueue(rubyClass, getLanguage().sizedQueueShape, new SizedQueue(0));` in `SizedQueue.allocate`. The downside is this is extra allocations, behind a TruffleBoundary, only to support broken code. If we can share a global "frozen/closed" (Java) SizedQueue instance then it'd be OK as it wouldn't change performance. This will not match CRuby semantics and not pass this test, but it will not crash which is maybe useful.
3. Have checks in every SizedQueue method if allocated and do the same as CRuby (which is inconsistent, sometimes it's TypeError, but e.g. for closed? it's `false`, which sounds like a bug, but irrelevant since nobody should do this). This is a lot of work, very error-prone and trying to match basically broken behavior in CRuby, so not a good idea from maintainability POV.

I'm against 3 for maintainability.
I think 1 or 2 is fine. Any thoughts on 1 vs 2?
