### ISSUE TITLE
Java exception escaping on `MatchData#[]`

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#2929]
I'm working on refreshing our tags for the MRI tests. While doing so, I ran into a situation where a Java exception is escaping into Ruby when indexing a `MatchData` object.

```ruby
m = /(...)(...)(...)(...)?/.match("foobarbaz")
p m[3, -1]
```

On MRI 3.1.3:

```
> ruby -v bad-matchdata-aref.rb
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]
nil
```

On TruffleRuby 23.0.0-dev:

```
> jt ruby -v bad-matchdata-aref.rb
truffleruby 23.0.0-dev-671182fb*, like ruby 3.1.3, GraalVM CE JVM [aarch64-darwin]

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

3 > 2 (java.lang.IllegalArgumentException)
        from java.util.Arrays.copyOfRange(Arrays.java:3782)
        from java.util.Arrays.copyOfRange(Arrays.java:3742)
        from org.truffleruby.core.regexp.MatchDataNodes$GetIndexNode.getIndex(MatchDataNodes.java:294)
        from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexNodeGen.executeAndSpecialize(MatchDataNodesFactory.java:578)
        from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexNodeGen.execute(MatchDataNodesFactory.java:522)
        from org.truffleruby.core.regexp.MatchDataNodes$GetIndexCoreMethodNode.getIndex(MatchDataNodes.java:451)
        from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexCoreMethodNodeFactory$GetIndexCoreMethodNodeGen.executeAndSpecialize(MatchDataNodesFactory.java:1064)
        from org.truffleruby.core.regexp.MatchDataNodesFactory$GetIndexCoreMethodNodeFactory$GetIndexCoreMethodNodeGen.execute(MatchDataNodesFactory.java:1051)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
bad-regexp-aref.rb:2:in `[]'
        from bad-regexp-aref.rb:2:in `<main>'
```

**Comment by andrykonchin** [comment]
Fixed in fbbc027e0ddbe377258dd1b0fb62b9dc83c2e0ac
