### ISSUE TITLE
TruffleRuby nightlies fail with yjit-bench chunky_png

### ISSUE THREAD

**Issue by noahgibbs** [oracle/truffleruby#2954]
If I download the most recent TruffleRuby head (truffleruby 23.0.0-dev-79587128, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]), it fails on chunky_png-1.4.0 (the latest released version) when trying to write a file. Stack trace below.

~~~
<internal:core> core/truffle/io_operations.rb:77:in `write_transcoding': undefined method `ascii_compatible?' for "ASCII-8BIT":String (NoMethodError)
Did you mean?  ascii_only?
	from /home/ubuntu/truffleruby-head/lib/truffle/stringio.rb:287:in `write'
	from /home/ubuntu/truffleruby-head/lib/truffle/stringio.rb:76:in `<<'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/chunk.rb:79:in `write_with_crc'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/chunk.rb:89:in `write'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/datastream.rb:165:in `block in write'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/datastream.rb:125:in `each_chunk'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/datastream.rb:165:in `write'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/datastream.rb:179:in `to_blob'
	from /home/ubuntu/truffleruby-head/lib/gems/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_encoding.rb:50:in `to_blob'
	from benchmarks/chunky_png/benchmark.rb:19:in `block (2 levels) in <main>'
	from <internal:core> core/integer.rb:148:in `times'
	from benchmarks/chunky_png/benchmark.rb:18:in `block in <main>'
	from /home/ubuntu/ym/yjit-bench/harness/harness.rb:29:in `block in run_benchmark'
	from /home/ubuntu/truffleruby-head/lib/mri/benchmark.rb:311:in `realtime'
	from /home/ubuntu/ym/yjit-bench/harness/harness.rb:29:in `run_benchmark'
	from benchmarks/chunky_png/benchmark.rb:17:in `<main>'
~~~

**Comment by eregon** [comment]
Thank you for the report, it looks like `StringIO.set_encoding` is not coercing the encoding argument to an Encoding (and chunky_png seems to call it with a String).
