### ISSUE TITLE
Polyglot::ForeignException: missing LLVM builtin: llvm.fshl.v4i32 with sqlite3 on aarch64-darwin22

### ISSUE THREAD

**Issue by rwstauner** [oracle/truffleruby#3069]
Using a mac (machine: `arm64e`, ruby platform: `aarch64-darwin22`)
trying to setup the db in a rails repo that uses sqlite3 i got this output:

```
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.language.objects.SingletonClassNodeGen node with values of type com.oracle.truffle.llvm.runtime.LLVMUnsupportedException
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeAndSpecialize(SingletonClassNodeGen.java:437)
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeSingletonClass(SingletonClassNodeGen.java:211)
        from org.truffleruby.core.module.ModuleNodes$ExtendObjectNode.extendObject(ModuleNodes.java:1552)
        from org.truffleruby.core.module.ModuleNodesFactory$ExtendObjectNodeFactory$ExtendObjectNodeGen.execute(ModuleNodesFactory.java:5442)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
<internal:core> core/kernel.rb:332:in `extend_object'
<internal:core> core/kernel.rb:332:in `block in extend'
<internal:core> core/array.rb:996:in `reverse_each'
<internal:core> core/kernel.rb:327:in `extend'

Caused by:
Polyglot::ForeignException: missing LLVM builtin: llvm.fshl.v4i32

/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `sqlite3_randomness'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `writeJournalHdr'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `pager_write'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `newDatabase'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `sqlite3BtreeBeginTrans'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `sqlite3VdbeExec'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `sqlite3_step'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/ext/sqlite3/statement.c:105:in `step'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/resultset.rb:170:in `SQLite3::ResultSet#next_hash'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/resultset.rb:105:in `SQLite3::ResultSet#next'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/resultset.rb:133:in `SQLite3::ResultSet#each'
<internal:core> core/enumerable.rb:308:in `Enumerable#to_a'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/database.rb:207:in `block in SQLite3::Database#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/database.rb:156:in `SQLite3::Database#prepare'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.2/lib/sqlite3/database.rb:198:in `SQLite3::Database#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.4/lib/active_record/connection_adapters/sqlite3/database_statements.rb:32:in `block (2 levels) in ActiveRecord::ConnectionAdapters::SQLite3::DatabaseStatements#execute'
...
```

I was able to reproduce the issue with a new minimal rails app:

```
$ ruby -v
truffleruby 23.1.0-dev-ab9f1a6a*, like ruby 3.1.3, GraalVM CE JVM [aarch64-darwin]

gem install rails
rails new trtest
cd trtest
rails g model User name
bin/rails db:migrate
```

```
rails aborted!
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.language.objects.SingletonClassNodeGen node with values of type com.oracle.truffle.llvm.runtime.LLVMUnsupportedException
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeAndSpecialize(SingletonClassNodeGen.java:437)
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeSingletonClass(SingletonClassNodeGen.java:211)
        from org.truffleruby.core.module.ModuleNodes$ExtendObjectNode.extendObject(ModuleNodes.java:1552)
        from org.truffleruby.core.module.ModuleNodesFactory$ExtendObjectNodeFactory$ExtendObjectNodeGen.execute(ModuleNodesFactory.java:5442)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)


Caused by:
Polyglot::ForeignException: missing LLVM builtin: llvm.fshl.v4i32

(See full trace by running task with --trace)
```

<details>
<summary>Click to expand trace output</summary>

```
$ bin/rails db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
rails aborted!
TypeError: TruffleRuby doesn't have a case for the org.truffleruby.language.objects.SingletonClassNodeGen node with values of type com.oracle.truffle.llvm.runtime.LLVMUnsupportedException
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeAndSpecialize(SingletonClassNodeGen.java:437)
        from org.truffleruby.language.objects.SingletonClassNodeGen.executeSingletonClass(SingletonClassNodeGen.java:211)
        from org.truffleruby.core.module.ModuleNodes$ExtendObjectNode.extendObject(ModuleNodes.java:1552)
        from org.truffleruby.core.module.ModuleNodesFactory$ExtendObjectNodeFactory$ExtendObjectNodeGen.execute(ModuleNodesFactory.java:5442)
        from org.truffleruby.language.RubyCoreMethodRootNode.execute(RubyCoreMethodRootNode.java:58)
<internal:core> core/kernel.rb:332:in `extend_object'
<internal:core> core/kernel.rb:332:in `block in extend'
<internal:core> core/array.rb:996:in `reverse_each'
<internal:core> core/kernel.rb:327:in `extend'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:230:in `add_chain_to'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:221:in `block in invoke_with_call_chain'
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_6DFCC9E7BF_JAVA17/graalvm-6dfcc9e7bf-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:218:in `mon_synchronize'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/command.rb:51:in `invoke'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands.rb:18:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `gem_original_require'
bin/rails:4:in `<main>'

Caused by:
Polyglot::ForeignException: missing LLVM builtin: llvm.fshl.v4i32
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `sqlite3_randomness'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `writeJournalHdr'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `pager_write'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `newDatabase'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `sqlite3BtreeBeginTrans'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `sqlite3VdbeExec'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `sqlite3_step'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/ext/sqlite3/statement.c:105:in `step'
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_6DFCC9E7BF_JAVA17/graalvm-6dfcc9e7bf-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `<unknown>'
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_6DFCC9E7BF_JAVA17/graalvm-6dfcc9e7bf-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/truffle/truffle/cext_ruby.rb:41:in `SQLite3::Statement#step'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/resultset.rb:170:in `SQLite3::ResultSet#next_hash'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/resultset.rb:105:in `SQLite3::ResultSet#next'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/resultset.rb:133:in `SQLite3::ResultSet#each'
<internal:core> core/enumerable.rb:308:in `Enumerable#to_a'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/database.rb:207:in `block in SQLite3::Database#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/database.rb:156:in `SQLite3::Database#prepare'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/sqlite3-1.6.3/lib/sqlite3/database.rb:198:in `SQLite3::Database#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/sqlite3/database_statements.rb:32:in `block (2 levels) in ActiveRecord::ConnectionAdapters::SQLite3::DatabaseStatements#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activesupport-7.0.5/lib/active_support/concurrency/share_lock.rb:187:in `ActiveSupport::Concurrency::ShareLock#yield_shares'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activesupport-7.0.5/lib/active_support/dependencies/interlock.rb:41:in `ActiveSupport::Dependencies::Interlock#permit_concurrent_loads'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/sqlite3/database_statements.rb:31:in `block in ActiveRecord::ConnectionAdapters::SQLite3::DatabaseStatements#execute'
<internal:core> core/thread.rb:94:in `Thread#handle_interrupt'
<internal:core> core/thread.rb:94:in `Thread.handle_interrupt'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in ActiveSupport::Concurrency::LoadInterlockAwareMonitor#synchronize'
<internal:core> core/thread.rb:94:in `Thread#handle_interrupt'
<internal:core> core/thread.rb:94:in `Thread.handle_interrupt'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activesupport-7.0.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `ActiveSupport::Concurrency::LoadInterlockAwareMonitor#synchronize'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in ActiveRecord::ConnectionAdapters::AbstractAdapter#log'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activesupport-7.0.5/lib/active_support/notifications/instrumenter.rb:24:in `ActiveSupport::Notifications::Instrumenter#instrument'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `ActiveRecord::ConnectionAdapters::AbstractAdapter#log'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/sqlite3/database_statements.rb:30:in `ActiveRecord::ConnectionAdapters::SQLite3::DatabaseStatements#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/connection_adapters/abstract/schema_statements.rb:326:in `ActiveRecord::ConnectionAdapters::SchemaStatements#create_table'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/schema_migration.rb:23:in `ActiveRecord::SchemaMigration.create_table'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/migration.rb:1259:in `ActiveRecord::Migrator#initialize'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/migration.rb:1117:in `ActiveRecord::MigrationContext#up'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/migration.rb:1092:in `ActiveRecord::MigrationContext#migrate'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/tasks/database_tasks.rb:262:in `ActiveRecord::Tasks::DatabaseTasks#migrate'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/activerecord-7.0.5/lib/active_record/railties/databases.rake:92:in `block (2 levels) in <top (required)>'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in Rake::Task#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `Array#each'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:281:in `Rake::Task#execute'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in Rake::Task#invoke_with_call_chain'
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_6DFCC9E7BF_JAVA17/graalvm-6dfcc9e7bf-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/mri/monitor.rb:218:in `MonitorMixin#mon_synchronize'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:199:in `Rake::Task#invoke_with_call_chain'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/task.rb:188:in `Rake::Task#invoke'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:160:in `Rake::Application#invoke_task'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in Rake::Application#top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `Array#each'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in Rake::Application#top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:125:in `Rake::Application#run_with_threads'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:110:in `Rake::Application#top_level'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in Rails::Command::RakeCommand.perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/application.rb:186:in `Rake::Application#standard_exception_handling'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:24:in `block in Rails::Command::RakeCommand.perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `Rake.with_application'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands/rake/rake_command.rb:18:in `Rails::Command::RakeCommand.perform'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/command.rb:51:in `Rails::Command.invoke'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/railties-7.0.5/lib/rails/commands.rb:18:in `<top (required)>'
<internal:core> core/kernel.rb:234:in `Kernel#gem_original_require'
bin/rails:4:in `<main>'
bin/rails db:migrate --trace  94.90s user 2.09s system 462% cpu 20.987 total
```

</details>

Not sure if it's a related problem or something else
but I tried the test suite of https://github.com/sparklemotion/sqlite3-ruby and it hangs a few tests in... after a while I tried to interrupt it:

```
info: sqlite3-ruby version: 1.6.3/1.6.3
info: sqlite3 version: 3.42.0/3.42.0
info: sqlcipher?: false
info: threadsafe?: true
Run options: --seed 59622

# Running:

E......^Crake aborted!
Interrupt: Interrupt
<internal:core> core/main.rb:68:in `block (2 levels) in <top (required)>'
<internal:core> core/posix.rb:142:in `truffleposix_waitpid'
<internal:core> core/truffle/process_operations.rb:146:in `block in wait'
<internal:core> core/truffle/ffi/pointer.rb:255:in `new'
<internal:core> core/truffle/process_operations.rb:145:in `wait'
<internal:core> core/process.rb:601:in `wait'
<internal:core> core/kernel.rb:598:in `system'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:381:in `load'
<internal:core> core/kernel.rb:381:in `load'
/Users/rwstauner/.gem/truffleruby/3.1.3/gems/bundler-2.4.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
```

**Comment by eregon** [comment]
Note we currently test sqlite3 1.5.3 in CI on all 4 platforms, so that may be a temporary workaround.
We'll update the test to use sqlite3 1.6.2 as in this repro.

**Comment by rschatz** [comment]
Fixed upstream by https://github.com/oracle/graal/pull/6858
Should be picked up by the next import update.
