### ISSUE TITLE
invalid hash (BCrypt::Errors::InvalidHash)

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#3122]
With (similar to the snippet in https://github.com/oracle/truffleruby/issues/3121):
```ruby
require "bcrypt"
require "benchmark"

1000.times { |i|
  puts Benchmark.realtime {
    BCrypt::Password.create("test#{i}", cost: 5)
  }
}
```

On CRuby it works fine, but on TruffleRuby 23.0 and master it gives:
```
/home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bcrypt-3.1.18/lib/bcrypt/password.rb:60:in `initialize': invalid hash (BCrypt::Errors::InvalidHash)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/bcrypt-3.1.18/lib/bcrypt/password.rb:46:in `create'
	from bcrypt.rb:6:in `block (2 levels) in <main>'
	from /home/eregon/.rubies/truffleruby-dev/lib/mri/benchmark.rb:311:in `realtime'
	from bcrypt.rb:5:in `block in <main>'
	from <internal:core> core/integer.rb:148:in `times'
	from bcrypt.rb:4:in `<main>'
```

Internal issue: GR-46796

**Comment by eregon** [comment]
With `ruby --experimental-options --engine.Compilation=false bcrypt.rb` it does not fail (but is also much slower of course).

**Comment by eregon** [comment]
Running the test suite of the gem also reproduces the issue:
```
cd bcrypt-ruby
bundle install
bundle exec rake
```
gives
```
Failures:

  1) Generating BCrypt hashes should be interoperable with other implementations
     Failure/Error: expect(BCrypt::Engine.hash_secret(secret, salt)).to eql(test_vector)
     
       expected: "$2y$06$ACfku9dT6.H8VjdKb8nhluaoBmhJyK7GfoNScEfOfrJffUxoUeCjK"
            got: nil
     
       (compared using eql?)
...
  2) Creating a hashed password should tolerate empty string secrets
     Failure/Error: expect { BCrypt::Password.create( "\n".chop  ) }.not_to raise_error
     
       expected no Exception, got #<BCrypt::Errors::InvalidHash: invalid hash> with backtrace:
...
```

It passed on January 5: https://github.com/bcrypt-ruby/bcrypt-ruby/actions/runs/3842970891/jobs/6544804825, so it seems a regression since then.
And indeed with 22.3.1 the test suite passes.

**Comment by eregon** [comment]
It was an upstream bug: https://github.com/bcrypt-ruby/bcrypt-ruby/pull/270
