### ISSUE TITLE
Attached local scope method cannot be called

### ISSUE THREAD

**Issue by itarato** [oracle/truffleruby#3134]
Example:

```ruby
private def bar; end

foo = Object.new
foo.singleton_class.send(:define_method, :bar, method(:bar))

foo.bar
```

This runs in CRuby fine. In TruffleRuby:

```
something.rb:6:in `<main>': private method `bar' called for #<Object:0xd8> (NoMethodError)
```

Different example:

```ruby
private def bar; end

foo = Object.new
foo.define_singleton_method(:bar, method(:bar))

foo.bar
```

This too runs in CRuby fine. In TruffleRuby:

```
something.rb:6:in `<main>': private method `bar' called for #<Object:0xd8> (NoMethodError)
```

---

Test cases:

```ruby
# Define new private (unbounded) method -> private

class Foo1
	private
	define_method(:bar) {}
end

begin
	Foo1.new.bar
	raise("Failed")
rescue NoMethodError
	puts("Is private")
end

# Define new public (unbounded) method -> public

class Foo2
	define_method(:bar) {}
	private
end

Foo2.new.bar
puts("Is public")

# Redefine public (unbounded) method -> public

class Foo3
	def bar
		"public"
	end

	define_method(:bar, Foo3.instance_method(:bar))
end

puts("Is #{Foo3.new.bar}")

# Redefine private (unbounded) method -> private

class Foo4
	private

	def bar; end

	define_method(:bar, Foo4.instance_method(:bar))
end

begin
	Foo4.new.bar
	raise("Failed")
rescue NoMethodError
	puts("Is private")
end

# Redefine private (unbounded) method as public -> private (TruffleRuby bug)

class Foo5
	private

	def bar; end

	public

	define_method(:bar, Foo5.instance_method(:bar))
end

begin
	Foo5.new.bar
	raise("Failed")
rescue NoMethodError
	puts("Is private")
end

# Redefine public (unbounded) method as private -> public (TruffleRuby bug)

class Foo6
	def bar
		"public"
	end

	private

	define_method(:bar, Foo6.instance_method(:bar))
end

puts("Is #{Foo6.new.bar}")

# Define public (unbounded) method with different private -> public

class Foo7
	private

	def bar
		"public"
	end

	public

	define_method(:baz, Foo7.instance_method(:bar))
end

puts("Is #{Foo7.new.baz}")

# Define private (unbounded) method with different public -> private

class Foo8
	def bar
		"public"
	end

	private

	define_method(:baz, Foo8.instance_method(:bar))
end

begin
	Foo8.new.baz
	raise("Failed")
rescue NoMethodError
	puts("Is private")
end

# Redefine public (bounded) method -> public

class Foo9
	def bar
		"public"
	end
end

foo9 = Foo9.new
foo9.define_singleton_method(:bar, foo9.method(:bar))

puts("Is #{foo9.bar}")

# Redefine private (bounded) method -> public (TruffleRuby bug)

class Foo10
	private

	def bar
		"public"
	end
end

foo10 = Foo10.new
foo10.define_singleton_method(:bar, foo10.method(:bar))

puts("Is #{foo10.bar}")

# Redefine public (bounded) method as private -> private

class Foo11
	def bar; end
end

foo11 = Foo11.new

class << foo11
	private
	
	define_method(:bar, Foo11.new.method(:bar))
end

begin
	foo11.bar
	raise("Failed")
rescue NoMethodError
	puts("Is private")
end
```

# Expectation

- if `define target == current callFrame self` -> use scope visibility
- use public visibility

### ~Redefine private (unbounded) method as public~ this is likely a CRuby bug

```ruby
class Foo5
	private

	def bar; end

	public

	define_method(:bar, Foo5.instance_method(:bar))
end

Foo5.new.bar # Fails in CRuby but no errors in TruffleRuby
```

### ~Redefine public (unbounded) method as private~ this is likely a CRuby bug

```ruby
class Foo6
	def bar
		"public"
	end

	private

	define_method(:bar, Foo6.instance_method(:bar))
end

Foo6.new.bar # No error in CRuby but fails in TruffleRuby
```

### Redefine private (bounded) method

```ruby
class Foo10
	private

	def bar
		"public"
	end
end

foo10 = Foo10.new
foo10.define_singleton_method(:bar, foo10.method(:bar))

foo10.bar # No error in CRuby but fails in TruffleRuby
```

### Redefine public (bounded) method as private -> private

```ruby
class Foo11
	def bar; end
end

foo11 = Foo11.new

class << foo11
	private
	
	define_method(:bar, Foo11.new.method(:bar))
end

foo11.bar # Fails in CRuby but no errors in TruffleRuby
```

**Comment by eregon** [comment]
I think it is probably a bug of CRuby rather.
First, the `send` is not needed, and removing it does not change anything.
Without the `send`, it's clear the caller of `define_method` is the main script top-level, and that has private visibility by default.
AFAIK `define_method` always uses the visibility from the caller, the fact CRuby seems to not use it here seems inconsistent. Could you report a CRuby issue for that?

Using `define_singleton_method`, `def foo.bar` or `class_exec`, etc all work fine and set the visibility correctly.

**Comment by itarato** [comment]
Added Ruby core issue: https://bugs.ruby-lang.org/issues/19745

**Comment by itarato** [comment]
@eregon https://bugs.ruby-lang.org/issues/19745#change-103692 Did we miss anything?

**Comment by itarato** [comment]
@eregon Added another issue about `define_method`: https://bugs.ruby-lang.org/issues/19749

**Comment by eregon** [comment]
@itarato I fixed the description. As Jeremy said, the visibility of the original method is irrelevant, that is never considered.
It's about the visibility in the caller frame.

**Comment by itarato** [comment]
It seems both cases (`define_method` and `define_singleton_method`) by default Ruby should add them as public methods: https://bugs.ruby-lang.org/issues/19749#change-103701

**Comment by eregon** [comment]
https://bugs.ruby-lang.org/issues/19749#note-8 so we need to implement that logic. Do you want to give it a try?

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/pull/3187 and https://github.com/oracle/truffleruby/pull/3143 and
