### ISSUE TITLE
Unexpected internal exception at_exit

### ISSUE THREAD

**Issue by rwstauner** [oracle/truffleruby#3169]
After dozens of successful CI runs on an internal app I saw one of them fail with this error:

> truffleruby: unexpected internal exception in at_exit,
> please report it to https://github.com/oracle/truffleruby/issues.
 
```
dead handle 0xbad00000014d980 (com.oracle.truffle.api.CompilerDirectives.ShouldNotReachHere)
	from com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:574)
	from com.oracle.truffle.api.CompilerDirectives.shouldNotReachHere(CompilerDirectives.java:520)
	from org.truffleruby.cext.UnwrapNode$UnwrapNativeNode.raiseError(UnwrapNode.java:107)
	from org.truffleruby.cext.UnwrapNode$UnwrapNativeNode.unwrapTaggedObject(UnwrapNode.java:92)
	from org.truffleruby.cext.UnwrapNodeGen$UnwrapNativeNodeGen$Inlined.execute(UnwrapNodeGen.java:377)
	from org.truffleruby.cext.UnwrapNode.longToWrapper(UnwrapNode.java:270)
	from org.truffleruby.cext.UnwrapNodeGen$Inlined.execute(UnwrapNodeGen.java:143)
	from org.truffleruby.cext.CExtNodes$CallWithCExtLockAndFrameAndUnwrapNode.callWithCExtLockAndFrame(CExtNodes.java:249)
	from org.truffleruby.cext.CExtNodesFactory$CallWithCExtLockAndFrameAndUnwrapNodeFactory$CallWithCExtLockAndFrameAndUnwrapNodeGen.execute(CExtNodesFactory.java:549)
	from org.truffleruby.language.locals.WriteLocalVariableNode.execute(WriteLocalVariableNode.java:28)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:64)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	from org.truffleruby.core.module.ModuleNodes$DefineMethodNode$CallMethodWithLambdaBody.execute(ModuleNodes.java:1388)
	from org.truffleruby.language.RubyLambdaRootNode.execute(RubyLambdaRootNode.java:84)
/usr/local/ruby/lib/truffle/truffle/cext_ruby.rb:22:in `next'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/node.rb:71:in `each'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:24:in `block in out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `each'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `out'
	from <private app file>.rb:18:in `block (2 levels) in blockquote'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:84:in `container'
	from <private app file>.rb:17:in `block in blockquote'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:78:in `block'
	from <private app file>.rb:16:in `blockquote'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:44:in `render'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:28:in `block in out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `each'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:24:in `block (2 levels) in out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/node.rb:72:in `each'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:24:in `block in out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `each'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:21:in `out'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:53:in `document'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer/html_renderer.rb:6:in `document'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/commonmarker-0.23.9/lib/commonmarker/renderer.rb:38:in `render'
	from <private app file>.rb:181:in `build_html'
	from <private app file>.rb:23:in `html'
	from <private app file>.rb:12:in `html'
	from <private app file>.rb:46:in `build_from_page'
	from <private app file>.rb:223:in `update_page'
	from <private app file>.rb:86:in `test_#update_page_indexes_the_page_in_search_index'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:97:in `block (3 levels) in run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest.rb:297:in `time_it'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:96:in `block (2 levels) in run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:197:in `capture_exceptions'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:89:in `block in run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest.rb:401:in `on_signal'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:245:in `with_info_handler'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest/test.rb:87:in `run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-reporters-3a07af0f213b/lib/minitest/reporters.rb:48:in `run_with_hooks'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest.rb:1062:in `run_one_method'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:179:in `block in run'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:168:in `with_timestamps'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:178:in `run'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:229:in `block in run_from_queue'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/ci/queue/redis/worker.rb:55:in `poll'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:228:in `run_from_queue'
	from /tmp/bundle/truffleruby/3.1.3.9/gems/ci-queue-0.31.0/lib/minitest/queue.rb:213:in `__run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest.rb:159:in `run'
	from /tmp/bundle/truffleruby/3.1.3.9/bundler/gems/minitest-29d18fb7a772/lib/minitest.rb:83:in `block in autorun'
```

Since these tests run with `ci-queue` retrying this job won't actually run anything so I'm not sure there's much I can do to try to reproduce, but let me know if there's any more info I could provide that would be helpful.

**Comment by eregon** [comment]
So this most likely means there is an issue in `commonmarker` where it does not mark a `VALUE`, and that one GCs and then it tries to access it and we get this error.
Probably a good way to repro would be to run the `commonmarker` test suite, or to extract how the app uses `commonmarker` if the test suite doesn't repro.

**Comment by andrykonchin** [comment]
Duplicates #2842
