### ISSUE TITLE
Process hangs at pthread_cond_wait during shutdown

### ISSUE THREAD

**Issue by ntkme** [oracle/truffleruby#3171]
I found it occurs rarely that the `truffleruby 23.0.0` would hang forever during shutdown.

It is reproducible on both linux and mac, on native or jvm mode.

Sending `SIGALRM`:

```
All Thread and Fiber backtraces:
#<Fiber:0x12308 root (created)> of #<Thread:0x12318 Ruby-reference-processor sleep>

#<Fiber:0x12338 root (created)> of #<Thread:0x12348 main run>
<internal:core> core/truffle/debug.rb:15:in `show_backtraces'
<internal:core> core/main.rb:74:in `block (2 levels) in <top (required)>'
```

Sending `SIGQUIT`:

```
Full thread dump:

"Ruby Thread id=61 from Ruby-reference-processor" #61 thread=0x00000001252050c0 state=WAITING

  SP 0x000000016c0965a0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_wait(Pthread.java)
  SP 0x000000016c0965a0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:361)
  SP 0x000000016c096630 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016c096680 IP 0x000000011306e764  [image code] com.oracle.svm.core.thread.PlatformThreads.parkCurrentPlatformOrCarrierThread(PlatformThreads.java:907)
  SP 0x000000016c0966d0 IP 0x00000001155cad3c  [image code] jdk.internal.misc.Unsafe.park(Unsafe.java:56)
  SP 0x000000016c096720 IP 0x0000000115457dd0  [image code] java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
  SP 0x000000016c096720 IP 0x0000000115457dd0  [image code] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
  SP 0x000000016c096760 IP 0x000000011541f910  [image code] java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
  SP 0x000000016c0967b0 IP 0x000000011541c5ec  [image code] java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
  SP 0x000000016c0967e0 IP 0x00000001154580c8  [image code] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
  SP 0x000000016c096830 IP 0x00000001150ea100  [image code] java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:67)
  SP 0x000000016c096830 IP 0x00000001150ea100  [image code] java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
  SP 0x000000016c096860 IP 0x00000001150e9c84  [image code] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:234)
  SP 0x000000016c0968a0 IP 0x00000001161d9914  [image code] org.truffleruby.core.ReferenceProcessingService$ReferenceProcessor.lambda$createProcessingThread$0(ReferenceProcessingService.java:123)
  SP 0x000000016c0968d0 IP 0x00000001161d8e94  [image code] org.truffleruby.core.ReferenceProcessingService$ReferenceProcessor$$Lambda$85ea39eaadc556bfc830a91f9fdcceb0c080cf0c.block(Unknown Source)
  SP 0x000000016c096900 IP 0x0000000116f83458  [image code] org.truffleruby.core.thread.ThreadManager.lambda$runUntilResult$4(ThreadManager.java:619)
  SP 0x000000016c096950 IP 0x0000000116f78734  [image code] org.truffleruby.core.thread.ThreadManager$$Lambda$6e1fcdf100613db8e134ae0d55f66237138ed027.apply(Unknown Source)
  SP 0x000000016c096980 IP 0x0000000113153fb8  [image code] com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedBoundary(ThreadLocalHandshake.java:596)
  SP 0x000000016c0969f0 IP 0x0000000116f85008  [image code] com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedWithException(ThreadLocalHandshake.java:567)
  SP 0x000000016c0969f0 IP 0x0000000116f85008  [image code] org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:616)
  SP 0x000000016c096a70 IP 0x00000001161d9b1c  [image code] org.truffleruby.core.thread.ThreadManager.runUntilResult(ThreadManager.java:595)
  SP 0x000000016c096a70 IP 0x00000001161d9b1c  [image code] org.truffleruby.core.ReferenceProcessingService$ReferenceProcessor.lambda$createProcessingThread$1(ReferenceProcessingService.java:122)
  SP 0x000000016c096ad0 IP 0x00000001161d8f0c  [image code] org.truffleruby.core.ReferenceProcessingService$ReferenceProcessor$$Lambda$d4a8c25707010067a25664df8e3f45f0468532bb.get(Unknown Source)
  SP 0x000000016c096b00 IP 0x0000000116f85b20  [image code] org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:322)
  SP 0x000000016c096b50 IP 0x0000000116f787b8  [image code] org.truffleruby.core.thread.ThreadManager.lambda$initialize$3(ThreadManager.java:308)
  SP 0x000000016c096b50 IP 0x0000000116f787b8  [image code] org.truffleruby.core.thread.ThreadManager$$Lambda$6ee3c0829ad44c683c251ca5bfb18f44c7bf908c.run(Unknown Source)
  SP 0x000000016c096b80 IP 0x0000000115003c6c  [image code] java.lang.Thread.runWith(Thread.java:1636)
  SP 0x000000016c096b80 IP 0x0000000115003c6c  [image code] java.lang.Thread.run(Thread.java:1623)
  SP 0x000000016c096bb0 IP 0x0000000114699bd0  [image code] com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  SP 0x000000016c096bb0 IP 0x0000000114699bd0  [image code] com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  SP 0x000000016c096bb0 IP 0x0000000114699bd0  [image code] com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  SP 0x000000016c096c00 IP 0x0000000114699a80  [image code] com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  SP 0x000000016c096c30 IP 0x0000000115cd8540  [image code] org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:718)
  SP 0x000000016c096c30 IP 0x0000000115cd8540  [image code] org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:641)
  SP 0x000000016c096cf0 IP 0x0000000115ccf0ac  [image code] org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:574)
  SP 0x000000016c096d30 IP 0x00000001130a0c0c  [image code] com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:115)
  SP 0x000000016c096d30 IP 0x00000001130a0c0c  [image code] com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:194)
  SP 0x000000016c096d60 IP 0x0000000115ccf2f4  [image code] com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:97)
  SP 0x000000016c096d60 IP 0x0000000115ccf2f4  [image code] org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:486)
  SP 0x000000016c096da0 IP 0x0000000115ccef30  [image code] org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:467)
  SP 0x000000016c096e00 IP 0x000000011469a5ac  [image code] com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
  SP 0x000000016c096e50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016c096e90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016c096ec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"Ruby-NativeCallInterrupt-Timer" #56 daemon thread=0x0000000124604f40 state=WAITING

  SP 0x000000016bddaac0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_wait(Pthread.java)
  SP 0x000000016bddaac0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:361)
  SP 0x000000016bddab50 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016bddaba0 IP 0x000000011306e764  [image code] com.oracle.svm.core.thread.PlatformThreads.parkCurrentPlatformOrCarrierThread(PlatformThreads.java:907)
  SP 0x000000016bddabf0 IP 0x00000001155cad3c  [image code] jdk.internal.misc.Unsafe.park(Unsafe.java:56)
  SP 0x000000016bddac40 IP 0x000000011545e6d4  [image code] java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
  SP 0x000000016bddac70 IP 0x000000011301be28  [image code] com.oracle.svm.core.monitor.JavaMonitorQueuedSynchronizer$ConditionNode.block(JavaMonitorQueuedSynchronizer.java:133)
  SP 0x000000016bddaca0 IP 0x000000011301c088  [image code] com.oracle.svm.core.monitor.JavaMonitorQueuedSynchronizer$JavaMonitorConditionObject.await(JavaMonitorQueuedSynchronizer.java:516)
  SP 0x000000016bddad10 IP 0x000000011301fe38  [image code] com.oracle.svm.core.monitor.MultiThreadedMonitorSupport.doWait(MultiThreadedMonitorSupport.java:355)
  SP 0x000000016bddad50 IP 0x000000011301f960  [image code] com.oracle.svm.core.monitor.MonitorSupport.wait(MonitorSupport.java:94)
  SP 0x000000016bddada0 IP 0x00000001153aa950  [image code] java.lang.Object.waitSubst(Object.java:110)
  SP 0x000000016bddada0 IP 0x00000001153aa950  [image code] java.lang.Object.wait(Object.java:339)
  SP 0x000000016bddada0 IP 0x00000001153aa950  [image code] java.util.TimerThread.mainLoop(Timer.java:537)
  SP 0x000000016bddae10 IP 0x00000001153aacb0  [image code] java.util.TimerThread.run(Timer.java:516)
  SP 0x000000016bddae50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016bddae90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016bddaec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"nfi-gc" #55 daemon thread=0x0000000124704dc0 state=WAITING

  SP 0x000000016bd4eae0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_wait(Pthread.java)
  SP 0x000000016bd4eae0 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:361)
  SP 0x000000016bd4eb70 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016bd4ebc0 IP 0x000000011306e764  [image code] com.oracle.svm.core.thread.PlatformThreads.parkCurrentPlatformOrCarrierThread(PlatformThreads.java:907)
  SP 0x000000016bd4ec10 IP 0x00000001155cad3c  [image code] jdk.internal.misc.Unsafe.park(Unsafe.java:56)
  SP 0x000000016bd4ec60 IP 0x0000000115457dd0  [image code] java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
  SP 0x000000016bd4ec60 IP 0x0000000115457dd0  [image code] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
  SP 0x000000016bd4eca0 IP 0x000000011541f910  [image code] java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
  SP 0x000000016bd4ecf0 IP 0x000000011541c5ec  [image code] java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
  SP 0x000000016bd4ed20 IP 0x00000001154580c8  [image code] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
  SP 0x000000016bd4ed70 IP 0x00000001150ea100  [image code] java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:67)
  SP 0x000000016bd4ed70 IP 0x00000001150ea100  [image code] java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
  SP 0x000000016bd4eda0 IP 0x00000001150e9c84  [image code] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:234)
  SP 0x000000016bd4ede0 IP 0x000000011451a9b8  [image code] com.oracle.truffle.nfi.backend.libffi.NativeAllocation$1.run(NativeAllocation.java:164)
  SP 0x000000016bd4ee20 IP 0x0000000115003c6c  [image code] java.lang.Thread.runWith(Thread.java:1636)
  SP 0x000000016bd4ee20 IP 0x0000000115003c6c  [image code] java.lang.Thread.run(Thread.java:1623)
  SP 0x000000016bd4ee50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016bd4ee90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016bd4eec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"Ruby-Cleaner" #53 daemon thread=0x0000000124704c00 state=TIMED_WAITING

  SP 0x000000016bcc2b00 IP 0x000000011303a78c  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_timedwait(Pthread.java)
  SP 0x000000016bcc2b00 IP 0x000000011303a78c  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:366)
  SP 0x000000016bcc2b90 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016bcc2be0 IP 0x000000011306e764  [image code] com.oracle.svm.core.thread.PlatformThreads.parkCurrentPlatformOrCarrierThread(PlatformThreads.java:907)
  SP 0x000000016bcc2c30 IP 0x00000001155cad3c  [image code] jdk.internal.misc.Unsafe.park(Unsafe.java:56)
  SP 0x000000016bcc2c80 IP 0x000000011545e84c  [image code] java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
  SP 0x000000016bcc2cb0 IP 0x0000000115458824  [image code] java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
  SP 0x000000016bcc2d20 IP 0x00000001150ea22c  [image code] java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
  SP 0x000000016bcc2d20 IP 0x00000001150ea22c  [image code] java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
  SP 0x000000016bcc2d80 IP 0x00000001150e9dd0  [image code] java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
  SP 0x000000016bcc2dc0 IP 0x0000000115636750  [image code] jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
  SP 0x000000016bcc2e20 IP 0x0000000115003c6c  [image code] java.lang.Thread.runWith(Thread.java:1636)
  SP 0x000000016bcc2e20 IP 0x0000000115003c6c  [image code] java.lang.Thread.run(Thread.java:1623)
  SP 0x000000016bcc2e50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016bcc2e90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016bcc2ec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"Signal Dispatcher" #51 daemon thread=0x0000000125104080 state=RUNNABLE

  SP 0x000000016bb1ed50 IP 0x0000000113031b58  [image code] com.oracle.svm.core.posix.headers.CSunMiscSignal.await(CSunMiscSignal.java)
  SP 0x000000016bb1ed50 IP 0x0000000113031b58  [image code] com.oracle.svm.core.posix.Util_jdk_internal_misc_Signal$SignalState.await(SunMiscSubstitutions.java:353)
  SP 0x000000016bb1eda0 IP 0x00000001130317bc  [image code] com.oracle.svm.core.posix.Util_jdk_internal_misc_Signal$DispatchThread.run(SunMiscSubstitutions.java:289)
  SP 0x000000016bb1ee20 IP 0x0000000115003c6c  [image code] java.lang.Thread.runWith(Thread.java:1636)
  SP 0x000000016bb1ee20 IP 0x0000000115003c6c  [image code] java.lang.Thread.run(Thread.java:1623)
  SP 0x000000016bb1ee50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016bb1ee90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016bb1eec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"Performance data" #42 daemon thread=0x0000000124604480 state=TIMED_WAITING

  SP 0x000000016ba92bf0 IP 0x000000011303a78c  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_timedwait(Pthread.java)
  SP 0x000000016ba92bf0 IP 0x000000011303a78c  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:366)
  SP 0x000000016ba92c80 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016ba92cd0 IP 0x000000011306ee98  [image code] com.oracle.svm.core.thread.PlatformThreads.sleep0(PlatformThreads.java:972)
  SP 0x000000016ba92d30 IP 0x000000011306e99c  [image code] com.oracle.svm.core.thread.PlatformThreads.sleep(PlatformThreads.java:936)
  SP 0x000000016ba92d70 IP 0x000000011306c644  [image code] com.oracle.svm.core.thread.JavaThreads.sleep0(JavaThreads.java:377)
  SP 0x000000016ba92d70 IP 0x000000011306c644  [image code] com.oracle.svm.core.thread.JavaThreads.sleep(JavaThreads.java:364)
  SP 0x000000016ba92dc0 IP 0x00000001150047cc  [image code] java.lang.Thread.sleep0(Thread.java:588)
  SP 0x000000016ba92dc0 IP 0x00000001150047cc  [image code] java.lang.Thread.sleep(Thread.java:484)
  SP 0x000000016ba92e10 IP 0x0000000113007008  [image code] com.oracle.svm.core.jvmstat.PerfManager$PerfDataThread.run(PerfManager.java:195)
  SP 0x000000016ba92e50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016ba92e90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016ba92ec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"Reference Handler" #50 daemon thread=0x0000000125004080 state=WAITING

  SP 0x000000016ba06d20 IP 0x0000000112f5a190  [image code] com.oracle.svm.core.genscavenge.HeapImpl.transitionToNativeThenAwaitPendingRefs(HeapImpl.java:577)
  SP 0x000000016ba06d70 IP 0x0000000112f5a298  [image code] com.oracle.svm.core.genscavenge.HeapImpl.waitForPendingReferenceList(HeapImpl.java:566)
  SP 0x000000016ba06db0 IP 0x0000000112f5a3c0  [image code] com.oracle.svm.core.genscavenge.HeapImpl.waitForReferencePendingList(HeapImpl.java:556)
  SP 0x000000016ba06df0 IP 0x0000000112fa79ec  [image code] com.oracle.svm.core.heap.ReferenceInternals.waitForPendingReferences(ReferenceInternals.java:159)
  SP 0x000000016ba06df0 IP 0x0000000112fa79ec  [image code] com.oracle.svm.core.heap.ReferenceHandlerThread.run(ReferenceHandlerThread.java:79)
  SP 0x000000016ba06e20 IP 0x0000000115003c6c  [image code] java.lang.Thread.runWith(Thread.java:1636)
  SP 0x000000016ba06e20 IP 0x0000000115003c6c  [image code] java.lang.Thread.run(Thread.java:1623)
  SP 0x000000016ba06e50 IP 0x0000000113070898  [image code] com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
  SP 0x000000016ba06e90 IP 0x000000011303b2b4  [image code] com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
  SP 0x000000016ba06ec0 IP 0x0000000112f26a84  [image code] com.oracle.svm.core.code.IsolateEnterStub.PosixPlatformThreads_pthreadStartRoutine_cf47bd191b082a3631657d369b9255c828b9a95c(IsolateEnterStub.java:0)
  
"main" #1 thread=0x0000000124704080 state=WAITING

  SP 0x000000016b979e10 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.headers.Pthread.pthread_cond_wait(Pthread.java)
  SP 0x000000016b979e10 IP 0x000000011303a834  [image code] com.oracle.svm.core.posix.thread.PosixParker.park0(PosixPlatformThreads.java:361)
  SP 0x000000016b979ea0 IP 0x000000011303a604  [image code] com.oracle.svm.core.posix.thread.PosixParker.park(PosixPlatformThreads.java:341)
  SP 0x000000016b979ef0 IP 0x000000011306e764  [image code] com.oracle.svm.core.thread.PlatformThreads.parkCurrentPlatformOrCarrierThread(PlatformThreads.java:907)
  SP 0x000000016b979f40 IP 0x00000001155cad3c  [image code] jdk.internal.misc.Unsafe.park(Unsafe.java:56)
  SP 0x000000016b979f90 IP 0x000000011545e6d4  [image code] java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
  SP 0x000000016b979fc0 IP 0x000000011301be60  [image code] com.oracle.svm.core.monitor.JavaMonitorQueuedSynchronizer$ConditionNode.block(JavaMonitorQueuedSynchronizer.java:133)
  SP 0x000000016b979ff0 IP 0x000000011301c088  [image code] com.oracle.svm.core.monitor.JavaMonitorQueuedSynchronizer$JavaMonitorConditionObject.await(JavaMonitorQueuedSynchronizer.java:516)
  SP 0x000000016b97a060 IP 0x000000011301fe38  [image code] com.oracle.svm.core.monitor.MultiThreadedMonitorSupport.doWait(MultiThreadedMonitorSupport.java:355)
  SP 0x000000016b97a0a0 IP 0x000000011301f960  [image code] com.oracle.svm.core.monitor.MonitorSupport.wait(MonitorSupport.java:94)
  SP 0x000000016b97a0f0 IP 0x000000011306e160  [image code] java.lang.Object.waitSubst(Object.java:110)
  SP 0x000000016b97a0f0 IP 0x000000011306e160  [image code] com.oracle.svm.core.thread.PlatformThreads.join(PlatformThreads.java:337)
  SP 0x000000016b97a150 IP 0x000000011306c32c  [image code] com.oracle.svm.core.thread.JavaThreads.join(JavaThreads.java:202)
  SP 0x000000016b97a190 IP 0x0000000116f78690  [image code] java.lang.Thread.join(Thread.java:594)
  SP 0x000000016b97a190 IP 0x0000000116f78690  [image code] java.lang.Thread.join(Thread.java:2191)
  SP 0x000000016b97a190 IP 0x0000000116f78690  [image code] org.truffleruby.core.thread.ThreadManager$$Lambda$46ed6f8605c07f1e1da47cef51aba441ea0a0abf.apply(Unknown Source)
  SP 0x000000016b97a1c0 IP 0x0000000113153fb8  [image code] com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedBoundary(ThreadLocalHandshake.java:596)
  SP 0x000000016b97a230 IP 0x00000001130dc56c  [image code] com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.setBlockedWithException(ThreadLocalHandshake.java:567)
  SP 0x000000016b97a230 IP 0x00000001130dc56c  [image code] com.oracle.truffle.api.TruffleSafepoint.setBlockedThreadInterruptible(TruffleSafepoint.java:278)
  SP 0x000000016b97a270 IP 0x0000000116f83204  [image code] org.truffleruby.core.thread.ThreadManager.runUntilResultKeepStatus(ThreadManager.java:528)
  SP 0x000000016b97a270 IP 0x0000000116f83204  [image code] org.truffleruby.core.thread.ThreadManager.killAndWaitOtherThreads(ThreadManager.java:673)
  SP 0x000000016b97a2b0 IP 0x0000000116040e3c  [image code] org.truffleruby.RubyContext.finalizeContext(RubyContext.java:481)
  SP 0x000000016b97a2e0 IP 0x000000011604c5fc  [image code] org.truffleruby.RubyLanguage.finalizeContext(RubyLanguage.java:525)
  SP 0x000000016b97a340 IP 0x000000011604c3f0  [image code] org.truffleruby.RubyLanguage.finalizeContext(RubyLanguage.java:141)
  SP 0x000000016b97a370 IP 0x00000001130c1758  [image code] com.oracle.truffle.api.LanguageAccessor$LanguageImpl.finalizeContext(LanguageAccessor.java:333)
  SP 0x000000016b97a3a0 IP 0x000000011464ede0  [image code] com.oracle.truffle.polyglot.PolyglotLanguageContext.finalizeContext(PolyglotLanguageContext.java:407)
  SP 0x000000016b97a3f0 IP 0x00000001145d5918  [image code] com.oracle.truffle.polyglot.PolyglotContextImpl.finalizeContext(PolyglotContextImpl.java:2890)
  SP 0x000000016b97a450 IP 0x00000001145d67d0  [image code] com.oracle.truffle.polyglot.PolyglotContextImpl.finishClose(PolyglotContextImpl.java:2438)
  SP 0x000000016b97a530 IP 0x00000001145d2824  [image code] com.oracle.truffle.polyglot.PolyglotContextImpl.closeImpl(PolyglotContextImpl.java:2352)
  SP 0x000000016b97a570 IP 0x00000001145d1e20  [image code] com.oracle.truffle.polyglot.PolyglotContextImpl.closeAndMaybeWait(PolyglotContextImpl.java:1630)
  SP 0x000000016b97a5b0 IP 0x00000001145d1b30  [image code] com.oracle.truffle.polyglot.PolyglotContextImpl.close(PolyglotContextImpl.java:1565)
  SP 0x000000016b97a600 IP 0x00000001145cc160  [image code] com.oracle.truffle.polyglot.PolyglotContextDispatch.close(PolyglotContextDispatch.java:73)
  SP 0x000000016b97a630 IP 0x0000000115d95188  [image code] org.graalvm.polyglot.Context.close(Context.java:835)
  SP 0x000000016b97a670 IP 0x0000000117535204  [image code] org.graalvm.polyglot.Context.close(Context.java:861)
  SP 0x000000016b97a670 IP 0x0000000117535204  [image code] org.truffleruby.launcher.RubyLauncher.runContext(RubyLauncher.java:311)
  SP 0x000000016b97a710 IP 0x0000000117536980  [image code] org.truffleruby.launcher.RubyLauncher.runRubyMain(RubyLauncher.java:254)
  SP 0x000000016b97a760 IP 0x00000001175330f0  [image code] org.truffleruby.launcher.RubyLauncher.launch(RubyLauncher.java:129)
  SP 0x000000016b97a7a0 IP 0x0000000115d5c388  [image code] org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
  SP 0x000000016b97a800 IP 0x0000000115d5be30  [image code] org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
  SP 0x000000016b97a840 IP 0x0000000115d5c95c  [image code] org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
  SP 0x000000016b97a8c0 IP 0x0000000112ff15a8  [image code] com.oracle.svm.core.jni.JNIJavaCallWrapperHolder.invoke_38238894020e363153a7ce9362a9ee24e7f32de5(JNIJavaCallWrapperHolder.java:0)
  SP 0x000000016b97a920 IP 0x0000000112fee970  [image code] com.oracle.svm.core.jni.JNIJavaCallVariantWrapperHolder.invokeJJIJIJI_J_VA_LIST(JNIJavaCallVariantWrapperHolder.java:0)
```

**Comment by eregon** [comment]
Thanks for the report.
I believe this was fixed in https://github.com/oracle/truffleruby/commit/89775c0a9301dca126d9667310eb65ac047d1f73, which is not 23.0 but will be in 23.1.
The problem happened due to Ruby-reference-processor catching the "shutdown exception".
