### ISSUE TITLE
Internal exception escaped out of the interpreter for newer ABI version

### ISSUE THREAD

**Issue by rwstauner** [oracle/truffleruby#3176]
I noticed this on an old version of TruffleRuby (so maybe it's fixed in newer versions),
but I'm reporting just in case because it told me too 😄 

If I compile an extension (`bootsnap`) with 23.1.0-dev
and then try to load it on 23.0.0. I get this:

truffleruby: an internal exception escaped out of the interpreter,
please report it to https://github.com/oracle/truffleruby/issues.

```
unknown for 4 (java.lang.AssertionError)
        from com.oracle.truffle.llvm.runtime.CommonNodeFactory.createFrameRead(CommonNodeFactory.java:698)
        from com.oracle.truffle.llvm.parser.nodes.LLVMSymbolReadResolver.resolve(LLVMSymbolReadResolver.java:140)
        from com.oracle.truffle.llvm.parser.nodes.LLVMBitcodeInstructionVisitor.visit(LLVMBitcodeInstructionVisitor.java:951)
        from com.oracle.truffle.llvm.parser.model.symbols.instructions.ReturnInstruction.accept(ReturnInstruction.java:46)
        from com.oracle.truffle.llvm.parser.model.symbols.instructions.ReturnInstruction.accept(ReturnInstruction.java:37)
        from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.generateCallTarget(LazyToTruffleConverterImpl.java:210)
        from com.oracle.truffle.llvm.parser.LazyToTruffleConverterImpl.convert(LazyToTruffleConverterImpl.java:128)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode$LazyLLVMIRFunction.resolve(LLVMFunctionCode.java:284)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode$ResolveFunctionNode.doLazyLLVMIRFunction(LLVMFunctionCode.java:227)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCodeFactory$ResolveFunctionNodeGen$Uncached.execute(LLVMFunctionCodeFactory.java:135)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode.isIntrinsicFunction(LLVMFunctionCode.java:380)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode.isIntrinsicFunctionSlowPath(LLVMFunctionCode.java:376)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode.initForeignCallTarget(LLVMFunctionCode.java:463)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionCode.getForeignCallTarget(LLVMFunctionCode.java:476)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptor$Execute.doPolymorphic(LLVMFunctionDescriptor.java:197)
        from com.oracle.truffle.llvm.runtime.LLVMFunctionDescriptorGen$InteropLibraryExports$Uncached.execute(LLVMFunctionDescriptorGen.java:472)
        from org.truffleruby.interop.InteropNodes.execute(InteropNodes.java:84)
        from org.truffleruby.language.loader.FeatureLoader.getEmbeddedABIVersion(FeatureLoader.java:536)
        from org.truffleruby.language.loader.FeatureLoader.loadCExtLibrary(FeatureLoader.java:519)
        from org.truffleruby.language.loader.RequireNode.requireCExtension(RequireNode.java:270)
        from org.truffleruby.language.loader.RequireNode.parseAndCall(RequireNode.java:219)
        from org.truffleruby.language.loader.RequireNode.doRequire(RequireNode.java:204)
        from org.truffleruby.language.loader.RequireNode.requireConsideringAutoload(RequireNode.java:128)
        from org.truffleruby.language.loader.RequireNode.lambda$requireWithMetrics$0(RequireNode.java:81)
        from org.truffleruby.debug.MetricsProfiler.callWithMetrics(MetricsProfiler.java:42)
        from org.truffleruby.language.loader.RequireNode.requireWithMetrics(RequireNode.java:78)
        from org.truffleruby.language.loader.RequireNode.require(RequireNode.java:68)
        from org.truffleruby.language.loader.RequireNodeGen.executeRequire(RequireNodeGen.java:27)
        from org.truffleruby.core.kernel.KernelNodes$LoadFeatureNode.loadFeature(KernelNodes.java:330)
        from org.truffleruby.core.kernel.KernelNodesFactory$LoadFeatureNodeFactory$LoadFeatureNodeGen.execute(KernelNodesFactory.java:868)
        from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:43)
        from org.truffleruby.language.control.IfElseNode.execute(IfElseNode.java:45)
        from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:37)
        from org.truffleruby.language.RubyMethodRootNode.execute(RubyMethodRootNode.java:65)
<internal:core> core/kernel.rb:226:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/lib/bootsnap/compile_cache/yaml.rb:3:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/test/test_helper.rb:11:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/test/bundler_test.rb:3:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/.gem/truffleruby/3.0.3/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /Users/rwstauner/.gem/truffleruby/3.0.3/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from /Users/rwstauner/.gem/truffleruby/3.0.3/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
```

If I do the reverse and compile the extension on 23.0.0 and try to load it with a more recent dev version I get a more appropriate looking error like this:

```
warning: The native extension at /Users/rwstauner/src/github.com/Shopify/bootsnap/lib-truffleruby/bootsnap/bootsnap.bundle has a different ABI version: "3.0.3.22.3.0" than the running TruffleRuby: "3.1.3.9"
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_C614F96B3C_JAVA21/graalvm-c614f96b3c-java21-23.1.0-dev/Contents/Home/languages/ruby/lib/truffle/truffle/cext.rb:135:in `check_abi_version': The native extension at /Users/rwstauner/src/github.com/Shopify/bootsnap/lib-truffleruby/bootsnap/bootsnap.bundle has a different ABI version: "3.0.3.22.3.0" than the running TruffleRuby: "3.1.3.9" (LoadError)
        from <internal:core> core/kernel.rb:226:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/lib/bootsnap/compile_cache/yaml.rb:3:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/test/test_helper.rb:11:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/src/github.com/Shopify/bootsnap/test/bundler_test.rb:3:in `<top (required)>'
        from <internal:core> core/kernel.rb:234:in `gem_original_require'
        from /Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_C614F96B3C_JAVA17/graalvm-c614f96b3c-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_C614F96B3C_JAVA17/graalvm-c614f96b3c-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from /Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_C614F96B3C_JAVA17/graalvm-c614f96b3c-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/Users/rwstauner/src/truffle-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_C614F96B3C_JAVA17/graalvm-c614f96b3c-java17-23.1.0-dev/Contents/Home/languages/ruby/lib/gems/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
<internal:core> core/kernel.rb:381:in `load'
```

**Comment by eregon** [comment]
In the first stacktrace we can see it fails during:
```
from org.truffleruby.language.loader.FeatureLoader.getEmbeddedABIVersion(FeatureLoader.java:536)
```
So it means to do the right thing, but even just loading the ABI version from that `.bundle` fails.
cc @rschatz I wonder why Sulong fails like that, maybe due different bitcode or not handling some type yet?
I don't think we can do anything about that in TruffleRuby unfortunately.
Loading the `.bundle` natively via NFI wouldn't be good for memory usage.

Maybe we could add a fake native library dependency to keep track of the GraalVM version and Sulong could check that.

Including the ABI in filenames could solve this (I think GraalPython does that), but that probably causes some incompatibilities.

**Comment by rschatz** [comment]
I think this error is coming from backwards incompatible changes in the bitcode format. LLVM bitcode is usually forward compatible, but not backward compatible. When you compile something with a newer LLVM, older versions are not necessarily able to read it.

GraalVM 23.0.0 is based on LLVM 15.0.6. Current master is at LLVM 16.0.1. So when you build an extension with GraalVM 23.1-dev, the native code is compiled with LLVM 16. And that produces new bitcodes that GraalVM 23.0 doesn't understand yet.

I'm afraid there is not much we can do about that. The LLVM tools themselves also fail with weird error messages if you try to use older tools on newer bitcode. The bitcode file format just doesn't contain a good version number we can check. The LLVM version number is in there, but only in the debug info, and we usually don't get that far in decoding the file.
