### ISSUE TITLE
Issue with TruffleRuby v20.3.0 and OpenProject v8.3

### ISSUE THREAD

**Issue by Dromak** [oracle/truffleruby#3206]
Hello. I'm trying to run a project on TruffleRuby, but I can't do it.

* Ubuntu 22.04.3 LTS
* rbenv 1.2.0-70-g4fec76f
* truffleruby+graalvm-20.3.0

Steps:

1. `libssl` v3.0.0 doesn't work for this version TruffleRuby, [download](http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/) older version.

2. Install TruffleRuby:

   ```shell
   rbenv install truffleruby+graalvm-20.3.0
   rbenv global truffleruby+graalvm-20.3.0
   ```

3. Clone OpenProject:

   ```shell
   git clone https://github.com/opf/openproject.git
   cd openproject
   git reset --hard 368c1db9b177c7aec6d910faae3b1d346ffe6481
   ```

4. Delete `ruby-prof` and `stackprof` from `Gemfile`.
5. Install gems:
   
   ```shell
   gem install bundler:2.0.2
   sudo apt install libxml2 libxslt1-dev
   gem install nokogiri -v '1.10.1' -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2
   bundle install
   ```

6. Rake doesn't work:

   ```shell
   bundle exec rake generate_secret_token --trace
   ```

   Stack trace:
   
   ```text
   rake aborted!
   Polyglot::UnsupportedMessageError: Message not supported.
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/will_paginate-3.1.6/lib/will_paginate/page_number.rb:46:in `==='
   <internal:core> core/truffle/kernel_operations.rb:148:in `normalize_backtrace_args'
   <internal:core> core/kernel.rb:752:in `caller_locations'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/railties-5.2.2.1/lib/rails/engine.rb:363:in `inherited'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/typed_dag-2.0.2/lib/typed_dag/engine.rb:1:in `<top (required)>'
   <internal:core> core/kernel.rb:234:in `gem_original_require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/typed_dag-2.0.2/lib/typed_dag.rb:4:in `<module:TypedDag>'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/typed_dag-2.0.2/lib/typed_dag.rb:1:in `<top (required)>'
   <internal:core> core/kernel.rb:234:in `gem_original_require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `each'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:76:in `block in require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `each'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:65:in `require'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler.rb:114:in `require'
   /home/user/RubymineProjects/opsd/config/application.rb:70:in `<top (required)>'
   <internal:core> core/kernel.rb:234:in `gem_original_require'
   /home/user/RubymineProjects/opsd/Rakefile:33:in `<top (required)>'
   <internal:core> core/kernel.rb:401:in `load'
   <internal:core> core/kernel.rb:401:in `load'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
   <internal:core> core/kernel.rb:401:in `load'
   <internal:core> core/kernel.rb:401:in `load'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/bin/rake:23:in `<top (required)>'
   <internal:core> core/kernel.rb:401:in `load'
   <internal:core> core/kernel.rb:401:in `load'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/graalvm/jre/languages/ruby/lib/gems/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
   <internal:core> core/kernel.rb:401:in `load'
   <internal:core> core/kernel.rb:401:in `load'
   /home/user/.rbenv/versions/truffleruby+graalvm-20.3.0/bin/bundle:23:in `<main>'
   ```

Is it possible to run project on this version TruffleRuby?

**Comment by eregon** [comment]
TruffleRuby/GraalVM 20.3.0 is ancient (2020).
Please use the latest release (23.0.0), that supports libssl 3, etc.
