### ISSUE TITLE
Infinite loop in Rails's descendants tracker

### ISSUE THREAD

**Issue by nirvdrum** [oracle/truffleruby#3245]
I ran into an infinite loop when running the new lobsters benchmark in [yjit-bench](https://github.com/shopify/yjit-bench). I've seen the same problem running the test suite for a private Rails 7 application on TruffleRuby. This occurs with both TruffleRuby 23.0.0 and 23.1.0-dev (2ed10973e791d80ca7333f2a7eba543e23bd2c6c).

```
> ./run_benchmarks.rb lobsters
Running benchmark "lobsters" (1/1)
/Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_F2FA4FF4E3_JAVA21/graalvm-f2fa4ff4e3-java21-24.0.0-dev/Contents/Home/languages/ruby/bin/truffleruby -I harness /Users/nirvdrum/dev/workspaces/yjit-bench/benchmarks/lobsters/benchmark.rb
truffleruby 24.0.0-dev-2ed10973, like ruby 3.2.2, GraalVM CE JVM [aarch64-darwin]
Command: bundle check 2> /dev/null || bundle install
[ruby] WARNING StackOverflowError
/Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:60:in `subclasses': stack level too deep (SystemStackError)
	from java.lang.String.checkBoundsBeginEnd(String.java:4861)
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	<... many more removed ...>
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/activesupport/lib/active_support/descendants_tracker.rb:61:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/railtie.rb:149:in `subclasses'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/engine/railties.rb:10:in `initialize'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/engine.rb:490:in `railties'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/application.rb:608:in `ordered_railties'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/application.rb:620:in `railties_initializers'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/application.rb:430:in `initializers'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/nirvdrum/.gem/truffleruby/3.2.2/bundler/gems/rails-4e01a7e8753c/railties/lib/rails/application.rb:423:in `initialize!'
	from /Users/nirvdrum/dev/workspaces/yjit-bench/benchmarks/lobsters/config/environment.rb:5:in `<top (required)>'
	from <internal:core> core/kernel.rb:297:in `require_relative'
	from /Users/nirvdrum/dev/workspaces/yjit-bench/benchmarks/lobsters/benchmark.rb:9:in `<main>'
Command "/Users/nirvdrum/dev/workspaces/truffleruby-ws/graal/sdk/mxbuild/darwin-aarch64/GRAALVM_F2FA4FF4E3_JAVA21/graalvm-f2fa4ff4e3-java21-24.0.0-dev/Contents/Home/languages/ruby/bin/truffleruby -I harness /Users/nirvdrum/dev/workspaces/yjit-bench/benchmarks/lobsters/benchmark.rb" failed in directory /Users/nirvdrum/dev/workspaces/yjit-bench
./run_benchmarks.rb:46:in `check_call': RuntimeError (RuntimeError)
	from ./run_benchmarks.rb:272:in `block in run_benchmarks'
	from <internal:core> core/enumerable.rb:380:in `each_with_index'
	from ./run_benchmarks.rb:218:in `run_benchmarks'
	from ./run_benchmarks.rb:405:in `block in <main>'
	from ./run_benchmarks.rb:404:in `each'
	from ./run_benchmarks.rb:404:in `<main>'
```

**Comment by eregon** [comment]
This is the same issue as https://github.com/oracle/truffleruby/issues/3161

**Comment by nirvdrum** [comment]
Thanks. I missed this was a duplicate issue. We can track it in #3161.
