### ISSUE TITLE
OpenSSL::PKey::PKeyError: EVP_DigestVerifyInit: invalid digest

### ISSUE THREAD

**Issue by HoneyryderChuck** [oracle/truffleruby#3284]
In the [httpx test suite](https://gitlab.com/os85/httpx/-/jobs/5212625012), I've been monitoring this truffleruby issue for a while, which still manifests after the upgrade to 23.1.0. FWIW I was able to reduce it to plain net-ssh-gateway example (ssh parameters relate to the [ssh server used in the tests](https://gitlab.com/os85/httpx/-/blob/master/docker-compose.yml#L48-559)):

```ruby
require "uri"
require "net/ssh/gateway"

ssh_uri = URI("ssh://sshproxy:22")

ssh_options = {
  auth_methods: %w[publickey],
  host_key: "ssh-rsa",
  keys: %w[test/support/ssh/ssh_host_ed25519_key]
}

gateway = Net::SSH::Gateway.new(ssh_uri.host, "root", ssh_options)

puts "done"
# works in ruby 3.2, breaks with truffleruby 23.1.0
# /opt/truffleruby-23.1.0/lib/truffle/truffle/cext.rb:1138:in `rb_exc_raise': EVP_DigestVerifyInit: invalid digest (OpenSSL::PKey::PKeyError)
#         from exception.c:29:in `rb_exc_raise'
#         from /opt/truffleruby-23.1.0/src/main/c/openssl/ossl.c:309:in `ossl_raise'
#         from /opt/truffleruby-23.1.0/src/main/c/openssl/ossl_pkey.c:1050:in `ossl_pkey_verify'
#         from /opt/truffleruby-23.1.0/lib/truffle/truffle/cext_ruby.rb:42:in `verify'
#         from /usr/local/bundle/truffleruby/3.2.2.23.1.0/gems/net-ssh-7.2.0/lib/net/ssh/transport/openssl.rb:73:in `ssh_do_verify'
```

**Comment by eregon** [comment]
Thank you for the report, we'll try to take a look.
I might wait after https://github.com/oracle/truffleruby/issues/3118 as that might possibly solve it.
