### ISSUE TITLE
Crash in redis-client CI: truffleruby: Unexpected internal exception in at_exit

### ISSUE THREAD

**Issue by byroot** [oracle/truffleruby#3321]
https://github.com/redis/redis-rb/actions/runs/6899762856/job/18771865853?pr=1238

```
java.lang.RuntimeException: Ruby Thread id=139 from /home/runner/work/redis-rb/redis-rb/test/redis/publish_subscribe_test.rb:275 terminated with internal error:
	at org.truffleruby.core.thread.ThreadManager.printInternalError(ThreadManager.java:337)
	at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:325)
	at org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:293)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:99)
	at com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:130)
	at com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:121)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:656)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:628)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:561)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:115)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:194)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:97)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:473)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:454)
	at com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:95)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.lang.UnsupportedOperationException: makeSharedShape() can only be called on non-shared shapes.
	at com.oracle.truffle.object.ShapeImpl.makeSharedShape(ShapeImpl.java:1094)
	at com.oracle.truffle.object.DynamicObjectLibraryImpl$MakeSharedNode.makeSharedShape(DynamicObjectLibraryImpl.java:1820)
	at com.oracle.truffle.object.DynamicObjectLibraryImplFactory$MakeSharedNodeGen.executeAndSpecialize(DynamicObjectLibraryImplFactory.java:338)
	at com.oracle.truffle.object.DynamicObjectLibraryImplFactory$MakeSharedNodeGen.execute(DynamicObjectLibraryImplFactory.java:328)
	at com.oracle.truffle.object.DynamicObjectLibraryImpl.markShared(DynamicObjectLibraryImpl.java:263)
	at com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports$Cached.markSharedNode_AndSpecialize(DynamicObjectLibraryImplGen.java:804)
	at com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports$Cached.markShared(DynamicObjectLibraryImplGen.java:786)
	at com.oracle.truffle.api.object.DynamicObjectLibraryGen$CachedDispatch.markShared(DynamicObjectLibraryGen.java:2051)
	at org.truffleruby.language.objects.shared.ShareObjectNode.shareCached(ShareObjectNode.java:62)
	at org.truffleruby.language.objects.shared.ShareObjectNodeGen.executeAndSpecialize(ShareObjectNodeGen.java:130)
	at org.truffleruby.language.objects.shared.ShareObjectNodeGen.executeShare(ShareObjectNodeGen.java:69)
	at org.truffleruby.language.objects.shared.WriteBarrierNode.writeBarrierCached(WriteBarrierNode.java:69)
	at org.truffleruby.language.objects.shared.WriteBarrierNodeGen.executeAndSpecialize(WriteBarrierNodeGen.java:201)
	at org.truffleruby.language.objects.shared.WriteBarrierNodeGen.executeWriteBarrier(WriteBarrierNodeGen.java:110)
	at org.truffleruby.language.objects.WriteObjectFieldNode.writeShared(WriteObjectFieldNode.java:47)
	at org.truffleruby.language.objects.WriteObjectFieldNodeGen.executeAndSpecialize(WriteObjectFieldNodeGen.java:150)
	at org.truffleruby.language.objects.WriteObjectFieldNodeGen.execute(WriteObjectFieldNodeGen.java:69)
	at org.truffleruby.language.objects.WriteInstanceVariableNode.write(WriteInstanceVariableNode.java:71)
	at org.truffleruby.language.objects.WriteInstanceVariableNode.execute(WriteInstanceVariableNode.java:47)
	at org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:63)
	at org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	at org.truffleruby.language.RubyProcRootNode.execute(RubyProcRootNode.java:64)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:656)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:628)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:561)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.invokeCallBoundary(SubstrateOptimizedCallTarget.java:115)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTargetInstalledCode.doInvoke(SubstrateOptimizedCallTargetInstalledCode.java:194)
	at com.oracle.svm.truffle.api.SubstrateOptimizedCallTarget.doInvoke(SubstrateOptimizedCallTarget.java:97)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:473)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:454)
	at org.truffleruby.core.proc.ProcOperations.rootCall(ProcOperations.java:54)
	at org.truffleruby.core.thread.ThreadNodes$ThreadInitializeNode.lambda$init$0(ThreadNodes.java:440)
	at org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:308)
	... 17 more
Caused by: Attached Guest Language Frames (2)

truffleruby: Unexpected internal exception in at_exit,
please report it to https://github.com/oracle/truffleruby/issues.


Ruby Thread id=139 from /home/runner/work/redis-rb/redis-rb/test/redis/publish_subscribe_test.rb:275 terminated with internal error: (java.lang.RuntimeException)
	from org.truffleruby.core.thread.ThreadManager.printInternalError(ThreadManager.java:337)
	from org.truffleruby.core.thread.ThreadManager.threadMain(ThreadManager.java:325)
	from org.truffleruby.core.thread.ThreadManager.lambda$initialize$5(ThreadManager.java:293)
	from java.lang.Thread.run(Thread.java:833)
	from com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	from com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:99)
	from com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:130)
	from com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:121)

Caused by:
makeSharedShape() can only be called on non-shared shapes. (java.lang.UnsupportedOperationException)
	from com.oracle.truffle.object.ShapeImpl.makeSharedShape(ShapeImpl.java:1094)
	from com.oracle.truffle.object.DynamicObjectLibraryImpl$MakeSharedNode.makeSharedShape(DynamicObjectLibraryImpl.java:1820)
	from com.oracle.truffle.object.DynamicObjectLibraryImplFactory$MakeSharedNodeGen.executeAndSpecialize(DynamicObjectLibraryImplFactory.java:338)
	from com.oracle.truffle.object.DynamicObjectLibraryImplFactory$MakeSharedNodeGen.execute(DynamicObjectLibraryImplFactory.java:328)
	from com.oracle.truffle.object.DynamicObjectLibraryImpl.markShared(DynamicObjectLibraryImpl.java:263)
	from com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports$Cached.markSharedNode_AndSpecialize(DynamicObjectLibraryImplGen.java:804)
	from com.oracle.truffle.object.DynamicObjectLibraryImplGen$DynamicObjectLibraryExports$Cached.markShared(DynamicObjectLibraryImplGen.java:786)
	from com.oracle.truffle.api.object.DynamicObjectLibraryGen$CachedDispatch.markShared(DynamicObjectLibraryGen.java:2051)
	from org.truffleruby.language.objects.shared.ShareObjectNode.shareCached(ShareObjectNode.java:62)
	from org.truffleruby.language.objects.shared.ShareObjectNodeGen.executeAndSpecialize(ShareObjectNodeGen.java:130)
	from org.truffleruby.language.objects.shared.ShareObjectNodeGen.executeShare(ShareObjectNodeGen.java:69)
	from org.truffleruby.language.objects.shared.WriteBarrierNode.writeBarrierCached(WriteBarrierNode.java:69)
	from org.truffleruby.language.objects.shared.WriteBarrierNodeGen.executeAndSpecialize(WriteBarrierNodeGen.java:201)
	from org.truffleruby.language.objects.shared.WriteBarrierNodeGen.executeWriteBarrier(WriteBarrierNodeGen.java:110)
	from org.truffleruby.language.objects.WriteObjectFieldNode.writeShared(WriteObjectFieldNode.java:47)
	from org.truffleruby.language.objects.WriteObjectFieldNodeGen.executeAndSpecialize(WriteObjectFieldNodeGen.java:150)
	from org.truffleruby.language.objects.WriteObjectFieldNodeGen.execute(WriteObjectFieldNodeGen.java:69)
	from org.truffleruby.language.objects.WriteInstanceVariableNode.write(WriteInstanceVariableNode.java:71)
	from org.truffleruby.language.objects.WriteInstanceVariableNode.execute(WriteInstanceVariableNode.java:47)
	from org.truffleruby.language.RubyNode.doExecuteVoid(RubyNode.java:63)
	from org.truffleruby.language.control.SequenceNode.execute(SequenceNode.java:34)
	from org.truffleruby.language.RubyProcRootNode.execute(RubyProcRootNode.java:64)

```

cc @eregon

**Comment by byroot** [comment]
BTW the report link is broken:

```
truffleruby: Unexpected internal exception in at_exit,
please report it to https://github.com/oracle/truffleruby/issues.
```

Somehow GitHub Actions include the final `.` in the link.

**Comment by eregon** [comment]
Thank you for the report, I will take a look.
Good point, I'll remove the final dot there.

**Comment by eregon** [comment]
This is the test on which it errors: https://github.com/redis/redis-rb/blob/a592a63d6371ea4359c5334dbe523cc1425a2228/test/redis/publish_subscribe_test.rb#L270-L302
The error likely means there is some race, either in the gem or in TruffleRuby.
An obvious race in that test is `@messages << [channel, message]` + `@messages.last` (`@messages` is an Array).
Using a Queue instead would be safe.
I'm not sure this is the race that the CI run found though.

The failure is on `truffleruby 22.2.0`, that's not supported anymore.
Simplifying a bit, currently only the latest version of truffleruby is supported.
I'll make a PR.

**Comment by eregon** [comment]
https://github.com/redis/redis-rb/pull/1239 that should hopefully fix it.
Regarding the final dot I made a local commit for that and will merge it with other changes.
