### ISSUE TITLE
Failure in SimpleCov test suite

### ISSUE THREAD

**Issue by eregon** [oracle/truffleruby#3535]
From https://github.com/simplecov-ruby/simplecov/pull/1079/files#r1566262539

The failure is:
```
$ bundle exec rake spec

Failures:

  1) return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests with default configuration prints a message to STDERR
     Failure/Error: expect(@stderr).to match(/stopped.+SimpleCov.+previous.+error/i)
     
       expected "" to match /stopped.+SimpleCov.+previous.+error/i
       Diff:
       @@ -1 +1 @@
       -/stopped.+SimpleCov.+previous.+error/i
       +""
       
     Shared Example Group: "bad tests" called from ./spec/return_codes_spec.rb:69
     # ./spec/return_codes_spec.rb:37:in `block (5 levels) in <top (required)>'
     # ./spec/return_codes_spec.rb:12:in `block (4 levels) in <top (required)>'
     # ./spec/return_codes_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 40.45 seconds (files took 1.59 seconds to load)
389 examples, 1 failure

Failed examples:

rspec './spec/return_codes_spec.rb[1:1:3:1:1:2]' # return codes inside fixtures/frameworks when running testunit_bad.rb behaves like bad tests with default configuration prints a message to STDERR
```

Note the exit code is already correct (the spec above), but for some reason there is no output.

**Comment by PragTob** [comment]
@andrykonchin great reproduction work, thank you very much! :green_heart:

**Comment by andrykonchin** [comment]
Fixed in cc2d0145ca405336827f95431d42fcebcbcd2aab

**Comment by eregon** [comment]
@andrykonchin Could you make a PR to SimpleCov to unexclude that test? (see link in description)

**Comment by andrykonchin** [comment]
The enabled back test case is supposed to pass on TruffleRuby head (that is used in the scheduled builds) and still fail on TruffleRuby 24.0.0 (that is used in builds triggered in PRs).

So what is better to do - to unexclude the test now and don't run specs on TruffleRuby 24.0.0 or unexclude it later when the fix is released?

**Comment by PragTob** [comment]
@andrykonchin unexclude it later when the fix is released and available on github actions (imo)

**Comment by eregon** [comment]
But it will be like 6 months until the next release.
I think it makes sense to alter the condition to only skip the test on TruffleRuby < 24.1.

**Comment by andrykonchin** [comment]
Right, makes sense.
