### ISSUE TITLE
gem error: OpenSSL is not available in Oracle Linux 9

### ISSUE THREAD

**Issue by yanecc** [oracle/truffleruby#3573]
I have had `openssl-devel` and other dependencies installed, but I just couldn't install any gems.

```
[root@Yane Oracle]# cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
[root@Yane Oracle]# gem install tnef_binary
ERROR:  While executing gem ... (Gem::Exception)
    OpenSSL is not available. Install OpenSSL and rebuild Ruby or use non-HTTPS sources (Gem::Exception)
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request.rb:47:in `configure_connection_for_https'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request/https_pool.rb:6:in `setup_connection'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request/http_pool.rb:39:in `make_connection'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request/http_pool.rb:20:in `checkout'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request.rb:129:in `connection_for'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request.rb:188:in `perform_request'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/request.rb:154:in `fetch'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/remote_fetcher.rb:309:in `request'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/remote_fetcher.rb:209:in `fetch_http'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/remote_fetcher.rb:248:in `fetch_path'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/source.rb:88:in `dependency_resolver_set'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/source_list.rb:94:in `each'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/source_list.rb:94:in `each_source'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/resolver/best_set.rb:22:in `pick_sets'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/resolver/best_set.rb:28:in `find_all'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/resolver/installer_set.rb:170:in `find_all'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/resolver/installer_set.rb:61:in `add_always_install'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/dependency_installer.rb:322:in `resolve_dependencies'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/commands/install_command.rb:205:in `install_gem'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/commands/install_command.rb:230:in `block in install_gems'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/commands/install_command.rb:223:in `each'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/commands/install_command.rb:223:in `install_gems'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/commands/install_command.rb:169:in `execute'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/command.rb:327:in `invoke_with_build_args'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/command_manager.rb:252:in `invoke_command'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/command_manager.rb:192:in `process_args'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/command_manager.rb:150:in `run'
        /home/truffleruby-community-24.0.1-linux-amd64/lib/mri/rubygems/gem_runner.rb:51:in `run'
        /home/truffleruby-community-24.0.1-linux-amd64/bin/gem:29:in `<main>'
```

os: Oracle Linux 9 in WSL

**Comment by yanecc** [comment]
This can be reproduced in Rocky Linux 9.2.

**Comment by andrykonchin** [comment]
Thank you for the report, we'll look into it.

**Comment by yanecc** [comment]
> @yanecc How did you install truffleruby? Did you run the post-install hook as documented [here](https://github.com/oracle/truffleruby/blob/master/doc/user/installing-truffleruby.md) and other places? I did test on OracleLinux 9 for the 24.0 release, so I'm pretty sure that's what you're missing here.

Yes, I missed this, thank you very much!
